'use strict';
const express=require('express'),http=require('http'),{WebSocketServer}=require('ws'),crypto=require('crypto');
const runtime=require('../../lib/party-runtime');const app=express(),server=http.createServer(app),wss=new WebSocketServer({server,path:'/ws'});
app.get('/host',(_,r)=>r.sendFile(__dirname+'/public/host.html'));app.use(express.static(__dirname+'/public'));
const W=1200,H=720,players=new Map(),bullets=[],pickups=[],effects=[];const weapons={cannon:{name:'ПУШКА',speed:580,damage:34,cd:.48,count:1},shotgun:{name:'ДРОБОВИК',speed:480,damage:16,cd:.9,count:5},rapid:{name:'ПУЛЕМЁТ',speed:760,damage:10,cd:.14,count:1},rocket:{name:'РАКЕТА',speed:330,damage:52,cd:1.2,count:1}};let phase='lobby',timer=90,match='',started=0,pickupTimer=0;
const colors=['#62e0e5','#ff789c','#ffcc66','#a78aff','#90e57b','#ff9557'];const rnd=(a,b)=>a+Math.random()*(b-a),clamp=(n,a,b)=>Math.max(a,Math.min(b,n));const weapon=()=>Object.keys(weapons)[Math.floor(Math.random()*4)];
function spawn(p){p.x=rnd(65,W-65);p.y=rnd(90,H-65);p.hp=100;p.dead=0;p.shield=2;p.weapon=weapon();p.input={x:0,y:0,fire:false};}
function view(){return {phase,timer,W,H,players:[...players.values()].map(({ws,input,...p})=>p),bullets,pickups,effects,weapons};}
function send(ws,type,data){if(ws.readyState===1)ws.send(JSON.stringify({type,data}));}
function finish(){phase='finished';const ps=[...players.values()],best=Math.max(0,...ps.map(p=>p.score));runtime.report({gameId:'tankarena',eventId:match,duration:(Date.now()-started)/1000,players:ps.map(p=>({id:p.id,name:p.name,score:p.score,won:p.score===best,metrics:{kills:p.kills,deaths:p.deaths,shots:p.shots,damage:Math.round(p.damage)}}))});}
function start(){if([...players.values()].filter(p=>p.connected).length<2)return;phase='playing';timer=process.env.TEST_FAST==='1'?2:90;match=crypto.randomUUID();started=Date.now();bullets.length=pickups.length=effects.length=0;for(const p of players.values()){p.score=p.kills=p.deaths=p.shots=p.damage=0;spawn(p);}}
wss.on('connection',(ws,req)=>{ws.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return;}const d=m.data||{};
if(m.type==='host'){const trusted=runtime.managed?req?.headers?.['x-party-local']==='1':['127.0.0.1','::1','::ffff:127.0.0.1'].includes(req?.socket?.remoteAddress);if(trusted)ws.host=true;return;}
if(m.type==='join'){const identity=runtime.identify(d,ws);if(process.env.PARTY_MANAGED==='1'&&!identity)return send(ws,'error','Вернитесь в главное меню для входа');const id=identity?.id||String(d.token||crypto.randomUUID());let p=players.get(id);if(!p){p={id,name:String(identity?.name||d.name||'Танкист').slice(0,24),color:colors[players.size%colors.length],angle:0,score:0,kills:0,deaths:0,shots:0,damage:0,cd:0};spawn(p);players.set(id,p);}const previous=p.ws;p.ws=ws;p.connected=true;if(previous&&previous!==ws)previous.close(4001,'Replaced');p.input={x:0,y:0,fire:false};ws.pid=id;send(ws,'joined',{id,name:p.name});return;}
if(m.type==='start'&&ws.host){start();return;}const p=players.get(ws.pid);if(!p||p.ws!==ws)return;if(m.type==='input'){p.input={x:clamp(Number(d.x)||0,-1,1),y:clamp(Number(d.y)||0,-1,1),fire:d.fire===true};}
});ws.on('close',()=>{const p=players.get(ws.pid);if(p?.ws===ws){p.connected=false;runtime.presence(p.id,false);p.input={x:0,y:0,fire:false};}});});
function shoot(p){const w=weapons[p.weapon];p.cd=w.cd;p.shots++;for(let i=0;i<w.count;i++){const a=p.angle+(i-(w.count-1)/2)*.16;bullets.push({id:crypto.randomUUID(),owner:p.id,x:p.x+Math.cos(a)*30,y:p.y+Math.sin(a)*30,vx:Math.cos(a)*w.speed,vy:Math.sin(a)*w.speed,damage:w.damage,kind:p.weapon,color:p.color,ttl:p.weapon==='shotgun'?.65:2});}}
function hurt(p,b){if(p.shield>0||p.dead>0)return;p.hp-=b.damage;effects.push({id:crypto.randomUUID(),x:b.x,y:b.y,t:.25,max:.25,color:"#ffe2a2"});if(effects.length>48)effects.shift();const owner=players.get(b.owner);if(owner)owner.damage+=b.damage;if(p.hp<=0){p.dead=2;p.deaths++;p.input.fire=false;if(owner&&owner!==p){owner.kills++;owner.score+=100;}effects.push({id:crypto.randomUUID(),x:p.x,y:p.y,t:.7,max:.7,color:p.color});}}
let last=Date.now();runtime.setInterval(()=>{const now=Date.now(),dt=Math.min(.05,(now-last)/1000);last=now;if(phase==='playing'){timer=Math.max(0,timer-dt);pickupTimer-=dt;if(pickupTimer<=0){pickupTimer=3;if(pickups.length<8)pickups.push({x:rnd(60,W-60),y:rnd(90,H-60),weapon:weapon()});}
for(const p of players.values()){if(!p.connected)continue;p.cd=Math.max(0,p.cd-dt);p.shield=Math.max(0,p.shield-dt);if(p.dead>0){p.dead-=dt;if(p.dead<=0)spawn(p);continue;}const q=p.input,n=Math.hypot(q.x,q.y),scale=n>1?1/n:1;p.x=clamp(p.x+q.x*scale*190*dt,46,W-46);p.y=clamp(p.y+q.y*scale*190*dt,60,H-46);if(n>.15)p.angle=Math.atan2(q.y,q.x);if(q.fire&&p.cd<=0)shoot(p);for(let i=pickups.length-1;i>=0;i--)if(Math.hypot(p.x-pickups[i].x,p.y-pickups[i].y)<40){p.weapon=pickups[i].weapon;pickups.splice(i,1);}}
for(let i=bullets.length-1;i>=0;i--){const b=bullets[i];b.x+=b.vx*dt;b.y+=b.vy*dt;b.ttl-=dt;let hit=false;for(const p of players.values())if(p.connected&&p.id!==b.owner&&p.dead<=0&&Math.hypot(p.x-b.x,p.y-b.y)<27){if(b.kind==='rocket'){for(const q of players.values())if(q.connected&&Math.hypot(q.x-b.x,q.y-b.y)<110)hurt(q,b);effects.push({id:crypto.randomUUID(),x:b.x,y:b.y,t:.5,max:.5,color:'#ffb454'});}else hurt(p,b);hit=true;break;}if(!hit&&(b.x<0||b.x>W||b.y<0||b.y>H)){effects.push({id:crypto.randomUUID(),x:clamp(b.x,4,W-4),y:clamp(b.y,4,H-4),t:.25,max:.25,color:'#ffe2a2'});if(effects.length>48)effects.shift();}if(hit||b.ttl<=0||b.x<0||b.x>W||b.y<0||b.y>H)bullets.splice(i,1);}for(let i=effects.length-1;i>=0;i--){effects[i].t-=dt;if(effects[i].t<=0)effects.splice(i,1);}if(timer<=0)finish();}runtime.ui?.({phase:phase==='lobby'?'waiting':phase==='finished'?'results':'playing',endsAt:phase==='playing'?Date.now()+timer*1000:null,label:'До конца боя'});const state=view();for(const ws of wss.clients)send(ws,'state',state);},33);
server.listen(Number(process.env.PORT||0),process.env.PARTY_MANAGED==='1'?'127.0.0.1':'0.0.0.0',()=>{const port=server.address().port;console.log('Tank Arena http://localhost:'+port+'/host');process.send?.({type:'ready',port});});

runtime.onPause(()=>{for(const p of players.values())p.input={x:0,y:0,fire:false};});



// Commands from the iPhone server console.
runtime.host({start:()=>{start();return phase==='playing';}});
