'use strict';
const {webkit,chromium}=require('playwright'),{spawn}=require('node:child_process'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve('output/playwright/console-motion135/choice');fs.mkdirSync(out,{recursive:true});const sleep=ms=>new Promise(r=>setTimeout(r,ms));const child=spawn(process.execPath,['server.js'],{env:{...process.env,PARTY_EMBEDDED:'1',PARTY_EPHEMERAL:'1',PARTY_PORT:'0',PARTY_INTERNAL_PORT:'0',PARTY_NO_BROWSER:'1',PARTY_ADMIN_KEY:'choice135'}});let log='',browser;child.stdout.on('data',d=>log+=d);child.stderr.on('data',d=>log+=d);const report={cases:[],errors:[]};
(async()=>{try{for(let i=0;i<400&&!/localhost:(\d+)/.test(log);i++)await sleep(40);assert(/localhost:(\d+)/.test(log),log);const origin='http://127.0.0.1:'+log.match(/localhost:(\d+)/)[1];const api=async b=>(await fetch(origin+'/api/manage',{method:b?'POST':'GET',headers:{Authorization:'Bearer choice135','Content-Type':'application/json'},body:b?JSON.stringify(b):undefined})).json();
for(const engine of ['webkit','chromium']){browser=await (engine==='webkit'?webkit:chromium).launch(engine==='chromium'?{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}:{});await api({type:'select',id:'push'});const page=await browser.newPage({viewport:{width:1280,height:720},recordVideo:{dir:out,size:{width:1280,height:720}}});page.on('pageerror',e=>report.errors.push(e.message));await page.goto(origin+'/tv');await page.waitForFunction(()=>window.HeyPalsTVMotion?.diagnostics().state==='idle'&&tvStartup.hidden);await sleep(300);assert.equal(await page.evaluate(()=>HeyPalsChoiceMotion.diagnostics().confirms),0);
await api({type:'select',id:'tankarena'});await page.waitForFunction(()=>HeyPalsChoiceMotion.diagnostics().confirms===1);await page.evaluate(()=>{for(const a of document.querySelector('.lp-choice-confirm')?.getAnimations()||[]){a.pause();a.currentTime=80;}});await page.screenshot({path:path.join(out,engine+'-confirmed.png')});await page.evaluate(()=>{for(const a of document.querySelector('.lp-choice-confirm')?.getAnimations()||[])a.play();});await sleep(300);assert.equal(await page.locator('.lp-choice-confirm').count(),0);await api({type:'select',id:'tankarena'});await sleep(200);assert.equal(await page.evaluate(()=>HeyPalsChoiceMotion.diagnostics().confirms),1);
await api({type:'select',id:'bomb'});await api({type:'select',id:'push'});await sleep(500);assert.equal(await page.locator('.lp-choice-confirm').count(),0);
await page.emulateMedia({reducedMotion:'reduce'});await api({type:'select',id:'tankarena'});await sleep(300);assert.equal(await page.locator('.lp-choice-confirm').count(),0);report.cases.push({engine,initialNoReplay:true,repeatedNoReplay:true,rapidCleanup:true,reducedCleanup:true});const video=page.video();await page.close();await video.saveAs(path.join(out,engine+'-choice.webm'));
const phone=await browser.newPage({viewport:{width:393,height:852},isMobile:true,hasTouch:true});phone.on('pageerror',e=>report.errors.push(e.message));await phone.route('**/native-shell/**',r=>r.fulfill({path:path.resolve('public',new URL(r.request().url()).pathname.slice(1))}));await phone.addInitScript(src=>{window.webkit={messageHandlers:{partyShell:{postMessage(){}}}};window.__partyPersistentTabs=true;(0,eval)(src);},fs.readFileSync('public/native-shell/tabs.js','utf8'));await phone.goto(origin+'/native-shell/index.html');const snapshot=await api();await phone.evaluate(s=>LocalPartyHost.update({...s,native:{ready:true,catalogReady:true}}),snapshot);await sleep(400);assert.equal(await phone.evaluate(()=>HeyPalsChoiceMotion.diagnostics().confirms),0);await phone.locator('[data-game=tankarena]').scrollIntoViewIfNeeded();await phone.evaluate(s=>LocalPartyHost.update({...s,selected:'push',native:{ready:true,catalogReady:true}}),snapshot);await phone.waitForFunction(()=>HeyPalsChoiceMotion.diagnostics().confirms===1);await phone.evaluate(()=>{for(const a of document.querySelector('.lp-choice-confirm')?.getAnimations()||[]){a.pause();a.currentTime=80;}});await phone.screenshot({path:path.join(out,engine+'-native-confirmed.png')});await phone.evaluate(()=>HeyPalsChoiceMotion.clear());assert.equal(await phone.locator('.lp-choice-confirm').count(),0);await phone.close();report.cases.push({engine,nativeFixture:true,confirmed:true,cleanup:true});await browser.close();browser=null;}
assert.deepEqual(report.errors,[]);report.ok=true;}catch(e){report.failure=e.stack;process.exitCode=1;}finally{fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));await browser?.close();child.kill();console.log(JSON.stringify(report));}})();
