'use strict';
// Actual server/TV routes, original-speed transitions and an exact final-scene
// oracle. Browser RAF/GL timings are diagnostics, never physical-cast acceptance.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{spawn,execFileSync}=require('node:child_process');
const pw=require(process.env.PARTY_PLAYWRIGHT||'playwright');
const out=path.resolve(process.env.QA_OUTPUT||'output/playwright/performance247/curtain');
fs.mkdirSync(out,{recursive:true});
const sourceFiles=['public/tv-motion-20261005.js','public/tv-motion-20261005.css','public/tv.js','games/sports_siege/server.js','games/sports_siege/public/host.js','games/sports_siege/public/scene-readiness.js','ios/LocalParty/ExternalDisplay.swift'];
const report={head:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),sourceHashes:Object.fromEntries(sourceFiles.map(file=>[file,crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex')])),method:'Actual /tv with real launch/stop APIs. Strict expected instance, destination URL/warmup, finite animation completion and screenshot pre/post assertions. Original-speed web compositor poses. GL/RAF/long-task timing instrumented in test pages only. Not UIKit/physical-cast or full-catalog acceptance.',rows:[],captures:[],errors:[]};
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));let server,browser,log='';
const watchdog=setTimeout(()=>{server?.kill();process.exit(2);},240000);watchdog.unref();

function instrument(){
 const qa=()=>document.documentElement?.setAttribute('data-scene-readiness-qa','');if(document.documentElement)qa();else new MutationObserver((_,observer)=>{if(document.documentElement){qa();observer.disconnect();}}).observe(document,{childList:true});
 const events=window.__curtain247={frames:[],tasks:[],gl:[],mainRenders:[],warmups:[],record:false,lastWarmup:null};
 const outer=()=>{try{return top.HeyPalsTVMotion?.diagnostics()?.state||'startup';}catch{return 'unavailable';}};
 try{new PerformanceObserver(list=>list.getEntries().forEach(e=>events.tasks.push({at:e.startTime,duration:e.duration,phase:outer(),frame:location.pathname}))).observe({entryTypes:['longtask']});}catch{}
 const seen=new WeakSet(),getContext=HTMLCanvasElement.prototype.getContext;
 HTMLCanvasElement.prototype.getContext=function(...args){const context=getContext.apply(this,args);if(context&&/webgl/.test(args[0])&&!seen.has(context)){seen.add(context);for(const name of ['compileShader','linkProgram','drawArrays','drawElements','drawArraysInstanced','drawElementsInstanced']){const original=context[name];if(typeof original!=='function')continue;context[name]=function(...values){const at=performance.now(),phase=outer(),result=original.apply(this,values);if(events.gl.length<6000&&(name==='compileShader'||name==='linkProgram'||!events.gl.some(e=>e.name.startsWith('draw'))))events.gl.push({name,at,duration:performance.now()-at,phase,warmup:document.body?.dataset.shaderWarmup||'absent'});return result;};}}return context;};
 const observe=()=>{if(!document.body)return requestAnimationFrame(observe);const record=()=>{const value=document.body.dataset.shaderWarmup||'absent';if(value!==events.lastWarmup){events.lastWarmup=value;events.warmups.push({value,at:performance.now(),phase:outer()});}};record();new MutationObserver(record).observe(document.body,{attributes:true,attributeFilter:['data-shader-warmup']});};observe();
 if(window===top)requestAnimationFrame(function frame(at){if(events.record){const d=window.HeyPalsTVMotion?.diagnostics(),el=document.getElementById('tvSceneTransition');if(d&&el){const matrix=node=>{if(!node)return null;const s=getComputedStyle(node);return {transform:s.transform,opacity:Number(s.opacity)};};events.frames.push({at,...d,left:matrix(el.querySelector('.tvm-door-l')),right:matrix(el.querySelector('.tvm-door-r')),opacity:Number(getComputedStyle(el).opacity)});}}requestAnimationFrame(frame);});
}
async function snapshot(page){return page.evaluate(()=>{
 const pose=node=>{if(!node)return null;const s=getComputedStyle(node),r=node.getBoundingClientRect(),matrix=new DOMMatrixReadOnly(s.transform==='none'?undefined:s.transform);return {hidden:node.hidden,display:s.display,visibility:s.visibility,opacity:Number(s.opacity),transform:s.transform,translationX:matrix.m41,translate:s.translate,rect:{x:r.x,y:r.y,width:r.width,height:r.height}};};
 const curtain=document.getElementById('tvSceneTransition'),frame=document.getElementById('gameFrame');let destination=null;
 try{const doc=frame.contentDocument;destination={src:frame.getAttribute('src'),path:frame.contentWindow.location.pathname,search:frame.contentWindow.location.search,readyState:doc?.readyState,warmup:doc?.body?.dataset.shaderWarmup||'absent',fonts:doc?.fonts?.status};}catch{}
 // Discovery progress is a recurring10s clock, not an entrance. Keep it live;
 // only this named clock is excluded, not its finite logo/metadata transitions.
 const finite=document.getAnimations().filter(a=>['running','paused'].includes(a.playState)&&Number.isFinite(a.effect?.getComputedTiming().endTime)&&!a.effect?.target?.classList?.contains('spotlight-step-fill')).map(a=>({state:a.playState,name:a.animationName||'',target:a.effect?.target?.id||a.effect?.target?.className||'',end:a.effect?.getComputedTiming().endTime}));
 const logo=document.querySelector('#waitingGameTitle .hp-smooth-game-logo:not([hidden])')||document.querySelector('#waitingGameTitle .waiting-game-logo'),logoPose=pose(logo);if(logoPose){let alpha=1;for(let n=logo;n;n=n.parentElement)alpha*=Number(getComputedStyle(n).opacity);logoPose.effectiveOpacity=alpha;}
 return {at:performance.now(),...HeyPalsTVMotion.diagnostics(),instance:window.PARTY_INSTANCE||null,lobby:pose(document.getElementById('lobby')),play:pose(document.getElementById('play')),waiting:pose(document.getElementById('waiting')),curtainPose:pose(curtain),left:pose(curtain.querySelector('.tvm-door-l')),right:pose(curtain.querySelector('.tvm-door-r')),seam:pose(curtain.querySelector('.tvm-seam')),logo:logoPose,destination,finite,fonts:document.fonts.status};
});}
function assertFinal(value,expected){
 assert.equal(value.committed,expected.key,'Exact authoritative scene committed');assert.equal(value.state,'idle');assert.equal(value.pending,false);assert.equal(value.curtain,false);assert(value.curtainPose.hidden||value.curtainPose.display==='none');assert.equal(value.finite.length,0);assert.equal(value.fonts,'loaded');
 if(expected.instance){assert.equal(value.instance,expected.instance);assert.equal(value.lobby.hidden,true);assert.equal(value.play.hidden,false);assert.equal(value.destination.path,expected.path);assert.equal(value.destination.search,expected.search);assert.equal(value.destination.readyState,'complete');assert.notEqual(value.destination.warmup,'pending');if(['curling','bowling','swarm_gate','peek_shoot'].includes(expected.id))assert.equal(value.destination.warmup,'ready','Stage must publish explicit ready, not an absent field');if(value.waiting&&!value.waiting.hidden&&value.logo){assert(value.logo.effectiveOpacity>.99,'Receiving logo has no dim final frame');}}
 else{assert.equal(value.instance,null);assert.equal(value.lobby.hidden,false);assert.equal(value.play.hidden,true);assert(!value.destination.src||value.destination.src==='about:blank');}
}
async function settled(page,expected){
 await page.evaluate(async expected=>{
  await document.fonts.ready;const until=performance.now()+14000;let stableSince=0;
  while(performance.now()<until){
   const finite=()=>document.getAnimations().filter(a=>['running','paused'].includes(a.playState)&&Number.isFinite(a.effect?.getComputedTiming().endTime)&&!a.effect?.target?.classList?.contains('spotlight-step-fill'));
   const animations=finite();if(animations.length)await Promise.race([Promise.allSettled(animations.map(a=>a.finished)),new Promise(resolve=>setTimeout(resolve,100))]);
   await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));
   const d=HeyPalsTVMotion.diagnostics(),frame=document.getElementById('gameFrame'),curtain=document.getElementById('tvSceneTransition');let destination=false;
   try{const doc=frame.contentDocument;destination=expected.instance?window.PARTY_INSTANCE===expected.instance&&frame.contentWindow.location.pathname===expected.path&&frame.contentWindow.location.search===expected.search&&doc?.readyState==='complete'&&doc.body?.dataset.shaderWarmup!=='pending':!window.PARTY_INSTANCE&&(!frame.getAttribute('src')||frame.getAttribute('src')==='about:blank');}catch{}
   const valid=d.committed===expected.key&&d.state==='idle'&&!d.pending&&!d.curtain&&curtain.hidden&&destination&&!finite().length&&document.fonts.status==='loaded'&&document.getElementById('lobby').hidden===!!expected.instance&&document.getElementById('play').hidden===!expected.instance;
   if(valid){if(!stableSince)stableSince=performance.now();if(performance.now()-stableSince>=120)return;}else stableSince=0;
  }
  throw new Error('Expected scene did not become stable: '+JSON.stringify(expected)+' '+JSON.stringify(HeyPalsTVMotion.diagnostics()));
 },expected);
 const value=await snapshot(page);assertFinal(value,expected);return value;
}
async function capture(page,name,phase,expected){
 const before=await snapshot(page);if(phase==='settled')assertFinal(before,expected);if(phase==='covered'&&['closed','revealing'].includes(before.state)){assert(Math.abs(before.left.translationX)<.6&&Math.abs(before.right.translationX)<.6,'Covered pose has closed door transforms');assert(before.curtainPose.opacity>.99,'Covered curtain has full opacity');}const png=!process.env.QA_FINAL_PNG_ONLY||phase==='settled';if(png)await page.screenshot({path:path.join(out,name+'.png')});const after=await snapshot(page);if(phase==='settled')assertFinal(after,expected);report.captures.push({name,phase,before,after,expected,png,phaseStable:before.state===after.state});return before;
}
async function film(page,name,trigger,expectedFor){
 await page.evaluate(()=>{__curtain247.frames=[];__curtain247.record=true;});const state=await trigger(),expected=expectedFor(state);
 await page.waitForFunction(()=>HeyPalsTVMotion.diagnostics().state==='closing',null,{timeout:4000});await capture(page,name+'-closing','closing',expected);
 await page.waitForFunction(()=>['closed','revealing'].includes(HeyPalsTVMotion.diagnostics().state),null,{timeout:5000});const covered=await capture(page,name+'-covered','covered',expected);
 await page.waitForFunction(()=>HeyPalsTVMotion.diagnostics().state==='opening',null,{timeout:14000});await capture(page,name+'-opening','opening',expected);
 const final=await settled(page,expected);await capture(page,name+'-settled','settled',expected);
 const frames=await page.evaluate(()=>{__curtain247.record=false;return __curtain247.frames;});assert(frames.some(f=>f.state==='closing')&&frames.some(f=>f.state==='opening'));assert(frames.filter(f=>f.state==='opening').every(f=>f.curtain),'Curtain remains present throughout sampled opening');
 report.rows.push({name,expected,covered,final,frames});return final;
}
(async()=>{try{
 server=spawn(process.execPath,['server.js'],{env:{...process.env,PARTY_EMBEDDED:'1',PARTY_INTERNAL_PORT:'0',PARTY_EPHEMERAL:'1',PARTY_PORT:'0',PARTY_NO_BROWSER:'1',PARTY_ADMIN_KEY:'curtain247'}});server.stdout.on('data',data=>log+=data);server.stderr.on('data',data=>log+=data);
 for(let i=0;i<300&&!/localhost:(\d+)/.test(log);i++)await delay(50);assert.match(log,/localhost:(\d+)/);const origin='http://127.0.0.1:'+log.match(/localhost:(\d+)/)[1];
 const api=async body=>{const r=await fetch(origin+'/api/manage',{method:body?'POST':'GET',headers:{Authorization:'Bearer curtain247','Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const s=await r.json();assert(r.ok,JSON.stringify(s));return s;};
 const expectedFor=state=>{if(!state.active)return {key:'lobby',instance:null};const game=state.catalog.find(g=>g.id===state.active.id),url=new URL('/games/'+game.id+game.host,origin);return {key:'game:'+state.active.instance,instance:state.active.instance,id:game.id,path:url.pathname,search:url.search};};
 await api({type:'force-language',language:'en'});
 for(const engine of (process.env.QA_ENGINE?[process.env.QA_ENGINE]:['chromium','webkit'])){
  browser=await pw[engine].launch(engine==='chromium'?{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}:{});const page=await browser.newPage({viewport:{width:1280,height:720}});await page.addInitScript(instrument);if(process.env.QA_MISSING_STATE)await page.addInitScript(()=>window.__curtain247HoldSnapshot=true);page.on('pageerror',error=>report.errors.push({engine,error:error.message}));page.on('response',response=>{if(response.status()>=400&&/\.js(?:[?]|$)/.test(response.url()))report.errors.push({engine,resource:response.url(),status:response.status()});});
  if(process.env.QA_READINESS_CANDIDATE||process.env.QA_MAIN_RENDER_TRACE||process.env.QA_MISSING_STATE){const candidate=process.env.QA_READINESS_CANDIDATE&&path.resolve(process.env.QA_READINESS_CANDIDATE);if(candidate)report.readinessCandidate=JSON.parse(fs.readFileSync(path.join(candidate,'source-proof.json'),'utf8'));await page.route('**/games/**',route=>{const url=new URL(route.request().url()),match=url.pathname.match(/^\/games\/(bowling|curling|swarm_gate|peek_shoot)\/(host|scene-readiness|net)\.js$/);if(!match||!candidate&&match[2]!=='host'&&!(process.env.QA_MISSING_STATE&&match[2]==='net'))return route.continue();let body=fs.readFileSync(candidate&&match[2]!=='net'?path.join(candidate,match[2]+'.js'):'games/sports_siege/public/'+match[2]+'.js','utf8');if(process.env.QA_MISSING_STATE&&match[2]==='net'){const marker='this.dispatchEvent(new CustomEvent(m.type,{detail:m.data}));';assert.equal(body.split(marker).length,2);body=body.replace(marker,"if(m.type==='state'&&window.__curtain247HoldSnapshot){window.__curtain247HeldSnapshot=m;window.__curtain247HeldCount=(window.__curtain247HeldCount||0)+1;window.__curtain247ReleaseSnapshot=()=>{window.__curtain247HoldSnapshot=false;const latest=window.__curtain247HeldSnapshot;this.dispatchEvent(new CustomEvent(latest.type,{detail:latest.data}));};return;}"+marker);}if(process.env.QA_STATE_GUARD&&match[2]==='host'){const marker="if(document.hidden||this.state?.phase==='waiting')";assert.equal(body.split(marker).length,2);body=body.replace(marker,"if(document.hidden||!this.state||this.state.phase==='waiting')");}if(process.env.QA_MAIN_RENDER_TRACE&&match[2]==='host'){const marker='    this.staticScene();this.makePools();this.resize();';assert.equal(body.split(marker).length,2);body=body.replace(marker,`    const unknownUpdates={objects:0,effects:0};for(const [method,key]of [['updateObjects','objects'],['updateEffects','effects']]){const actual=this[method].bind(this);this[method]=(...args)=>{if(!this.state)unknownUpdates[key]++;return actual(...args);};}window.__curtain247StageStatus=()=>({clock:this.clock,phase:this.state?.phase||'unknown',unknownUpdates});const traceRender=this.renderer.render.bind(this.renderer);this.renderer.render=(scene,camera,...rest)=>{const at=performance.now(),main=scene===this.scene;let curtain='unavailable';try{curtain=top.HeyPalsTVMotion?.diagnostics()?.state||'startup';}catch{}const result=traceRender(scene,camera,...rest);if(__curtain247.mainRenders.length<80)__curtain247.mainRenders.push({at,duration:performance.now()-at,main,curtain,clock:this.clock,matchPhase:this.state?.phase||'unknown',warmup:document.body.dataset.shaderWarmup||'absent'});return result;};\n`+marker);}report.runtimeOverrides||={};report.runtimeOverrides[engine+':'+url.pathname]=crypto.createHash('sha256').update(body).digest('hex');return route.fulfill({body,contentType:'application/javascript'});});}
  await page.goto(origin+'/tv');await page.waitForFunction(()=>window.HeyPalsTVMotion?.diagnostics().state==='opening',null,{timeout:14000});const lobby=expectedFor(await api());await capture(page,engine+'-cold-menu-opening','opening',lobby);await settled(page,lobby);await capture(page,engine+'-cold-menu-settled','settled',lobby);
  await api({type:'bots-set',count:3});for(let i=0;i<60&&(await api()).players.length<3;i++)await delay(50);
  for(const id of (process.env.QA_GAMES||'curling,bowling,push').split(',')){
   await film(page,engine+'-'+id+'-launch',()=>api({type:'launch',id}),expectedFor);
   if(process.env.QA_MAIN_RENDER_TRACE&&['curling','bowling','swarm_gate','peek_shoot'].includes(id)&&!process.env.QA_MISSING_STATE){await page.waitForFunction(()=>document.getElementById('gameFrame').contentWindow.__curtain247StageStatus?.().phase==='waiting');if(process.env.QA_PRODUCTION_GUARD)assert.equal(await page.locator('#gameFrame').evaluate(frame=>frame.contentWindow.__curtain247StageStatus().clock),0);}
   const preparation=await page.locator('#gameFrame').evaluate(frame=>({trace:frame.contentWindow.__curtain247,candidate:frame.contentWindow.__partyInitialScenePreparation||null}));report.rows.push({name:engine+'-'+id+'-preparation',preparation});if((process.env.QA_READINESS_CANDIDATE||process.env.QA_PRODUCTION_GUARD)&&['curling','bowling','swarm_gate','peek_shoot'].includes(id))assert(preparation.candidate,'Explicit readiness QA proof must exist for actual Stage');if(preparation.candidate){assert.equal(preparation.candidate.status,'ready');assert.equal(preparation.candidate.simulationAdvanced,false);assert(preparation.candidate.events.filter(e=>['first-render-returned','first-frame-gpu-complete','preparation-ready'].includes(e.name)).every(e=>['closed','revealing'].includes(e.curtain)),'Candidate initial draw finishes under closed cover');}
   if(process.env.QA_MISSING_STATE){
    await page.waitForFunction(()=>!!document.getElementById('gameFrame').contentWindow.__curtain247HeldSnapshot);await delay(220);const held=await page.locator('#gameFrame').evaluate(frame=>({status:frame.contentWindow.__curtain247StageStatus(),main:frame.contentWindow.__curtain247.mainRenders.filter(e=>e.main&&e.matchPhase==='unknown'&&e.warmup==='ready'),heldCount:frame.contentWindow.__curtain247HeldCount,heldPhase:frame.contentWindow.__curtain247HeldSnapshot?.data?.phase}));assert.equal(held.status.phase,'unknown');assert.equal(held.heldPhase,'waiting');if(process.env.QA_STATE_GUARD||process.env.QA_PRODUCTION_GUARD){assert.equal(held.status.clock,0);assert.equal(held.main.length,0);assert.deepEqual(held.status.unknownUpdates,{objects:0,effects:0});}else{assert(held.status.clock>0);assert(held.main.length>0);assert(held.status.unknownUpdates.effects>0);}await page.locator('#gameFrame').evaluate(frame=>frame.contentWindow.__curtain247ReleaseSnapshot());await page.waitForFunction(()=>document.getElementById('gameFrame').contentWindow.__curtain247StageStatus().phase==='waiting');await delay(120);const released=await page.locator('#gameFrame').evaluate(frame=>frame.contentWindow.__curtain247StageStatus());if(process.env.QA_STATE_GUARD||process.env.QA_PRODUCTION_GUARD)assert.equal(released.clock,0);report.rows.push({name:engine+'-'+id+'-held-first-snapshot',held,released});
   }
   if(process.env.QA_PLAY_DRAW){const state=await api();await api({type:'force-start',instance:state.active.instance});await page.waitForFunction(()=>document.getElementById('gameFrame').contentWindow.__curtain247?.mainRenders.some(e=>e.main&&e.matchPhase!=='waiting'),null,{timeout:10000});report.rows.push({name:engine+'-'+id+'-actual-start-trace',trace:await page.locator('#gameFrame').evaluate(frame=>frame.contentWindow.__curtain247)});}
   await film(page,engine+'-'+id+'-return',()=>api({type:'stop'}),expectedFor);
  }
  if(process.env.QA_TRACE_ONLY){
   if(process.env.QA_STRICT_REDUCED){await page.emulateMedia({reducedMotion:'reduce'});await settled(page,expectedFor(await api({type:'launch',id:'curling'})));const reduced=expectedFor(await api({type:'stop'}));await settled(page,reduced);await capture(page,engine+'-reduced-return-settled','settled',reduced);}
   report.rows.push({name:engine+'-outer-work',tasks:await page.evaluate(()=>__curtain247.tasks)});await page.close();await browser.close();browser=null;fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));continue;
  }
  // A newer destination must not reuse the older complete document. The warmup
  // hold below additionally tests the real sports scene's explicit pending flag.
  await settled(page,expectedFor(await api({type:'launch',id:'curling'})));
  let release;const held=new Promise(resolve=>release=resolve),pattern='**/games/push/host?mode=push';await page.route(pattern,async route=>{await held;await route.continue();});const next=expectedFor(await api({type:'launch',id:'push'}));await page.waitForFunction(()=>HeyPalsTVMotion.diagnostics().state==='revealing');await delay(250);const blocked=await capture(page,engine+'-destination-held','covered',next);assert.equal(blocked.state,'revealing');release();await settled(page,next);await page.unroute(pattern);report.rows.push({name:engine+'-held-destination',blocked,final:await capture(page,engine+'-destination-settled','settled',next)});
  await settled(page,expectedFor(await api({type:'stop'})));
  await api({type:'launch',id:'curling'});await page.waitForFunction(()=>HeyPalsTVMotion.diagnostics().state==='opening');const before=await capture(page,engine+'-reverse-before','opening',expectedFor(await api()));await api({type:'stop'});await page.waitForFunction(()=>HeyPalsTVMotion.diagnostics().state==='closing');const reversing=await capture(page,engine+'-reverse-closing','closing',expectedFor(await api()));const rapid=expectedFor(await api({type:'launch',id:'push'}));await settled(page,rapid);const after=await capture(page,engine+'-reverse-settled','settled',rapid);report.rows.push({name:engine+'-reverse',before,reversing,after});
  await settled(page,expectedFor(await api({type:'stop'})));await page.emulateMedia({reducedMotion:'reduce'});await settled(page,expectedFor(await api({type:'launch',id:'curling'})));const reducedLobby=expectedFor(await api({type:'stop'}));await settled(page,reducedLobby);report.rows.push({name:engine+'-reduced-return',final:await capture(page,engine+'-reduced-return-settled','settled',reducedLobby)});await page.emulateMedia({reducedMotion:'no-preference'});
  // Isolated page keeps the real route/renderer but holds its ready signal and
  // limits only outer-shell RAF. This is a readiness fault fixture, not FPS QA.
  const slow=await browser.newPage({viewport:{width:1280,height:720}});await slow.addInitScript(()=>{if(window===top){window.requestAnimationFrame=fn=>setTimeout(()=>fn(performance.now()),80);window.cancelAnimationFrame=clearTimeout;}else document.addEventListener('DOMContentLoaded',()=>{if(!location.pathname.startsWith('/games/'))return;window.__curtain247Hold=true;const flag=()=>document.body.dataset.shaderWarmup='pending';flag();new MutationObserver(()=>{if(window.__curtain247Hold&&document.body.dataset.shaderWarmup!=='pending')flag();}).observe(document.body,{attributes:true,attributeFilter:['data-shader-warmup']});},{once:true});});slow.on('pageerror',error=>report.errors.push({engine,slow:true,error:error.message}));await slow.goto(origin+'/tv');await settled(slow,lobby);const warming=expectedFor(await api({type:'launch',id:'bowling'}));await slow.waitForFunction(()=>HeyPalsTVMotion.diagnostics().state==='revealing');await delay(350);const warmHeld=await capture(slow,engine+'-warmup-held','covered',warming);assert.equal(warmHeld.state,'revealing');const readyAt=await slow.locator('#gameFrame').evaluate(frame=>{frame.contentWindow.__curtain247Hold=false;frame.contentDocument.body.dataset.shaderWarmup='ready';return frame.contentWindow.performance.timeOrigin+frame.contentWindow.performance.now();});
  await slow.waitForFunction(()=>HeyPalsTVMotion.diagnostics().state==='opening');const slowOpening=await capture(slow,engine+'-warmup-opening','opening',warming);await settled(slow,warming);const slowFinal=await capture(slow,engine+'-warmup-settled','settled',warming);await slow.close();await settled(page,warming);await settled(page,expectedFor(await api({type:'stop'})));report.rows.push({name:engine+'-slow-warmup-hold',held:warmHeld,readyAt,opening:slowOpening,final:slowFinal});
  report.rows.push({name:engine+'-outer-work',tasks:await page.evaluate(()=>__curtain247.tasks)});await page.close();await browser.close();browser=null;fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));
 }
 assert.deepEqual(report.errors,[]);report.status='passed';console.log(JSON.stringify({status:report.status,rows:report.rows.length,captures:report.captures.length}));
}catch(error){report.status='failed';report.failure=error.stack;process.exitCode=1;console.error(error);}finally{await browser?.close();server?.kill();clearTimeout(watchdog);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));}})();
