'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),pw=require('playwright');
const before=process.env.QA_BEFORE==='1',out=path.resolve('output/playwright/keyboard243/browser-'+(before?'before':'after'));fs.mkdirSync(out,{recursive:true});const report={method:'Real /play application; native controller bridge AND persistent tabs. Keyboard viewport modes are synthetic browser regression coverage, not iOS software keyboard evidence.',rows:[],failures:[],errors:[]};
const child=spawn(process.execPath,['server.js'],{env:{...process.env,PARTY_EMBEDDED:'1',PARTY_EPHEMERAL:'1',PARTY_INTERNAL_PORT:'0',PARTY_PORT:'0',PARTY_NO_BROWSER:'1',PARTY_ADMIN_KEY:'keyboard243'}});let log='';child.stdout.on('data',d=>log+=d);child.stderr.on('data',d=>log+=d);const wait=ms=>new Promise(r=>setTimeout(r,ms));
const bridge=fs.readFileSync('public/native-shell/controller-bridge.js','utf8'),tabs=fs.readFileSync('public/native-shell/tabs.js','utf8');
const check=(ok,message)=>{if(!ok)report.failures.push(message)};
(async()=>{try{for(let i=0;i<300&&!/localhost:(\d+)/.test(log);i++)await wait(50);assert(/localhost:(\d+)/.test(log),log);const origin='http://127.0.0.1:'+log.match(/localhost:(\d+)/)[1];
for(const engine of ['webkit','chromium']){const browser=await pw[engine].launch(engine==='chromium'?{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}:{});try{for(const [width,height]of[[320,740],[393,852]])for(const mode of ['overlay','resize']){
 const p=await browser.newPage({viewport:{width,height},isMobile:true,hasTouch:true});p.on('pageerror',e=>report.errors.push({engine,width,mode,message:e.message}));await p.addInitScript({content:'window.__messages=[];window.webkit={messageHandlers:{partyShell:{postMessage(m){window.__messages.push(m)}}}};'+bridge+'\nwindow.__partyPersistentTabs=true;'+tabs});if(mode==='overlay')await p.addInitScript(()=>{const v=new EventTarget();Object.defineProperties(v,{height:{get:()=>window.__testKeyboard?innerHeight-310:innerHeight},width:{get:()=>innerWidth},offsetTop:{get:()=>0},offsetLeft:{get:()=>0},scale:{get:()=>1}});window.__testVV=v;Object.defineProperty(window,'visualViewport',{value:v,configurable:true});});await p.goto(origin+'/play');await p.locator('#name').fill('Taylor');await p.locator('#joinForm button[type=submit]').click();await p.locator('#home').waitFor();await p.addScriptTag({path:'public/native-shell/nearby-rooms.js'});if(!before)check(await p.evaluate(()=>!!window.PartyInputViewport),engine+' '+width+' '+mode+' shared keyboard asset is served');await p.evaluate(()=>document.fonts.ready);await wait(500);
 const rooms=[{id:'own',name:'Friday night',players:4},{id:'neighbor',name:'Alexandra’s Friday party',game:'Pocket Strike',players:8},{id:'third',name:'Friends in the living room',players:16}];
 const prefix=engine+'-'+width+'-'+mode;
 const sample=async(name,selectors)=>{const row=await p.evaluate(selectors=>{const rect=n=>{if(!n)return null;const r=n.getBoundingClientRect();return {top:r.top,bottom:r.bottom,left:r.left,right:r.right,height:r.height}},viewport=visualViewport;return {innerHeight,bottom:viewport.height+viewport.offsetTop,top:viewport.offsetTop,keyboard:document.body.hasAttribute('data-hp-keyboard'),active:document.activeElement?.id,rects:selectors.map(s=>({selector:s,rect:rect(document.querySelector(s))})),dialog:document.querySelector('dialog[open]:modal')?.id,clips:selectors.map(s=>{const n=document.querySelector(s),r=n?.getBoundingClientRect();if(!r)return false;for(let a=n.parentElement;a&&a!==document.body;a=a.parentElement){if(/(auto|scroll|hidden|clip)/.test(getComputedStyle(a).overflowY)){const b=a.getBoundingClientRect();if(r.top<b.top-1||r.bottom>b.bottom+1)return false;}}return true}),branches:[...document.querySelectorAll('[data-hp-modal-background]')].map(n=>getComputedStyle(n).filter)}},selectors);row.name=name;row.engine=engine;row.width=width;row.mode=mode;row.file=prefix+'-'+name+'.png';report.rows.push(row);await p.screenshot({path:path.join(out,row.file)});for(const [i,item] of row.rects.entries()){const r=item.rect;check(r&&r.top>=row.top-1&&r.bottom<=row.bottom-8&&row.clips[i],prefix+' '+name+' '+item.selector+' within keyboard viewport '+JSON.stringify(row));}fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));};
 const keyboard=async open=>{if(mode==='resize'){await p.setViewportSize({width,height:open?height-310:height})}else{await p.evaluate(open=>{if(!window.__testVV){const v=new EventTarget();Object.defineProperties(v,{height:{get:()=>window.__testKeyboard?innerHeight-310:innerHeight},width:{get:()=>innerWidth},offsetTop:{get:()=>0},offsetLeft:{get:()=>0},scale:{get:()=>1}});window.__testVV=v;Object.defineProperty(window,'visualViewport',{value:v,configurable:true});}window.__testKeyboard=open;visualViewport.dispatchEvent(new Event('resize'));},open)}await wait(350)};
 await p.evaluate(rooms=>{LocalPartyRooms.update(rooms,'own');nearbyToggle.click()},rooms);await wait(400);await p.locator('.nearby-rename-toggle').click();await p.locator('#nearbyRoomName').fill('Moonlight crew');await keyboard(true);await sample('room-rename',['#nearbyRoomName','.nearby-rename-save','#nearbyClose']);
 await p.evaluate(rooms=>LocalPartyRooms.update(rooms.map(r=>({...r,players:r.players+1})),'own'),rooms);check(await p.locator('#nearbyRoomName').inputValue()==='Moonlight crew',prefix+' draft survives discovery update');await p.locator('.nearby-rename-save').evaluate(n=>n.click());check(await p.evaluate(()=>__messages.some(m=>m.type==='rename-room'&&m.name==='Moonlight crew')),prefix+' rename sends native request');await p.evaluate(()=>LocalPartyRooms.renamed('Moonlight crew'));await keyboard(false);
 for(let i=0;i<4;i++){await p.locator('.nearby-rename-toggle').evaluate(n=>n.click());await wait(35);await p.locator('.nearby-rename-toggle').evaluate(n=>n.click());await wait(35)}await wait(260);check(await p.locator('.nearby-rename-toggle').getAttribute('aria-expanded')==='false',prefix+' rapid disclosure settlesclosed');
 await p.locator('[role=tab]').filter({hasText:'By code'}).click();await p.locator('.rooms-code-cells input').first().pressSequentially('123456');await keyboard(true);await sample('room-code',['.rooms-code-cells','.rooms-code-panel>.primary','#nearbyClose']);check(await p.locator('.rooms-code-cells input').evaluateAll(ns=>ns.map(n=>n.value).join(''))==='123456',prefix+' code advances');await p.locator('.rooms-code-cells input').nth(5).press('Backspace');await p.locator('.rooms-code-cells input').nth(5).press('Backspace');check(await p.locator('.rooms-code-cells input').nth(4).evaluate(n=>n===document.activeElement),prefix+' deletion returns previous');await keyboard(false);
 await p.locator('#nearbyClose').evaluate(n=>n.click());await wait(260);check(!await p.evaluate(()=>document.querySelector('[data-hp-modal-background]')||document.body.hasAttribute('data-hp-modal-active')),prefix+' popupclose cleansblur in260ms');
 await p.locator('#nearbyToggle').evaluate(n=>n.click());await wait(250);await p.locator('#nearbyClose').evaluate(n=>n.click());await wait(55);await p.locator('#nearbyToggle').evaluate(n=>n.click());await wait(260);check(await p.evaluate(()=>nearbyDialog.open&&!nearbyDialog.classList.contains('lp-dialog-closing')),prefix+' close at55ms immediately reverses on reopen');await p.locator('#nearbyClose').evaluate(n=>n.click());await wait(260);
 await p.locator('#edit').evaluate(n=>n.click());await wait(700);await p.locator('#name').focus();await keyboard(true);await sample('profile-name',['#name','#joinForm button[type=submit]','#profileCancel']);await p.locator('#profileCancel').evaluate(n=>n.click());await keyboard(false);await wait(500);
 const search=p.locator('input[type=search]').first();await search.scrollIntoViewIfNeeded();await search.focus();await keyboard(true);await sample('catalog-search',['input[type=search]']);await search.fill('Curling');await keyboard(false);await p.evaluate(()=>document.activeElement.blur());await wait(250);check(!await p.evaluate(()=>document.body.hasAttribute('data-hp-keyboard')||document.querySelector('[data-hp-keyboard-panel]')),prefix+' keyboard geometry restored');
 await p.close();
}}finally{await browser.close();}}
}finally{child.kill();report.ok=!report.failures.length&&!report.errors.length;fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));}console.log(JSON.stringify({rows:report.rows.length,failures:report.failures.length,errors:report.errors,ok:report.ok}));if(!before&&!report.ok)process.exitCode=1;})().catch(e=>{report.errors.push({message:e.stack});fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.error(e);process.exitCode=1});
