'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),express=require('express'),pw=require('playwright');
const out=path.resolve('output/playwright/keyboard243/host-after');fs.mkdirSync(out,{recursive:true});const tabs=fs.readFileSync('public/native-shell/tabs.js','utf8'),catalog=require('../../lib/catalog'),report={method:'Native host source with actual host tabs injection; synthetic keyboard overlay/resizing. Not device keyboard evidence.',rows:[],failures:[],errors:[]};const wait=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{const server=express().use(express.static('public')).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));try{for(const engine of ['webkit','chromium']){const b=await pw[engine].launch(engine==='chromium'?{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}:{});try{for(const [width,height]of[[320,740],[393,852]])for(const mode of ['overlay','resize']){
const p=await b.newPage({viewport:{width,height},isMobile:true,hasTouch:true});p.on('pageerror',e=>report.errors.push(e.message));await p.addInitScript({content:'window.__messages=[];window.webkit={messageHandlers:{partyShell:{postMessage(m){__messages.push(m)}}}};window.__partyPersistentTabs=true;'+tabs});if(mode==='overlay')await p.addInitScript(()=>{const v=new EventTarget();Object.defineProperties(v,{height:{get:()=>window.__testKeyboard?innerHeight-310:innerHeight},width:{get:()=>innerWidth},offsetTop:{get:()=>0},offsetLeft:{get:()=>0},scale:{get:()=>1}});window.__testVV=v;Object.defineProperty(window,'visualViewport',{value:v,configurable:true});});await p.goto(`http://127.0.0.1:${server.address().port}/native-shell/index.html`);await p.evaluate(catalog=>LocalPartyHost.update({catalog,players:[{id:'a',name:'Taylor',connected:true}],leaderboard:[],votes:[],screens:1,native:{ready:true,catalogReady:true},selected:null}),catalog);await p.addScriptTag({url:`http://127.0.0.1:${server.address().port}/native-shell/nearby-rooms.js`});await p.evaluate(()=>document.fonts.ready);await wait(500);
const prefix=engine+'-'+width+'-'+mode;const keyboard=async open=>{if(mode==='resize')await p.setViewportSize({width,height:open?height-310:height});else await p.evaluate(open=>{window.__testKeyboard=open;visualViewport.dispatchEvent(new Event('resize'));},open);await wait(350)};
const sample=async(name,selectors)=>{const row=await p.evaluate(selectors=>{const rect=n=>{const r=n?.getBoundingClientRect();return r?{top:r.top,bottom:r.bottom,left:r.left,right:r.right}:null};const clips=n=>{const r=n?.getBoundingClientRect();if(!r)return false;for(let a=n.parentElement;a&&a!==document.body;a=a.parentElement){if(/(auto|scroll|hidden|clip)/.test(getComputedStyle(a).overflowY)){const b=a.getBoundingClientRect();if(r.top<b.top-1||r.bottom>b.bottom+1)return false;}}return true};return {bottom:visualViewport.height+visualViewport.offsetTop,top:visualViewport.offsetTop,innerHeight,keyboard:document.body.hasAttribute('data-hp-keyboard'),active:document.activeElement?.id,rects:selectors.map(s=>({selector:s,rect:rect(document.querySelector(s)),visible:clips(document.querySelector(s))}))}},selectors);Object.assign(row,{engine,width,mode,name,file:prefix+'-'+name+'.png'});report.rows.push(row);for(const {selector,rect:r,visible}of row.rects)if(!r||!visible||r.top<row.top-1||r.bottom>row.bottom-8)report.failures.push(prefix+' '+name+' '+selector+': '+JSON.stringify(row));await p.screenshot({path:path.join(out,row.file)});fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));};
await p.evaluate(()=>{LocalPartyRooms.update([{id:'own',name:'Friday night',players:4},{id:'friend',name:'Friends in the living room',game:'Pocket Strike',players:8}],'own');nearbyToggle.click()});await wait(400);await p.locator('.nearby-rename-toggle').click();await keyboard(true);await sample('room-rename',['#nearbyRoomName','.nearby-rename-save','#nearbyClose']);await keyboard(false);await p.locator('[role=tab]').filter({hasText:'By code'}).click();await p.locator('[data-room-digit]').first().pressSequentially('123456');await keyboard(true);await sample('room-code',['.rooms-code-cells','.rooms-code-panel>.primary','#nearbyClose']);await keyboard(false);await p.locator('#nearbyClose').evaluate(n=>n.click());await wait(260);
const s=p.locator('#search');await s.scrollIntoViewIfNeeded();await s.focus();await keyboard(true);await sample('catalog-search',['#search']);await keyboard(false);await p.evaluate(()=>document.activeElement.blur());await wait(250);assert(!await p.evaluate(()=>document.body.hasAttribute('data-hp-keyboard')||document.querySelector('[data-hp-keyboard-panel]')));await p.close();
}}finally{await b.close()}}}finally{await new Promise(r=>server.close(r));report.ok=!report.failures.length&&!report.errors.length;fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));}console.log(JSON.stringify({rows:report.rows.length,failures:report.failures.length,errors:report.errors,ok:report.ok}));assert(report.ok,JSON.stringify(report.failures));})().catch(e=>{console.error(e);process.exitCode=1});
