'use strict';
// Focused structural/ResizeObserver contract using the production bridge.
const {chromium,webkit}=require(process.env.PARTY_PLAYWRIGHT||'playwright'),express=require('express'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../..'),out=path.join(root,'output/playwright/performance243/bridge');fs.mkdirSync(out,{recursive:true});
(async()=>{const app=express();app.get('/bridge-parent',(req,res)=>res.type('html').send(`<div id="play"><div class="gamebar" data-layout="centered-scoreboard"></div><div class="tv-info-dock" style="position:absolute;left:400px;top:0;width:200px;height:80px"></div><iframe id="gameFrame" src="/bridge-child" style="width:960px;height:600px"></iframe></div><script>PARTY_INSTANCE='bridge243';PARTY_DISPLAY_ONLY=true;PARTY_PROFILE={};__layoutEvents=0;addEventListener('message',e=>{if(e.data?.type==='party-tv-layout')__layoutEvents++});</script>`));app.get('/bridge-child',(req,res)=>res.type('html').send(`<style>body{margin:0}#fixed{width:280px;height:220px;display:flex;flex-direction:column;align-items:center}#lead{width:220px;flex:none}#anchor{height:40px;width:80px;flex:none}#clock{position:absolute;top:400px;width:100px;height:20px}</style><div id="fixed"><div id="lead">Short</div><div id="anchor" data-tv-hud-anchor>Anchor</div></div><span id="clock">0</span><script src="/bridge.js" data-prefix="/games/kart"></script>`));app.use(express.static(path.join(root,'public')));const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const reports=[];
try{for(const[engine,provider]of Object.entries({chromium,webkit})){const browser=await provider.launch({headless:true,...(engine==='chromium'?{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}:{})});try{const p=await browser.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:'+server.address().port+'/bridge-parent');const frame=p.frames().find(f=>f.url().includes('bridge-child'));await p.waitForFunction(()=>__layoutEvents>0);await p.waitForTimeout(150);await p.evaluate(()=>__layoutEvents=0);
await frame.evaluate(()=>{for(let i=0;i<100;i++)document.getElementById('clock').textContent=String(i);});await p.waitForTimeout(150);assert.equal(await p.evaluate(()=>__layoutEvents),0,'Unchanged-size clock text does not schedule full parent fit');
const top=await frame.locator('#anchor').evaluate(n=>n.getBoundingClientRect().top);await frame.locator('#lead').evaluate(n=>n.textContent='A long sentence that wraps to several lines while the fixed-height layout container does not change size.');await p.waitForFunction(()=>__layoutEvents>0);assert((await frame.locator('#anchor').evaluate(n=>n.getBoundingClientRect().top))>top,'Sibling RO sees moved anchor inside fixed-height parent');
await p.evaluate(()=>__layoutEvents=0);await frame.evaluate(()=>{const n=document.createElement('div');n.dataset.tvHudAnchor='';n.style.cssText='width:90px;height:50px';document.getElementById('fixed').append(n);});await p.waitForFunction(()=>__layoutEvents>0);await p.waitForTimeout(100);
await p.evaluate(()=>__layoutEvents=0);await frame.evaluate(()=>{document.querySelector('[data-tv-hud-anchor]').removeAttribute('data-tv-hud-anchor');});await p.waitForFunction(()=>__layoutEvents>0);
await p.evaluate(()=>__layoutEvents=0);await frame.evaluate(()=>document.getElementById('fixed').lastElementChild.remove());await p.waitForFunction(()=>__layoutEvents>0);
await p.setViewportSize({width:1920,height:1080});await p.waitForTimeout(100);assert.equal(errors.length,0,errors.join('\n'));reports.push({engine,clockLayouts:0,fixedParentMovedAnchor:true,addedRemovedAnchors:true,resize:true,errors});}finally{await browser.close();}}
fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(reports,null,2));console.log('PASS shared stage bridge: clock guard, fixed-parent sibling wrap, anchor insert/remove, resize; Chromium/WebKit');
}finally{await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
