'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),express=require('express'),pw=require('playwright');
const out=path.resolve('output/playwright/phone-copy133');fs.mkdirSync(out,{recursive:true});const tabs=fs.readFileSync('public/native-shell/tabs.js','utf8'),bridge=fs.readFileSync('public/native-shell/controller-bridge.js','utf8');
const child=spawn(process.execPath,['server.js'],{env:{...process.env,PARTY_EMBEDDED:'1',PARTY_EPHEMERAL:'1',PARTY_INTERNAL_PORT:'0',PARTY_PORT:'0',PARTY_NO_BROWSER:'1',PARTY_ADMIN_KEY:'phone-copy133'}});let log='';child.stdout.on('data',d=>log+=d);child.stderr.on('data',d=>log+=d);const sleep=ms=>new Promise(r=>setTimeout(r,ms));const report={rows:[],errors:[]};
(async()=>{const server=express().use(express.static('public')).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));try{for(let i=0;i<300&&!/localhost:(\d+)/.test(log);i++)await sleep(50);assert(/localhost:(\d+)/.test(log),log);const origin='http://127.0.0.1:'+log.match(/localhost:(\d+)/)[1];
for(const name of ['chromium','webkit']){const browser=await pw[name].launch(name==='chromium'?{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}:{});try{for(const [width,height] of [[393,852],[320,568]]){
 const native=await browser.newPage({viewport:{width,height},isMobile:true,hasTouch:true});native.on('pageerror',e=>report.errors.push(e.message));await native.addInitScript(tabs=>{window.webkit={messageHandlers:{partyShell:{postMessage(){}}}};window.__partyPersistentTabs=true;(0,eval)(tabs);},tabs);await native.goto(`http://127.0.0.1:${server.address().port}/native-shell/index.html`);await native.evaluate(catalog=>LocalPartyHost.update({catalog,players:[{id:'a',name:'Taylor',connected:true}],leaderboard:[],votes:[],screens:1,native:{ready:true,catalogReady:true},selected:'push',tv:{mode:'none',focusNumber:1,total:catalog.length}}),require('../../lib/catalog'));await native.evaluate(()=>document.fonts.ready);await native.waitForTimeout(800);
 await native.screenshot({path:path.join(out,`${name}-${width}-native.png`)});const masthead=await native.evaluate(()=>{const e=document.querySelector('.intro>div>.eyebrow'),c=document.querySelector('#gameCount'),h=document.querySelector('.intro h1'),r=e.getBoundingClientRect(),pick=document.querySelector('#choiceStrip').getBoundingClientRect();return {eyebrow:{y:r.y,bottom:r.bottom},pickBottom:pick.bottom,count: getComputedStyle(c.querySelector('.hp-menu-counter-value')).fontSize,label:getComputedStyle(c.querySelector('.hp-menu-counter-label')).fontSize,shadow:getComputedStyle(h).filter,aboveHero:document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)===e,overflow:document.documentElement.scrollWidth>innerWidth};});assert(!masthead.overflow);assert(masthead.aboveHero,'headline art must not cover intro copy');assert(masthead.shadow.includes('drop-shadow'));assert(masthead.eyebrow.y>=masthead.pickBottom+50,'intro copy clears the dense sticky fade');
 const page=await browser.newPage({viewport:{width,height},isMobile:true,hasTouch:true});page.on('pageerror',e=>report.errors.push(e.message));await page.addInitScript(({tabs,bridge})=>{window.webkit={messageHandlers:{partyShell:{postMessage(){}}}};(0,eval)(bridge);window.__partyPersistentTabs=true;(0,eval)(tabs);},{tabs,bridge});await page.goto(origin+'/play');await page.locator('#name').fill('Taylor');await page.locator('#joinForm button[type=submit]').click();await page.locator('#home').waitFor();await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(800);
 const summary=page.locator('.return-entry-help>summary');await summary.scrollIntoViewIfNeeded();await page.waitForTimeout(250);await page.screenshot({path:path.join(out,`${name}-${width}-closed.png`)});
 const samples=[];for(const offset of [40,110,190]){await page.evaluate(offset=>{const d=document.querySelector('.return-entry-help');for(const a of d.getAnimations())a.cancel();d.open=false;d.style.overflow='';d.style.height='';d.querySelector('summary').click();const a=d.getAnimations().find(a=>a.effect.getKeyframes().some(k=>k.height));if(!a)throw Error('missing details height animation');a.pause();a.currentTime=offset;},offset);samples.push(await page.evaluate(()=>{const d=document.querySelector('.return-entry-help'),s=document.querySelector('.return-entry-shell'),r=s.getBoundingClientRect(),g=getComputedStyle(s,'::before');return {height:d.getBoundingClientRect().height,clip:getComputedStyle(d).overflow,fade:g.backgroundImage,fadeDisplay:g.display,fadeRect:{y:r.y+parseFloat(g.top),height:parseFloat(g.height)},outsideClip:s.contains(d)&&getComputedStyle(s).overflow==='visible',white:getComputedStyle(d.querySelector('svg')).color,arrow:d.querySelector('svg')?.dataset.packIcon};}));await page.screenshot({path:path.join(out,`${name}-${width}-opening-${offset}.png`)});await page.evaluate(async()=>{const a=document.querySelector('.return-entry-help').getAnimations()[0];a.finish();await Promise.resolve();});}
 await page.waitForTimeout(100);await page.screenshot({path:path.join(out,`${name}-${width}-open.png`)});await summary.click();await page.waitForTimeout(80);await page.screenshot({path:path.join(out,`${name}-${width}-closing.png`)});await page.waitForTimeout(300);assert.equal(await page.locator('.return-entry-help').getAttribute('open'),null);
 for(const s of samples){assert(s.fade.includes('radial-gradient'));assert(s.outsideClip);assert.equal(s.white,'rgb(255, 255, 255)');assert.equal(s.arrow,'arrow-up-right');}
 report.rows.push({browser:name,width,masthead,samples,realControllerBridge:await page.evaluate(()=>document.body.classList.contains('native-controller')),tabs:await page.evaluate(()=>!!window.LocalPartyTabs)});await page.close();await native.close();
 }}finally{await browser.close();}}
 assert.deepEqual(report.errors,[]);
}finally{child.kill();await new Promise(r=>server.close(r));fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));}console.log(JSON.stringify(report));})().catch(e=>{console.error(e);process.exitCode=1;});
