'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),pw=require('playwright');
const out=path.resolve(process.env.QA_OUTPUT||'output/playwright/scroll170/outside');fs.mkdirSync(out,{recursive:true});
const child=spawn(process.execPath,['server.js'],{env:{...process.env,PARTY_EMBEDDED:'1',PARTY_EPHEMERAL:'1',PARTY_INTERNAL_PORT:'0',PARTY_PORT:'0',PARTY_NO_BROWSER:'1'}});let log='';child.stdout.on('data',x=>log+=x);child.stderr.on('data',x=>log+=x);const wait=ms=>new Promise(r=>setTimeout(r,ms)),rows=[];
(async()=>{try{for(let i=0;i<300&&!/localhost:(\d+)/.test(log);i++)await wait(50);assert(/localhost:(\d+)/.test(log),log);const url='http://127.0.0.1:'+log.match(/localhost:(\d+)/)[1];for(const engine of ['chromium','webkit']){const browser=await pw[engine].launch(engine==='chromium'?{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}:{});try{const p=await browser.newPage({viewport:{width:393,height:852},isMobile:true,hasTouch:true});await p.goto(url+'/play');await p.locator('#name').fill('Outside Review');await p.locator('#joinForm button[type=submit]').click();await p.locator('#home').waitFor();await p.evaluate(()=>document.fonts.ready);await wait(450);if(process.env.QA_LEGACY==='1')await p.addStyleTag({content:'html body dialog.lp-dialog-managed:not([open]){transition:opacity 200ms,transform 200ms,display 200ms allow-discrete,overlay 200ms allow-discrete!important}'});
for(const id of ['joinDialog','confirmStop','roomDialog','statsDialog']){
 await p.evaluate(id=>{const d=document.getElementById(id);d.returnValue='yes';d.showModal();},id);await wait(350);const rect=await p.locator('#'+id).boundingBox();const point={x:rect.x+rect.width/2,y:Math.max(1,rect.y-12)};assert(rect.y>2,id+' has outside region');
 // A gesture beginning outside and moving must not dismiss the sheet.
 await p.mouse.move(point.x,point.y);await p.mouse.down();await p.mouse.move(point.x+28,point.y);await p.mouse.up();await wait(230);assert(await p.locator('#'+id).evaluate(d=>d.open),id+' dismissed after drag');
 await p.screenshot({path:path.join(out,engine+'-'+id+'.png')});
 await p.evaluate(id=>{window.__closeFrames=[];const d=document.getElementById(id),start=performance.now();requestAnimationFrame(function frame(t){const s=getComputedStyle(d);__closeFrames.push({t:t-start,open:d.open,overlay:s.overlay,display:s.display,opacity:s.opacity,transition:s.transitionProperty});if(t-start<520)requestAnimationFrame(frame);});},id);
 await p.mouse.click(point.x,point.y);const immediate=await p.locator('#'+id).evaluate(d=>({open:d.open,closing:d.classList.contains('lp-dialog-closing')}));assert(immediate.open&&immediate.closing,id+' skipped animated close');await wait(550);const frames=await p.evaluate(()=>__closeFrames);fs.writeFileSync(path.join(out,engine+'-'+id+'-close.json'),JSON.stringify(frames,null,2));assert(!frames.some(f=>!f.open&&f.overlay==='auto'),id+' closed dialog retained top-layer backdrop');assert(await p.locator('#'+id).evaluate(d=>!d.open&&d.returnValue===''),id+' not safely cancelled');rows.push({engine,id,dragProtected:true,animated:true,cancelled:true});
}
// Only the top dialog closes, and explicit blocking opt-out is respected.
await p.evaluate(()=>{statsDialog.showModal();confirmStop.showModal();confirmStop.dataset.backdropDismiss='false';});await wait(350);let r=await p.locator('#confirmStop').boundingBox();await p.mouse.click(r.x+r.width/2,r.y-10);await wait(230);assert(await p.locator('#confirmStop').evaluate(d=>d.open));await p.locator('#confirmStop').evaluate(d=>delete d.dataset.backdropDismiss);await p.mouse.click(r.x+r.width/2,r.y-10);await wait(250);assert(await p.evaluate(()=>statsDialog.open&&!confirmStop.open));await p.evaluate(()=>statsDialog.close());await wait(250);
await p.evaluate(()=>document.getElementById('edit').click());await wait(350);const profile=await p.locator('#onboarding').boundingBox();assert(profile.y>2);await p.mouse.move(195,profile.y-8);await p.mouse.down();await p.mouse.move(220,profile.y-8);await p.mouse.up();await wait(250);assert(await p.evaluate(()=>document.body.classList.contains('profile-editing')));await p.mouse.click(195,profile.y-8);await wait(300);assert(!await p.evaluate(()=>document.body.classList.contains('profile-editing')));rows.push({engine,id:'profile',dragProtected:true,closed:true});
await p.close();}finally{await browser.close();}}}finally{child.kill();fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(rows,null,2));}console.log(JSON.stringify({rows:rows.length,ok:true}));})().catch(e=>{console.error(e);process.exitCode=1;});
