'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),express=require('express'),pw=require('playwright');
const out=path.resolve('output/playwright/scroll170/menu');fs.mkdirSync(out,{recursive:true});const tabs=fs.readFileSync('public/native-shell/tabs.js','utf8'),bridge=fs.readFileSync('public/native-shell/controller-bridge.js','utf8');
const child=spawn(process.execPath,['server.js'],{env:{...process.env,PARTY_EMBEDDED:'1',PARTY_EPHEMERAL:'1',PARTY_INTERNAL_PORT:'0',PARTY_PORT:'0',PARTY_NO_BROWSER:'1',PARTY_ADMIN_KEY:'phone-copy133'}});let log='';child.stdout.on('data',d=>log+=d);child.stderr.on('data',d=>log+=d);const sleep=ms=>new Promise(r=>setTimeout(r,ms));const report={rows:[],errors:[]};
(async()=>{const server=express().use(express.static('public')).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));try{for(let i=0;i<300&&!/localhost:(\d+)/.test(log);i++)await sleep(50);assert(/localhost:(\d+)/.test(log),log);const origin='http://127.0.0.1:'+log.match(/localhost:(\d+)/)[1];
for(const name of ['webkit']){const browser=await pw[name].launch(name==='chromium'?{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}:{});try{for(const [width,height] of [[393,852]]){
 const native=await browser.newPage({viewport:{width,height},isMobile:true,hasTouch:true});native.on('pageerror',e=>report.errors.push(e.message));await native.addInitScript(tabs=>{window.webkit={messageHandlers:{partyShell:{postMessage(){}}}};window.__partyPersistentTabs=true;(0,eval)(tabs);},tabs);await native.goto(`http://127.0.0.1:${server.address().port}/native-shell/index.html`);await native.evaluate(catalog=>LocalPartyHost.update({catalog,players:[{id:'a',name:'Taylor',connected:true}],leaderboard:[],votes:[],screens:1,native:{ready:true,catalogReady:true},selected:'push',tv:{mode:'none',focusNumber:1,total:catalog.length}}),require('../../lib/catalog'));await native.evaluate(()=>document.fonts.ready);await native.waitForTimeout(800);
 const descriptionColors=await native.locator('#catalog .game .game-info>p').evaluateAll(nodes=>nodes.map(n=>({id:n.closest('.game').dataset.id,color:getComputedStyle(n).color,accent:getComputedStyle(n).getPropertyValue('--card')})));assert(new Set(descriptionColors.map(x=>x.color)).size>5,'descriptions follow game palettes');fs.writeFileSync(path.join(out,'description-colors.json'),JSON.stringify(descriptionColors,null,2));
 console.log('CTA',await native.evaluate(()=>{let b=document.querySelector('#choiceStart'),s=getComputedStyle(b,'::after');return{html:b.outerHTML,after:{content:s.content,display:s.display,bg:s.backgroundImage,mask:s.maskImage,animation:s.animation,play:s.animationPlayState,angle:s.getPropertyValue('--hp-edge-angle'),width:s.width,height:s.height,z:s.zIndex},cards:[...document.querySelectorAll('.native-game,.game,.fresh-card')].slice(0,3).map(e=>({tag:e.className,bg:getComputedStyle(e).background,blur:getComputedStyle(e).backdropFilter}))}}));assert(await native.locator('#choiceStart').evaluate(b=>getComputedStyle(b,'::before').content==='none'),'legacy halo disabled');
 const edge=()=>native.locator('#choiceStart').evaluate(b=>{const s=getComputedStyle(b,'::after');return{content:s.content,angle:s.getPropertyValue('--hp-edge-angle'),play:s.animationPlayState}});const e0=await edge();await native.waitForTimeout(1000);const e1=await edge();assert(e1.content!=='none'&&e1.play==='running'&&e0.angle!==e1.angle,JSON.stringify({e0,e1}));for(let phase=0;phase<3;phase++){await native.screenshot({path:path.join(out,`start-phase-${phase}.png`)});await native.waitForTimeout(700);}await native.screenshot({path:path.join(out,`${name}-${width}-native.png`)});await native.evaluate(()=>window.scrollTo(0,380));await native.waitForTimeout(350);await native.screenshot({path:path.join(out,`${name}-${width}-native-scrolled.png`)});await native.evaluate(()=>window.scrollTo(0,0));await native.waitForTimeout(350);const masthead=await native.evaluate(()=>{const e=document.querySelector('.intro>div>.eyebrow'),c=document.querySelector('#gameCount'),h=document.querySelector('.intro h1'),r=e.getBoundingClientRect(),pick=document.querySelector('#choiceStrip').getBoundingClientRect();return {startInsets:(()=>{const a=document.querySelector('#choiceStrip').getBoundingClientRect(),b=document.querySelector('#choiceStart').getBoundingClientRect();return{top:b.top-a.top,right:a.right-b.right,bottom:a.bottom-b.bottom};})(),choiceMeta:document.querySelector('#choiceMeta').outerHTML,choiceFonts:[...document.querySelectorAll('#choiceMeta *')].map(n=>[n.className,getComputedStyle(n).fontSize,getComputedStyle(n).fontStyle]),eyebrow:{y:r.y,bottom:r.bottom},pickBottom:pick.bottom,count: getComputedStyle(c.querySelector('.hp-menu-counter-value')).fontSize,label:getComputedStyle(c.querySelector('.hp-menu-counter-label')).fontSize,shadow:getComputedStyle(h).filter,aboveHero:document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)===e,overflow:document.documentElement.scrollWidth>innerWidth};});console.log('START_INSETS',JSON.stringify(masthead.startInsets));assert(!masthead.overflow);assert(masthead.aboveHero,'headline art must not cover intro copy');assert(masthead.shadow.includes('drop-shadow'));
 const page=await browser.newPage({viewport:{width,height},isMobile:true,hasTouch:true});await page.addInitScript(({tabs,bridge})=>{window.__messages=[];window.webkit={messageHandlers:{partyShell:{postMessage(m){window.__messages.push(m)}}}};(0,eval)(bridge);window.__partyPersistentTabs=true;(0,eval)(tabs);},{tabs,bridge});await page.goto(origin+'/play');await page.locator('#name').fill('Taylor');await page.locator('#joinForm button[type=submit]').click();await page.locator('#home').waitFor();await page.addScriptTag({path:'public/native-shell/nearby-rooms.js'});await page.evaluate(()=>document.fonts.ready);
 await page.screenshot({path:path.join(out,`controller-${name}-${width}.png`)});
 const web=await browser.newPage({viewport:{width,height},isMobile:true,hasTouch:true});await web.goto(origin+'/play');await web.locator('#name').fill('Taylor Web');await web.locator('#joinForm button[type=submit]').click();await web.locator('#home').waitFor();await web.evaluate(()=>document.fonts.ready);await web.waitForTimeout(800);console.log('HEADER',await web.evaluate(()=>{const h=document.querySelector('#brandHeader'),r=h.getBoundingClientRect();return{body:document.body.className,h:{height:r.height,top:r.top,position:getComputedStyle(h).position},before:{...Object.fromEntries(['display','background','backdropFilter','height','zIndex','maskImage'].map(k=>[k,getComputedStyle(h,'::before')[k]]))},after:{...Object.fromEntries(['display','background','height','zIndex'].map(k=>[k,getComputedStyle(h,'::after')[k]]))}}}));await web.screenshot({path:path.join(out,`web-controller-${name}-${width}.png`)});await web.close();
 const rooms=[{id:'own',name:'Your room',players:4},{id:'alice',name:'Alexandra’s Friday party',game:'Pocket Strike',players:8,phase:'playing'},{id:'long',name:'Очень длинное название комнаты друзей Александры',game:'Don’t Bite the Gate',players:16,phase:'waiting'}];
 await page.evaluate(rooms=>{LocalPartyRooms.update(rooms,'own');document.getElementById('nearbyToggle').click();},rooms);await page.waitForTimeout(800);console.log('GLASS',await page.locator('#nearbyDialog').evaluate(n=>({supports:CSS.supports('-webkit-touch-callout','none'),page:[...document.querySelectorAll('main,#home,#brandHeader')].map(x=>[x.id,x.parentElement.tagName,getComputedStyle(x).filter]),filter:getComputedStyle(n).backdropFilter,webkit:getComputedStyle(n).webkitBackdropFilter,bg:getComputedStyle(n).backgroundImage,modal:n.matches(':modal')})));await page.screenshot({path:path.join(out,`rooms-${name}-${width}.png`)});const bounds=await page.evaluate(()=>{const d=nearbyDialog.getBoundingClientRect(),b=nearbyClose.getBoundingClientRect();return{top:d.top,bottom:d.bottom,close:b.bottom,viewport:innerHeight};});assert(bounds.top>=0&&bounds.close<=bounds.viewport-56,JSON.stringify(bounds));await page.locator('[data-room=long]').scrollIntoViewIfNeeded();assert(await page.locator('[data-room=long] button').isVisible());await page.locator('[data-room="alice"] button').click();assert(await page.evaluate(()=>__messages.some(m=>m.type==='join-room'&&m.id==='alice')));await page.waitForTimeout(240);assert.equal(await page.locator('#lobby').evaluate(n=>getComputedStyle(n).filter),'none');
 await page.evaluate(()=>{LocalPartyRooms.update([],'missing');document.getElementById('nearbyToggle').click();});await page.waitForTimeout(800);console.log('GLASS',await page.locator('#nearbyDialog').evaluate(n=>({supports:CSS.supports('-webkit-touch-callout','none'),page:[...document.querySelectorAll('main,#home,#brandHeader')].map(x=>[x.id,x.parentElement.tagName,getComputedStyle(x).filter]),filter:getComputedStyle(n).backdropFilter,webkit:getComputedStyle(n).webkitBackdropFilter,bg:getComputedStyle(n).backgroundImage,modal:n.matches(':modal')})));await page.screenshot({path:path.join(out,`lost-${name}-${width}.png`)});await page.close();await native.close();
 }}finally{await browser.close();}}
 assert.deepEqual(report.errors,[]);
}finally{child.kill();await new Promise(r=>server.close(r));fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));}console.log(JSON.stringify(report));})().catch(e=>{console.error(e);process.exitCode=1;});
