'use strict';
// Controlled named feedback events over the real Arcade renderer. These are
// presentation captures, not a claim that every game outcome was played here.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),express=require('express');
const {chromium,webkit}=require('playwright');const {Arcade}=require('../../games/arcade/simulation');
const out=path.resolve('output/playwright/semantic-feel133');fs.mkdirSync(out,{recursive:true});
(async()=>{const app=express();app.use('/arcade',express.static('games/arcade/public'));app.use('/assets',express.static('games/assets'));app.use(express.static('public'));const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const report={engines:[],captureMode:'Named injected presentation events over real Hungry renderer; fixed animation offsets. Invariants use live effects.'};
try{for(const [name,engine] of [['chrome',chromium],['webkit',webkit]]){const browser=await engine.launch(name==='chrome'?{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}:{});try{const context=await browser.newContext({viewport:{width:1280,height:720},recordVideo:{dir:path.join(out,name),size:{width:1280,height:720}}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{window.WebSocket=class{readyState=1;send(){}close(){}};});await page.goto(`http://127.0.0.1:${server.address().port}/arcade/host.html`);
 const game=new Arcade('hungry',()=>.4);for(let i=0;i<4;i++)game.join('p'+i,'Player '+(i+1));game.start();await page.evaluate(s=>{state=s;update();document.documentElement.classList.add('party-host');document.documentElement.dataset.partyGame='hungry';},game.view());
 await page.addStyleTag({path:'public/game-feel.css'});await page.addScriptTag({path:'public/game-feel-state.js'});await page.addScriptTag({path:'public/game-feel.js'});await page.waitForTimeout(250);
 const invariants=await page.evaluate(async()=>{const f=LocalPartyFeel,before=JSON.stringify(state);f.reset();let quietReads=0;const originalRect=Element.prototype.getBoundingClientRect;Element.prototype.getBoundingClientRect=function(){quietReads++;return originalRect.call(this);};try{for(let i=0;i<20;i++)f.observe(state);await Promise.resolve();if(quietReads)throw Error('unchanged snapshot measured geometry');}finally{Element.prototype.getBoundingClientRect=originalRect;}f.reset();const one=f.emit('elimination',{id:'edge-1',x:.45,y:.42,shake:false}),dup=f.emit('elimination',{id:'edge-1',x:.45,y:.42});if(!dup.duplicate)throw Error('duplicate event replay');
 f.reset();f.emit('score',{id:'no-anchor'});if(document.querySelector('.lp-feel-mark-score'))throw Error('unanchored center reward');
 for(let i=0;i<200;i++)f.emit(i%2?'explosion':'elimination',{id:'spam'+i,impactPlayer:'p'+i,x:.5,y:.5,shake:false});const spam=f.diagnostics();if(spam.children>16||spam.particles>48||spam.pending>16)throw Error('budget exceeded');
 f.reset();const clean=f.diagnostics();if(clean.children||clean.pending||clean.activeTargets)throw Error('reset leaked');
 f.observe({phase:'playing',players:[{id:'p0',alive:true,dead:0}]},{selfId:'p0'});f.observe({phase:'playing',players:[{id:'p0',alive:true,dead:2}]},{selfId:'p0'});dispatchEvent(new Event('pagehide'));await Promise.resolve();if(f.diagnostics().children||f.diagnostics().pending)throw Error('queued work escaped pagehide');
 f.emit('hit',{id:'paused',x:.4,y:.4,impactTarget:document.querySelector('#phase')});f.reset();if(before!==JSON.stringify(state))throw Error('presentation mutated game state');return {spam,clean,unchangedState:true,duplicate:dup.duplicate};});
 for(const [type,x,y] of [['hit',.35,.45],['score',.85,.23],['elimination',.45,.45],['round-result',.5,.35],['turn-ready',.85,.23]]){
  await page.evaluate(({type,x,y})=>{LocalPartyFeel.reset();LocalPartyFeel.emit(type,{id:'capture-'+type,x,y,shake:false,impactTarget:type==='score'?document.querySelector('#phase'):null});for(const a of document.querySelector('.lp-feel-layer').getAnimations({subtree:true})){a.pause();a.currentTime=120;}},{type,x,y});await page.screenshot({path:path.join(out,`${name}-${type}.png`)});await page.waitForTimeout(650);
 }
 // Genuine renderer path: the unchanged simulation resolves a size-advantage
 // overlap; app.js detects its returned dead/mass edges and emits the effects.
 await page.evaluate(()=>dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true})));
 game.food=[];game.players[0].mass=100;game.players[0].x=600;game.players[0].y=340;game.players[1].x=610;game.players[1].y=340;game.players[1].shield=0;
 await page.evaluate(s=>{LocalPartyFeel.reset();state=s;update();},game.view());await page.waitForTimeout(180);game.tick(.05);assert(game.players[1].dead>0);
 await page.evaluate(s=>{LocalPartyFeel.reset();state=s;update();},game.view());await page.waitForFunction(()=>document.querySelector('.lp-feel-mark-ko'));
 const runtimeEvent=await page.evaluate(()=>{const mark=document.querySelector('.lp-feel-mark-ko');for(const a of document.querySelector('.lp-feel-layer').getAnimations({subtree:true})){a.pause();a.currentTime=120;}return {id:mark.dataset.eventId,text:mark.textContent,dead:state.players[1].dead,score:state.players[0].score};});assert.match(runtimeEvent.id,/^arcade:hungry:/);await page.screenshot({path:path.join(out,`${name}-hungry-real-ko.png`)});
 await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>LocalPartyFeel.reduced());const reduced=await page.evaluate(()=>{LocalPartyFeel.reset();const target=document.querySelector('#phase');LocalPartyFeel.emit('score',{id:'reduced',impactTarget:target,x:.5,y:.5});return {diag:LocalPartyFeel.diagnostics(),calm:target.classList.contains('lp-feel-calm'),animations:target.getAnimations().length};});assert.equal(reduced.diag.children,0);assert(reduced.calm);assert.equal(reduced.animations,0);
 await page.waitForTimeout(280);assert.equal(await page.evaluate(()=>LocalPartyFeel.diagnostics().pending),0);await page.screenshot({path:path.join(out,`${name}-reduced.png`)});
 assert.deepEqual(errors,[]);report.engines.push({name,invariants,runtimeEvent,reduced,errors});await context.close();}finally{await browser.close();}}
}finally{fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));await new Promise(r=>server.close(r));}console.log(JSON.stringify(report));})().catch(e=>{console.error(e);process.exitCode=1;});
