'use strict';
const crypto=require('crypto');
const WORDS=require('./words.json');
class Crocodile{
 constructor(report=()=>{}){this.report=report;this.players=new Map();this.phase='lobby';this.settings={mode:'solo',seconds:60,turns:6};this.turn=-1;this.used=[];this.wordId=0;this.teamScores=[0,0,0,0];this.teamLast=[null,null,null,null];this.lastActor=null;this.lastTeam=-1;}
 join(id,name){let p=this.players.get(id);if(!p){const counts=[0,0,0,0];for(const x of this.players.values())counts[x.team]++;p={id,name,team:counts.indexOf(Math.min(...counts)),online:true,score:0,guessed:0,skips:0,performed:0};this.players.set(id,p);}p.name=name;p.online=true;return p;}
 configure(s){if(!['lobby','finished'].includes(this.phase))return;for(const [key,values]of Object.entries({mode:['solo','teams'],seconds:[60,90,120],turns:[6,10,16]}))if(values.includes(s[key]))this.settings[key]=s[key];}
 setTeam(id,team){if(!['lobby','finished'].includes(this.phase)||!Number.isInteger(team)||team<0||team>3||!this.players.has(id))return false;this.players.get(id).team=team;return true;}
 start(){if(!['lobby','finished'].includes(this.phase)||[...this.players.values()].filter(p=>p.online).length<2)return false;this.eventId=crypto.randomUUID();this.startedAt=Date.now();this.turn=-1;this.teamScores=[0,0,0,0];this.teamLast=[null,null,null,null];this.lastActor=null;this.lastTeam=-1;this.used=[];for(const p of this.players.values())Object.assign(p,{score:0,guessed:0,skips:0,performed:0});return this.next();}
 next(){if(!['lobby','finished','between'].includes(this.phase))return false;if(this.turn+1>=this.settings.turns)return this.finish();const online=[...this.players.values()].filter(p=>p.online);if(!online.length)return false;this.turn++;let candidates=online;
 if(this.settings.mode==='teams'){const teams=[...new Set(online.map(p=>p.team))].sort();const next=teams.find(t=>t>this.lastTeam)??teams[0];this.lastTeam=next;candidates=online.filter(p=>p.team===next);const last=candidates.findIndex(p=>p.id===this.teamLast[next]);this.actor=candidates[(last+1)%candidates.length].id;this.teamLast[next]=this.actor;}else{const least=Math.min(...online.map(p=>p.performed));candidates=online.filter(p=>p.performed===least);this.actor=(candidates.find(p=>p.id!==this.lastActor)||candidates[0]).id;}
 this.lastActor=this.actor;this.players.get(this.actor).performed++;this.phase='turn';this.turnGuessed=0;this.turnSkips=0;this.endsAt=Date.now()+this.settings.seconds*1000;this.word();return true;}
 word(){if(this.used.length===WORDS.length)this.used=[];const available=WORDS.filter(w=>!this.used.includes(w));this.secret=available[crypto.randomInt(available.length)];this.used.push(this.secret);this.wordId++;}
 action(id,wordId,kind,host=false,now=Date.now()){if(this.phase!=='turn'||now>=this.endsAt||wordId!==this.wordId||(!host&&id!==this.actor)||!['guessed','skip'].includes(kind))return false;const p=this.players.get(this.actor);if(kind==='guessed'){p.guessed++;p.score+=100;this.teamScores[p.team]+=100;this.turnGuessed++;}else{p.skips++;this.turnSkips++;}this.word();return true;}
 end(){if(this.phase!=='turn')return false;this.phase='between';this.endsAt=Date.now()+3000;this.secret=null;return true;}
 score(p){if(this.players.size===2)return [...this.players.values()].reduce((sum,x)=>sum+x.score,0);return this.settings.mode==='teams'?this.teamScores[p.team]:p.score;}
 tick(now=Date.now()){if(!['turn','between','paused'].includes(this.phase))return false;const online=[...this.players.values()].some(p=>p.online);if(!online&&this.phase!=='paused'){this.resumePhase=this.phase;this.remaining=Math.max(0,this.endsAt-now);this.phase='paused';this.endsAt=null;return true;}if(this.phase==='paused'){if(!online)return false;this.phase=this.resumePhase;this.endsAt=now+this.remaining;return true;}if(now>=this.endsAt){if(this.phase==='turn')return this.end();return this.next();}return false;}
 finish(){if(this.phase==='finished')return false;this.phase='finished';this.secret=null;const active=[...this.players.values()].filter(p=>p.performed>0),top=Math.max(0,...active.map(p=>this.score(p)));this.report({eventId:this.eventId,gameId:'crocodile',duration:Date.now()-this.startedAt,players:active.map(p=>({id:p.id,name:p.name,score:this.score(p),won:this.score(p)===top,metrics:{guessed:p.guessed,skips:p.skips,performed:p.performed}}))});return true;}
 view(id){const p=this.players.get(id),actor=this.players.get(this.actor);return{type:'state',phase:this.phase,settings:this.settings,turn:this.turn,endsAt:this.endsAt,serverTime:Date.now(),wordId:this.wordId,actor:actor?{id:actor.id,name:actor.name,team:actor.team,online:actor.online}:null,secret:this.phase==='turn'&&id===this.actor?this.secret:null,turnGuessed:this.turnGuessed||0,turnSkips:this.turnSkips||0,me:p?{...p,score:this.score(p)}:null,players:[...this.players.values()].map(p=>({...p,score:this.score(p)})).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name)),teamScores:this.teamScores,cooperative:this.players.size===2};}
}
module.exports={Crocodile,WORDS};
