'use strict';const express=require('express'),http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),{WebSocketServer,WebSocket}=require('ws'),party=require('../../lib/party-runtime'),{Crocodile}=require('./engine');
const app=express(),server=http.createServer(app),wss=new WebSocketServer({server,maxPayload:8192}),game=new Crocodile(party.report),hostKey=crypto.randomBytes(24).toString('hex'),clients=new Map(),standalone=new Map();
const local=req=>['127.0.0.1','::1','::ffff:127.0.0.1'].includes(req.socket.remoteAddress);
app.get('/host',(req,res)=>{if(!local(req))return res.sendStatus(403);res.type('html').send(fs.readFileSync(path.join(__dirname,'public/index.html'),'utf8').replace('window.CROC_HOST_KEY=null','window.CROC_HOST_KEY='+JSON.stringify(hostKey)));});app.use(express.static(path.join(__dirname,'public')));
const send=(ws,v)=>{if(ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify(v));};const broadcast=()=>{party.ui?.({phase:({lobby:'waiting',turn:'playing',between:'reveal',finished:'results',paused:'paused'})[game.phase],endsAt:game.endsAt||null,label:game.phase==='finished'?'Итоги':game.phase==='between'?'Следующий актёр':'Показываем',currentPlayer:game.players.get(game.actor)?.name||null,progress:(game.turn+1)+' / '+game.settings.turns,actions:[]});for(const [ws,c]of clients)send(ws,game.view(c.id));};
wss.on('connection',(ws,req)=>{const c={id:null,host:false};clients.set(ws,c);send(ws,game.view());ws.on('message',raw=>{let m;try{m=JSON.parse(raw);}catch{return;}if(!m||typeof m!=='object')return;
if(m.type==='host'&&m.key===hostKey&&local(req))c.host=true;
else if(m.type==='join'){let p=party.identify(m,ws);if(!party.managed&&!p){const old=standalone.get(m.id);if(old&&old.token===m.token)p=old;else{p={id:crypto.randomUUID(),token:crypto.randomBytes(18).toString('hex'),name:String(m.name||'Игрок').trim().slice(0,24)||'Игрок'};standalone.set(p.id,p);}send(ws,{type:'identity',...p});}if(!p)return send(ws,{type:'error',message:'Откройте главное лобби для подключения.'});if(!game.players.has(p.id)&&game.players.size>=16)return send(ws,{type:'error',message:'Уже 16 игроков.'});for(const [other,oc]of clients)if(other!==ws&&oc.id===p.id){oc.id=null;other.close(4001,'Replaced');}c.id=p.id;game.join(p.id,p.name);send(ws,{type:'joined',id:p.id});party.presence(p.id,true);}
else if(m.type==='team'&&c.id)game.setTeam(c.id,m.team);
else if(m.type==='action'){if(!game.action(c.id,m.wordId,m.kind,c.host))send(ws,{type:'error',message:'Действие уже принято или ход завершён.'});}
else if(c.host){if(m.type==='configure')game.configure(m.settings||{});if(m.type==='start')game.start();if(m.type==='end')game.end();if(m.type==='next'&&game.phase==='between')game.next();}broadcast();});ws.on('close',()=>{clients.delete(ws);if(c.id&&![...clients.values()].some(x=>x.id===c.id)){const p=game.players.get(c.id);if(p)p.online=false;party.presence(c.id,false);}broadcast();});});
party.setInterval(()=>{if(game.tick())broadcast();},150).unref();server.listen(Number(process.env.PORT||0),party.managed?'127.0.0.1':'0.0.0.0',()=>console.log('Crocodile http://localhost:'+server.address().port+'/host'));


// Commands from the iPhone server console.
party.host({configure:s=>game.configure(s),start:()=>{const ok=game.start();broadcast();return ok;},end:()=>{game.end();broadcast();},next:()=>{if(game.phase!=='between')return false;game.next();broadcast();}});
