const fs=require('fs'),vm=require('vm'),assert=require('assert');
let source=fs.readFileSync('games/party/server.js','utf8');const reports=[];const ctx={require:n=>n==='../../lib/party-runtime'?{now:()=>Date.now(),setInterval(){},allowMessage:()=>true,onPause(){},host(){},identify:d=>d.partyId?{id:d.partyId,name:'Lobby '+d.partyId}:null,report:r=>reports.push(r),presence:()=>{}}:n==='http'?{createServer:()=>({on(){},listen(){}})}:require(n),__dirname:process.cwd()+'/games/party',process:{env:{TEST_FAST:'1'},hrtime:process.hrtime},console,Buffer,setInterval(){},URL};vm.createContext(ctx);vm.runInContext(source,ctx);vm.runInContext(`
const testSockets=Array.from({length:3},(_,i)=>({id:'s'+i,data:{},send(){}}));
testSockets.forEach((s,i)=>handleMessage(s,{type:'join',data:{partyId:'u'+i}}));
if(players.size!==3)throw Error('three joins');
const oldId=testSockets[0].data.playerId;
startGame({mode:'push',maxRounds:5});beginRoundPlaying();game.timer=.3;updatePush(.01);if(game.arenaRadius!==292)throw Error('push shrinks');
let p=players.get(oldId);p.x=640;p.y=360;p.vx=200;p.vy=0;p.input={jx:0,jy:0};updatePush(1/60);if(p.vx<190)throw Error('missing inertia');
startGame({mode:'shrink',maxRounds:5});beginRoundPlaying();game.timer=.2;updatePush(.01);if(game.arenaRadius>=292)throw Error('shrink absent');
const replacement={id:'new',data:{},send(){}};handleMessage(replacement,{type:'join',data:{partyId:'u0'}});handleDisconnect(testSockets[0]);if(!p.connected||p.socketId!=='new'||players.size!==3)throw Error('reconnect lost');
handleMessage(testSockets[0],{type:'joystick',data:{x:1,y:0}});if(p.input.jx!==0)throw Error('stale socket controls');
const late={id:'late',data:{},send(){}};handleMessage(late,{type:'join',data:{partyId:'u3'}});if(!players.get(late.data.playerId).active)throw Error('late join');
startGame({mode:'western',maxRounds:5});beginRoundPlaying();const round=game.round;
handleMessage(replacement,{type:'westernShoot',data:{round:round-1}});if(p.shotThisRound)throw Error('stale shot');
western.phase='draw';western.drawAt=Date.now()-100;handleMessage(replacement,{type:'westernShoot',data:{round}});handleMessage(replacement,{type:'westernShoot',data:{round}});if(western.shots.length!==1)throw Error('double shot');resolveWestern();if([...players.values()].filter(p=>p.alive).length!==1)throw Error('losers alive');nextRound();if(p.shotThisRound||p.falseStart)throw Error('shot reset');finishMatch();
for(let i=4;i<16;i++)handleMessage({id:'extra'+i,data:{},send(){}},{type:'join',data:{partyId:'u'+i}});for(const mode of ['push','shrink','knives','bomb','western']){startGame({mode,maxRounds:5});beginRoundPlaying();updateGame(.01);if(activePlayers().length!==16)throw Error('16 players '+mode);}
`,ctx);assert.equal(reports.length,1);console.log('PASS party: inertia, fixed/shrinking arenas, joins, reconnect replacement, stale actions, one shot, death, reset, stats');
const tankCtx={require:n=>n==='express'?Object.assign(()=>({get(){},use(){}}),{static(){}}):n==='http'?{createServer:()=>({listen(){}})}:n==='ws'?{WebSocketServer:class{constructor(){this.clients=[];}on(){}}}:n==='../../lib/party-runtime'?{report(){},setInterval(){},now:()=>Date.now(),allowMessage:()=>true,onPause(){},host(){}}:require(n),__dirname:process.cwd()+'/games/tankarena',process:{env:{}},console,setInterval(){}};vm.createContext(tankCtx);vm.runInContext(fs.readFileSync('games/tankarena/server.js','utf8'),tankCtx);vm.runInContext(`if(Object.keys(weapons).length!==4)throw Error('weapon count');const p={id:'t',angle:0,x:100,y:100,shots:0,color:'#fff'};for(const w of Object.keys(weapons)){p.weapon=w;const before=bullets.length;shoot(p);if(bullets.length-before!==weapons[w].count)throw Error('projectiles');}if(new Set(Object.values(weapons).map(w=>w.cd)).size!==4)throw Error('same weapons');`,tankCtx);console.log('PASS tanks: four distinct weapon cadences/projectile counts');

const normalSource=source.replace("const TEST_FAST = process.env.TEST_FAST === '1';","const TEST_FAST = false;");const normalCtx=vm.createContext({...ctx});vm.runInContext(normalSource,normalCtx);vm.runInContext(`for(let i=0;i<2;i++)handleMessage({id:'n'+i,data:{},send(){}},{type:'join',data:{partyId:'n'+i}});startGame({mode:'shrink',shrinkSpeed:'normal'});beginRoundPlaying();game.timer=game.roundDuration-7;updatePush(.001);if(game.arenaRadius!==292)throw Error('normal delay');game.timer=game.roundDuration-30.5;updatePush(.001);if(Math.abs(game.arenaRadius-222)>1)throw Error('normal45duration');startGame({mode:'shrink',shrinkSpeed:'fast'});beginRoundPlaying();game.timer=game.roundDuration-10;updatePush(.001);if(Math.abs(game.arenaRadius-222)>1)throw Error('fast20duration');`,normalCtx);console.log('PASS shrink normal8+45,fast0+20');
