'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),zlib=require('node:zlib'),http=require('node:http'),net=require('node:net');
const {extract,safeName,crc32}=require('../lib/update-archive');
const {createUpdater,dependencyIdentity,allowedDownload,withPublicFallback}=require('../lib/updater');
const {run,restorePortable,SCOPE}=require('../lib/update-worker.cjs');
function temporary(t){const p=fs.mkdtempSync(path.join(os.tmpdir(),'lp-alpha-test-'));t.after(()=>fs.rmSync(p,{force:true,recursive:true}));return p;}
function archive(entries){let position=0;const locals=[],centrals=[];for(const e of entries){const name=Buffer.from(e.name),bytes=Buffer.from(e.text||''),packed=zlib.deflateRawSync(bytes),head=Buffer.alloc(30);head.writeUInt32LE(0x04034b50);head.writeUInt16LE(20,4);head.writeUInt16LE(8,8);head.writeUInt32LE(crc32(bytes),14);head.writeUInt32LE(packed.length,18);head.writeUInt32LE(bytes.length,22);head.writeUInt16LE(name.length,26);locals.push(head,name,packed);const c=Buffer.alloc(46);c.writeUInt32LE(0x02014b50);c.writeUInt16LE(0x314,4);c.writeUInt16LE(20,6);c.writeUInt16LE(8,10);c.writeUInt32LE(crc32(bytes),16);c.writeUInt32LE(packed.length,20);c.writeUInt32LE(bytes.length,24);c.writeUInt16LE(name.length,28);c.writeUInt32LE(((e.mode||0o100644)<<16)>>>0,38);c.writeUInt32LE(position,42);centrals.push(c,name);position+=head.length+name.length+packed.length;}const central=Buffer.concat(centrals),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(entries.length,8);end.writeUInt16LE(entries.length,10);end.writeUInt32LE(central.length,12);end.writeUInt32LE(position,16);return Buffer.concat([...locals,central,end]);}
test('bounded archive extracts real deflate entries and executable bits',t=>{const dir=temporary(t),out=path.join(dir,'out');extract(archive([{name:'root/server.js',text:'okay'},{name:'root/runtime/node',text:'bin',mode:0o100755}]),out);assert.equal(fs.readFileSync(path.join(out,'server.js'),'utf8'),'okay');assert.ok(fs.statSync(path.join(out,'runtime/node')).mode&0o111);});
test('reject traversal, absolute paths, Windows devices/ADS, links, collisions',t=>{const dir=temporary(t);for(const name of ['../evil','/tmp/evil','root/../evil','root/C:evil','root/x\\evil','root/NUL','root/a.'])assert.throws(()=>extract(archive([{name,text:'bad'}]),path.join(dir,'out')));assert.throws(()=>extract(archive([{name:'root/link',mode:0o120777}]),path.join(dir,'out')));assert.throws(()=>extract(archive([{name:'root/A',text:'a'},{name:'root/a',text:'b'}]),path.join(dir,'out')));assert.equal(fs.existsSync(path.join(dir,'out')),false);});
test('reject corruption, oversized expansion, multiple roots and existing destination',t=>{const dir=temporary(t);const buf=archive([{name:'root/a',text:'hello'}]);buf[18]^=1; // local length does not matter; authoritative central CRC does.
 const corrupt=archive([{name:'root/a',text:'hello'}]);const c=corrupt.indexOf(Buffer.from([0x50,0x4b,0x01,0x02]));corrupt[c+16]^=1;
 assert.throws(()=>extract(corrupt,path.join(dir,'out')));assert.equal(fs.existsSync(path.join(dir,'out')),false);
 assert.throws(()=>extract(archive([{name:'root/a',text:'x'.repeat(100)}]),path.join(dir,'out'),{maxBytes:20}));
 assert.throws(()=>extract(archive([{name:'a/a'},{name:'b/b'}]),path.join(dir,'out')));fs.mkdirSync(path.join(dir,'out'));assert.throws(()=>extract(archive([{name:'a/a'}]),path.join(dir,'out')));
});
test('archive CRC agrees with published standard test vector',()=>assert.equal(crc32(Buffer.from('123456789')),0xcbf43926));
test('allowlist rejects non-GitHub, userinfo and insecure transports',()=>{for(const url of ['https://evil.test/file','http://api.github.com/x','https://api.github.com.evil.test/x','https://x@api.github.com/x','file:///tmp/x','https://github.com:8443/x'])assert.equal(allowedDownload(url),false);assert.equal(allowedDownload('https://codeload.github.com/lomatoq/localparty/zip/abc'),true);});
test('public GitHub access is attempted before optional credentials',async()=>{const attempts=[];assert.equal(await withPublicFallback(async auth=>{attempts.push(auth);return 'public';},async()=>assert.fail('token should not be read')),'public');assert.deepEqual(attempts,['']);});
test('credentials are only a fallback for an access response',async()=>{const attempts=[];const result=await withPublicFallback(async auth=>{attempts.push(auth);if(!auth){const error=Error('access');error.statusCode=403;throw error;}return 'private';},async()=>'secret');assert.equal(result,'private');assert.deepEqual(attempts,['','secret']);});
test('dependency check ignores application version but rejects package changes',()=>{const a={version:'1',packages:{'':{version:'1'},'node_modules/ws':{version:'1'}}};const b=structuredClone(a);b.version='2';b.packages[''].version='2';assert.equal(dependencyIdentity(JSON.stringify(a)),dependencyIdentity(JSON.stringify(b)));b.packages['node_modules/ws'].version='2';assert.notEqual(dependencyIdentity(JSON.stringify(a)),dependencyIdentity(JSON.stringify(b)));});
test('portable mutation scope never includes profiles, certificates, environment or git',()=>{for(const p of ['data','.git','.env','certs','.certificates'])assert.ok(!SCOPE.includes(p));});
async function apiFixture(t,{local=true,busy=false}={}){const root=temporary(t);fs.writeFileSync(path.join(root,'package.json'),'{"version":"0.6.2"}');const update=createUpdater({root,hostKey:'secret',isLocal:()=>local,isBusy:()=>busy,getPort:()=>1,shutdown:()=>assert.fail('must not stop')});const server=http.createServer(async(q,s)=>{if(!await update.route(q,s)){s.writeHead(404);s.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>server.close());return{url:'http://127.0.0.1:'+server.address().port,update};}
test('updater status is host authenticated; no token in status',async t=>{const {url}=await apiFixture(t);assert.equal((await fetch(url+'/api/updates')).status,403);const r=await fetch(url+'/api/updates',{headers:{'X-Party-Host':'secret'}});assert.equal(r.status,200);const text=await r.text();assert.ok(!text.includes('secret'));});
test('remote client cannot update even with host header',async t=>{const {url}=await apiFixture(t,{local:false});assert.equal((await fetch(url+'/api/updates',{headers:{'X-Party-Host':'secret'}})).status,403);});
test('cross-origin update requests are forbidden',async t=>{const {url}=await apiFixture(t);assert.equal((await fetch(url+'/api/updates',{headers:{'X-Party-Host':'secret',Origin:'https://evil.test'}})).status,403);});
test('active game and missing confirmation block installation',async t=>{const {url}=await apiFixture(t,{busy:true});for(const confirm of [false,true]){const r=await fetch(url+'/api/updates/install',{method:'POST',headers:{'X-Party-Host':'secret','Content-Type':'application/json'},body:JSON.stringify({confirm})});assert.equal(r.status,400);}});
test('portable rollback removes partial new files and restores originals',t=>{const root=temporary(t),backup=path.join(root,'backup');fs.mkdirSync(backup);fs.writeFileSync(path.join(root,'server.js'),'new');fs.writeFileSync(path.join(backup,'server.js'),'old');fs.mkdirSync(path.join(root,'newdir'));restorePortable({root,backup},[{name:'server.js',installed:true},{name:'newdir',installed:true}]);assert.equal(fs.readFileSync(path.join(root,'server.js'),'utf8'),'old');assert.equal(fs.existsSync(path.join(root,'newdir')),false);});
async function port(){const s=net.createServer();await new Promise(r=>s.listen(0,'127.0.0.1',r));const p=s.address().port;await new Promise(r=>s.close(r));return p;}
async function health(p){for(let n=0;n<80;n++){try{return await(await fetch('http://127.0.0.1:'+p+'/api/health')).json();}catch{}await new Promise(r=>setTimeout(r,50));}throw Error('server did not start');}
function fixtureServer(label){return `require('http').createServer((q,s)=>{s.setHeader('Content-Type','application/json');s.end(JSON.stringify({ok:true,pid:process.pid,label:${JSON.stringify(label)}}))}).listen(+process.env.PARTY_PORT,'127.0.0.1');`;}
test('worker installs fixture, restarts, checks health and preserves profiles',async t=>{const root=temporary(t),cache=path.join(root,'cache'),stage=path.join(root,'stage');fs.mkdirSync(cache);fs.mkdirSync(stage);fs.mkdirSync(path.join(root,'data'));fs.writeFileSync(path.join(root,'data/party.json'),'profiles');fs.writeFileSync(path.join(root,'server.js'),fixtureServer('old'));fs.writeFileSync(path.join(stage,'server.js'),fixtureServer('new'));const p=await port();await run({root,cache,stage,backup:path.join(cache,'backup'),kind:'portable',port:p,pid:2147483647,executable:process.execPath});const h=await health(p);process.kill(h.pid);assert.equal(h.label,'new');assert.equal(fs.readFileSync(path.join(root,'data/party.json'),'utf8'),'profiles');assert.equal(JSON.parse(fs.readFileSync(path.join(cache,'status.json'))).phase,'done');});
test('worker restores old installation automatically when new server exits',async t=>{const root=temporary(t),cache=path.join(root,'cache'),stage=path.join(root,'stage');fs.mkdirSync(cache);fs.mkdirSync(stage);fs.writeFileSync(path.join(root,'server.js'),fixtureServer('old'));fs.writeFileSync(path.join(stage,'server.js'),'process.exit(1);');const p=await port();await run({root,cache,stage,backup:path.join(cache,'backup'),kind:'portable',port:p,pid:2147483647,executable:process.execPath});const h=await health(p);process.kill(h.pid);assert.equal(h.label,'old');assert.equal(JSON.parse(fs.readFileSync(path.join(cache,'status.json'))).phase,'error');});
