const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const { createAudioManager } = require('../public/audio-system.js');
function rig(saved) {
 const listeners = {}, sources = [], gains = []; let fetches = 0, resumes = 0, persisted;
 class AudioContext { constructor() { this.state = 'suspended'; this.currentTime = 0; } resume() { resumes++; this.state = 'running'; return Promise.resolve(); } createGain() { const g = { gain: { cancelScheduledValues(){}, setTargetAtTime(v){g.value=v;} }, connect(){} }; gains.push(g); return g; } createDynamicsCompressor(){return {threshold:{},knee:{},ratio:{},attack:{},release:{},connect(){}};} decodeAudioData(){return Promise.resolve({});} createBufferSource(){const s={connect(){},disconnect(){},start(){s.started=true;},stop(){s.stopped=true;s.onended?.();}};sources.push(s);return s;} }
 const document = { hidden: false, addEventListener(n,f){listeners[n]=f;} };
 const env = { AudioContext, document, localStorage: {getItem(){return saved;},setItem(k,v){persisted=v;}}, fetch(){fetches++; return Promise.resolve({ok:true,arrayBuffer:async()=>new ArrayBuffer(1)});},addEventListener(){} };
 return { manager:createAudioManager(env),document,listeners,sources,gains,get fetches(){return fetches;},get resumes(){return resumes;},get persisted(){return persisted;} };
}
const settle = () => new Promise(r=>setImmediate(r));
test('no network or audio until gesture unlock; phones never own music by default',async()=>{const r=rig();r.manager.scene('game');await r.manager.play('hit');assert.equal(r.fetches,0);await r.manager.unlock();await settle();assert.equal(r.fetches,0);assert.equal(r.resumes,1);await r.manager.play('hit');assert.equal(r.fetches,1);});
test('TV music switches scenes, pauses, hides, resumes without duplicate loops',async()=>{const r=rig();r.manager.configure({surface:'tv'});await r.manager.unlock();await settle();assert.equal(r.manager.status().music,'lobby');const first=r.sources[0];r.manager.scene('game');await settle();assert.equal(first.stopped,true);assert.equal(r.manager.status().music,'battle');r.manager.scene('pause');assert.equal(r.manager.status().music,null);r.manager.scene('game');await settle();r.document.hidden=true;r.listeners.visibilitychange();assert.equal(r.manager.status().music,null);r.document.hidden=false;r.listeners.visibilitychange();await settle();assert.equal(r.manager.status().music,'battle');});
test('mute stops music and effects; volumes persisted and clamped',async()=>{const r=rig('{bad');r.manager.configure({surface:'tv'});await r.manager.unlock();await settle();r.manager.preferences({muted:true,musicVolume:8,sfxVolume:-2});assert.deepEqual(JSON.parse(r.persisted),{muted:true,musicVolume:1,sfxVolume:0});assert.equal(r.manager.status().music,null);assert.equal(await r.manager.play('click'),false);r.manager.preferences({muted:false,sfxVolume:.5});await settle();assert.equal(r.manager.status().music,'lobby');});
test('bounded polyphony, repeated-hit debounce and asset cache',async()=>{const r=rig();await r.manager.unlock();await Promise.all(['click','confirm','back','error','ready','countdown','hit','win'].map(n=>r.manager.play(n)));assert.equal(r.manager.status().activeEffects,6);assert.equal(await r.manager.play('hit'),false);r.sources[0].onended();assert.equal(r.manager.status().activeEffects,5);});
test('explicit music handoff stops the TV and enables selected host only',async()=>{const r=rig();await r.manager.unlock();r.manager.configure({surface:'tv'});await settle();r.manager.configure({surface:'host',musicOwner:false});assert.equal(r.manager.status().music,null);r.manager.configure({surface:'host',musicOwner:true});await settle();assert.equal(r.manager.status().music,'lobby');});
test('every shipped audio asset has expected binary signature and provenance',()=>{for(const n of ['click','confirm','back','error','ready','countdown','hit','win'])assert.equal(fs.readFileSync(`public/audio/sfx/${n}.wav`).toString('ascii',0,4),'RIFF');for(const n of ['lobby','battle','matchmaking'])assert.equal(fs.readFileSync(`public/audio/music/${n}.m4a`).toString('ascii',4,8),'ftyp');assert.ok(fs.existsSync('public/audio/licenses/not-jam.txt'));});
