'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
test('Bow HUD guards identical frames while score, pull, locale, hand, connection and fresh aim stay responsive',()=>{
 const source=fs.readFileSync('games/bow_club/public/phone.js','utf8'),aim=source.slice(source.indexOf('function currentAim('),source.indexOf('function cancel(')),hud=source.slice(source.indexOf('function bowHudText('),source.indexOf("$('draw').addEventListener('pointerdown'"));
 let writes=0;const nodes=new Map(),element=()=>{let text='',inner='',disabled=false;const attr=new Map();return{get textContent(){return text},set textContent(v){writes++;text=v},get innerHTML(){return inner},set innerHTML(v){writes++;inner=v},get disabled(){return disabled},set disabled(v){writes++;disabled=v},getAttribute:k=>attr.has(k)?attr.get(k):null,setAttribute(k,v){writes++;attr.set(k,v)}}};const $=id=>{if(!nodes.has(id))nodes.set(id,element());return nodes.get(id)},classes=new Set();
 const dictionary={'Прицел пальцем':'Touch aiming','Натяните и отпустите':'Draw and release','Левая рука':'Left hand','Правая рука':'Right hand','Пауза':'Paused','Экран найден':'Screen found','Нет соединения':'Disconnected','Держи экран в кадре':'Keep screen in frame','Наведи камеру на экран':'Aim at screen'};
 const context={$,window:{PartyI18n:{language:'en',t(s,options){if(/рука$/.test(s))assert.equal(options?.ui,true,'Semantic aria labels retain shared localization treatment');return this.language==='ru'?s:dictionary[s]||s;}}},document:{body:{classList:{contains:c=>classes.has(c),toggle(c,v){writes++;if(v)classes.add(c);else classes.delete(c);}}}},bowPoints:element(),bowArrows:element(),state:{phase:'playing',arrows:10,revision:1,players:[{id:'p',score:0,shots:0,connected:true}]},id:'p',joined:true,holding:false,drawAt:0,mode:'touch',hand:'right',touchUV:{u:.5,v:.5},worker:null,workerReady:true,tracking:null,stable:0,offset:{u:0,v:0},filter:{sample:()=>({u:.5,v:.5})},performance:{now:()=>100}};vm.createContext(context);vm.runInContext(aim+hud,context);const update=now=>vm.runInContext('updateHUD('+now+')',context);
 update(100);assert.equal($('draw').disabled,false);assert.equal($('tracking').textContent,'Touch aiming');writes=0;for(let i=0;i<100;i++)update(100+i);assert.equal(writes,0,'Identical authored values cause no HUD DOM writes');
 context.state.players[0].score=25;context.state.players[0].shots=1;update(250);assert.equal(context.bowPoints.textContent,'25');assert.equal(context.bowArrows.textContent,'9');
 context.holding=true;context.drawAt=300;update(700);assert.match($('draw').innerHTML,/RELEASE/);assert.match($('draw').innerHTML,/50%/);update(900);assert.match($('draw').innerHTML,/75%/);writes=0;update(900);assert.equal(writes,0);
 context.hand='left';update(901);assert(classes.has('left-hand'));assert.equal($('hand').getAttribute('aria-pressed'),'true');assert.equal($('hand').getAttribute('aria-label'),'Left hand');
 context.holding=false;context.state.paused=true;context.window.PartyI18n.language='ru';update(1000);assert.equal($('draw').disabled,true);assert.equal($('metrics').textContent,'Пауза');assert.equal($('hand').getAttribute('aria-label'),'Левая рука');assert.match($('draw').innerHTML,/НАТЯНИ/);
 context.state.paused=false;context.mode='camera';context.stable=3;context.tracking={at:1000,quality:1,uv:{u:.5,v:.5}};update(1000);assert.equal($('draw').disabled,false);update(1400);assert.equal($('draw').disabled,true,'Expired real aim disables release action');
 context.joined=false;update(1500);assert.equal($('tracking').textContent,'Нет соединения');writes=0;update(1500);assert.equal(writes,0);
});
