const test=require('node:test'),assert=require('node:assert/strict');
const {board}=require('./fixtures/bow/camera.cjs');
async function tracker(){const cv=await require('../games/bow_club/public/vendor/opencv.js');const {HybridTracker}=await import('../games/bow_club/public/src/hybrid-tracker.mjs');return new HybridTracker(cv);}
function translate(f,dx,dy){const pixels=new Uint8ClampedArray(f.pixels.length);pixels.fill(75);for(let y=0;y<f.height;y++){const yy=y+dy;if(yy<0||yy>=f.height)continue;const lo=Math.max(0,-dx),hi=Math.min(f.width,f.width-dx);pixels.set(f.pixels.subarray((y*f.width+lo)*4,(y*f.width+hi)*4),(yy*f.width+lo+dx)*4);}return {...f,pixels};}
test('OpenCV acquires portrait board and uneven lighting using our actual dictionary',async()=>{const t=await tracker();try{for(const shade of [false,true]){const f=await board({shade}),r=t.detect(f.pixels,f.width,f.height,shade?300:0);assert.ok(r);assert.equal(r.source,'markers');assert.equal(r.tags.length,4);assert.ok(Math.abs(r.uv.u-.5)<.01);}}finally{t.close();}});
test('optical flow follows movement between decoded frames and rejects a blank camera',async()=>{const t=await tracker();try{const f=await board();assert.ok(t.detect(f.pixels,f.width,f.height,0));for(let i=1;i<=3;i++){const moved=translate(f,i*4,i*2),r=t.detect(moved.pixels,f.width,f.height,i*45);assert.ok(r,'flow frame '+i);assert.equal(r.source,'flow');assert.ok(Math.abs(r.uv.u-(.5-i*4/640))<.01);assert.ok(r.pointCount>=8);}const blank=new Uint8ClampedArray(f.pixels.length).fill(75);assert.equal(t.detect(blank,f.width,f.height,175),null);}finally{t.close();}});
test('two separated markers acquire while a lone marker never creates a new plane',async()=>{const t=await tracker();try{const one=await board({missing:[1,2,3]});assert.equal(t.detect(one.pixels,one.width,one.height,0),null);const two=await board({missing:[2,3]}),r=t.detect(two.pixels,two.width,two.height,200);assert.ok(r);assert.equal(r.tags.length,2);}finally{t.close();}});
test('flow keeps the screen through partial occlusion and expires without decoded anchors',async()=>{const t=await tracker();try{const f=await board(),covered=await board({missing:[1]}),first=t.detect(f.pixels,f.width,f.height,0);assert.ok(first);let r=t.detect(covered.pixels,f.width,f.height,60);assert.ok(r);assert.equal(r.source,'flow');assert.ok(Math.abs(r.uv.u-.5)<.012);t.decode=()=>[];for(let at=120;at<1400;at+=100){r=t.detect(covered.pixels,f.width,f.height,at);assert.ok(r,'bounded flow '+at);}assert.equal(t.detect(covered.pixels,f.width,f.height,1500),null);}finally{t.close();}});
test('RANSAC rejects mismatched points instead of moving the screen to them',async()=>{const t=await tracker();try{const f=await board(),r=t.detect(f.pixels,f.width,f.height,0);assert.ok(r);const pairs=t.points.map(p=>({board:[...p.board],image:[...p.image]}));for(let i=0;i<15;i++)pairs[i].image=[.02+i*.001,.05];const fit=t.fit(pairs,f.width,f.height,'flow');assert.ok(fit);assert.ok(Math.abs(fit.uv.u-.5)<.015);assert.ok(fit.inliers.length<pairs.length);}finally{t.close();}});
test('inertial seed is verified by visual flow and bad hints never become an unmeasured aim',async()=>{const t=await tracker();try{const f=await board();assert.ok(t.detect(f.pixels,f.width,f.height,0,{x:0,y:0,z:0}));const moved=translate(f,5,2),r=t.detect(moved.pixels,f.width,f.height,60,{x:.003,y:.008,z:0,focal:.85});assert.ok(r);assert.ok(Math.abs(r.uv.u-(.5-5/640))<.012);}finally{t.close();}});
