'use strict';const test=require('node:test'),assert=require('node:assert/strict'),{Crocodile,WORDS}=require('../games/crocodile/engine');
const make=(count=3)=>{const g=new Crocodile();for(let i=0;i<count;i++)g.join('p'+i,'Игрок '+i);return g;};
test('100+ distinct familiar prompts',()=>{assert(WORDS.length>=100);assert.equal(new Set(WORDS).size,WORDS.length);assert(WORDS.every(w=>typeof w==='string'&&w.length>1));});
test('secret only delivered to actor, not host, spectator, teammate or unjoined socket',()=>{const g=make();g.configure({mode:'teams'});g.setTeam('p0',0);g.setTeam('p1',0);g.start();const actor=g.actor;assert(g.view(actor).secret);for(const id of [undefined,null,'stranger',...g.players.keys()].filter(id=>id!==actor)){const s=g.view(id);assert.equal(s.secret,null);assert(!JSON.stringify(s).includes(g.secret));}});
test('guessed and skip are idempotent by wordId; spectator rejected',()=>{const g=make();g.start();const word=g.wordId;assert.equal(g.action('p2',word,'guessed'),false);assert.equal(g.action(g.actor,word,'guessed'),true);assert.equal(g.action(g.actor,word,'guessed'),false);assert.equal(g.action(g.actor,word,'skip'),false);assert.equal(g.players.get(g.actor).guessed,1);assert.equal(g.action(null,g.wordId,'skip',true),true);assert.equal(g.players.get(g.actor).skips,1);assert.equal(g.action(g.actor,g.wordId,'guessed',false,g.endsAt),false);});
test('reconnect restores current secret, deadline, team and score without new turn',()=>{const g=make();g.setTeam('p0',2);g.start();const actor=g.actor,secret=g.secret,end=g.endsAt,id=g.wordId,team=g.players.get(actor).team;g.players.get(actor).online=false;g.join(actor,'Новое имя');assert.equal(g.secret,secret);assert.equal(g.wordId,id);assert.equal(g.endsAt,end);assert.equal(g.players.get(actor).team,team);assert.equal(g.view(actor).secret,secret);});
test('solo rotates fairly and late player enters next turn',()=>{const g=make();g.start();const seen=[g.actor];g.end();g.next();seen.push(g.actor);g.end();g.next();seen.push(g.actor);assert.equal(new Set(seen).size,3);g.join('late','Поздний');assert.equal(g.view('late').secret,null);g.end();g.next();assert.equal(g.actor,'late');});
test('team turns alternate and actors rotate within team',()=>{const g=make(4);g.configure({mode:'teams'});g.setTeam('p0',0);g.setTeam('p1',0);g.setTeam('p2',1);g.setTeam('p3',1);g.start();const sequence=[];for(let i=0;i<4;i++){sequence.push(g.actor);g.end();g.next();}assert.deepEqual(sequence,['p0','p2','p1','p3']);});
test('two players cooperate; finish reports once with stable IDs and metrics',()=>{const g=make(2),results=[];g.report=r=>results.push(r);g.start();for(let i=0;i<6;i++){g.action(g.actor,g.wordId,'guessed');g.end();g.next();}assert.equal(g.phase,'finished');assert.equal(results.length,1);assert.equal(results[0].players.length,2);assert(results[0].players.every(p=>p.won&&p.score===600&&p.metrics.performed===3));assert.equal(g.finish(),false);assert.equal(results.length,1);assert.equal(g.view('p0').secret,null);});
test('settings bounded and frozen, insufficient players cannot start',()=>{const g=make(1);assert.equal(g.start(),false);g.configure({seconds:5,turns:999});assert.equal(g.settings.seconds,60);g.join('p1','Второй');g.start();g.configure({seconds:120});assert.equal(g.settings.seconds,60);assert.equal(g.setTeam('p0',3),false);});
for(const count of [2,4,8,16])test(`${count} players: auto interturn and all-offline pause preserve deadline`,()=>{const g=make(count);assert(g.start());g.end();assert.equal(g.phase,'between');const deadline=g.endsAt;assert.equal(g.tick(deadline-1),false);assert.equal(g.tick(deadline),true);assert.equal(g.turn,1);const left=g.endsAt-Date.now();for(const p of g.players.values())p.online=false;g.tick();assert.equal(g.phase,'paused');g.join('p0','Вернулся');const now=Date.now()+10000;g.tick(now);assert.equal(g.phase,'turn');assert(Math.abs(g.endsAt-now-left)<30);});

