'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const ready=import('data:text/javascript;base64,'+fs.readFileSync('public/sports-motion.js').toString('base64'));
const flat={w:1,x:0,y:0,z:0},upright={w:Math.SQRT1_2,x:Math.SQRT1_2,y:0,z:0},side={w:Math.SQRT1_2,x:0,y:0,z:Math.SQRT1_2};
const s=(at,forward=0,lateral=0,spin=0,q=flat)=>({at,acceleration:q===side?{x:forward,y:-lateral,z:0}:q===upright?{x:lateral,y:0,z:-forward}:{x:lateral,y:forward,z:0},rotation:q===side?{x:spin,y:0,z:0}:q===upright?{x:0,y:0,z:-spin}:{x:0,y:spin,z:0},quaternion:q,deviceQuaternion:q});
function settle(g,start=0,q=flat,allowed=true){for(let t=start;t<=start+900;t+=30)assert.equal(g.feed(s(t,0,0,0,q),allowed),null);}
function flick(g,start=930,force=10,lateral=0,spin=0,q=flat,allowed=true){const shots=[];for(let i=0;i<12;i++){const shot=g.feed(s(start+i*30,i<6?force:0,i<6?lateral:0,i<6?spin:0,q),allowed);if(shot)shots.push(shot);}return shots;}
test('hands-free impulse launches once after quiet arming; acceleration controls power, rotation only spin',async()=>{const {FreeMotionThrow}=await ready;const shots=[];for(const force of [5,18]){const g=new FreeMotionThrow();settle(g);assert(g.armed);const a=flick(g,930,force,0,100);assert.equal(a.length,1);assert.equal(a[0].position,0);assert.equal(a[0].angle,0);assert(a[0].spin>0);shots.push(a[0]);}assert(shots[1].power>shots[0].power);});
test('gentle and medium flicks leave useful power headroom while a deliberate hard throw can reach full power',async()=>{const {FreeMotionThrow}=await ready;const shots=[5,18,40].map(force=>{const g=new FreeMotionThrow();settle(g);return flick(g,930,force)[0];});assert(shots[0].power<.3);assert(shots[1].power>.45&&shots[1].power<.65);assert.equal(shots[2].power,1);});
test('fixed TV frame survives arbitrary grip changes: flat, upright, side-on all aim straight with same power/spin',async()=>{const {FreeMotionThrow}=await ready;const actual=[];for(const q of [flat,upright,side]){const g=new FreeMotionThrow();settle(g);const shot=flick(g,930,10,0,80,q)[0];assert(shot);actual.push(shot);}for(const shot of actual){assert(Math.abs(shot.angle)<1e-8);assert(Math.abs(shot.power-actual[0].power)<1e-8);assert(Math.abs(shot.spin-actual[0].spin)<1e-8);}const g=new FreeMotionThrow();settle(g,0,upright);assert(Math.abs(g.frame.forward.y-1)<1e-8);assert(Math.abs(flick(g,930,10,0,0,upright)[0].angle)<1e-8);});
test('left/right movement determines lane angle while gyro does not add artificial power',async()=>{const {FreeMotionThrow}=await ready;const make=(side,spin)=>{const g=new FreeMotionThrow();settle(g);return flick(g,930,10,side,spin)[0];};const left=make(-2,0),right=make(2,0),twisted=make(2,240);assert(left.angle<0&&right.angle>0);assert(Math.abs(left.angle+right.angle)<1e-8);assert.equal(right.power,twisted.power);assert.equal(right.spin,0);assert(twisted.spin>0);});
test('idle, setup movement, gyro-only, vertical/lateral/backwards motion and one noisy sample never throw',async()=>{const {FreeMotionThrow}=await ready;for(const pattern of ['setup','gyro','vertical','lateral','backwards','bump']){const g=new FreeMotionThrow();if(pattern!=='setup')settle(g);const shots=[];for(let i=0;i<20;i++){let a=s(930+i*30);if(pattern==='setup')a=s(i*30,20);if(pattern==='gyro')a=s(a.at,0,0,300);if(pattern==='vertical')a.acceleration.z=12;if(pattern==='lateral')a.acceleration.x=12;if(pattern==='backwards')a.acceleration.y=-12;if(pattern==='bump'&&i===2)a.acceleration.y=20;const shot=g.feed(a,true);if(shot)shots.push(shot);}assert.deepEqual(shots,[],pattern);}});
test('turn/permission gates, cancellation and sensor gaps discard an impulse without losing the TV frame',async()=>{const {FreeMotionThrow}=await ready;for(const reason of ['turn','cancel','gap']){const g=new FreeMotionThrow();settle(g);const frame=g.frame;g.feed(s(930,12),true);g.feed(s(960,12),true);if(reason==='turn')g.feed(s(990,12),false);else if(reason==='cancel')g.cancel();else g.feed(s(1290,12),true);assert.deepEqual(flick(g,1320,12),[],reason);assert.equal(g.frame,frame);settle(g,1700);assert.equal(flick(g,2630,12).length,1);}});
test('native attitude uses physical device coordinates regardless of screen orientation',async()=>{const {SportsSensors}=await ready;let sample;const sent=[];const host={screen:{orientation:{angle:90}},addEventListener(){},removeEventListener(){},webkit:{messageHandlers:{partyShell:{postMessage:m=>sent.push(m)}}}};const sensor=new SportsSensors({host,onSample:s=>sample=s,onStatus(){}});await sensor.enable();const session=sent.at(-1).session;host.__partySportsMotion({session,sourceTime:1,acceleration:{x:0,y:0,z:-10},rotation:{x:0,y:0,z:0},quaternion:{...upright,x:-upright.x}});for(const k of ['x','y','z','w'])assert(Math.abs(sample.deviceQuaternion[k]-upright[k])<1e-10);assert.notDeepEqual(sample.quaternion,sample.deviceQuaternion);sensor.stop();});
test('measured native gravity establishes device→world attitude and retains it in ambiguous flat poses',async()=>{const {SportsSensors}=await ready;for(const inverse of [false,true]){let sample;const messages=[];const host={addEventListener(){},removeEventListener(){},webkit:{messageHandlers:{partyShell:{postMessage:m=>messages.push(m)}}}};const sensor=new SportsSensors({host,onSample:s=>sample=s,onStatus(){}});try{await sensor.enable();const session=messages.at(-1).session;const payload={session,sourceTime:1,acceleration:{x:0,y:0,z:-10},rotation:{x:0,y:0,z:0},gravity:{x:0,y:-1,z:0},quaternion:{...upright,x:inverse?-upright.x:upright.x}};host.__partySportsMotion(payload);for(const k of ['x','y','z','w'])assert(Math.abs(sample.deviceQuaternion[k]-upright[k])<1e-10);assert.equal(sample.attitudeBasis,inverse?'native-inverse':'native-direct');host.__partySportsMotion({...payload,sourceTime:2,gravity:{x:0,y:0,z:-1},quaternion:flat});assert.equal(sample.attitudeBasis,inverse?'native-inverse':'native-direct');}finally{sensor.stop();}}});
test('a corrected sensor basis discards old direction and impulse before recalibration',async()=>{const {FreeMotionThrow}=await ready;const g=new FreeMotionThrow();for(let t=0;t<=900;t+=30)g.feed({...s(t),attitudeBasis:'native-inverse'},true);assert(g.armed);g.feed({...s(930,12),attitudeBasis:'native-inverse'},true);assert.equal(g.feed({...s(960,12),attitudeBasis:'native-direct'},true),null);assert.equal(g.frame,null);assert.equal(g.attempt,null);});
test('twelve successive straight throws keep a neutral lane and spin under small sensor bias and changing grips',async()=>{const {FreeMotionThrow}=await ready;const g=new FreeMotionThrow();let t=0,frame;for(let round=0;round<12;round++){const q=[flat,upright,side][round%3];for(let i=0;i<31;i++,t+=30)g.feed(s(t,0,.5,4,q),true);frame??=g.frame;assert.equal(g.frame,frame);const shots=[];for(let i=0;i<12;i++,t+=30){const shot=g.feed(s(t,i<6?10:0,.5,4,q),true);if(shot)shots.push(shot);}assert.equal(shots.length,1);assert.equal(shots[0].angle,0);assert.equal(shots[0].spin,0);}});
test('aim neutral zone is symmetric and continuous; deliberate lateral movement and wrist spin remain',async()=>{const {FreeMotionThrow}=await ready;const shot=lateral=>{const g=new FreeMotionThrow();settle(g);return flick(g,930,10,lateral,80)[0];};assert.equal(shot(.4).angle,0);assert.equal(shot(-.4).angle,0);const left=shot(-2),right=shot(2);assert(left.angle<-.1&&right.angle>.1);assert(Math.abs(left.angle+right.angle)<1e-8);assert(right.spin>.2);assert(shot(.71).angle<.005);});
