'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {webkit}=require(process.env.PARTY_PLAYWRIGHT||'playwright');
const out=path.resolve('.localparty-build/design-round2/logo-rendering'),asset=path.resolve('public/assets/game-logos-v1');
fs.mkdirSync(out,{recursive:true});
const manifest=JSON.parse(fs.readFileSync(path.join(asset,'manifest.json'))),report={capturedAt:new Date().toISOString(),method:'Actual review gallery and shipped renderer, WebKit at DPR1/2/3. Original PNG hashes must remain unchanged.',logos:[],densities:[],errors:[]};
async function inspect(figure){return figure.evaluate(el=>{const img=el.querySelector('img'),canvas=el.querySelector('canvas'),r=img.getBoundingClientRect(),c=canvas?.getBoundingClientRect(),data=canvas?.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data;let painted=0,edge=0;if(data)for(let y=0;y<canvas.height;y++)for(let x=0;x<canvas.width;x++){const alpha=data[(y*canvas.width+x)*4+3];if(alpha)painted++;if((x===0||y===0||x===canvas.width-1||y===canvas.height-1)&&alpha)edge++;}return{source:img.currentSrc,naturalWidth:img.naturalWidth,naturalHeight:img.naturalHeight,sourceOpacity:getComputedStyle(img).opacity,box:{width:r.width,height:r.height},canvas:canvas&&{width:canvas.width,height:canvas.height,cssWidth:c.width,cssHeight:c.height,xError:c.x-r.x,yError:c.y-r.y},painted,edge,dpr:devicePixelRatio};});}
function check(row){assert(row.canvas,'Canvas painted');assert.equal(row.sourceOpacity,'0');assert.equal(row.canvas.width,Math.round(row.box.width*Math.min(row.dpr,3)));assert.equal(row.canvas.height,Math.round(row.box.height*Math.min(row.dpr,3)));assert(Math.abs(row.canvas.xError)<.6&&Math.abs(row.canvas.yError)<.6,'Canvas aligns with actual logo');assert(row.painted>100,'Logo pixels visible');assert.equal(row.edge,0,'Transparent reserve survives contain scaling');}
(async()=>{const browser=await webkit.launch({headless:true});try{
 const context=await browser.newContext({viewport:{width:1280,height:852},deviceScaleFactor:2}),page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));await page.goto('http://127.0.0.1:17799/');assert.equal(await page.locator('.logo').count(),36);
 for(const logo of manifest.logos){const article=page.locator('.logo').filter({has:page.locator(`img[src="/logos/${logo.id}.png"]`)}),figure=article.locator('figure');await article.scrollIntoViewIfNeeded();await figure.locator('img').evaluate(img=>img.loading='eager');await page.waitForFunction(id=>document.querySelector(`img[src="/logos/${id}.png"]`)?.dataset.hpLogoSmooth==='ready',logo.id);const row={id:logo.id,...await inspect(figure)};check(row);assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(asset,logo.file))).digest('hex'),logo.sha256);await figure.screenshot({path:path.join(out,logo.id+'-dpr2.png')});report.logos.push(row);}
 for(const dpr of [1,3]){const ctx=await browser.newContext({viewport:{width:375,height:812},deviceScaleFactor:dpr}),p=await ctx.newPage();await p.goto('http://127.0.0.1:17799/');for(const id of ['push','pocket_siege','millionaire']){const figure=p.locator('.logo').filter({has:p.locator(`img[src="/logos/${id}.png"]`)}).locator('figure');await figure.scrollIntoViewIfNeeded();await p.waitForFunction(id=>document.querySelector(`img[src="/logos/${id}.png"]`)?.dataset.hpLogoSmooth==='ready',id);const row={id,...await inspect(figure)};check(row);await figure.screenshot({path:path.join(out,`${id}-dpr${dpr}.png`)});report.densities.push(row);}await ctx.close();}
 // TV CSS zoom must increase bitmap density, without doubling positioning.
 const zoomed=page.locator('.logo').first();await zoomed.scrollIntoViewIfNeeded();await zoomed.evaluate(el=>el.style.zoom='1.5');await page.evaluate(()=>dispatchEvent(new Event('resize')));
 await page.waitForFunction(()=>{const img=document.querySelector('.logo img'),canvas=img.parentElement.querySelector('canvas');return canvas.width===Math.round(parseFloat(getComputedStyle(img).width)*devicePixelRatio*1.5);});
 report.zoomed=await inspect(zoomed.locator('figure'));check(report.zoomed);await zoomed.locator('figure').screenshot({path:path.join(out,'push-zoom15-dpr2.png')});
 await zoomed.evaluate(el=>el.style.zoom='1');await page.evaluate(()=>dispatchEvent(new Event('resize')));
 // A renderer failure preserves the original image as a useful fallback.
 const fallback=await browser.newPage({viewport:{width:393,height:852}});await fallback.addInitScript(()=>HTMLCanvasElement.prototype.getContext=function(){return null;});await fallback.goto('http://127.0.0.1:17799/');const img=fallback.locator('.logo img').first();await img.scrollIntoViewIfNeeded();await img.evaluate(img=>new Promise(resolve=>img.complete?resolve():img.addEventListener('load',resolve,{once:true})));assert.equal(await img.evaluate(img=>getComputedStyle(img).opacity),'1');assert.equal(await fallback.locator('.hp-smooth-game-logo').count(),0);await fallback.locator('.logo').first().screenshot({path:path.join(out,'fallback.png')});
 // Removing and reattaching an existing logo must not leave an old painted copy.
 const first=page.locator('.logo').first();await first.scrollIntoViewIfNeeded();await first.evaluate(async el=>{const img=el.querySelector('img'),parent=img.parentElement;img.remove();await new Promise(r=>requestAnimationFrame(r));parent.append(img);});await page.waitForFunction(()=>document.querySelector('.logo img')?.dataset.hpLogoSmooth==='ready');assert.equal(await first.locator('.hp-smooth-game-logo').count(),1);check(await inspect(first.locator('figure')));
 assert.deepEqual(report.errors,[]);console.log('PASS36 logos at DPR2,6 density checks, fallback and remount');
}finally{fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));await browser.close();}})().catch(error=>{report.failure=error.message;fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.error(error);process.exitCode=1;});
