'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{Arcade}=require('../games/arcade/simulation');
function arena(attacker=23,victim=20,gap=28){const g=new Arcade('hungry',()=>.5);g.join('a','A');g.join('b','B');g.start();g.food=[];Object.assign(g.players[0],{mass:attacker,x:500,y:400,shield:0});Object.assign(g.players[1],{mass:victim,x:500+gap,y:400,shield:0});return g;}
function step(g,seconds){for(let t=0;t<seconds;t+=.01)g.tick(.01);}
test('One food from starting20→23 enables immediate contact absorption without a hold',()=>{const g=arena(20);g.food=[{id:900,x:500,y:400,kind:1}];g.tick(.01);assert.equal(g.players[1].dead,1.5);assert.equal(g.players[0].mass,37);assert.equal(g.players[0].score,37);assert.equal(g.players[1].mass,20);assert.equal(g.players[1].score,20);});
test('Equal, smaller and barely larger attackers cannot consume the target',()=>{for(const mass of [19,20,20.99,21]){const g=arena(mass,20,0);g.tick(.01);assert.equal(g.players[1].dead,0,String(mass));if(mass>=20)assert.equal(g.players[0].dead,0,'Equal or sub5% lead stays neutral');}});
test('A visible advantage succeeds; separated silhouettes do not absorb remotely',()=>{const contact=arena(21.01,20,28);contact.tick(.01);assert(contact.players[1].dead>0);const far=arena(100,20,60);far.tick(.01);assert.equal(far.players[1].dead,0);});
test('Original two-second spawn protection prevents contact absorption',()=>{const g=arena();g.players[1].shield=2;step(g,1.98);assert.equal(g.players[1].dead,0);assert.equal(g.players[0].mass,23);step(g,.03);assert(g.players[1].dead>0);});
test('Dead targets reward only once; returning players receive the original shield',()=>{const g=arena();g.tick(.01);step(g,1);assert.equal(g.players[0].mass,37);assert(g.players[1].dead>0);step(g,.51);assert.equal(g.players[1].dead,0);assert(g.players[1].shield>1.9);assert.equal(g.players[1].mass,20);});
test('A target in contact with two larger blobs rewards only one attacker',()=>{const g=arena(23,20,28);g.join('c','C');Object.assign(g.players[2],{mass:23,x:556,y:400,shield:0});g.tick(.01);assert(g.players[1].dead>0);assert.equal(g.players[0].mass,37);assert.equal(g.players[2].mass,23);assert.equal(g.players[2].dead,0);});
test('Player absorption leaves every food identity, position and appearance unchanged',()=>{const g=arena();g.food=[{id:101,x:1000,y:650,kind:2},{id:102,x:950,y:600,kind:3}];const before=structuredClone(g.food);g.tick(.01);assert(g.players[1].dead>0);assert.deepEqual(g.food,before);});
