'use strict';
const {spawn}=require('node:child_process'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {webkit}=require(process.env.PARTY_PLAYWRIGHT||'playwright');
const phase=process.env.QA_GRADIENT_PHASE||'after',out=path.resolve('.localparty-build/mobile-gradient103',phase);fs.mkdirSync(out,{recursive:true});
const sources=['public/game-polish.css','public/background-scene.css','public/game-ui-system.css','public/game-ui-system.js','public/app.js','public/native-shell/controller-bridge.js','public/native-shell/tabs.js'];
const hashes=()=>Object.fromEntries(sources.map(p=>[p,crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')]));
const report={method:'Real six-player Tap Race state transitions. Native WebKit fixture runs shipped controller-bridge in all frames and shipped tabs at document start in main frame with persistent-tabs=true, matching the native script order. Logical widths320/393/402, the latter matching reported iPhone17Pro402x874. No physical iPhone claim. Normal engine clock by default (QA_GRADIENT_FAST=1 is diagnostic-only); no injected game outcomes.',startedAt:new Date().toISOString(),sourceStart:hashes(),captures:[],errors:[],nativeMessages:[]};
const child=spawn(process.execPath,['server.js'],{env:{...process.env,PARTY_EMBEDDED:'1',PARTY_INTERNAL_PORT:'0',PARTY_PORT:'0',PARTY_EPHEMERAL:'1',PARTY_NO_BROWSER:'1',PARTY_ADMIN_KEY:'gradient-103-qa',TEST_FAST:process.env.QA_GRADIENT_FAST||'0'}});let log='',browser;
child.stdout.on('data',d=>log+=d);child.stderr.on('data',d=>log+=d);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,label){for(let i=0;i<2000;i++){const v=await fn();if(v)return v;await sleep(40);}throw Error(label);}
async function metrics(p){return p.evaluate(()=>{const s=(selector,pseudo)=>{const n=document.querySelector(selector);if(!n)return null;const c=getComputedStyle(n,pseudo),r=n.getBoundingClientRect();return{hidden:n.hidden,visible:c.display!=='none'&&c.visibility!=='hidden',background:c.background,backgroundColor:c.backgroundColor,backgroundImage:c.backgroundImage,display:c.display,position:c.position,opacity:c.opacity,zIndex:c.zIndex,isolation:c.isolation,filter:c.filter,backdropFilter:c.backdropFilter,top:c.top,bottom:c.bottom,rect:{x:r.x,y:r.y,width:r.width,height:r.height,bottom:r.bottom}};};return{width:innerWidth,height:innerHeight,classes:document.body.className,phase:document.body.dataset.phase,horizontal:document.documentElement.scrollWidth-innerWidth,native:!!window.LocalPartyNative,tabs:!!window.LocalPartyTabs,persistent:!!window.__partyPersistentTabs,body:s('body'),bodyBefore:s('body','::before'),header:s('#brandHeader'),headerBefore:s('#brandHeader','::before'),play:s('#play'),frame:s('#gameFrame'),pause:s('#pauseOverlay'),controls:s('#sessionControls'),controlsBefore:s('#sessionControls','::before'),controlsAfter:s('#sessionControls','::after'),results:s('#sharedMatchResults'),dock:s('#partyNativeDock'),rules:document.querySelector('.waiting-details')?.open||false,waitingContent:s('#waitingContent'),waitingSummary:s('.waiting-details>summary'),ruleScroll:document.querySelector('.waiting-rules-body')?{height:document.querySelector('.waiting-rules-body').clientHeight,scrollHeight:document.querySelector('.waiting-rules-body').scrollHeight}:null};});}
(async()=>{try{
 await until(()=>/localhost:(\d+)/.test(log),'server ready');const origin='http://127.0.0.1:'+log.match(/localhost:(\d+)/)[1];
 const api=async body=>{const r=await fetch(origin+'/api/manage',{method:body?'POST':'GET',headers:{Authorization:'Bearer gradient-103-qa','Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});assert(r.ok,await r.clone().text());return r.json();};
 browser=await webkit.launch({headless:true});const tv=await browser.newPage({viewport:{width:1280,height:720}});await tv.goto(origin+'/tv');const phones=[];
 for(const kind of ['native','web'])for(const width of [320,393,402]){
  const context=await browser.newContext({viewport:{width,height:Number(process.env.QA_GRADIENT_HEIGHT)||(width===320?568:width===402?874:852)},isMobile:true,hasTouch:true,deviceScaleFactor:2});
  if(kind==='native')await context.addInitScript({content:'window.webkit={messageHandlers:{partyShell:{postMessage(data){}}}};'+fs.readFileSync('public/native-shell/controller-bridge.js','utf8')+'\nif(window===window.top){window.__partyPersistentTabs=true;'+fs.readFileSync('public/native-shell/tabs.js','utf8')+'\n}'});
  const p=await context.newPage();p.on('pageerror',e=>report.errors.push(kind+width+': '+e.message));await p.goto(origin+'/play');await p.locator('#name').fill(kind+' '+width);await p.locator('#joinForm button[type=submit]').click();await p.locator('#home').waitFor();phones.push({p,kind,width});
 }
 async function capture(name){for(const {p,kind,width} of phones){await sleep(130);const state=await api(),m=await metrics(p),file=kind+'-'+width+'-'+name+'.png';await p.screenshot({path:path.join(out,file)});report.captures.push({file,sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(out,file))).digest('hex'),state:{phase:state.active?.ui.phase,paused:state.active?.session.paused,resultKey:state.active?.result?.key},metrics:m});assert.equal(m.horizontal,0,file+' horizontal overflow');if(kind==='native'){assert(m.native&&m.tabs&&m.persistent,file+' real native scripts present');}if(phase==='after'||phase==='final104'){const expected=name.startsWith('waiting')?'waiting':name==='playing'||name==='resumed'?'playing':name.includes('paused')?'paused':name.startsWith('results')?'results':null;if(expected)assert.equal(m.phase,expected,file+' genuine UI state');if(name.includes('paused')||name.startsWith('results')){assert.equal(m.frame.visible,false,file+' opaque iframe no longer paints');assert.equal(m.pause.backgroundColor,'rgba(0, 0, 0, 0)',file+' no clipped pause plane');assert.equal(m.pause.backdropFilter,'none',file+' no clipped plane blur');if(name.includes('paused')&&m.results)assert.equal(m.results.visible,false,file+' results do not paint through pause');assert(!m.bodyBefore.backgroundImage.includes('radial-gradient'),file+' no mobile glow');}}if((phase==='final104'||phase.startsWith('pause-final'))&&name==='waiting'){assert(m.waitingSummary.rect.y>=m.waitingContent.rect.y-1&&m.waitingSummary.rect.bottom<=m.waitingContent.rect.bottom+1,file+' complete closed Rules tap target visible');}if(name==='playing'||name==='resumed'){const f=p.frames().find(f=>f.url().includes('/games/'));assert(f,file+' actual game iframe');const plane=await f.evaluate(()=>({root:getComputedStyle(document.documentElement).backgroundColor,body:getComputedStyle(document.body).backgroundColor,pseudo:getComputedStyle(document.body,'::before').display}));assert.equal(plane.root,'rgba(0, 0, 0, 0)',file+' transparent game root');assert.equal(plane.body,'rgba(0, 0, 0, 0)',file+' transparent game body');assert.equal(plane.pseudo,'none',file+' no duplicate opaque background');}if(name!=='lobby'){assert(m.headerBefore.backgroundImage.includes('linear-gradient'),file+' header gradient');assert(m.controlsBefore.backgroundImage.includes('linear-gradient'),file+' footer gradient');assert.equal(m.play.backgroundColor,'rgba(0, 0, 0, 0)',file+' transparent parent');assert(m.controls.rect.bottom<=m.height+1,file+' footer in viewport');}}fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));}
 await api({type:'launch',id:'taprace'});await Promise.all(phones.map(({p})=>p.waitForFunction(()=>!document.getElementById('readyButton').disabled)));await sleep(400);await capture('waiting');
 if(!process.env.QA_GRADIENT_HEIGHT){for(const {p} of phones)await p.locator('.waiting-details>summary').click();await sleep(400);await capture('waiting-open');if(phase==='final104'){for(const {p} of phones){await p.locator('.waiting-rules-body').evaluate(n=>n.scrollTo({top:n.scrollHeight,behavior:'instant'}));await sleep(100);const reached=await p.locator('.waiting-rules-body').evaluate(n=>{const r=n.getBoundingClientRect(),last=n.lastElementChild.getBoundingClientRect();return{bottom:r.bottom,lastBottom:last.bottom,below:n.dataset.scrollBelow,soft:n.classList.contains('hp-soft-scroll'),scrollTop:n.scrollTop,client:n.clientHeight,scrollHeight:n.scrollHeight};});assert(reached.lastBottom<=reached.bottom+1,'last expanded rule reachable');assert(!reached.soft||reached.below!=='true','rules end fade clears only when scrolling class applies');}await capture('waiting-open-end');}for(const {p} of phones)await p.locator('.waiting-details>summary').click();await sleep(350);}
 if(!(process.env.QA_GRADIENT_PAUSE_ONLY==='1'&&process.env.QA_GRADIENT_HEIGHT)){for(const {p} of phones){await p.locator('#readyButton').click();await sleep(100);}report.afterReady=await api();fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));await until(async()=>{const s=await api();return s.active?.ui.phase==='playing';},'real playing');await capture('playing');}else report.pauseOrigin='Real session paused in matchmaking via the actual Pause button; same shared pause component in an extreme480px fixture.';
 await phones[0].p.locator('#pauseButton').click();await until(async()=>(await api()).active?.session.paused,'real pause');await sleep(400);await capture('paused');
 if(process.env.QA_GRADIENT_PAUSE_ONLY==='1'){
  report.pauseCards=[];
  for(const {p,kind,width} of phones){
   const measure=()=>p.evaluate(()=>{const n=document.querySelector('#pauseOverlay'),card=n.firstElementChild,language=n.querySelector('.party-language-setting'),rect=x=>{const r=x.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,bottom:r.bottom};};return{overlay:rect(n),card:rect(card),language:language?rect(language):null,scrollTop:n.scrollTop,scrollHeight:n.scrollHeight,clientHeight:n.clientHeight,cardStyle:getComputedStyle(card).cssText,titleSize:getComputedStyle(n.querySelector('h2')).fontSize,resumeHeight:n.querySelector('#resumeButton').getBoundingClientRect().height,fadeBefore:n.dataset.scrollAbove,fadeAfter:n.dataset.scrollBelow,mask:getComputedStyle(n).maskImage,fadeBottom:getComputedStyle(n).getPropertyValue('--hp-scroll-fade-bottom'),targets:[...n.querySelectorAll('button,select')].filter(x=>!x.hidden).map(x=>({id:x.id,height:x.getBoundingClientRect().height}))};});
   const before=await measure();await p.locator('#pauseOverlay').evaluate(n=>n.scrollTo({top:n.scrollHeight,behavior:'instant'}));await sleep(250);const after=await measure(),file=kind+'-'+width+'-paused-bottom.png';await p.screenshot({path:path.join(out,file)});report.pauseCards.push({kind,width,before,after,file});if(phase.startsWith('pause-final')){assert(after.language.bottom<=after.overlay.bottom+1,file+' Language accessible');assert(after.card.bottom<=after.overlay.bottom+1,file+' rounded card bottom visible');assert(after.targets.every(t=>t.height>=44),file+'44px targets');if(before.scrollHeight>before.clientHeight+2){assert.equal(before.fadeAfter,'true',file+' bottom continuation fades');assert.equal(after.fadeAfter,'false',file+' fade clears at reached edge');}else{assert(before.card.bottom<=before.overlay.bottom,file+' full card initially fits');}}
  }
  report.scrollMethod='Actual DOM scrollTo on the native-fixture scroll container; mobile WebKit does not support mouse.wheel. No physical touch claim.';console.log('PASS pause-only real rendered container end-scroll evidence');return;
 }
 await phones[0].p.locator('#resumeButton').click();await until(async()=>!(await api()).active?.session.paused,'real resume');await sleep(280);await capture('resumed');
 await until(async()=>{const s=await api();return s.active?.ui.phase==='results'&&s.active.result;},'real finish');await Promise.all(phones.map(({p})=>p.locator('#sharedMatchResults').waitFor({state:'visible'})));await sleep(500);await capture('results');
 // Finished controllers cannot pause a completed game; keep the result surface stable.
 for(const {p} of phones)assert(await p.locator('#pauseButton').isDisabled(),'Pause is unavailable after a real finish');
 const resultKey=(await api()).active.result.key;
 await phones[0].p.locator('#pauseButton').evaluate(el=>el.click());await sleep(400);
 assert.equal((await api()).active.session.paused,false,'Disabled finish Pause cannot change session');
 assert.equal((await api()).active.result.key,resultKey,'Finished result identity is preserved');await capture('results-stable');
 await api({type:'stop'});await Promise.all(phones.map(({p})=>p.locator('#home').waitFor()));await sleep(350);await capture('lobby');
 assert.deepEqual(report.errors,[]);console.log('PASS '+phase+' '+report.captures.length+' captures; real native + web waiting/playing/pause/resume/results/disabled-finish-pause/lobby.');
}finally{report.finishedAt=new Date().toISOString();report.sourceEnd=hashes();report.changedFiles=sources.filter(f=>report.sourceStart[f]!==report.sourceEnd[f]);report.serverLogTail=log.slice(-2000);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));await browser?.close();child.kill();}})().catch(e=>{report.failure=e.message;fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.error(e);process.exitCode=1;});
