const {test}=require('node:test'),assert=require('node:assert/strict'),{fork}=require('node:child_process'),path=require('node:path'),{WebSocket}=require('ws'),{PNG}=require('pngjs'),drawing=require('../games/monster/public/drawing');
test('drawing trims vertical blank space, preserves seam and composes at original scale',()=>{const w=720,h=520,data=new Uint8ClampedArray(w*h*4);for(let i=0;i<data.length;i+=4)data.set([...drawing.BACKGROUND,255],i);for(let y=100;y<201;y++)for(let x=280;x<291;x++)data.set([10,10,10,255],(y*w+x)*4);assert.deepEqual(drawing.bounds(data,w,h),{top:100,bottom:200,height:101});assert.equal(drawing.bounds(data,w,h,true).top,0);assert.deepEqual(drawing.layout([{height:101},{height:90,overlap:12},{height:160,overlap:12}]).items.map(i=>i.y),[0,89,167]);assert.equal(drawing.layout([{height:101},{height:90,overlap:12}]).height,179);const slice=data.slice(100*w*4,201*w*4);assert.equal(drawing.connectors(slice,w,101).length,1);assert.ok(Math.abs(drawing.connectors(slice,w,101)[0]-285/w)<.001);});
async function client(port){const ws=new WebSocket(`ws://127.0.0.1:${port}/socket.io/?EIO=4&transport=websocket`);let seq=0;const acks=new Map(),events=[];ws.on('message',raw=>{const text=String(raw);if(text==='2')ws.send('3');else if(text[0]==='0')ws.send('40');else if(text.startsWith('43')){const m=text.match(/^43(\d+)(.*)$/);acks.get(+m[1])?.(JSON.parse(m[2])[0]);}else if(text.startsWith('42'))events.push(JSON.parse(text.slice(2)));});await new Promise((r,j)=>{ws.on('message',raw=>{if(String(raw).startsWith('40'))r();});ws.once('error',j);});return{ws,events,emit(event,payload={}){return new Promise((resolve,reject)=>{const id=seq++,timer=setTimeout(()=>reject(new Error(event+' ack timeout')),3000);acks.set(id,value=>{clearTimeout(timer);acks.delete(id);resolve(value);});ws.send('42'+id+JSON.stringify([event,payload]));});}};}
function png(h){const p=new PNG({width:720,height:h});p.data.fill(255);return'data:image/png;base64,'+PNG.sync.write(p).toString('base64');}
test('Monster: 16 identities, refresh, private seam, submissions, late joining and result report',async t=>{
const profiles=Array.from({length:16},(_,i)=>({id:'monster-'+i,name:'Художник '+i,token:'secret-'+i,hand:'right'}));const child=fork(path.resolve('games/monster/server.js'),[],{silent:true,env:{...process.env,PORT:'0',PARTY_MANAGED:'1',PARTY_ROSTER:JSON.stringify(profiles)}});const clients=[],reports=[];child.on('message',m=>{if(m.type==='party:result')reports.push(m.result);});t.after(()=>{clients.forEach(c=>c.ws.terminate());child.kill();});
const port=await new Promise((r,j)=>{let out='';const timer=setTimeout(()=>j(new Error(out)),5000);child.stdout.on('data',d=>{out+=d;const m=out.match(/localhost:(\d+)/);if(m){clearTimeout(timer);r(+m[1]);}});child.stderr.on('data',d=>out+=d);});const host=await client(port);clients.push(host);
async function join(i,resume=false){const c=await client(port);clients.push(c);const p=profiles[i],ack=await c.emit(resume?'player:resume':'player:join',{partyId:p.id,partyToken:p.token});assert.equal(ack.ok,true);assert.equal(ack.playerId,p.id);return c;}
const phones=[];for(let i=0;i<15;i++)phones.push(await join(i));assert.equal((await host.emit('host:start')).ok,true);phones[0]=await join(0,true);phones.push(await join(15));
const active=phones[0].events.find(e=>e[0]==='turn:start')?.[1];assert.ok(active);assert.equal(active.stripData,null);assert.ok(active.turnDeadline>Date.now());
const image=png(70),strip=png(12);for(let i=0;i<16;i++){const ack=await phones[i].emit('turn:submit',{imageData:image,height:70,stripData:strip,stripHeight:12,overlap:i?12:0,connectorXs:[.4,.6],strokes:5});assert.equal(ack.ok,true);if(i===0){await new Promise(r=>setTimeout(r,20));const turn=phones[1].events.find(e=>e[0]==='turn:start')[1];assert.equal(turn.stripData,strip);assert.equal(turn.imageData,undefined);assert.equal(turn.overlap,12);}}
await new Promise(r=>setTimeout(r,30));assert.equal(reports.length,1);assert.equal(reports[0].players.length,16);assert.equal(reports[0].players[0].id,profiles[0].id);assert.equal(reports[0].players[0].metrics.strokes,5);const reveal=host.events.find(e=>e[0]==='round:reveal')[1];assert.equal(drawing.layout(reveal.segments).height,16*70-15*12);
});
