'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname, '..');
const read = p => fs.readFileSync(path.join(root,p),'utf8');
const bridge = read('public/native-shell/controller-bridge.js');
const html = read('public/native-shell/index.html');
const ui = read('public/native-shell/host.js');
const swift = read('ios/LocalParty/LocalPartyApp.swift');
const {parts, compare, classify} = require('../scripts/check-release-versions.cjs');
function controller({protocol='http:', hostname='127.0.0.1', native=true, frame=false}={}) {
  const messages=[];
  const context={location:{protocol,hostname}, navigator:{}, document:{readyState:'loading', addEventListener(){}}, window:{}};
  context.window=context;
  context.top=frame?{}:context;
  if(native)context.webkit={messageHandlers:{partyShell:{postMessage:m=>messages.push(m)}}};
  vm.runInNewContext(bridge,context);
  return {context,messages};
}
test('browser guests never receive a fake vibration API',()=>{const {context}=controller({native:false});assert.equal(context.navigator.vibrate,undefined);});
test('remote origins do not receive a native adapter',()=>{const {context}=controller({hostname:'attacker.example'});assert.equal(context.navigator.vibrate,undefined);});
test('HTTPS pages are not mistaken for the trusted loopback controller',()=>{const {context}=controller({protocol:'https:'});assert.equal(context.navigator.vibrate,undefined);});
test('native controller forwards numeric haptics',()=>{const {context,messages}=controller();assert.equal(context.navigator.vibrate(20),true);assert.equal(JSON.stringify(messages[0]),JSON.stringify({type:'haptic',pattern:[20]}));});
test('native controller forwards a pattern from a game iframe',()=>{const {context,messages}=controller({frame:true});assert.equal(context.navigator.vibrate([12,24,18]),true);assert.equal(messages.length,1);});
test('native controller validates all haptic durations',()=>{const {context,messages}=controller();for(const x of [Infinity,NaN,-1,'20',[1,-2],[undefined]])assert.equal(context.navigator.vibrate(x),false);assert.equal(messages.length,0);});
test('native haptic patterns are bounded and rounded',()=>{const {context,messages}=controller();context.navigator.vibrate([800,1.8]);assert.equal(JSON.stringify(messages[0].pattern),'[500,2]');assert.equal(context.navigator.vibrate(Array(13).fill(1)),false);});
test('empty pattern cancels pending feedback',()=>{const {context,messages}=controller();assert.equal(context.navigator.vibrate([]),true);assert.equal(JSON.stringify(messages[0].pattern),'[0]');});
test('standard launcher CSS is reused, not a forked visual theme',()=>{for(const f of ['style.css','refresh.css','glass.css','ux.css','fresh.css'])assert.ok(html.includes(`href="/${f}"`));});
test('host menu is a normal nav button with dialog semantics',()=>{assert.match(html,/id="openHost" class="nav"[^>]*aria-haspopup="dialog"/);assert.match(html,/id="hostPanel"[^>]*aria-labelledby="hostTitle"/);});
test('static IDs are unique and every literal JS lookup exists',()=>{const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length);for(const [,id]of ui.matchAll(/\$\('([^']+)'\)/g))assert.ok(ids.includes(id),`Missing ${id}`);});
test('untrusted names are never inserted as HTML',()=>{assert.doesNotMatch(ui,/\.innerHTML\s*=/);assert.match(ui,/textContent/);});
test('menu cannot connect to HTTP admin endpoints',()=>{assert.match(html,/connect-src 'none'/);assert.doesNotMatch(ui,/fetch\(|new WebSocket/);});
test('Swift separates admin authorization from player haptics',()=>{assert.match(swift,/guard shell else \{ return \}/);assert.match(swift,/message\.webView === menu && message\.frameInfo\.isMainFrame/);assert.match(swift,/origin\.port == url\.port/);assert.doesNotMatch(swift,/PARTY_ADMIN_KEY|Bearer /);});
test('native shell rejects directory traversal and other filesystem roots',()=>{assert.match(swift,/contains\("\.\."\)/);assert.match(swift,/file\.path\.hasPrefix\(base\.path \+ "\/"\)/);});
test('held input and feedback are cancelled when leaving the controller',()=>{assert.match(swift,/party-native-hide/);assert.match(swift,/w\.frames\[i\]/);assert.match(swift,/if value != \.active \{ cancelHaptics\(\) \}/);});
test('external display role and guarded permission strings remain in plist',()=>{const plist=read('ios/LocalParty/Info.plist');for(const key of ['UIWindowSceneSessionRoleExternalDisplayNonInteractive','NSMotionUsageDescription','NSCameraUsageDescription'])assert.ok(plist.includes(key));assert.ok(!plist.includes('NSAllowsArbitraryLoads'));});
test('stable version parsing rejects pre-release tags',()=>{assert.deepEqual(parts('v24.21.0'),[24,21,0]);assert.equal(parts('27.2.0-beta'),null);});
test('version comparisons use numeric components',()=>{assert.equal(compare('24.21.0','24.9.0'),1);assert.equal(compare('1.0.0','1.0.0'),0);});
test('latest audit never recommends downgrading',()=>{assert.equal(classify('0.186.0','0.180.0','three'),'ahead-of-registry-do-not-downgrade');});
test('0.x minors and major bumps require review',()=>{assert.equal(classify('0.186.0','0.187.0','three'),'breaking-upgrade-review');assert.equal(classify('4.22.2','5.0.0','express'),'breaking-upgrade-review');});
test('native physics upgrades require regeneration',()=>{assert.equal(classify('0.20.0','0.21.0','@dimforge/rapier3d-compat'),'native-regeneration-required');});
test('patch upgrades remain test-first candidates',()=>{assert.equal(classify('4.8.1','4.8.2','socket.io'),'update-candidate-test-first');});
