'use strict';
const assert=require('assert/strict'),path=require('path'),{spawn}=require('child_process');
const {chromium}=require('C:/Users/nirrt/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const child=spawn(process.execPath,['server.js'],{cwd:path.join(__dirname,'..'),env:{...process.env,PARTY_PORT:'0',PARTY_EPHEMERAL:'1',PARTY_NO_BROWSER:'1'},windowsHide:true,stdio:['ignore','pipe','pipe']});let browser;
try{const base=await new Promise((resolve,reject)=>{let out='';const timer=setTimeout(()=>reject(Error(out)),12000);child.stderr.on('data',d=>out+=d);child.stdout.on('data',d=>{out+=d;const m=out.match(/LOCAL PARTY — http:\/\/localhost:(\d+)\/host/);if(m){clearTimeout(timer);resolve('http://localhost:'+m[1]);}});child.on('error',reject);});
 browser=await chromium.launch({channel:'msedge',headless:true});const errors=[],phones=[];
 const host=await browser.newPage({viewport:{width:1440,height:1000}});host.on('pageerror',e=>errors.push(e.message));await host.goto(base+'/host');
 async function phone(name){const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.locator('#name').fill(name);await page.locator('#joinForm button').click();await page.waitForFunction(()=>!!window.PARTY_PROFILE.id);return {page,context,id:await page.evaluate(()=>PARTY_PROFILE.id)};}
 phones.push(await phone('Аня'),await phone('Боря'));await host.waitForFunction(()=>document.querySelectorAll('#players .player').length===2);
 await host.screenshot({path:path.join(__dirname,'platform-host.png'),fullPage:true});await phones[0].page.screenshot({path:path.join(__dirname,'platform-phone.png'),fullPage:true});
 const allIds=await host.locator('.game').evaluateAll(cards=>cards.map(c=>c.dataset.id));const selected=process.env.PARTY_SMOKE_GAMES?.split(',');const ids=selected?allIds.filter(id=>selected.includes(id)):allIds;const checks=[];
 for(const id of ids){await host.locator(`.game[data-id="${id}"] .start-game`).click();await host.waitForFunction(id=>document.querySelector('#gameFrame').getAttribute('src')?.startsWith('/games/'+id+'/'),id);
   for(const p of phones){await p.page.waitForFunction(id=>document.querySelector('#gameFrame').getAttribute('src')?.startsWith('/games/'+id+'/'),id);await p.page.waitForFunction(()=>document.querySelector('#gameConnection').textContent==='Ты в игре',null,{timeout:12000});}
   const hostFrame=host.frames().find(f=>f.url().includes('/games/'+id+'/'));
   const starts={push:'[data-mode="push"]',shrink:'[data-mode="shrink"]',knives:'[data-mode="knives"]',bomb:'[data-mode="bomb"]',western:'[data-mode="western"]',tanks:'[data-mode="survival"]',chaos:'#start',kart:'#startBtn',monster:'#startGame',spy:'#startBtn'};
   await hostFrame.locator(starts[id]||'#start').click({timeout:10000,force:true});
   const frame=phones[0].page.frames().find(f=>f.url().includes('/games/'+id+'/'));assert(frame,'missing frame '+id);await frame.waitForTimeout(400);
   const check=await frame.evaluate(()=>{const buttons=[...document.querySelectorAll('button,[role=button],canvas')].filter(b=>b.getBoundingClientRect().width>0);const b=buttons[0];return {width:innerWidth,scroll:document.documentElement.scrollWidth,buttons:buttons.length,select:buttons.every(b=>getComputedStyle(b).userSelect==='none'),blocked:!b||!b.dispatchEvent(new Event('selectstart',{bubbles:true,cancelable:true}))};});assert(check.select,id+' selectable controls');assert(check.blocked,id+' selection event');assert(check.scroll<=check.width+2,id+' overflow '+JSON.stringify(check));checks.push({id,...check});
   if(id==='push'){const late=await phone('Вера');phones.push(late);await late.page.waitForFunction(()=>document.querySelector('#gameConnection').textContent==='Ты в игре');const before=await phones[0].page.locator('#gameFrame').getAttribute('src');await phones[0].context.setOffline(true);await new Promise(r=>setTimeout(r,1000));await phones[0].context.setOffline(false);await phones[0].page.evaluate(()=>window.dispatchEvent(new Event('online')));await phones[0].page.waitForFunction(()=>document.querySelector('#connection').classList.contains('online'));await phones[0].page.waitForFunction(()=>document.querySelector('#gameConnection').textContent==='Ты в игре');assert.equal(await phones[0].page.evaluate(()=>PARTY_PROFILE.id),phones[0].id);assert.equal(await phones[0].page.locator('#gameFrame').getAttribute('src'),before);await phones[0].page.reload();await phones[0].page.waitForFunction(()=>document.querySelector('#gameConnection').textContent==='Ты в игре');assert.equal(await phones[0].page.evaluate(()=>PARTY_PROFILE.id),phones[0].id);}
   await host.locator('#roomToggle').click();await host.locator('#back').click();await host.locator('#confirmStop button[value=yes]').click();await host.waitForFunction(()=>document.querySelector('#play').hidden);console.log('PASS '+id);
 }
 await phones[0].page.route('**/api/profile',route=>route.abort());await phones[0].page.reload();await phones[0].page.waitForFunction(()=>!!window.PARTY_PROFILE.id&&document.querySelector('#onboarding').hidden);assert.equal(await phones[0].page.evaluate(()=>PARTY_PROFILE.id),phones[0].id);
 assert.deepEqual(errors,[]);console.log(JSON.stringify({pass:true,checks,errors}));
}finally{await browser?.close();child.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});


