const test=require('node:test'),assert=require('node:assert/strict');
const {makeGame}=require('../scripts/audit-pocket-runtime.cjs');
const Pocket=require('../games/arcade_deluxe/core/pocket-runtime.cjs');
const {ColumnTerrain}=require('../games/arcade_deluxe/core/terrain.cjs');
const {definitions,terrainMaterial}=require('../games/arcade_deluxe/core/pocket-terrain.cjs');
function flat(){const g=makeGame();g.soil.fromHeights(Array(640).fill(500));g.syncTerrain();for(const p of g.players)g.seat(p);return g;}
function bury(g){const p=g.active();g.stage='flight';g.flightStarted=g.t;Pocket.command(g,{weapon:'mud_pie',owner:p.id,name:'MudPieSmall',type:'DIRTBALL',x:p.x,y:p.y,angle:0,power:0});for(let i=0;i<180;i++){g.step(1/60);assert.equal(p.y,492,'new dirt must not lift the chassis');}return p;}
test('Mud Pie buries without lifting, blocks driving and retains authored brown',()=>{const g=flat(),p=bury(g);assert(p.buried&&p.underground);assert(g.ground(p.x)<440);assert.deepEqual(g.soil.materialsSnapshot()[g.soil.index(p.x)][0],['#472f00','#924700']);const e=g.events.find(e=>e.effectName==='MudPieSmall');assert.deepEqual(e.terrainMaterial,['#472f00','#924700']);assert.equal(e.color,'#924700');g.stage='aim';g.activeId=p.id;const x=p.x,fuel=p.fuel;g.input(p.id,'move',{value:1});for(let i=0;i<10;i++)g.step(1/60);assert.equal(p.x,x);assert.equal(p.fuel,fuel);});
test('a hollow roof does not teleport a tank upward; excavated floor permits falling',()=>{const g=flat(),p=bury(g);g.soil.circle(p.x,p.y-10,36,false,false);g.syncTerrain();g.updateBodies(1/60);assert(p.underground&&!p.buried);assert(p.y>=492);for(let i=0;i<60;i++)g.updateBodies(1/60);assert(p.y>500,'tank falls onto lower cavity floor');});
test('buried tank can still fire to excavate surrounding dirt',()=>{const g=flat(),p=bury(g);g.stage='aim';g.activeId=p.id;p.weapon='big_shot';p.inventory.big_shot=1;const volume=g.soil.volume();assert(g.input(p.id,'fire',{}));for(let i=0;i<120;i++)g.step(1/60);assert(g.soil.volume()<volume);});
test('Pedistal authored jump jets still lift tank onto its new pedestal',()=>{const g=flat(),p=g.active();p.weapon='pedistal';g.fire();let peak=p.y;for(let i=0;i<180;i++){g.step(1/60);peak=Math.min(peak,p.y);}assert(peak<390);assert(p.y<430);assert(!p.buried);assert.equal(p.y,g.ground(p.x)-8);});
test('all additive definitions carry valid original palettes',()=>{let count=0;for(const w of definitions.values())for(const n of w.chain)if(['DIRTBALL','MAGICWALL','DIRTSLINGER'].includes(n.type)){assert(terrainMaterial(n.values),n.name);count++;}assert.equal(count,176);});
test('overlapping color deposits preserve volume and aligned palettes after cuts',()=>{const t=new ColumnTerrain(100,1800,2).fromHeights(Array(50).fill(500)),brown=['#472f00','#924700'],green=['#002200','#00e800'];t.rect(50,450,40,100,true,brown);const volume=t.volume();t.rect(50,450,40,100,true,green);assert.equal(t.volume(),volume);t.circle(50,455,12,false,false);const colors=t.materialsSnapshot();for(let i=0;i<t.columns.length;i++){assert.equal(colors[i].length,t.columns[i].length);for(const r of t.columns[i])if(r.material)assert.deepEqual(r.material,brown);}});
