const test=require('node:test'),assert=require('node:assert/strict');
const {timeline,waveSample}=require('../games/arcade_deluxe/public/explosion-timeline.js');
const Pocket=require('../games/arcade_deluxe/core/pocket-runtime.cjs');
const {makeGame}=require('../scripts/audit-pocket-runtime.cjs');
const {definitions}=require('../games/arcade_deluxe/core/pocket-terrain.cjs');
const Snapshot=require('../games/arcade_deluxe/core/snapshot-view.cjs');
const values=name=>definitions.get('earth_mover').chain.find(n=>n.name===name).values;
function game(){const g=makeGame();g.soil.fromHeights(Array(640).fill(500));g.syncTerrain();g.stage='flight';g.flightStarted=g.t;return g;}
function stepTo(g,t){while(g.t<t-1e-8)g.step(Math.min(1/60,t-g.t));}
test('binary-derived 20ms tick uses ERASE_DELAY as visual lag, not ms per radial pixel',()=>{const w={...timeline(values('EarthMoverExplosion')),started:0};assert.equal(w.drawDuration,2.8);assert.equal(w.eraseDelayTicks,147);assert.equal(w.eraseDelayMs,2940);assert.equal(w.duration,5.76);assert.equal(waveSample(w,1).drawProgress,50);assert.equal(waveSample(w,2.8).outerRadius,140);assert.equal(waveSample(w,2.8).innerRadius,0);assert.equal(waveSample(w,3.94).innerRadius,50);assert(!waveSample(w,5.76).active);});
test('Earth Mover cuts progressively with draw front and keeps both authored waves in late snapshots',()=>{const g=game();Pocket.trigger(g,{weapon:'earth_mover',owner:'a',x:640,y:500,vx:0,vy:1,surfaceImpact:true},'EarthMoverExplosionTrigger');stepTo(g,.5);assert(g.ground(640)>520&&g.ground(640)<526);assert.equal(g.explosionWaves.length,1);stepTo(g,1);assert.equal(g.explosionWaves.length,2);assert(Math.abs(g.explosionWaves[1].started-.75)<1/60+.0001);assert(g.ground(640)>545&&g.ground(640)<551);const ids=g.snapshot().explosionWaves.map(w=>w.id);stepTo(g,2);assert.deepEqual(g.snapshot().explosionWaves.map(w=>w.id),ids);stepTo(g,3);assert(g.ground(640)>639);assert.equal(g.turn,0);assert.equal(g.explosionWaves[1].eraseDelayTicks,72);assert.equal(Snapshot.view(g.snapshot(),{id:'a'}).explosionWaves,undefined);assert.equal(Snapshot.view(g.snapshot(),{host:true}).explosionWaves.length,2);stepTo(g,6);assert.equal(g.explosionWaves.length,0);assert.equal(g.turn,1);});
test('Earth Mover second stage is a visible non-erasing wave',()=>{const g=game(),volume=g.soil.volume();Pocket.command(g,{weapon:'earth_mover',owner:'a',x:640,y:500,type:'EXPLOSION',name:'EarthMoverExplosion2',angle:0,power:0});stepTo(g,3);assert.equal(g.soil.volume(),volume);assert.equal(g.explosionWaves.length,1);assert.equal(g.pending.length,0);});
test('inward draw and independently directed visual eraser produce bounded bands',()=>{for(const drawDirection of ['EXPLOSION_IN','EXPLOSION_OUT'])for(const eraseDirection of ['EXPLOSION_IN','EXPLOSION_OUT']){const w={...timeline({RADIUS:60,ERASE_DELAY:70,DRAW_DIRECTION:drawDirection,ERASE_DIRECTION:eraseDirection}),started:0};for(let t=0;t<3;t+=.01){const s=waveSample(w,t);for(const k of ['drawProgress','eraseProgress','drawRadius','eraseRadius','innerRadius','outerRadius'])assert(s[k]>=0&&s[k]<=60);}}});
test('reset clears persistent waves; DOUBLE_UP does not double duration',()=>{const g=game(),v=values('EarthMoverExplosion');assert.equal(timeline({...v,DOUBLE_UP_FLAG:false}).duration,timeline(v).duration);Pocket.command(g,{weapon:'earth_mover',owner:'a',x:640,y:500,type:'EXPLOSION',name:'EarthMoverExplosion',angle:0,power:0});assert.equal(g.explosionWaves.length,1);g.reset();assert.equal(g.explosionWaves.length,0);});
