'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict'),{spawn}=require('node:child_process');
const {webkit}=require(process.env.PARTY_PLAYWRIGHT||'playwright');
const mode=process.env.QA_POPUP_MODE||'after',out=path.resolve('.localparty-build/popup-stability106',mode);fs.mkdirSync(out,{recursive:true});
const sources=['public/motion.js','public/native-shell/host.js','public/background-scene.css','public/polish.css','public/game-ui-system.js','public/game-ui-system.css','public/app.js','public/native-shell/controller-bridge.js','public/native-shell/tabs.js'];
const hash=()=>Object.fromEntries(sources.map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex')]));
const report={method:'Shipped native host and controller pages in isolated WebKit, actual controller-bridge and tabs document-start order; Swift snapshot transport alone replaced with an explicit fixture. Real controller joins server via UI. No physical-device claim.',start:new Date().toISOString(),sourceStart:hash(),rows:[],errors:[]};
const child=spawn(process.execPath,['server.js'],{env:{...process.env,PARTY_EPHEMERAL:'1',PARTY_EMBEDDED:'1',PARTY_PORT:'0',PARTY_INTERNAL_PORT:'0',PARTY_NO_BROWSER:'1',PARTY_ADMIN_KEY:'popup106qa'}});let log='',browser;child.stdout.on('data',d=>log+=d);child.stderr.on('data',d=>log+=d);
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn){for(let i=0;i<300;i++){if(await fn())return;await wait(30);}throw Error('Timeout '+log.slice(-500));}
async function sample(p,selectors){return p.evaluate(selectors=>({scrollY,bodyPosition:getComputedStyle(document.body).position,rootOverflow:getComputedStyle(document.documentElement).overflowY,items:Object.fromEntries(selectors.map(s=>{const e=document.querySelector(s);if(!e)return[s,null];const r=e.getBoundingClientRect(),c=getComputedStyle(e);return[s,{x:r.x,y:r.y,width:r.width,height:r.height,opacity:c.opacity,visibility:c.visibility,hidden:e.hidden,classes:e.className}];}))}),selectors);}
(async()=>{try{
 await until(()=>/localhost:(\d+)/.test(log));const origin='http://127.0.0.1:'+log.match(/localhost:(\d+)/)[1];const state=await(await fetch(origin+'/api/manage',{headers:{Authorization:'Bearer popup106qa'}})).json();
 browser=await webkit.launch({headless:true});
 for(const width of [320,393,402]){
  const context=await browser.newContext({viewport:{width,height:width===320?568:width===402?874:852},deviceScaleFactor:2,isMobile:true,hasTouch:true});
  await context.addInitScript({content:'window.webkit={messageHandlers:{partyShell:{postMessage(){}}}};'+fs.readFileSync('public/native-shell/controller-bridge.js','utf8')+'\nif(window===window.top){window.__partyPersistentTabs=true;'+fs.readFileSync('public/native-shell/tabs.js','utf8')+'\n}'});
  const p=await context.newPage();p.on('pageerror',e=>report.errors.push(e.message));
  await p.route('**/native-shell/**',r=>r.fulfill({path:path.resolve('public',new URL(r.request().url()).pathname.slice(1))}));
  await p.goto(origin+'/native-shell/index.html');
  await p.evaluate(s=>LocalPartyHost.update({...s,selected:'push',screens:1,players:[{id:'a',name:'Alexandra'},{id:'b',name:'Christopher'}],native:{ready:true,catalogReady:true,buildLabel:'Popup QA Swift transport fixture'}}),state);
  await p.evaluate(()=>document.fonts.ready);await wait(1800);await p.evaluate(()=>scrollTo(0,180));await wait(350);
  const selectors=['#brandHeader','#choiceStrip','.native-catalog-tools','.lp-catalog-card'];
  const before=await sample(p,selectors);await p.screenshot({path:path.join(out,`native-${width}-lobby.png`)});
  const choice=await p.locator('#choiceOpen').boundingBox();await p.touchscreen.tap(choice.x+choice.width/2,choice.y+choice.height/2);await p.locator('#gameDetail').waitFor({state:'visible'});await wait(70);const opening=await sample(p,selectors);await p.screenshot({path:path.join(out,`native-${width}-rules-opening.png`)});
  await wait(750);const open=await sample(p,selectors);await p.screenshot({path:path.join(out,`native-${width}-rules-open.png`)});
  await p.locator('[data-close=gameDetail]').click();await wait(70);const closing=await sample(p,selectors);await p.screenshot({path:path.join(out,`native-${width}-rules-closing.png`)});await p.locator('#gameDetail').waitFor({state:'hidden'});await wait(350);const after=await sample(p,selectors);await p.screenshot({path:path.join(out,`native-${width}-rules-closed.png`)});
  const row={kind:'native-host',width,before,opening,open,closing,after};report.rows.push(row);
  if(mode==='after')for(const [phase,m] of Object.entries({opening,open,closing,after})){assert.equal(m.bodyPosition,before.bodyPosition,'modal never changes body positioning');assert.equal(m.scrollY,before.scrollY,'modal does not reset document scroll');for(const selector of selectors){const a=before.items[selector],b=m.items[selector];if(a&&b){assert(Math.abs(a.y-b.y)<1,`${width} ${phase} ${selector} remains in place`);assert.equal(b.hidden,a.hidden);}}}
  if(width===402){
   await p.evaluate(s=>{scrollTo(0,0);LocalPartyHost.update({...s,selected:'push',screens:1,players:[{id:'a',name:'Alexandra'},{id:'b',name:'Christopher'}],active:{id:'bomb',instance:'swift-transport-fixture',session:{paused:false,readyIds:['a','b']},roster:[],ui:{phase:'playing',label:'Playing'}},native:{ready:true,catalogReady:true,buildLabel:'Popup QA Swift transport fixture'}});},state);await wait(350);await p.locator('#activeMore').click();await wait(300);
   const as=['#activeCard','#choiceStrip','.native-catalog-tools'],ab=await sample(p,as);assert(ab.items['#activeCard'].classes.includes('is-expanded'));
   await p.screenshot({path:path.join(out,'native-402-expanded-deck.png')});const b=await p.locator('.native-run-settings').boundingBox();await p.touchscreen.tap(b.x+b.width/2,b.y+b.height/2);await p.locator('#gameDetail').waitFor();await wait(300);const ao=await sample(p,as);await p.screenshot({path:path.join(out,'native-402-expanded-settings.png')});
   await p.keyboard.press('Escape');await p.locator('#gameDetail').waitFor({state:'hidden'});await wait(300);const aa=await sample(p,as);report.rows.push({kind:'native-expanded-deck',width,before:ab,open:ao,after:aa});
   if(mode==='after')for(const m of [ao,aa]){assert.equal(m.scrollY,ab.scrollY);assert(m.items['#activeCard'].classes.includes('is-expanded'),'opening and Escape preserve expanded active deck');assert.equal(m.items['#activeCard'].height,ab.items['#activeCard'].height);for(const s of as)assert(Math.abs(m.items[s].y-ab.items[s].y)<1,'expanded deck does not reflow under settings');}
   const danger=await p.locator('#activeActions .native-danger').boundingBox();await p.touchscreen.tap(danger.x+danger.width/2,danger.y+danger.height/2);await p.locator('#confirmDialog').waitFor();await wait(300);const ac=await sample(p,as);await p.screenshot({path:path.join(out,'native-402-expanded-confirm.png')});await p.locator('#confirmCancel').click();await p.locator('#confirmDialog').waitFor({state:'hidden'});await wait(250);const ace=await sample(p,as);report.rows.push({kind:'native-confirm',width,before:ab,open:ac,after:ace});if(mode==='after'){assert.equal(ace.scrollY,ab.scrollY,'confirm close keeps document position');assert(ace.items['#activeCard'].classes.includes('is-expanded'),'confirm cancel preserves active deck');assert(ac.items['#activeCard'].classes.includes('is-expanded'));assert.equal(ac.items['#activeCard'].height,ab.items['#activeCard'].height);}
   await p.emulateMedia({reducedMotion:'reduce'});const rs=await p.locator('.native-run-settings').boundingBox();await p.touchscreen.tap(rs.x+rs.width/2,rs.y+rs.height/2);await p.locator('#gameDetail').waitFor();assert.equal(await p.locator('#gameDetail').evaluate(e=>getComputedStyle(e).animationName),'none');await p.keyboard.press('Escape');await p.locator('#gameDetail').waitFor({state:'hidden'});await p.emulateMedia({reducedMotion:'no-preference'});
  }
  // Controller route uses the same shared modal lock but the real server/profile.
  await p.goto(origin+'/play');await p.locator('#name').fill('Popup '+width);await p.locator('#joinForm button[type=submit]').click();await p.locator('#home').waitFor();await wait(1800);await p.locator('.guest-game[data-id=push] .guest-info').scrollIntoViewIfNeeded();await wait(400);
  const cs=['#brandHeader','#catalogFilters','.guest-game[data-id=push]'],cb=await sample(p,cs);await p.locator('.guest-game[data-id=push] .guest-info').click();await wait(800);const co=await sample(p,cs);await p.screenshot({path:path.join(out,`controller-${width}-rules-open.png`)});const docScroll=await p.evaluate(()=>scrollY);const ruleEnd=await p.locator('#rulesBody').evaluate(n=>{n.scrollTo({top:n.scrollHeight,behavior:'instant'});return{scroll:n.scrollHeight,client:n.clientHeight,top:n.scrollTop};});await wait(100);assert.equal(await p.evaluate(()=>scrollY),docScroll,'reading Rules never scrolls background');assert(ruleEnd.scroll<=ruleEnd.client+1||ruleEnd.top>0,'long Rules remain scrollable within sheet');if(mode==='after'){const end=await p.evaluate(()=>{const text=document.querySelector('#rulesBody').lastElementChild.getBoundingClientRect(),button=document.querySelector('#closeRules').getBoundingClientRect();return{textBottom:text.bottom,actionTop:button.top};});assert(end.textBottom<=end.actionTop-8,'last rule fully visible above Got it');}await p.screenshot({path:path.join(out,`controller-${width}-rules-end.png`)});await p.locator('#closeRules').click();await p.locator('#rulesDialog').waitFor({state:'hidden'});await wait(350);const ca=await sample(p,cs);await p.screenshot({path:path.join(out,`controller-${width}-rules-closed.png`)});report.rows.push({kind:'native-controller',width,before:cb,open:co,after:ca});
  if(mode==='after')for(const m of [co,ca]){assert.equal(m.bodyPosition,cb.bodyPosition);assert.equal(m.scrollY,cb.scrollY);for(const s of cs)assert(Math.abs(m.items[s].y-cb.items[s].y)<1,`controller ${width} ${s} stable`);}
  await context.close();
 }
 assert.deepEqual(report.errors,[]);console.log('PASS '+mode+' native host/controller popup stability widths 320/393/402');
}finally{report.finish=new Date().toISOString();report.sourceEnd=hash();fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));await browser?.close();child.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
