'use strict';
const assert=require('assert/strict'),path=require('path'),{spawn}=require('child_process');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/nirrt/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const child=spawn(process.execPath,['server.js'],{cwd:path.join(__dirname,'../games/quiz'),env:{...process.env,PORT:'0',PARTY_MANAGED:'0'},windowsHide:true,stdio:['ignore','pipe','pipe']});let browser;try{
const port=await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('Startup timeout')),10000);child.stdout.on('data',d=>{const m=String(d).match(/localhost:(\d+)/);if(m){clearTimeout(timeout);resolve(Number(m[1]));}});child.on('error',reject);});const base='http://localhost:'+port;
browser=await chromium.launch({channel:'msedge',headless:true});const errors=[];
const host=await browser.newPage({viewport:{width:1440,height:1000}});host.on('pageerror',e=>errors.push(e.message));await host.goto(base+'/host?topic=warsaw');const phones=[];
for(const name of ['Аня','Боря','Вера']){const ctx=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/');await p.locator('#name').fill(name);await p.locator('#joinButton').click();phones.push(p);}
await host.waitForFunction(()=>document.querySelectorAll('#board .row').length===3);await host.locator('#mode').selectOption('teams');await phones[0].locator('#team').selectOption('0');await phones[1].locator('#team').selectOption('0');await phones[2].locator('#team').selectOption('1');await host.locator('#start').click();await phones[0].locator('#answers button:not([disabled])').first().waitFor();await phones[0].locator('#answers button').first().tap();await phones[0].waitForFunction(()=>document.getElementById('status').textContent.includes('Ответ принят'));await phones[0].reload();await phones[0].waitForFunction(()=>document.getElementById('status').textContent.includes('Ответ принят'));assert.equal(await phones[0].locator('#answers button:not([disabled])').count(),0);
const geometry=await phones[0].evaluate(()=>({width:innerWidth,body:document.documentElement.scrollWidth,buttons:[...document.querySelectorAll('#answers button')].map(b=>b.getBoundingClientRect().height),select:getComputedStyle(document.querySelector('#answers button')).userSelect}));assert(geometry.body<=geometry.width);assert(geometry.buttons.every(h=>h>=60));assert.equal(geometry.select,'none');await host.screenshot({path:path.join(__dirname,'quiz-host.png'),fullPage:true});await phones[0].screenshot({path:path.join(__dirname,'quiz-phone.png'),fullPage:true});await host.locator('#reveal').click();await host.locator('#explanation').waitFor({state:'visible'});await host.locator('#next').click();await phones[0].locator('#answers button:not([disabled])').first().waitFor();assert.deepEqual(errors,[]);console.log(JSON.stringify({pass:true,geometry,errors}));
}finally{await browser?.close();child.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
