'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {Quiz}=require('../games/quiz/engine');
const banks={warsaw:require('../games/quiz/data/warsaw.json'),sinyak:require('../games/millionaire/data/questions.json')};
function game(mode='solo',report=()=>{}){const g=new Quiz(banks,report);g.join('a','Аня');g.join('b','Боря');g.configure({mode,count:10});return g;}
const right=g=>g.deck[g.round].answers.indexOf(g.deck[g.round].correct);
test('Warsaw150 complete unique sourced questions; existing150 Sinyak unchanged',()=>{for(const b of Object.values(banks)){assert.equal(b.length,150);assert.equal(new Set(b.map(q=>q.id)).size,150);for(const q of b){assert.equal(q.answers.length,4);assert.equal(new Set(q.answers).size,4);assert(q.answers.includes(q.correct));assert(q.explanation);}}assert.equal(new Set(banks.warsaw.map(q=>q.question)).size,150);for(const q of banks.warsaw){assert.match(q.sourceUrl,/^https:\/\/go2warsaw.pl\/en\/.+\/$/);assert(q.sourceTitle);}});
test('solo idempotence, no answer leaks, stale/late invalid answer rejected',()=>{const g=game();assert(g.start());assert.equal(g.view('a').question.correct,undefined);assert.equal(g.submit('a',0,right(g)),true);assert.equal(g.submit('a',0,0),false);assert.equal(g.submit('b',99,0),false);assert.equal(g.submit('b',0,4),false);assert.equal(g.submit('b',0,0,g.endsAt),false);g.reveal();assert.equal(g.players.get('a').correct,1);assert.equal(g.reveal(),false);assert(g.view('a').question.explanation);});
test('teams score once and captain hands off after disconnect',()=>{const g=game('teams');g.join('c','Вера');g.team('a',0);g.team('b',0);g.team('c',1);g.start();assert.equal(g.submit('b',0,right(g)),false);g.players.get('a').online=false;assert.equal(g.captain(g.players.get('b')),'b');assert.equal(g.submit('b',0,right(g)),true);g.join('a','Аня');assert.equal(g.submit('a',0,right(g)),false);g.reveal();assert.equal(g.players.get('a').correct,1);assert.equal(g.players.get('b').correct,1);assert.equal(g.score(g.players.get('a')),g.score(g.players.get('b')));assert(g.teamScores[0]>=1000&&g.teamScores[0]<=1300);});
test('reconnection retains team and answer; late join eligible next question',()=>{const g=game('teams');g.team('a',2);g.start();g.submit('a',0,right(g));g.players.get('a').online=false;const p=g.join('a','Аня');assert.equal(p.team,2);assert.notEqual(g.view('a').me.answer,null);g.join('late','Опоздал');assert.equal(g.view('late').me.eligible,false);assert.equal(g.submit('late',0,0),false);g.reveal();g.next();assert.equal(g.view('late').me.eligible,true);assert.equal(g.view('a').me.answer,null);});
test('match reports once, includes correct/answers/streak; no duplicate Sinyak group',()=>{const reports=[],g=game('solo',r=>reports.push(r));g.configure({topic:'sinyak',count:30});g.start();assert.equal(new Set(g.deck.map(q=>q.group)).size,g.deck.length);for(let i=0;i<g.deck.length;i++){g.submit('a',g.round,right(g));g.reveal();g.next();}assert.equal(g.phase,'finished');assert.equal(reports.length,1);assert.equal(reports[0].players[0].metrics.correct,30);assert.equal(reports[0].players[0].won,true);g.reveal();assert.equal(reports.length,1);});
test('settings are bounded and frozen during play; at least2 needed',()=>{const g=new Quiz(banks);g.join('a','A');assert.equal(g.start(),false);g.configure({seconds:1,count:500,mode:'bad'});assert.equal(g.settings.seconds,10);g.join('b','B');g.start();g.configure({seconds:90});assert.equal(g.settings.seconds,10);assert.equal(g.team('a',2),false);});
