'use strict';
const assert=require('node:assert/strict'),{spawn}=require('node:child_process'),WebSocket=require('ws');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{for(const embedded of [true,false]){let logs='';const sockets=[];const child=spawn(process.execPath,['server.js'],{env:{...process.env,PARTY_EMBEDDED:embedded?'1':'0',PARTY_EPHEMERAL:'1',PARTY_PORT:'0',PARTY_INTERNAL_PORT:'0',PARTY_NO_BROWSER:'1',PARTY_ADMIN_KEY:'rematch-test',TEST_FAST:'1'}});child.stdout.on('data',d=>logs+=d);child.stderr.on('data',d=>logs+=d);
try{
async function until(fn){for(let i=0;i<800;i++){if(await fn())return;await sleep(25);}throw Error('timeout '+logs.slice(-2000));}
await until(()=>/localhost:(\d+)/.test(logs));const origin='http://127.0.0.1:'+logs.match(/localhost:(\d+)/)[1];
const api=async(body,status=200)=>{const r=await fetch(origin+'/api/manage',{method:body?'POST':'GET',headers:{Authorization:'Bearer rematch-test','Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const value=await r.json();assert.equal(r.status,status,JSON.stringify(value));return value;};
async function connect(url='/lobby'){const ws=new WebSocket(origin.replace('http','ws')+url);sockets.push(ws);ws.messages=[];ws.on('message',b=>{const m=JSON.parse(b);ws.messages.push(m);if(m.type==='joined')ws.profile=m;if(m.type==='state')ws.state=m;});await new Promise((r,j)=>{ws.once('open',r);ws.once('error',j);});return ws;}
const send=(w,m)=>w.send(JSON.stringify(m));const a=await connect(),b=await connect(),stranger=await connect();send(a,{type:'join',name:'A'});send(b,{type:'join',name:'B'});await until(()=>a.profile&&b.profile);let snap=await api({type:'launch',id:'taprace',externalDisplay:true});const original=snap.active.instance;
await api({type:'rematch',instance:original},400);send(stranger,{type:'rematch',instance:original});await until(()=>stranger.messages.some(m=>m.type==='error'));
async function attach(instance,initial=false){const gameHost=await connect('/games/taprace/ws');send(gameHost,{type:'host'});for(const p of [a,b]){const c=await connect('/games/taprace/ws');send(c,{type:'join',data:{partyId:p.profile.id,partyToken:p.profile.token}});await until(()=>c.profile);send(p,{type:'game-status',instance,status:'ready'});if(initial)send(p,{type:'ready-set',instance,ready:true});}if(!embedded)send(gameHost,{type:'start'});await until(async()=>(await api()).active?.ui?.phase==='results');}
await attach(original,true);const before=await api(),startIndex=a.messages.length;send(a,{type:'rematch',instance:original});send(b,{type:'rematch',instance:original});await until(async()=>{snap=await api();return snap.active?.instance!==original&&!snap.busy;});assert.equal(snap.active.id,'taprace');assert.equal(snap.metrics.gameStarts,before.metrics.gameStarts+1);assert.deepEqual(snap.players.map(p=>p.id),before.players.map(p=>p.id));assert(a.messages.slice(startIndex).filter(m=>m.type==='state').every(m=>m.active),'rematch must never expose lobby');const second=snap.active.instance;
await api({type:'rematch',instance:original});assert.equal((await api()).active.instance,second,'late duplicate cannot restart successor');await api({type:'rematch',instance:second},400);await api({type:'rematch',instance:'stale'},400);await attach(second);const secondFinal=await api();assert.equal(secondFinal.active.session.readyIds.length,2);assert.equal(secondFinal.totalMatches,before.totalMatches+1,'fresh result exactly once');
const [x,y]=await Promise.all([api({type:'rematch',instance:second}),api({type:'rematch',instance:second})]);assert.equal(x.active.instance,y.active.instance);assert.equal(x.metrics.gameStarts,before.metrics.gameStarts+2);assert.equal(x.active.id,'taprace');console.log('PASS rematch '+(embedded?'embedded':'desktop')+': participants, host, concurrent taps, stale, before-finish denial, same settings/roster, no lobby, auto-ready, fresh results');
}finally{for(const s of sockets)s.terminate();child.kill();}}
})().catch(e=>{console.error(e);process.exitCode=1;});
