'use strict';
const {spawn}=require('child_process'),assert=require('assert/strict'),WebSocket=require('ws');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{const child=spawn(process.execPath,['server.js'],{env:{...process.env,PARTY_PORT:'0',PARTY_NO_BROWSER:'1',PARTY_EPHEMERAL:'1'},stdio:['ignore','pipe','pipe']});let logs='';child.stdout.on('data',d=>logs+=d);child.stderr.on('data',d=>logs+=d);const sockets=[];try{
 async function until(fn){for(let i=0;i<300;i++){if(fn())return;await delay(30);}throw Error('timeout '+logs.slice(-1000));}
 await until(()=>/localhost:(\d+)/.test(logs));const port=logs.match(/localhost:(\d+)/)[1],html=await(await fetch('http://localhost:'+port+'/host')).text(),key=JSON.parse(html.match(/window.PARTY_HOST_KEY=(.*?);/)[1]);
 async function connect(){const w=new WebSocket('ws://localhost:'+port+'/lobby');sockets.push(w);w.messages=[];w.on('message',d=>{const m=JSON.parse(d);w.messages.push(m);if(m.type==='state')w.state=m;if(m.type==='joined')w.profile=m;});await new Promise(r=>w.once('open',r));return w;}const send=(w,m)=>w.send(JSON.stringify({...m,instance:host.state?.active?.instance}));
 const host=await connect();send(host,{type:'host',key});const a=await connect(),b=await connect();send(a,{type:'join',name:'А'});send(b,{type:'join',name:'Б'});await until(()=>a.profile&&b.profile);send(host,{type:'launch',id:'warsaw'});await until(()=>host.state?.active?.id==='warsaw');send(a,{type:'game-status',status:'ready'});send(a,{type:'ready-set',ready:true});await delay(80);assert.equal(host.messages.some(m=>m.type==='session-start'),false,'must wait for second loaded controller');send(b,{type:'game-status',status:'ready'});await until(()=>host.state.active.ready.length===2);send(a,{type:'ready-set',ready:true});await delay(80);assert.equal(host.messages.some(m=>m.type==='session-start'),false);send(b,{type:'ready-set',ready:true});await until(()=>host.messages.some(m=>m.type==='session-start'));send(b,{type:'ready-set',ready:true});await delay(80);assert.equal(host.messages.filter(m=>m.type==='session-start').length,1);
 send(a,{type:'pause-set',paused:true});await until(()=>host.state.active.session.paused);await delay(100);send(b,{type:'pause-set',paused:false});await until(()=>!host.state.active.session.paused);assert.ok(host.state.active.session.clockOffset>=100);
 send(a,{type:'exit-vote',vote:true});await delay(80);assert.ok(host.state.active);b.close();await until(()=>!host.state.active);
 const br=await connect();send(br,{type:'join',token:b.profile.token,name:'Б'});await until(()=>br.profile);assert.equal(br.profile.id,b.profile.id);
 send(host,{type:'test-mode',enabled:true});await until(()=>host.messages.some(m=>m.type==='test-profiles'&&m.profiles?.length));assert.equal(host.state.testMode,true);console.log('PASS root WS: readiness once, pause any player, offset, unanimous online exit after disconnect, identity reconnect, host-only test profile.');
 }finally{for(const w of sockets)w.close();child.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
