'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {Match}=require('../games/sports_siege/match');
const {SIEGE_TURRET_Z,targetAt}=require('../games/sports_siege/rules');
function game(){const m=new Match('swarm_gate');m.add({id:'a',name:'A'});m.start();m.stage='wave';m.waveLeft=0;m.players.get('a').aim={x:.5,y:.5};return m;}
function bug(id,kind,hp=24,x=0,z=-14){return{id,kind,hp,maxHp:hp,x,z,r:.5,speed:0,slowUntil:0};}
for(const[kind,score]of[['termite',10],['runner',10],['tank',25],['boss',100]])test(`shot ${kind}: awarded score and death center survive removal`,()=>{const m=game(),p=m.players.get('a');m.enemies=[bug(1,kind)];m.siegeFire(p);const event=m.events.findLast(e=>e.kind==='shot');assert.equal(p.score,score);assert.equal(event.awardedScore,score);assert.deepEqual(event.deathPosition,{x:0,z:-14.14});assert.equal(event.ox,0);assert.equal(event.oz,SIEGE_TURRET_Z);assert.notEqual(event.z,event.deathPosition.z,'ray surface is not the enemy center');m.siegeStep(0);assert.equal(m.enemies.length,0);assert.deepEqual(event.deathPosition,{x:0,z:-14.14});m.siegeFire(p);assert.equal(p.score,score);assert.equal(m.events.findLast(e=>e.kind==='shot').awardedScore,0);});
test('nonlethal hit and miss never advertise kill points',()=>{const m=game(),p=m.players.get('a');m.enemies=[bug(1,'tank',112)];m.siegeFire(p);let e=m.events.findLast(e=>e.kind==='shot');assert.equal(e.hit,true);assert.equal(e.dead,false);assert.equal(e.awardedScore,0);assert.equal(e.deathPosition,null);p.aim.x=1;m.siegeFire(p);e=m.events.findLast(e=>e.kind==='shot');assert.equal(e.hit,false);assert.equal(e.awardedScore,0);assert.equal(e.deathPosition,null);});
test('pulse exposes actual unchanged flat score for every killed kind and ignores survivors',()=>{const m=game(),p=m.players.get('a');m.enemies=[bug(1,'termite',40,-1),bug(2,'tank',80,0),bug(3,'boss',80,1),bug(4,'boss',360,2)];assert.equal(m.input('a','ability'),true);const e=m.events.findLast(e=>e.kind==='pulse');assert.equal(p.score,30);assert.equal(p.kills,3);assert.equal(e.awardedScore,30);assert.deepEqual(e.kills.map(k=>[k.targetId,k.awardedScore,k.deathPosition]),[[1,10,{x:-1,z:-14}],[2,10,{x:0,z:-14}],[3,10,{x:1,z:-14}]]);assert.equal(m.enemies.length,1);assert.equal(m.enemies[0].hp,275);const shots=m.events.filter(e=>e.kind==='shot');assert.equal(shots.length,3);assert(shots.every(e=>e.source==='pulse'&&e.awardedScore===10));assert.equal(m.input('a','ability'),false);assert.equal(p.score,30);});
test('ray event is collinear with authoritative turret and aim; nearest enemy takes damage',()=>{const m=game(),p=m.players.get('a');p.aim={x:1,y:.5};const ox=m.turretX(p),oz=SIEGE_TURRET_Z,ax=18,az=-14,dx=ax-ox,dz=az-oz;m.enemies=[bug(1,'tank',112,ox+dx*.75,oz+dz*.75),bug(2,'tank',112,ox+dx*.4,oz+dz*.4)];m.siegeFire(p);const e=m.events.findLast(e=>e.kind==='shot');assert.equal(e.targetId,2);assert(Math.abs((e.x-ox)*dz-(e.z-oz)*dx)<1e-9);assert.equal(m.enemies[0].hp,112);assert.equal(m.enemies[1].hp,88);});

test('peek shot retains actual moving target identity, style and death center after removal',()=>{const m=new Match('peek_shoot');const p=m.add({id:'a',name:'A'});m.start();m.t=1;const target={id:17,kind:'gold',style:3,baseX:.5,coverY:.6,r:.041,born:0,life:3,speed:2,seed:.8,depth:1,hp:1};m.targets=[target];m.covers=[];const at=targetAt(target,m.t);p.aim={x:at.x,y:at.y};m.galleryFire(p);const e=m.events.findLast(e=>e.kind==='shot');assert.equal(e.targetId,17);assert.equal(e.targetStyle,3);assert.equal(e.awardedScore,30);assert.deepEqual(e.deathPosition,{x:at.x,y:at.y});assert.equal(e.targetSnapshot.rise,at.rise);m.spawnAt=100;m.galleryStep();assert.equal(m.targets.length,0);assert.equal(e.targetSnapshot.id,17);assert.equal(e.targetSnapshot.hp,1);});
test('swarm snapshot advertises the same depth used by authoritative rays',()=>{const m=game();assert.equal(m.snapshot().players[0].turretZ,SIEGE_TURRET_Z);});
