'use strict';
const {spawn}=require('node:child_process'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {webkit}=require(process.env.PARTY_PLAYWRIGHT||'playwright');
const root=path.resolve('.localparty-build/tv-audit-fixes'),output=root;fs.mkdirSync(output,{recursive:true});
const clockRate=1;
const child=spawn(process.execPath,['--require',path.resolve('scripts/capture-qa-clock.cjs'),'server.js'],{env:{...process.env,NODE_OPTIONS:[process.env.NODE_OPTIONS||'','--require='+path.resolve('scripts/capture-qa-clock.cjs')].join(' '),PARTY_EMBEDDED:'1',PARTY_INTERNAL_PORT:'0',PARTY_EPHEMERAL:'1',PARTY_PORT:'0',PARTY_NO_BROWSER:'1',PARTY_ADMIN_KEY:'screen-review',QA_CLOCK_RATE:String(clockRate)}});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));let log='',browser;
const report={capturedAt:new Date().toISOString(),method:'Real games, host actions, minimum supported settings; QA server clock '+clockRate+'x. Does not validate real-time physics or timing.',games:[],errors:[]};
let extras=[];try{extras=JSON.parse(fs.readFileSync(path.join(root,'manifest-extra.json')));}catch{}
child.stdout.on('data',d=>log+=d);child.stderr.on('data',d=>log+=d);
const save=()=>{fs.writeFileSync(path.join(output,process.env.QA_REPORT_NAME||'complete-report.json'),JSON.stringify(report,null,2));fs.writeFileSync(path.join(root,'manifest-extra.json'),JSON.stringify(extras,null,2));};
for(const signal of ['SIGINT','SIGTERM'])process.on(signal,()=>{save();child.kill();browser?.close().finally(()=>process.exit(130));});
const deadline=setTimeout(()=>{console.error('Global review timeout');save();child.kill();process.exit(2);},45*60*1000);deadline.unref();
(async()=>{try{
 for(let i=0;i<300&&!/localhost:(\d+)/.test(log);i++)await sleep(50);assert.match(log,/localhost:(\d+)/);const origin='http://127.0.0.1:'+log.match(/localhost:(\d+)/)[1];
 const api=async body=>{const r=await fetch(origin+'/api/manage',{signal:AbortSignal.timeout(15000),method:body?'POST':'GET',headers:{Authorization:'Bearer screen-review','Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const state=await r.json();if(!r.ok)throw Error(JSON.stringify(state));return state;};
 browser=await webkit.launch({headless:true});const tv=await browser.newPage({viewport:{width:1280,height:720}}),phone=await browser.newPage({viewport:{width:393,height:852},isMobile:true,hasTouch:true});
 for(const [surface,p]of[['tv',tv],['phone',phone]])p.on('pageerror',e=>report.errors.push({surface,error:e.message}));
 await tv.goto(origin+'/tv');await phone.goto(origin+'/play');await phone.locator('#name').fill('Александра ДлинноеИмя');await phone.locator('#joinForm button[type=submit]').click();await phone.locator('#home').waitFor();

 for(const id of ['chaos','tanks','sinyakquiz','warsaw','crocodile','drawguess','millionaire']){
  await api({type:'bots-set',count:3});await sleep(500);await api({type:'launch',id});
  await phone.waitForFunction(id=>document.querySelector('#gameFrame').src.includes('/games/'+id+'/'),id);
  await phone.waitForFunction(()=>!document.getElementById('readyButton').disabled,null,{timeout:30000});await phone.locator('#readyButton').click();await sleep(1600);
  const snap=await api();if(snap.active?.ui?.phase==='waiting')await api({type:'force-start',instance:snap.active.instance});await sleep(900);
  for(const width of []){await phone.setViewportSize({width,height:width===320?568:width===375?667:852});await sleep(350);await phone.screenshot({path:path.join(output,id+'-'+width+'.png')});const f=phone.frames().find(f=>f.url().includes('/games/'+id+'/'));console.log('TYPE',id,width,await f.evaluate(()=>[...document.querySelectorAll('h1,h2,h3,#status,.turn,.hp-stat-label,.hp-number,#ss-throw-hint,#ss-power,.ss-controller-status b,.ss-controller-status span,.ss-throw-settings label,.ss-controller-foot>span,#jengaForce,#motion,#action,#notice')].filter(n=>n.getBoundingClientRect().height>0).map(n=>{let c=getComputedStyle(n);return{text:n.textContent.trim().slice(0,100),tag:n.tagName,id:n.id,size:c.fontSize,font:c.fontFamily,style:c.fontStyle,transform:c.textTransform}})));}
  for(const width of [1280,1920]){await tv.setViewportSize({width,height:width===1280?720:1080});await sleep(500);await tv.screenshot({path:path.join(output,id+'-tv-'+width+'.png')});const f=tv.frames().find(f=>f.url().includes('/games/'+id+'/'));const check=await f.evaluate(()=>{let n=document.querySelector('.hudTitle'),c=document.querySelector('canvas#game'),rules=document.querySelector('main>details'),name=document.querySelector('.person strong,.scoreTop b'),score=document.querySelector('.points,.money');return{inset:parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--party-stage-inset-top'))||0,title:n?.getBoundingClientRect().toJSON(),canvas:c?.getBoundingClientRect().toJSON(),height:innerHeight,rulesVisible:!!rules&&rules.getBoundingClientRect().height>0,name:name?{font:getComputedStyle(name).fontFamily,style:getComputedStyle(name).fontStyle}:null,score:score?{font:getComputedStyle(score).fontFamily,style:getComputedStyle(score).fontStyle}:null}});if(id==='drawguess'){const drawing=await f.evaluate(()=>{const c=document.querySelector('#canvas').getBoundingClientRect(),s=document.querySelector('.stage').getBoundingClientRect();return{canvas:c.toJSON(),stage:s.toJSON(),innerHeight}});console.log('DRAWING',drawing);assert.ok(drawing.canvas.bottom<=drawing.stage.bottom);assert.ok(drawing.canvas.height>=100);assert.ok(drawing.stage.bottom<=drawing.innerHeight);}console.log('FIT',id,width,check);if(id==='chaos'){
    const bounds=await f.evaluate(()=>{const r=document.querySelector('#arena').getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height,width:innerWidth,height:innerHeight};});
    assert.ok(Math.abs(bounds.w/bounds.h-5/3)<.01,'Chaos keeps a uniform complete field');
    assert.ok(bounds.x>=-1&&bounds.y>=-1&&bounds.x+bounds.w<=bounds.width+1&&bounds.y+bounds.h<=bounds.height+1,'Chaos physical bounds are visible');
    assert.ok(bounds.w>=bounds.width*.82&&bounds.h>=bounds.height*.9,'Chaos uses available stage area');
    const actual=(await api()).active.ui.label;
    const caption=await tv.evaluate(label=>({text:document.getElementById('phase').textContent,expected:window.PartyI18n?.t?.(label)||label}),actual);
    assert.equal(caption.text,caption.expected,'Shared caption is the actual current task');
    assert.ok(caption.text.trim()&&!/^(Game|Игра)$/i.test(caption.text.trim()),'Task cannot be generic Game');
  }if(id==='tanks'){assert.ok(check.canvas.top>=-1&&check.canvas.bottom<=check.height+1,'canvas fits the actual field viewport');const receiver=await tv.evaluate(()=>{const frame=document.getElementById('gameFrame').getBoundingClientRect(),notch=document.querySelector('.tv-info-center').getBoundingClientRect(),scale=parseFloat(document.getElementById('tvStage').style.zoom)||1;return{frame:frame.toJSON(),notch:notch.toJSON(),scale,height:innerHeight};});assert.ok(receiver.frame.top>=12*receiver.scale-1&&receiver.frame.top<=12*receiver.scale+1,'scene keeps a small gutter without shrinking below the full notch');assert.ok(receiver.frame.bottom<=receiver.height-12*receiver.scale+1,'field keeps a bottom breathing gap');}if(['sinyakquiz','warsaw','crocodile','drawguess','millionaire'].includes(id)){assert.equal(check.rulesVisible,false);assert.ok(check.name.font.includes('KardiaFit'));assert.equal(check.name.style,'normal');{/* Draw guess uses quieter supporting score numerals; place/title retain the display role. */const supporting=id==='drawguess';assert.ok(check.score.font.includes(supporting?'KardiaFit':'KardiaFatRunner'));assert.equal(check.score.style,supporting?'normal':'italic');}}console.log(id,'TV',width,await f.evaluate(()=>({canvas:document.querySelector('canvas')?.getBoundingClientRect().toJSON(),inset:getComputedStyle(document.documentElement).getPropertyValue('--party-stage-inset-top'),seats:[...document.querySelectorAll('.seat')].map(n=>n.getBoundingClientRect().toJSON()),labels:[...document.querySelectorAll('.hockey-last-hitter')].map(n=>({visible:!n.hidden,name:n.textContent}))})));}
  await api({type:'stop'});await sleep(500);
 }
 console.log('ERRORS',report.errors);assert.deepEqual(report.errors,[]);
 }finally{clearTimeout(deadline);await browser?.close();child.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
