const {spawn}=require('child_process'),fs=require('fs'),{chromium}=require('C:/Users/nirrt/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{let browser;const child=spawn(process.execPath,['server.js'],{env:{...process.env,PARTY_PORT:'0',PARTY_EPHEMERAL:'1',PARTY_NO_BROWSER:'1'},windowsHide:true});child.stderr.on('data',d=>process.stderr.write(d));try{const port=await new Promise((r,j)=>{child.stdout.on('data',d=>{const m=String(d).match(/localhost:(\d+)/);if(m)r(m[1]);});setTimeout(()=>j(Error('startup')),15000).unref();});browser=await chromium.launch({channel:'msedge',headless:true});const base='http://localhost:'+port,host=await browser.newPage({viewport:{width:1920,height:1080}});await host.goto(base+'/host');for(let i=0;i<2;i++){const p=await browser.newPage();await p.goto(base);await p.locator('#name').fill('Audit'+i);await p.locator('#joinForm button').click();await p.waitForTimeout(200);}await host.evaluate(()=>new Promise(r=>{window.qaSocket=new WebSocket('ws://'+location.host+'/lobby');qaSocket.onopen=()=>{qaSocket.send(JSON.stringify({type:'host',key:PARTY_HOST_KEY}));r();};}));await host.evaluate(()=>qaSocket.send(JSON.stringify({type:'launch',id:'push'})));await host.waitForFunction(()=>document.querySelector('#gameFrame').src.includes('/games/push/'));await host.waitForTimeout(1400);await host.screenshot({path:'tests/ux-01-push-waiting.png'});const frame=host.frames().find(f=>f.url().includes('/games/push/'));const metrics=await frame.evaluate(()=>{const box=s=>{const r=document.querySelector(s).getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height};};return{lobby:box('#lobbyOverlay'),panel:box('.left-panel'),topbar:getComputedStyle(document.querySelector('.topbar')).display};});fs.writeFileSync('tests/ux-layout-metrics.json',JSON.stringify(metrics,null,2));if(metrics.panel.h>650||metrics.topbar!=='none')throw Error('Unbounded lobby');
// Render the real result component with a representative completed score payload.
await frame.evaluate(()=>{updateUI=()=>{};document.querySelector('#lobbyOverlay').classList.add('hidden');document.querySelector('#resultOverlay').classList.remove('hidden');document.querySelector('#resultText').textContent='Глеб победил!';document.querySelector('#resultStats').innerHTML='<div class="stat-row"><b>1</b><span class="name">Глеб</span><span class="metric">6 побед</span><span class="score">6</span></div><div class="stat-row"><b>2</b><span class="name">Саша</span><span class="metric">1 победа</span><span class="score">1</span></div>';});await host.waitForTimeout(400);await host.screenshot({path:'tests/ux-02-result-layout.png'});console.log(metrics);const waiting=[];for(const game of require('../catalog.json')){await host.evaluate(id=>qaSocket.send(JSON.stringify({type:'launch',id})),game.id);await host.waitForFunction(id=>document.querySelector('#gameFrame').src.includes('/games/'+id+'/'),game.id);await host.waitForTimeout(450);const f=host.frames().find(x=>x.url().includes('/games/'+game.id+'/'));waiting.push({id:game.id,...await f.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,bodyHeight:document.body.scrollHeight,height:innerHeight}))});await host.screenshot({path:'tests/ux-wait-'+game.id+'.png'});}fs.writeFileSync('tests/ux-waiting-matrix.json',JSON.stringify(waiting,null,2));console.log(waiting);
}finally{await browser?.close();child.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});




