'use strict';
// Original weapons. Variants deliberately share a behavior; the family is visible in UI.
// damage = maximum score yield of an explosion, radius = world units, not real-world units.
const definitions=[
 ['pebble',"Камешек",'shell',24,32,"Один точный снаряд."],
 ['thumper',"Гром",'shell',40,49,"Крупный кратер и более широкая зона поражения."],
 ['moon',"Мини-луна",'shell',65,76,"Тяжёлый медленный снаряд с большим взрывом.",{speed:.85}],
 ['spark',"Искра",'shell',20,26,"Быстрый точный снаряд.",{speed:1.25}],
 ['triple',"Трио",'spread',20,29,"Три снаряда веером.",{count:3,spread:.075}],
 ['fan',"Веер",'spread',16,25,"Пять снарядов веером.",{count:5,spread:.085}],
 ['confetti',"Конфетти",'spread',12,22,"Семь маленьких снарядов.",{count:7,spread:.065}],
 ['twins',"Близнецы",'spread',28,38,"Два тяжёлых снаряда.",{count:2,spread:.035}],
 ['seedpod',"Стручок",'cluster',18,29,"Разделяется на шесть частей в верхней точке.",{count:6}],
 ['piñata',"Пиньята",'cluster',11,24,"Двенадцать маленьких подарков.",{count:12}],
 ['rain',"Звёздный дождь",'rain',20,31,"Пять ударов сверху возле точки попадания.",{count:5}],
 ['meteor',"Метеорный рой",'rain',24,38,"Восемь метеоров на большой площади.",{count:8,width:220}],
 ['skip',"Лягушка",'bounce',32,42,"Один рикошет от земли.",{bounces:1}],
 ['superball',"Супермяч",'bounce',28,39,"Три рикошета перед взрывом.",{bounces:3}],
 ['rubber',"Резина",'bounce',20,34,"Пять небольших прыжков.",{bounces:5}],
 ['roller',"Колобок",'roller',42,49,"После посадки катится к ближайшему танку."],
 ['saw',"Пила",'saw',12,26,"Едет по земле и оставляет цепочку взрывов."],
 ['mole',"Крот",'burrow',40,47,"Проходит под поверхностью и взрывается глубже.",{depth:55}],
 ['deep',"Глубина",'burrow',58,64,"Глубокий взрыв под танком.",{depth:100}],
 ['drill',"Бур",'drill',18,31,"Четыре взрыва один под другим.",{count:4}],
 ['ember',"Уголёк",'fire',9,35,"Оставляет горящую зону на три секунды.",{duration:3}],
 ['inferno',"Огненный сад",'fire',8,57,"Широкая горящая зона.",{duration:3.8}],
 ['acid',"Кислотная капля",'acid',6,38,"Постепенно разъедает землю.",{duration:3.4}],
 ['slime',"Слизь",'acid',5,65,"Широкая медленная кислотная лужа.",{duration:4}],
 ['rail',"Игла",'rail',35,22,"Мгновенный узкий луч через рельеф."],
 ['prism',"Призма",'rail',21,33,"Широкий луч, проходящий через несколько танков."],
 ['lightning',"Молния",'lightning',60,54,"Вертикальный удар в точку приземления."],
 ['laser',"Орбитальный разрез",'laser',40,34,"Вертикальный луч вырезает узкую шахту."],
 ['quake',"Волна",'quake',15,36,"Семь взрывов расходятся вдоль земли.",{count:7}],
 ['fault',"Разлом",'quake',19,42,"Одиннадцать ударов вдоль поверхности.",{count:11}],
 ['garden',"Садовник",'dirt',0,65,"Насыпает холм. Само создание грунта не даёт очков.",{height:65}],
 ['wall',"Бастион",'dirt',0,32,"Строит высокую узкую преграду.",{height:120}],
 ['blink',"Блинк",'teleport',0,24,"Переносит твой танк в точку попадания."],
 ['hop',"Прыжок",'jump',0,24,"Перемещает танк на 140 единиц по направлению ствола."],
 ['magnet',"Магнит",'pull',26,90,"Стягивает ближайшие танки к центру."],
 ['push',"Толчок",'push',32,90,"Отбрасывает танки от взрыва."],
 ['void',"Пустота",'vortex',12,83,"Несколько импульсов притяжения, затем взрыв.",{duration:2}],
 ['boomerang',"Бумеранг",'boomerang',44,45,"В полёте меняет горизонтальное направление."],
 ['comet',"Комета",'comet',54,60,"Быстрый снаряд с дополнительными взрывами по бокам.",{speed:1.15}],
 ['seeker',"Искатель",'seeker',36,40,"Плавно поворачивает к ближайшему противнику."],
 ['bees',"Пчёлы",'seeker',17,27,"Три маленьких самонаводящихся снаряда.",{count:3}],
 ['splitter',"Вилка",'split',22,32,"Разделяется в полёте на пять частей.",{count:5}],
 ['carpet',"Ковёр",'rain',14,30,"Десять ударов вдоль широкой полосы.",{count:10,width:330}],
 ['chain',"Цепь",'chain',26,40,"Последовательные взрывы к ближайшему танку.",{count:5}],
 ['pulse',"Пульс",'pulse',20,52,"Три расширяющихся взрыва.",{count:3}],
 ['daisy',"Ромашка",'flower',16,29,"Из места удара вылетают восемь снарядов.",{count:8}],
 ['frost',"Иней",'freeze',35,53,"Взрыв и блокировка движения на один ход танка."],
 ['echo',"Эхо",'echo',29,42,"Повторяет взрыв в той же точке через полсекунды."],
 ['single_shot',"Single Shot",'shell',24,32,"Classic medium shell."],
 ['big_shot',"Big Shot",'shell',38,50,"Large blast, low score efficiency."],
 ['three_shot',"3 Shot",'spread',18,28,"Three bullet spread.",{'count':3, 'spread':0.075}],
 ['five_shot',"5 Shot",'spread',14,24,"Five bullet spread.",{'count':5, 'spread':0.085}],
 ['jackhammer',"Jackhammer",'bounce',18,30,"Bounces several times before exploding.",{'bounces':5}],
 ['heatseeker',"Heatseeker",'seeker',34,38,"Curves toward the closest tank."],
 ['tracer',"Tracer",'spread',8,18,"Five small tracers for practice.",{'count':5, 'spread':0.065}],
 ['pile_driver',"Pile Driver",'drill',16,27,"Directed downward drilling explosions.",{'count':4}],
 ['dirt_mover',"Dirt Mover",'quake',0,28,"Directional terrain removal.",{'count':5}],
 ['crazy_ivan',"Crazy Ivan",'cluster',17,28,"Chaotic proximity multi-warhead.",{'count':8}],
 ['spider',"Spider",'chain',18,26,"Web-like follow-up strikes.",{'count':5}],
 ['sniper_rifle',"Sniper Rifle",'rail',52,12,"No splash, lots of direct score."],
 ['magic_wall',"Magic Wall",'dirt',0,30,"Vertical wall grows where it lands.",{'height':130}],
 ['dirt_slinger',"Dirt Slinger",'dirt',0,54,"Throws a V-shape of dirt.",{'height':60}],
 ['zapper',"Zapper",'rail',24,18,"Laser zaps nearby enemies."],
 ['napalm',"Napalm",'fire',10,42,"Burning liquid that coats the ground.",{'duration':3.6}],
 ['hail_storm',"Hail Storm",'rain',18,24,"Hundreds of little bouncy pellets.",{'count':10, 'width':150}],
 ['ground_hog',"Ground Hog",'burrow',42,44,"Tunnels through the terrain.",{'depth':75}],
 ['worm',"Worm",'burrow',36,40,"Tunnels and rises upward.",{'depth':70}],
 ['homing_worm',"Homing Worm",'burrow',42,44,"Tunnels under tanks then pops upward.",{'depth':88}],
 ['skipper',"Skipper",'bounce',24,34,"Skips before exploding.",{'bounces':4}],
 ['chain_reaction',"Chain Reaction",'chain',20,34,"Random-looking chained blasts.",{'count':7}],
 ['pineapple',"Pineapple",'cluster',14,22,"Tiny explosions burst everywhere.",{'count':16}],
 ['firecracker',"Firecracker",'quake',14,26,"Horizontal spread of explosions.",{'count':7}],
 ['homing_missile',"Homing Missile",'seeker',30,34,"Slows over a tank then dives."],
 ['dirtball',"Dirtball",'dirt',0,46,"Creates a dirt clump.",{'height':65}],
 ['tommy_gun',"Tommy Gun",'spread',10,18,"Automatic machine-gun style spray.",{'count':8, 'spread':0.03}],
 ['mountain_mover',"Mountain Mover",'quake',0,68,"Huge dirt removal that scores nothing.",{'count':9}],
 ['scatter_shot',"Scatter Shot",'flower',13,23,"Bullets spread upward from impact.",{'count':6}],
 ['cruiser',"Cruiser",'roller',28,36,"Cruises along terrain before exploding."],
 ['jump_jets',"Jump Jets",'jump',0,24,"Launches your tank based on aim."],
 ['mud_pie',"Mud Pie",'dirt',0,74,"Throws many dirtball fragments.",{'height':80}],
 ['pin_cushion',"Pin Cushion",'cluster',14,26,"Each mini-bullet acts like a zapper.",{'count':10}],
 ['laser_battery',"Laser Battery",'pulse',18,28,"A ring of lasers fires outward.",{'count':4}],
 ['cannon_ball',"Cannon Ball",'roller',46,28,"Heavy rolling metal sphere."],
 ['wacky_tank',"Wacky Tank",'push',18,52,"Scrambles movement and knocks tanks around."],
 ['digger',"Digger",'drill',0,20,"Digs a narrow tunnel.",{'count':7}],
 ['glue_bomb',"Glue Bomb",'freeze',18,44,"Sticky coating slows the field."],
 ['fission_bomb',"Fission Bomb",'split',26,34,"Upward splitting warheads.",{'count':7}],
 ['late_bloomer',"Late Bloomer",'burrow',22,26,"Emerges and launches extra bullets.",{'depth':72}],
 ['fire_bolt',"Fire Bolt",'fire',18,26,"Fast flying fireball.",{'duration':2.6}],
 ['color_bomb',"Color Bomb",'cluster',14,24,"Huge rainbow of bouncy bullets.",{'count':18}],
 ['potholes',"Potholes",'chain',12,30,"Rips the terrain apart.",{'count':9}],
 ['boomerang_pt',"Boomerang",'boomerang',34,36,"Cruiser-style boomerang shell."],
 ['popcorn',"Popcorn",'bounce',10,18,"Many little hopping blasts.",{'bounces':6}],
 ['sprinkler',"Sprinkler",'flower',10,22,"Dangerous symmetric spray.",{'count':10}],
 ['well_digger',"Well Digger",'drill',0,18,"Digs you out of any dirt.",{'count':8}],
 ['bouncy_dirt',"Bouncy Dirt",'dirt',0,42,"Covers the ground with rubbery dirt.",{'height':45}],
 ['super_tracer',"Super Tracer",'spread',6,16,"Ten tracer bullets for aiming.",{'count':10, 'spread':0.06}],
 ['minigun',"Minigun",'spread',12,20,"Fast bullets with tiny explosions.",{'count':10, 'spread':0.025}],
 ['crater_maker',"Crater Maker",'shell',72,84,"One of the biggest classic explosions.",{'speed':0.8}],
 ['big_dirtball',"Big Dirtball",'dirt',0,60,"The Dirtball's bigger brother.",{'height':95}],
 ['super_zapper',"Super Zapper",'rail',34,26,"Longer-range zapper beam."],
 ['cruball',"Cruball",'roller',0,42,"A cruising dirtball.",{'damage':0}],
 ['mega_cruiser',"Mega Cruiser",'roller',42,46,"Cruiser with a much bigger bang."],
 ['heavy_roller',"Heavy Roller",'roller',50,52,"A Roller with big explosion and points."],
 ['flash_blast',"Flash Blast",'pulse',22,40,"Scorches ground and extracts score.",{'count':3}],
 ['nuke',"Nuke",'shell',88,64,"The hardest-hitting weapon."],
 ['mega_nuke',"Mega Nuke",'shell',76,90,"Huge nuclear explosion."],
 ['pillow_fight',"Pillow Fight",'cluster',16,22,"Direct hit with exploding feathers.",{'count':8}],
 ['sink_and_swim',"Sink and Swim",'rain',18,28,"Sinks the tank and hails it from above.",{'count':8, 'width':110}],
 ['hotfoot',"Hotfoot",'burrow',24,28,"Timed underground detonation with upward warheads.",{'depth':84}],
 ['ambush',"Ambush",'roller',28,28,"Surrounds the target with cruisers."],
 ['beehive',"Beehive",'seeker',12,20,"A swarming hive of bees.",{'count':6}],
 ['blast_off',"Blast Off",'jump',0,26,"More powerful than jump jets."],
 ['fire_in_the_hole',"Fire in the Hole",'fire',18,46,"Big hole full of napalm, then dirt.",{'duration':3.2}],
 ['lob_o_matic',"Lob-o-Matic",'rain',22,30,"Missile that bombs when it gets close.",{'count':6, 'width':120}],
 ['rainbow_dirt',"Rainbow Dirt",'dirt',0,72,"Thin layer of dirt over a large area.",{'height':35}],
 ['super_laser',"Super Laser",'laser',48,28,"Burns through many layers of terrain."],
 ['ground_shocker',"Ground Shocker",'burrow',16,26,"Spread of underground tunneling missiles.",{'depth':65}],
 ['bouncy_wall',"Bouncy Wall",'dirt',0,36,"Rubberized defensive wall.",{'height':110}],
 ['lodestones',"Lodestones",'pull',16,90,"Lots of magnetic bullets."],
 ['particle_bomb',"Particle Bomb",'fire',16,30,"Burning shrapnel in all directions.",{'duration':2.8}],
 ['magic_forest',"Magic Forest",'dirt',0,38,"Forest of mini magic walls.",{'height':90}],
 ['buckshot',"Buckshot",'spread',12,20,"Burst of little bullets that spread over distance.",{'count':9, 'spread':0.04}],
 ['quad_missile',"Quad Missile",'seeker',16,22,"Four small missiles home in.",{'count':4}],
 ['carpet_bomb',"Carpet Bomb",'rain',20,34,"Difficult to miss at distance.",{'count':12, 'width':340}],
 ['flamethrower',"Flamethrower",'fire',12,30,"Huge spray of flaming napalm.",{'duration':4}],
 ['skimmer',"Skimmer",'bounce',18,24,"Two ricochets fly out horizontally.",{'bounces':2}],
 ['volcano',"Volcano",'flower',14,26,"Massive eruption that throws fire and debris.",{'count':12}],
 ['pedestal',"Pedestal",'dirt',0,34,"Raises a high pedestal under a tank.",{'height':140}],
 ['fire_storm',"Fire Storm",'rain',12,26,"Multiple explosions with bouncing fireballs.",{'count':12, 'width':240}],
 ['meteor_shower',"Meteor Shower",'rain',22,34,"Rain of meteors from the sky.",{'count':12, 'width':260}],
 ['roman_candle',"Roman Candle",'spread',14,20,"Six sparkling flares in the same path.",{'count':6, 'spread':0.01}],
 ['flying_digger',"Flying Digger",'drill',0,18,"Digs where the missile lands.",{'count':6}],
 ['sunburn',"Sunburn",'rail',22,28,"Laser beams bounce off the terrain."],
 ['riptide',"Riptide",'spread',12,22,"Horizontal wave of reflective missiles.",{'count':8, 'spread':0.02}],
 ['buzzsaw',"Buzzsaw",'saw',18,24,"Chews the terrain as it bounces along."],
 ['static_ball',"Static Ball",'vortex',14,32,"Shocks tanks nearby."],
 ['mystery_bombs',"Mystery Bombs",'split',20,28,"Four randomly diving bullets.",{'count':4}],
 ['flower_power',"Flower Power",'flower',14,26,"Tunneling missile that spreads bombs.",{'count':10}],
 ['turn_and_burn',"Turn and Burn",'jump',0,24,"Sets a fuse then rockets you away."],
 ['dome_protect',"Dome Protect",'dirt',0,50,"Creates a protective dome.",{'height':100}],
 ['backfire',"Backfire",'teleport',0,26,"Random tank teleporter with a twist."],
 ['old_faithful',"Old Faithful",'rain',24,28,"Extremely powerful hail storm.",{'count':18, 'width':170}],
 ['bouncy_bomb',"Bouncy Bomb",'dirt',0,56,"Big crater with lots of bouncy dirt.",{'height':50}],
];
const palette={shell:'#ffd17d',spread:'#ff936a',cluster:'#ffba58',rain:'#a8baff',bounce:'#b9f981',roller:'#edb88b',saw:'#dadde0',burrow:'#bb9bf2',drill:'#b4a2f9',fire:'#ff8153',acid:'#b6e76c',rail:'#75e0ff',lightning:'#e4ec92',laser:'#ef9fff',quake:'#f0bd83',dirt:'#a8bc80',teleport:'#a889ff',jump:'#8feadf',pull:'#bb92ed',push:'#91e5e5',vortex:'#a797ff',boomerang:'#e8dc92',comet:'#ffc78b',seeker:'#9fd8ae',split:'#e5acde',chain:'#f59d83',pulse:'#a4e5fa',flower:'#ffaccd',freeze:'#b7efff',echo:'#d5b9f5'};
const {profiles}=require('./weapon-profiles.cjs');
const {reference,compileWeapon}=require('./pocket-effects.cjs');
// The handwritten table above remains useful documentation for LocalParty's
// earlier adaptation. Runtime weapons now come from the complete decoded
// Pocket Tanks definition graph supplied by the developer's local copy.
// The accent colour paints trails, fallback shells and explosion rings over a
// black sky. The first emitter colour can be black (transparent or smoke
// nodes), which made those shots and rings invisible; use the first authored
// colour that reads on the dark background, else the family colour.
const readable=c=>/^#[0-9a-f]{6}$/i.test(c||'')&&Math.max(...[1,3,5].map(i=>parseInt(c.slice(i,i+2),16)))>=0x60;
const WEAPONS=reference.weapons.map(source=>{
 const imported=compileWeapon(source),profile=profiles[imported.id]||{};
 return {...imported,...profile,color:[imported.color,...imported.fx.colors].find(readable)||palette[imported.family]||'#ffd17d'};
});
const BY_ID=Object.fromEntries(WEAPONS.map(w=>[w.id,w]));
module.exports={WEAPONS,BY_ID};
