'use strict';const crypto=require('crypto');
const SIZE=6;
function fleet(){const ships=[];for(const length of [2,2,1]){let cells;do{const x=crypto.randomInt(SIZE),y=crypto.randomInt(SIZE),horizontal=crypto.randomInt(2);cells=Array.from({length},(_,i)=>(y+(horizontal?0:i))*SIZE+x+(horizontal?i:0));if((horizontal&&x+length>SIZE)||(!horizontal&&y+length>SIZE))cells=null;}while(!cells||ships.some(s=>s.some(c=>cells.includes(c))));ships.push(cells);}return ships;}
class Naval{
 constructor(report=()=>{}){this.report=report;this.players=new Map();this.phase='lobby';this.seconds=180;this.cooldown=2500;this.sequence=0;}
 join(id,name){let p=this.players.get(id);if(!p){p={id,name,online:true,active:false,hits:0,misses:0,sunk:0,shots:0,score:0,health:0,nextShot:0,seen:new Set(),ships:[],board:Array(36).fill(null)};this.players.set(id,p);}p.name=name;p.online=true;return p;}
 start(){if(!['lobby','finished'].includes(this.phase))return false;const online=[...this.players.values()].filter(p=>p.online);if(online.length<2)return false;for(const p of this.players.values())Object.assign(p,{active:p.online,hits:0,misses:0,sunk:0,shots:0,score:0,health:p.online?5:0,nextShot:0,seen:new Set(),ships:p.online?fleet():[],board:Array(36).fill(null)});this.lastShot=null;this.phase='battle';this.startedAt=Date.now();this.endsAt=this.startedAt+this.seconds*1000;this.eventId=crypto.randomUUID();this.winners=[];return true;}
 shoot(id,targetId,cell,shotId,now=Date.now()){const p=this.players.get(id),target=this.players.get(targetId);if(this.phase!=='battle'||now>=this.endsAt||!p?.active||p.health<=0||!target?.active||target.health<=0||id===targetId||!Number.isInteger(cell)||cell<0||cell>=36||typeof shotId!=='string'||shotId.length>80||!shotId||p.seen.has(shotId)||now<p.nextShot||target.board[cell]!==null)return false;p.seen.add(shotId);p.nextShot=now+this.cooldown;p.shots++;const ship=target.ships.find(s=>s.includes(cell));if(ship){target.board[cell]='hit';target.health--;p.hits++;p.score+=100;if(ship.every(c=>target.board[c]==='hit'||target.board[c]==='sunk')){for(const c of ship)target.board[c]='sunk';p.sunk++;p.score+=150;}}else{target.board[cell]='miss';p.misses++;}this.lastShot={sequence:++this.sequence,by:p.name,target:target.name,targetId,cell,result:target.board[cell]};if([...this.players.values()].filter(x=>x.active&&x.health>0).length<=1)this.finish();return true;}
 finish(){if(this.phase!=='battle')return false;this.phase='finished';const active=[...this.players.values()].filter(p=>p.active);const maxHealth=Math.max(...active.map(p=>p.health)),survivors=active.filter(p=>p.health===maxHealth),top=Math.max(...survivors.map(p=>p.score));this.winners=survivors.filter(p=>p.score===top).map(p=>p.id);this.report({eventId:this.eventId,gameId:'naval',duration:Date.now()-this.startedAt,players:active.map(p=>({id:p.id,name:p.name,score:p.score,won:this.winners.includes(p.id),metrics:{hits:p.hits,misses:p.misses,sunk:p.sunk,shots:p.shots,survived:p.health>0?1:0}}))});return true;}
 view(id){const p=this.players.get(id);return{type:'state',phase:this.phase,endsAt:this.endsAt,serverTime:Date.now(),cooldown:this.cooldown,winners:this.winners||[],lastShot:this.lastShot,players:[...this.players.values()].map(p=>({id:p.id,name:p.name,online:p.online,active:p.active,health:p.health,score:p.score,hits:p.hits,misses:p.misses,sunk:p.sunk,shots:p.shots,board:p.board})).sort((a,b)=>b.health-a.health||b.score-a.score),me:p?{id:p.id,name:p.name,active:p.active,health:p.health,ships:p.ships,nextShot:p.nextShot}:null};}
}
module.exports={Naval,fleet,SIZE};
