'use strict';
const express=require('express'),http=require('http'),crypto=require('crypto'),{WebSocketServer}=require('ws'),QRCode=require('qrcode'),runtime=require('../../lib/party-runtime');
const {initialize,TowerPhysics,SCALE,WIDTH:BLOCK_W,HEIGHT:BLOCK_H}=require('./physics');let physics=null,settleFor=0,contactAt=0,turnStage='aiming',nextTurnAt=0,physicsAccumulator=0;
const app=express(),server=http.createServer(app),wss=new WebSocketServer({server,path:'/ws'}),players=new Map();
const {HangingLoad}=require('./pendulum');const hangingLoad=new HangingLoad();
const WIDTH=1100,FLOOR=780,DROP_GAP=230,colors=['#b8f778','#78dbf7','#ffb779','#e6a4ff','#ff839b','#f5df79'];
let phase='lobby',blocks=[],falling=null,trolley=550,trolleyVelocity=0,turnIndex=0,turnId='',deadline=0,turnOrder=[],turns=0,maxTurns=12,lives=3,heightRecord=0,roundId='',startedAt=0,lastMessage='Соберите башню вместе',particles=[],finishAt=0,fallReason='',lastInput=0;
const send=(ws,d)=>{if(ws?.readyState===1)ws.send(JSON.stringify(d));},connected=()=>[...players.values()].filter(p=>p.connected),active=()=>players.get(turnOrder[turnIndex%Math.max(1,turnOrder.length)]),clamp=(x,a,b)=>Math.max(a,Math.min(b,Number(x)||0)),rnd=()=>crypto.randomUUID();
function state(){const top=physics?.top(blocks)||{x:550,y:FLOOR},hook=hangingLoad.pose(trolley,top.y-BLOCK_H/2-DROP_GAP,trolleyVelocity),hookY=hook.y,hookX=hook.x;return{type:'state',phase,width:WIDTH,blockWidth:BLOCK_W,blockHeight:BLOCK_H,floor:FLOOR,players:[...players.values()].map(({id,name,color,connected,score,perfects,placed,misses})=>({id,name,color,connected,score,perfects,placed,misses})),blocks:blocks.map(b=>physics.public(b)),falling:falling&&physics.public(falling),trolley,hookX,hookY,beamY:hook.beamY,hookAngle:hook.angle,topY:top.y,turnStage,projection:physics?.project(hookX,hookY,falling),activeId:active()?.id,activeName:active()?.name,turnId,deadline,turns,maxTurns,lives,height:blocks.length,heightRecord,message:lastMessage,particles,roundId};}
function broadcast(){runtime.ui({phase:phase==='lobby'?'waiting':turnStage==='paused'?'paused':phase==='playing'?'playing':phase==='collapsing'?'reveal':phase,endsAt:phase==='playing'&&turnStage==='aiming'?deadline:null,label:turnStage==='settling'?'Блок садится':turnStage==='falling'?'Блок падает':turnStage==='feedback'?'Результат хода':phase==='playing'?'Твой ход':'Общая башня',currentPlayer:active()?.name||null,progress:heightRecord+' этажей · ход '+(turns+(phase==='results'?0:1)),actions:[]});const d=state();for(const ws of wss.clients)send(ws,d);}
function newTurn(){if(phase!=='playing')return;if(lives<=0){end(lives<=0?'Закончились попытки':'Смена закончена — отличная работа!');return;}let tries=0;while(tries++<turnOrder.length&&!active()?.connected)turnIndex++;if(!active()?.connected){turnStage='paused';lastMessage='Ждём возвращения строителей';deadline=Date.now()+90000;turnId=rnd();return;}turnId=rnd();turnStage='aiming';settleFor=0;contactAt=0;deadline=Date.now()+90000;trolley=physics.top(blocks).x;trolleyVelocity=0;hangingLoad.reset();lastInput=0;falling=null;lastMessage=`${active().name}, твой блок!`;broadcast();}
function start(){if(connected().length<2)return false;phase='playing';physics?.free();physics=new TowerPhysics();blocks=[];falling=null;particles=[];turnOrder=connected().map(p=>p.id);turnIndex=turns=heightRecord=0;lives=3;maxTurns=null;roundId=rnd();startedAt=Date.now();finishAt=0;for(const p of players.values())Object.assign(p,{score:0,perfects:0,placed:0,misses:0,left:false,right:false});newTurn();return true;}
function end(message){if(phase==='results')return;phase='results';lastMessage=message;finishAt=Date.now();runtime.report({gameId:'crane',eventId:roundId,duration:(Date.now()-startedAt)/1000,players:[...players.values()].map(p=>({id:p.id,name:p.name,score:p.score,won:heightRecord>=8,metrics:{placed:p.placed,perfects:p.perfects,misses:p.misses,towerHeight:heightRecord}}))});broadcast();}
function burst(x,y,color,n=16){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*200,vy:-Math.random()*180-40,life:1,color});}
function drop(){if(phase!=='playing'||falling||turnStage!=='aiming'||!active())return;const top=physics.top(blocks);const hook=hangingLoad.pose(trolley,top.y-BLOCK_H/2-DROP_GAP,trolleyVelocity);falling=physics.add(hook.x,hook.y,{owner:active().id,color:active().color});falling.body.setRotation(hook.angle*.6,true);falling.body.setAngvel(hangingLoad.velocity*.7,true);falling.body.setLinvel({x:hook.vx/SCALE,y:hook.vy/SCALE},true);active().left=active().right=false;turnStage='falling';lastMessage='Блок падает…';}
function advance(){turns++;turnIndex++;newTurn();}
function miss(){const shape=physics.public(falling),p=players.get(falling.owner);if(p)p.misses++;lives--;lastMessage='Мимо опоры · минус попытка';burst(shape.x,FLOOR,'#ff839b',25);physics.remove(falling);falling=null;turnStage='feedback';nextTurnAt=Date.now()+650;}
function collapse(){if(phase!=='playing')return;phase='collapsing';fallReason='Башня потеряла равновесие';finishAt=Date.now()+3000;lastMessage=fallReason;}
function update(dt){if(!(dt>0))return;for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=400*dt;p.life-=dt;}particles=particles.filter(p=>p.life>0).slice(-150);if(!physics||!['playing','collapsing'].includes(phase))return;physicsAccumulator=Math.min(.1,physicsAccumulator+dt);while(physicsAccumulator>=1/120){physics.step();physicsAccumulator-=1/120;}if(phase==='collapsing'){if(Date.now()>finishAt)end(fallReason);return;}
 for(const b of blocks){const shape=physics.public(b);if(Math.abs(shape.angle)>.85||shape.y>b.settledY+80){collapse();return;}}
 if(turnStage==='paused'){if(connected().length)newTurn();return;}if(turnStage==='feedback'){if(Date.now()>nextTurnAt)advance();return;}
 if(!falling){const p=active(),direction=p?.connected&&Date.now()-lastInput<450?Number(!!p.right)-Number(!!p.left):0;const previousVelocity=trolleyVelocity;trolleyVelocity+=(direction*420-trolleyVelocity)*(1-Math.exp(-dt*12));const nextTrolley=clamp(trolley+trolleyVelocity*dt,90,WIDTH-90);trolleyVelocity=(nextTrolley-trolley)/dt;trolley=nextTrolley;hangingLoad.step(dt,(trolleyVelocity-previousVelocity)/dt);if(Date.now()>=deadline){if(p?.connected)drop();else{turnIndex++;newTurn();}}return;}
 const shape=physics.public(falling);if(shape.y>FLOOR+90){miss();return;}if(physics.supported(falling)){if(!contactAt){contactAt=Date.now();const top=physics.top(blocks),offset=clamp((shape.x-top.x)/BLOCK_W,-1,1),lean=blocks.reduce((n,b)=>n+Math.abs(b.body.rotation()),0),stress=Math.min(1.6,.35+blocks.length*.07+lean*.25);for(let i=0;i<blocks.length;i++){const b=blocks[i];b.body.applyTorqueImpulse(offset*stress*.035*(i+1)/blocks.length,true);}}turnStage='settling';lastMessage='Контакт · ждём устойчивости';}settleFor=physics.quiet(falling)?settleFor+dt:0;
 if(settleFor>=.35){const top=physics.top(blocks),owner=players.get(falling.owner),offset=Math.abs(shape.x-top.x),perfect=offset<12;falling.settledY=shape.y;blocks.push(falling);falling=null;heightRecord=Math.max(heightRecord,blocks.length);if(owner){owner.placed++;owner.score+=Math.max(20,Math.round(100-offset*.5))+(perfect?50:0);if(perfect)owner.perfects++;}burst(shape.x,shape.y,shape.color,perfect?24:12);lastMessage=perfect?'Идеально! +150':'Этаж готов · '+blocks.length;turnStage='feedback';nextTurnAt=Date.now()+450;}
 else if(contactAt&&Date.now()-contactAt>6500){const unstable=physics.public(falling);if(Math.abs(unstable.angle)>.7||unstable.y>physics.top(blocks).y+BLOCK_H||Date.now()-contactAt>12000)collapse();}
}
app.use((req,res,next)=>{res.set('Cache-Control','no-store');next();});app.get('/host',(req,res)=>res.sendFile(__dirname+'/public/host.html'));app.get('/',(req,res)=>res.sendFile(__dirname+'/public/play.html'));app.get('/api/info',(req,res)=>{const port=server.address().port;res.json({port,joinUrl:process.env.PARTY_JOIN_URL||`http://localhost:${port}/`});});app.get('/qr.png',async(req,res)=>res.type('png').send(await QRCode.toBuffer(process.env.PARTY_JOIN_URL||`http://localhost:${server.address().port}/`)));app.use(express.static(__dirname+'/public'));
wss.on('connection',(ws,req)=>{const local=['127.0.0.1','::1','::ffff:127.0.0.1'].includes(req.socket.remoteAddress);const host=new URL(req.url,'http://local').searchParams.get('role')==='host'&&(runtime.managed?req.headers['x-party-local']==='1':local);ws.host=host;send(ws,state());ws.on('message',raw=>{let d;try{d=JSON.parse(raw);}catch{return;}if(!d||typeof d!=='object'||Array.isArray(d)||typeof d.type!=='string')return;if(d.type==='join'||d.type==='resume'){const identity=runtime.identify(d,ws);if(runtime.managed&&!identity)return send(ws,{type:'error',message:'Войди через общее лобби'});let p=identity?players.get(identity.id):players.get(d.id);if(p&&!identity&&p.token!==d.token)return send(ws,{type:'error',message:'Не удалось восстановить игрока'});if(!p){if(players.size>=16)return send(ws,{type:'error',message:'Максимум 16 игроков'});p={id:identity?.id||rnd(),token:identity?.token||rnd(),name:String(identity?.name||d.name||'Строитель').slice(0,28),color:colors[players.size%colors.length],score:0,perfects:0,placed:0,misses:0};players.set(p.id,p);if(phase==='playing')turnOrder.push(p.id);}const old=p.ws;p.ws=ws;p.connected=true;p.left=p.right=false;ws.player=p;if(old&&old!==ws)old.close(4001,'Player resumed');send(ws,{type:'joined',id:p.id,token:p.token,name:p.name});broadcast();}
else if(d.type==='input'&&ws.player?.ws===ws&&active()?.id===ws.player.id&&d.turnId===turnId&&phase==='playing'&&!falling&&turnStage==='aiming'){ws.player.left=!!d.left;ws.player.right=!!d.right;lastInput=Date.now();}
else if(d.type==='drop'&&ws.player?.ws===ws&&active()?.id===ws.player.id&&d.turnId===turnId)drop();
else if(host&&d.type==='start'&&(phase==='lobby'||phase==='results')){if(!start())send(ws,{type:'error',message:'Нужно минимум 2 игрока'});}
else if(host&&d.type==='reset'){phase='lobby';physics?.free();physics=new TowerPhysics();blocks=[];falling=null;lastMessage='Соберите башню вместе';broadcast();}
});ws.on('close',()=>{if(ws.player?.ws===ws){ws.player.connected=false;ws.player.left=ws.player.right=false;runtime.presence(ws.player.id,false);broadcast();}});});
let last=runtime.now();runtime.setInterval(()=>{const t=runtime.now();update(Math.min(.05,(t-last)/1000));last=t;},1000/60);runtime.setInterval(broadcast,1000/30);initialize().then(()=>{physics=new TowerPhysics();server.listen(Number(process.env.PORT||0),runtime.managed?'127.0.0.1':'0.0.0.0',()=>console.log(`CRANE http://127.0.0.1:${server.address().port}/host`));}).catch(e=>{console.error(e);process.exitCode=1;});

app.use('/assets/fonts',express.static(require('path').resolve(__dirname,'../../public/assets/fonts')));

runtime.onPause(()=>{for(const p of players.values()){p.left=false;p.right=false;}lastInput=0;trolleyVelocity=0;});

// Commands from the iPhone server console.
runtime.host({start:()=>{const ok=start();broadcast();return ok;}});
