'use strict';
const crypto=require('crypto'),WORDS=require('../crocodile/words.json');
const normalize=s=>String(s||'').toLocaleLowerCase('ru').replace(/ё/g,'е').replace(/[^а-яa-z0-9 ]/g,' ').replace(/\s+/g,' ').trim();
const ALIASES={'Котёнок':['кот','кошка','котик'],'Щенок':['собака','пес','собачка'],'Паровоз':['поезд','локомотив'],'Пианино':['фортепиано','рояль'],'Самолёт':['аэроплан'],'Велосипед':['велик'],'Фотоаппарат':['камера','фотокамера'],'Мотоцикл':['байк','мото'],'Космонавт':['астронавт'],'Повар':['шеф','шеф повар'],'Врач':['доктор'],'Парикмахер':['барбер'],'Осьминог':['спрут'],'Воздушный змей':['змей'],'Человек невидимка':['невидимка'],'Стиральная машина':['стиралка'],'Зубная щётка':['щетка для зубов'],'Сахарная вата':['сладкая вата'],'Спагетти':['макароны','паста'],'Пожарный':['пожарник'],'Водитель автобуса':['автобусный водитель'],'Снеговик':['снежная баба'],'Скрипка':['виолина'],'Стоматолог':['зубной врач','дантист'],'Диджей':['dj','ди джей'],'Тяжелоатлет':['штангист'],'Канатоходец':['эквилибрист'],'Петь в душе':['пение в душе'],'Делать селфи':['селфи'],'Выгуливать собаку':['выгул собаки'],'Играть в боулинг':['боулинг']};
class DrawGuess{
 constructor(report=()=>{}){this.report=report;this.players=new Map();this.phase='lobby';this.settings={seconds:60};this.turn=-1;this.turnId=0;this.strokes=[];this.messages=[];this.used=[];}
 join(id,name){let p=this.players.get(id);if(!p){p={id,name,online:true,score:0,correct:0,drawings:0,guessed:false,lastGuess:0};this.players.set(id,p);}p.name=name;p.online=true;if(this.order&&['drawing','reveal','paused'].includes(this.phase)&&!this.order.includes(id))this.order.push(id);return p;}
 configure(s){if(['lobby','finished'].includes(this.phase)&&[30,60,90].includes(Number(s.seconds)))this.settings.seconds=Number(s.seconds);}
 start(){const ids=[...this.players.values()].filter(p=>p.online).map(p=>p.id);if(!['lobby','finished'].includes(this.phase)||ids.length<2)return false;this.order=ids;this.turn=-1;this.used=[];this.eventId=crypto.randomUUID();this.startedAt=Date.now();for(const p of this.players.values())Object.assign(p,{score:0,correct:0,drawings:0});return this.next();}
 next(now=Date.now()){if(++this.turn>=this.order.length){this.phase='finished';this.secret=null;this.endsAt=null;const rows=this.order.map(id=>this.players.get(id)),top=Math.max(...rows.map(p=>p.score));this.report({eventId:this.eventId,gameId:'drawguess',duration:Date.now()-this.startedAt,players:rows.map(p=>({id:p.id,name:p.name,score:p.score,won:p.score===top,metrics:{correct:p.correct,drawings:p.drawings}}))});return true;}this.artist=this.order[this.turn];this.turnId++;const pool=WORDS.filter(w=>!this.used.includes(w));this.secret=pool[crypto.randomInt(pool.length)];this.used.push(this.secret);this.strokes=[];this.segmentIds=new Set();this.messages=[];this.eligible=new Set([...this.players.values()].filter(p=>p.online&&p.id!==this.artist).map(p=>p.id));for(const p of this.players.values())p.guessed=false;this.players.get(this.artist).drawings++;this.phase='drawing';this.endsAt=now+this.settings.seconds*1000;return true;}
 disconnect(id,now=Date.now()){const p=this.players.get(id);if(p){p.online=false;p.disconnectedAt=now;}}
 stroke(id,turnId,segment){if(this.phase!=='drawing'||id!==this.artist||turnId!==this.turnId||Date.now()>=this.endsAt||!segment||typeof segment.id!=='string'||segment.id.length>80||this.segmentIds.has(segment.id)||this.strokes.length>=4000)return false;const pts=segment.points;if(!Array.isArray(pts)||pts.length!==4||pts.some(n=>typeof n!=='number'||!Number.isFinite(n)||n<0||n>1))return false;const color=['#eef4e9','#c8ff73','#ff8d98','#81cfff','#ffd773'].includes(segment.color)?segment.color:'#eef4e9';const width=[3,7,13].includes(segment.width)?segment.width:7;const item={id:segment.id,points:pts,color,width};this.segmentIds.add(item.id);this.strokes.push(item);return item;}
 clear(id,turnId){if(this.phase!=='drawing'||id!==this.artist||turnId!==this.turnId)return false;this.strokes=[];return true;}
 guess(id,turnId,text,now=Date.now()){const p=this.players.get(id);if(this.phase!=='drawing'||turnId!==this.turnId||!p||!this.eligible.has(id)||p.guessed||now>=this.endsAt||now-p.lastGuess<500)return false;const guess=normalize(text);if(!guess||guess.length>80)return false;p.lastGuess=now;const correct=[this.secret,...(ALIASES[this.secret]||[])].some(w=>normalize(w)===guess);if(correct){p.guessed=true;p.correct++;p.score+=100+Math.round(Math.max(0,this.endsAt-now)/(this.settings.seconds*1000)*50);this.players.get(this.artist).score+=75;}this.messages.push({id:p.id,name:p.name,text:correct?'Угадал!':String(text).slice(0,80),correct});this.messages=this.messages.slice(-12);this.tick(now);return true;}
 reveal(now=Date.now()){if(this.phase!=='drawing')return false;this.phase='reveal';this.endsAt=now+3000;return true;}
 tick(now=Date.now()){if(!['drawing','reveal','paused'].includes(this.phase))return false;const online=[...this.players.values()].some(p=>p.online);if(!online&&this.phase!=='paused'){this.resumePhase=this.phase;this.remaining=Math.max(0,this.endsAt-now);this.endsAt=null;this.phase='paused';return true;}if(this.phase==='paused'){if(!online)return false;this.phase=this.resumePhase;this.endsAt=now+this.remaining;return true;}if(this.phase==='reveal'&&now>=this.endsAt)return this.next(now);if(this.phase==='drawing'){const artist=this.players.get(this.artist),expected=[...this.eligible].map(id=>this.players.get(id)).filter(p=>p.online||now-(p.disconnectedAt||now)<5000);if(now>=this.endsAt||(!artist.online&&now-(artist.disconnectedAt||now)>=5000)||(expected.length>0&&expected.every(p=>p.guessed)))return this.reveal(now);}return false;}
 view(id){const p=this.players.get(id);return{type:'state',phase:this.phase,settings:this.settings,turn:this.turn,total:this.order?.length||0,turnId:this.turnId,endsAt:this.endsAt,serverTime:Date.now(),artist:this.players.get(this.artist)?.name||null,artistId:this.artist,secret:id===this.artist||this.phase==='reveal'?this.secret:null,me:p?{...p,canGuess:this.eligible?.has(id)||false}:null,players:[...this.players.values()].map(p=>({...p})).sort((a,b)=>b.score-a.score),strokes:this.strokes,messages:this.messages};}
}
module.exports={DrawGuess,WORDS,normalize,ALIASES};
