'use strict';const express=require('express'),http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),{WebSocketServer,WebSocket}=require('ws'),party=require('../../lib/party-runtime'),{DrawGuess}=require('./engine');
const app=express(),server=http.createServer(app),wss=new WebSocketServer({server,maxPayload:8192}),game=new DrawGuess(party.report),hostKey=crypto.randomBytes(24).toString('hex'),clients=new Map(),standalone=new Map();
const local=req=>['127.0.0.1','::1','::ffff:127.0.0.1'].includes(req.socket.remoteAddress);
app.get('/host',(req,res)=>{if(!local(req))return res.sendStatus(403);res.type('html').send(fs.readFileSync(path.join(__dirname,'public/index.html'),'utf8').replace('window.DRAW_HOST_KEY=null','window.DRAW_HOST_KEY='+JSON.stringify(hostKey)));});app.use(express.static(path.join(__dirname,'public')));
const send=(ws,v)=>{if(ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify(v));};const broadcast=()=>{party.ui?.({phase:({lobby:'waiting',drawing:'playing',reveal:'reveal',finished:'results',paused:'paused'})[game.phase],endsAt:game.endsAt||null,label:game.phase==='finished'?'Итоги':game.phase==='reveal'?'Следующий художник':'Рисуем',currentPlayer:game.players.get(game.artist)?.name||null,progress:Math.min(game.turn+1,game.order?.length||0)+' / '+(game.order?.length||0),actions:[]});for(const [ws,c]of clients)send(ws,game.view(c.id));};
wss.on('connection',(ws,req)=>{const c={id:null,host:false};clients.set(ws,c);send(ws,game.view());ws.on('message',raw=>{let m;try{m=JSON.parse(raw);}catch{return;}if(!m||typeof m!=='object')return;
if(m.type==='host'&&m.key===hostKey&&local(req))c.host=true;
else if(m.type==='join'){let p=party.identify(m);if(!party.managed&&!p){const old=standalone.get(m.id);if(old&&old.token===m.token)p=old;else{p={id:crypto.randomUUID(),token:crypto.randomBytes(18).toString('hex'),name:String(m.name||'Игрок').trim().slice(0,24)||'Игрок'};standalone.set(p.id,p);}send(ws,{type:'identity',...p});}if(!p)return send(ws,{type:'error',message:'Откройте главное лобби для подключения.'});if(!game.players.has(p.id)&&game.players.size>=16)return send(ws,{type:'error',message:'Уже 16 игроков.'});for(const [other,oc]of clients)if(other!==ws&&oc.id===p.id){oc.id=null;other.close(4001,'Replaced');}c.id=p.id;game.join(p.id,p.name);send(ws,{type:'joined',id:p.id});party.presence(p.id,true);}
else if(m.type==='stroke'&&c.id){const segment=game.stroke(c.id,m.turnId,m.segment);if(segment)for(const other of clients.keys())send(other,{type:'stroke',turnId:game.turnId,segment});return;}else if(m.type==='clear'&&c.id)game.clear(c.id,m.turnId);else if(m.type==='guess'&&c.id)game.guess(c.id,m.turnId,m.text);

else if(c.host){if(m.type==='configure')game.configure(m.settings||{});if(m.type==='start')game.start();if(m.type==='end')game.reveal();}broadcast();});ws.on('close',()=>{clients.delete(ws);if(c.id&&![...clients.values()].some(x=>x.id===c.id)){game.disconnect(c.id);party.presence(c.id,false);}broadcast();});});
party.setInterval(()=>{if(game.tick())broadcast();},150).unref();server.listen(Number(process.env.PORT||0),party.managed?'127.0.0.1':'0.0.0.0',()=>console.log('DrawGuess http://localhost:'+server.address().port+'/host'));

