'use strict';
const express=require('express'),http=require('http'),{WebSocketServer}=require('ws'),qr=require('qrcode'),crypto=require('crypto');
const runtime=require('../../lib/party-runtime');
const app=express(),server=http.createServer(app),wss=new WebSocketServer({server,path:'/ws'});
const managed=process.env.PARTY_MANAGED==='1',players=new Map(),hosts=new Set();let limit=16,round=null,modifier='',finalResult=null;const controlsForLevel=require('./static/game-contract').controlsForLevel;
const send=(ws,o)=>{if(ws?.readyState===1)ws.send(JSON.stringify(o));};
const controllers=()=>[...players.values()].filter(p=>p.ws?.readyState===1);
const broadcast=(o,targets=wss.clients)=>{for(const ws of targets)send(ws,o);};
function info(){const port=server.address()?.port;return{build:'CHAOS-NODE-5',port,lanIp:'127.0.0.1',joinUrl:process.env.PARTY_JOIN_URL||`http://localhost:${port}/controller`,playerLimit:limit,joined:controllers().length};}
function lobby(){if(round===null)runtime.ui({phase:'waiting',endsAt:null,label:'Общий курсор',currentPlayer:null,progress:controllers().length+' / 16 игроков',actions:[]});broadcast({type:'players',playerLimit:limit,players:[...players.values()].map(p=>({id:p.id,name:p.name,connected:p.ws?.readyState===1,role:p.roles}))},hosts);broadcast({type:'lobby_state',playerLimit:limit,joined:controllers().length,names:controllers().map(p=>p.name)});}
app.use((req,res,next)=>{res.set('Cache-Control','no-store');next();});app.get('/',(req,res)=>res.sendFile(__dirname+'/static/host.html'));app.get('/controller',(req,res)=>res.sendFile(__dirname+'/static/controller.html'));app.get('/api/config',(req,res)=>res.json(info()));app.get('/qr.png',async(req,res)=>res.type('png').send(await qr.toBuffer(info().joinUrl)));app.use('/static',express.static(__dirname+'/static'));
wss.on('connection',(ws,req)=>{const host=new URL(req.url,'http://local').searchParams.get('type')==='host';if(host){hosts.add(ws);send(ws,{type:'config',...info()});}lobby();ws.on('message',raw=>{let d;try{d=JSON.parse(raw);}catch{return;}
if((d.type==='join'||d.type==='resume')&&!host){const identity=runtime.identify(d);if(managed&&!identity)return send(ws,{type:'join_error',message:'Вернитесь в общее лобби для подключения'});let id=identity?.id||d.id||crypto.randomUUID(),p=players.get(id);if(p&&!identity&&p.token!==d.token)return send(ws,{type:'join_error',message:'Неверный ключ игрока'});if(!p){if(players.size>=16)return send(ws,{type:'join_error',message:'Максимум 16 игроков'});const name=String(identity?.name||d.name||'').trim().slice(0,28);if(!name)return send(ws,{type:'join_error',message:'Введи имя'});p={id,name,token:identity?.token||crypto.randomUUID(),roles:round===null?[]:controlsForLevel(round-1)};players.set(id,p);}if(round!==null&&!p.roles.length)p.roles=controlsForLevel(round-1);const old=p.ws;p.ws=ws;ws.player=p;if(old&&old!==ws)old.close(4001,'Identity reconnected');send(ws,{type:'joined',id:p.id,token:p.token,name:p.name,role:p.roles,playerLimit:limit});if(p.roles.length)send(ws,{type:'role',role:p.roles,round,modifier});if(finalResult)send(ws,finalResult);lobby();}
else if(d.type==='input'&&ws.player?.ws===ws){const p=ws.player;if(!p.roles.includes(d.control))return;p.lastInput=Date.now();p.inputs??={};const value=d.control==='move'?{x:Math.max(-1,Math.min(1,Number(d.value?.x)||0)),y:Math.max(-1,Math.min(1,Number(d.value?.y)||0))}:null;p.inputs[d.control]=d.control==='move'?value:d.state==='down';broadcast({type:'input',name:p.name,control:d.control,state:d.state==='down'?'down':'up',value},hosts);}
else if(host&&d.type==='ui'){runtime.ui?.({phase:d.phase,endsAt:d.endsAt||null,label:d.label||'Общий курсор',currentPlayer:null,progress:d.progress||'',actions:[]});}
else if(host&&d.type==='assign_roles'){finalResult=null;round=d.round;modifier=d.modifier;for(const p of players.values()){p.roles=Array.isArray(d.roles?.[p.name])?d.roles[p.name]:[];p.inputs={};send(p.ws,{type:'role',role:p.roles,round,modifier});}lobby();}
else if(host&&d.type==='controller_message'){for(const p of controllers())if(!d.target||p.name===d.target)send(p.ws,{...d,type:'controller_message'});}
else if(host&&d.type==='configure_lobby'){limit=16;send(ws,{type:'lobby_configured',playerLimit:limit});lobby();}
else if(host&&d.type==='reset'){finalResult=null;round=null;for(const p of players.values()){p.roles=[];p.inputs={};}broadcast({type:'reset'});lobby();}
else if(host&&d.type==='results'){finalResult={type:'results',score:Number(d.score)||0,levels:Number(d.levels)||0};for(const p of players.values()){p.roles=[];p.inputs={};send(p.ws,finalResult);}runtime.report({eventId:String(d.eventId),gameId:'chaos',duration:d.duration||0,players:[...players.values()].map(p=>({id:p.id,name:p.name,score:Number(d.score)||0,won:true,metrics:{levels:Number(d.levels)||0,...d.stats?.[p.name]}}))});}
});ws.on('close',()=>{hosts.delete(ws);if(ws.player?.ws===ws){runtime.presence(ws.player.id,false);for(const control of ws.player.roles)broadcast({type:'input',name:ws.player.name,control,state:'up'},hosts);ws.player.ws=null;ws.player.inputs={};lobby();}});});
runtime.setInterval(()=>{for(const p of players.values())if(p.lastInput&&Date.now()-p.lastInput>450){p.lastInput=0;p.inputs={};for(const control of p.roles)broadcast({type:'input',name:p.name,control,state:'up',value:control==='move'?{x:0,y:0}:null},hosts);}},90);
server.listen(Number(process.env.PORT||0),managed?'127.0.0.1':'0.0.0.0',()=>console.log(`CHAOS listening http://127.0.0.1:${server.address().port}/`));

app.use('/assets/fonts',express.static(require('path').resolve(__dirname,'../../public/assets/fonts')));

runtime.onPause(()=>{for(const p of players.values()){p.inputs={};p.lastInput=0;for(const control of p.roles)broadcast({type:"input",name:p.name,control,state:"up",value:control==="move"?{x:0,y:0}:null},hosts);}});
