'use strict';
const R=require('@dimforge/rapier3d-compat');
const WIDTH=.98,LENGTH=3.06,HEIGHT=.56,PITCH=1.02,DT=1/120;
let ready;const init=()=>ready||(ready=R.init());
function createTower(){const engine=new R.World({x:0,y:-9.81,z:0});engine.timestep=DT;engine.numSolverIterations=12;const floor=engine.createRigidBody(R.RigidBodyDesc.fixed().setTranslation(0,-.1,0));engine.createCollider(R.ColliderDesc.cuboid(16,.1,16).setFriction(.8),floor);const blocks=[];
for(let i=0;i<36;i++){const layer=Math.floor(i/3),slot=i%3,odd=layer%2,across=(slot-1)*PITCH,y=(layer+.5)*HEIGHT+.008;const body=engine.createRigidBody(R.RigidBodyDesc.dynamic().setTranslation(odd?across:0,y,odd?0:across).setRotation({x:0,y:odd?Math.SQRT1_2:0,z:0,w:odd?Math.SQRT1_2:1}).setLinearDamping(.12).setAngularDamping(.18).setCcdEnabled(true).setAdditionalSolverIterations(4));engine.createCollider(R.ColliderDesc.cuboid(LENGTH/2,HEIGHT/2,WIDTH/2).setDensity(.6).setFriction(.55).setRestitution(0),body);blocks.push({id:'b'+i,layer,slot,offset:0,sideOffset:0,body,restY:y,grace:0});}
const w={engine,blocks,collapsed:false,acc:0,grip:null,steps:0,tilt:{x:0,z:0},pivot:0,stability:{margin:1,safety:1,level:0}};for(let i=0;i<240;i++)engine.step();sync(w);for(const b of blocks)b.restY=b.position.y;return w;}
function sync(w){for(const b of w.blocks){b.position={...b.body.translation()};b.rotation={...b.body.rotation()};b.velocity={...b.body.linvel()};b.offset=Math.abs(b.layer%2?b.position.z:b.position.x);b.sideOffset=(b.layer%2?b.position.x:b.position.z)-(b.slot-1)*PITCH;}const tilt=Math.max(...w.blocks.map(b=>{const q=b.rotation;return Math.acos(Math.max(-1,Math.min(1,1-2*(q.x*q.x+q.z*q.z))));}));w.stability={margin:Math.max(0,1-tilt),safety:Math.max(0,1-tilt),level:0};}
function select(w,b){if(w.grip?.id===b.id)return;const p=b.body.translation();w.grip={id:b.id,target:{...p},origin:{...p}};}
function applyJoystick(w,b,input,dt){select(w,b);const n=Math.max(1,Math.hypot(input.x||0,input.y||0)),x=(input.x||0)/n,y=(input.y||0)/n,g=w.grip;const along=b.layer%2?'z':'x',side=b.layer%2?'x':'z';g.target[along]+=y*1.25*dt;g.target[along]=Math.max(g.origin[along]-.1,Math.min(g.origin[along]+3.6,g.target[along]));g.target[side]=Math.max(g.origin[side]-3,Math.min(g.origin[side]+3,g.target[side]+x*.8*dt));g.active=!!(x||y);}
function stepPhysics(w,dt,selectedId=null){w.acc+=Math.min(.1,dt);while(w.acc>=DT){w.acc-=DT;for(const b of w.blocks){b.body.resetForces(false);b.body.resetTorques(false);}const b=w.blocks.find(b=>b.id===w.grip?.id);if(b&&w.grip.active){const p=b.body.translation(),v=b.body.linvel(),t=w.grip.target;let force={x:(t.x-p.x)*110-v.x*13,y:(t.y-p.y)*160-v.y*18+9.81*b.body.mass(),z:(t.z-p.z)*110-v.z*13};const mag=Math.hypot(force.x,force.z),cap=72;if(mag>cap){force.x*=cap/mag;force.z*=cap/mag;}force.y=Math.max(-45,Math.min(45,force.y));b.body.addForce(force,true);const along=b.layer%2?'z':'x',side=b.layer%2?'x':'z',lever={...p};lever[along]+=1.2;b.body.addForceAtPoint({x:side==='x'?force.x*.35:0,y:0,z:side==='z'?force.z*.35:0},lever,true);}
w.engine.step();w.steps++;}sync(w);for(const b of w.blocks){if(b.id===selectedId||b.grace>w.steps)continue;const q=b.rotation,up=1-2*(q.x*q.x+q.z*q.z);if(b.layer>0&&(b.position.y<b.restY-.8||up<.35)){w.collapsed=true;break;}}return w.stability;}
function release(w){if(w.grip){w.grip.active=false;const b=w.blocks.find(b=>b.id===w.grip.id);if(b)w.grip.target={...b.body.translation()};}}
function extracted(w,b){if(w.grip?.id!==b.id)return false;const a=b.layer%2?'z':'x';return Math.abs(b.position[a]-w.grip.origin[a])>LENGTH+.08;}
function placeOnTop(w,b){const other=w.blocks.filter(x=>x!==b);let layer=Math.max(...other.map(x=>x.layer)),top=other.filter(x=>x.layer===layer);if(top.length>=3){layer++;top=[];}const slot=[1,0,2].find(s=>!top.some(x=>x.slot===s)),odd=layer%2,y=Math.max(...other.map(x=>x.position.y+HEIGHT/2))+.4;const across=(slot-1)*PITCH;b.layer=layer;b.slot=slot;b.body.setTranslation({x:odd?across:0,y,z:odd?0:across},true);b.body.setRotation({x:0,y:odd?Math.SQRT1_2:0,z:0,w:odd?Math.SQRT1_2:1},true);b.body.setLinvel({x:0,y:0,z:0},true);b.body.setAngvel({x:0,y:0,z:0},true);b.restY=y-.4+HEIGHT/2;b.grace=w.steps+180;w.grip=null;sync(w);}
function candidates(blocks){const top=Math.max(...blocks.map(b=>b.layer));return blocks.filter(b=>b.layer<top-1);}
function serialize(w){return w.blocks.map(({body,...b})=>b);}
module.exports={init,createTower,select,release,applyJoystick,stepPhysics,extracted,placeOnTop,candidates,serialize,WIDTH,LENGTH,HEIGHT};

