'use strict';
const express=require('express'),http=require('http'),{WebSocketServer}=require('ws'),crypto=require('crypto');
const runtime=require('../../lib/party-runtime'),physics=require('./physics');const app=express(),server=http.createServer(app),wss=new WebSocketServer({server,path:'/ws'});app.use('/vendor',express.static(require('path').join(__dirname,'../../node_modules/three/build')));app.get('/host',(_,r)=>r.sendFile(__dirname+'/public/host.html'));app.use(express.static(__dirname+'/public'));
const players=new Map();let phase='lobby',order=[],turnIndex=0,turnId='',selected=null,joystick={x:0,y:0},turnEnds=0,endsAt=0,matchId='',started=0,result=null,reported=false,moves=0,world=null,offlineSince=0,notice='',settleUntil=0,lastInputAt=0;
function resetWorld(){world?.engine?.free();world=physics.createTower();}
const current=()=>players.get(order[turnIndex]);function send(ws,type,data){if(ws.readyState===1)ws.send(JSON.stringify({type,data}));}
function publicState(){return{phase,turnId,inputMagnitude:Math.hypot(joystick.x,joystick.y),settling:!!settleUntil,currentId:current()?.id,selected,turnEnds,endsAt,moves,notice,players:[...players.values()].map(({ws,...p})=>p),blocks:physics.serialize(world),tilt:world.tilt,pivot:world.pivot,stability:{margin:world.stability?.margin,safety:world.stability?.safety,level:world.stability?.level},result,candidates:physics.candidates(world.blocks).map(b=>b.id)};}
function broadcast(){const s=publicState();for(const ws of wss.clients){send(ws,'state',s);if(ws.pid)send(ws,'private',{id:ws.pid,yourTurn:phase==='playing'&&current()?.id===ws.pid,turnId,goal:'Выбери блок. Вниз джойстиком — вытянуть, вверх — вернуть, вбок — сдвиг и давление. Чем дальше палец, тем сильнее движение.'});}}
function nextTurn(){joystick={x:0,y:0};if(world)physics.release(world);offlineSince=0;turnId=crypto.randomUUID();let found=false;for(let i=0;i<order.length;i++){turnIndex=(turnIndex+1)%order.length;if(players.get(order[turnIndex])?.connected){found=true;break;}}if(!found){finish('empty',null);return;}turnEnds=Date.now()+30000;}
function start(){const ps=[...players.values()].filter(p=>p.connected);if(ps.length<2)return;resetWorld();phase='playing';order=ps.map(p=>p.id);turnIndex=-1;selected=null;settleUntil=0;moves=0;notice='Выбери блок ниже двух верхних рядов.';started=Date.now();endsAt=started+240000;matchId=crypto.randomUUID();result=null;reported=false;for(const p of players.values()){p.moves=0;p.skipped=0;p.towerHeight=12;p.participant=p.connected;}nextTurn();}
function finish(reason,loser){if(phase!=='playing')return;phase='finished';joystick={x:0,y:0};physics.release(world);const ps=[...players.values()].filter(p=>p.participant),best=Math.max(0,...ps.map(p=>p.moves));result={reason,loserId:loser?.id||null,title:reason==='collapse'?`${loser?.name||'Игрок'} уронил башню!`:'Башня устояла — считаем успешные ходы.',winners:ps.filter(p=>reason==='collapse'?p!==loser:p.moves===best).map(p=>p.id)};if(!reported){reported=true;runtime.report({gameId:'jenga',eventId:matchId,duration:(Date.now()-started)/1000,players:ps.map(p=>({id:p.id,name:p.name,score:p.moves+(result.winners.includes(p.id)?2:0),won:result.winners.includes(p.id),metrics:{blocks:p.moves,skipped:p.skipped,towerHeight:p.towerHeight,collapsed:p===loser?1:0}}))});}}
wss.on('connection',(ws,req)=>{ws.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return;}if(!m||typeof m!=='object'||Array.isArray(m)||typeof m.type!=='string')return;const d=m.data||{};if(m.type==='host'){const trusted=runtime.managed?req?.headers?.['x-party-local']==='1':['127.0.0.1','::1','::ffff:127.0.0.1'].includes(req?.socket?.remoteAddress);if(trusted)ws.host=true;return;}if(m.type==='join'){const profile=runtime.identify(d,ws);if(runtime.managed&&!profile)return send(ws,'error','Открой главное лобби для входа');const id=profile?.id||String(d.token||crypto.randomUUID());let p=players.get(id);if(!p){if(players.size>=16)return send(ws,'error','Максимум16 игроков');p={id,name:String(profile?.name||d.name||'Игрок').slice(0,24),moves:0,skipped:0,towerHeight:12,participant:phase==='playing'};players.set(id,p);if(phase==='playing')order.push(id);}const previous=p.ws;p.ws=ws;p.connected=true;if(previous&&previous!==ws)previous.close(4001,'Replaced');ws.pid=id;if(current()?.id===id){joystick={x:0,y:0};if(world)physics.release(world);offlineSince=0;}send(ws,'joined',{id,name:p.name});broadcast();return;}if(m.type==='start'&&ws.host){start();broadcast();return;}const p=players.get(ws.pid);if(phase!=='playing'||settleUntil||!p||p.ws!==ws||p.id!==current()?.id||d.turnId!==turnId)return;
if(m.type==='select'){const existing=world.blocks.find(b=>b.id===selected);if(existing&&(existing.offset>.08||Math.abs(existing.sideOffset||0)>.08))return;const b=physics.candidates(world.blocks).find(b=>b.id===d.id);if(b){selected=b.id;physics.select(world,b);joystick={x:0,y:0};notice='Тяни джойстик вниз. Боковое давление раскачивает башню; вверх — вернуть блок.';}}
if(m.type==='joystick'){if(!selected)return;let x=Math.max(-1,Math.min(1,Number(d.x)||0)),y=Math.max(-1,Math.min(1,Number(d.y)||0));const n=Math.hypot(x,y);if(n>1){x/=n;y/=n;}joystick={x,y};if(!x&&!y)physics.release(world);lastInputAt=Date.now();}
});ws.on('close',()=>{const p=players.get(ws.pid);if(p?.ws===ws){p.connected=false;runtime.presence(p.id,false);if(current()?.id===p.id){joystick={x:0,y:0};if(world)physics.release(world);offlineSince=Date.now();}broadcast();}});});
let previous=Date.now();runtime.setInterval(()=>{const now=Date.now(),dt=Math.min(.05,(now-previous)/1000);previous=now;if(!world)return;if(phase==='playing'){if(now-lastInputAt>450){joystick={x:0,y:0};physics.release(world);}const b=world.blocks.find(b=>b.id===selected);if(b&&(joystick.x||joystick.y)){physics.applyJoystick(world,b,joystick,dt);if(b.offset===0&&joystick.y<0)notice='Блок возвращён по длине. Отпусти джойстик, чтобы выбрать другой.';}physics.stepPhysics(world,dt,selected);if(world.collapsed){finish('collapse',current());}else if(b&&physics.extracted(world,b)){physics.placeOnTop(world,b);notice='Блок наверху. Ждём, пока башня успокоится…';selected=null;joystick={x:0,y:0};settleUntil=now+1400;}else if(settleUntil&&now>=settleUntil&&world.stability.margin>=0){settleUntil=0;current().moves++;current().towerHeight=Math.max(...world.blocks.map(b=>b.layer))+1;moves++;notice=`${current().name} добавил блок наверх. Следующий!`;nextTurn();}else if(now>=endsAt){finish('time',null);}else if(!settleUntil&&(now>=turnEnds||(offlineSince&&now-offlineSince>8000))){if(current())current().skipped++;notice='Ход передан. Частично выдвинутый блок можно вернуть или вытянуть.';nextTurn();}}if(phase==='finished')physics.stepPhysics(world,dt,selected);runtime.ui?.({phase:phase==='playing'?'playing':phase==='finished'?'results':'waiting',endsAt:phase==='playing'?turnEnds:null,label:'До передачи хода',currentPlayer:current()?.name||null,progress:moves+' блоков',actions:[]});broadcast();},50);
physics.init().then(()=>{resetWorld();server.listen(Number(process.env.PORT||0),process.env.PARTY_MANAGED==='1'?'127.0.0.1':'0.0.0.0',()=>{const port=server.address().port;console.log('Jenga http://localhost:'+port+'/host');process.send?.({type:'ready',port});});}).catch(e=>{console.error(e);process.exit(1)});

runtime.onPause(()=>{joystick={x:0,y:0};lastInputAt=0;if(world)physics.release(world);});

// Commands from the iPhone server console.
runtime.host({start:()=>{start();broadcast();return phase==='playing';}});
