'use strict';
const express=require('express'),http=require('http'),{WebSocketServer}=require('ws'),qr=require('qrcode'),crypto=require('crypto'),runtime=require('../../lib/party-runtime');
const app=express(),server=http.createServer(app),wss=new WebSocketServer({server,path:'/ws'}),managed=process.env.PARTY_MANAGED==='1';
const track=require('./static/track'),TRACK={width:1600,height:900,roadWidth:track.width,points:track.points},colors=['#FF5C8A','#4CC9F0','#FFD166','#7AE582','#B388FF','#FF9F1C','#00D4AA','#F72585','#90BE6D','#43AA8B','#577590','#F94144'];
const players=new Map(),now=()=>runtime.now()/1000,clamp=(v,a,b)=>Math.max(a,Math.min(b,Number(v)||0)),norm=a=>(a%(2*Math.PI)+2*Math.PI)%(2*Math.PI),wrap=a=>norm(a+Math.PI)-Math.PI;
let status='lobby',laps=5,countdownStarted=0,raceStarted=0,firstFinish=0,finishCounter=0,tick=0,eventId='',resultsAt=0;
const send=(ws,d)=>{if(ws?.readyState===1)ws.send(JSON.stringify(d));};
function reset(p,i,start){const offset=-35-Math.floor(i/2)*48,point=track.at(offset),lane=i%2?20:-20;Object.assign(p,{x:point.x-Math.sin(point.angle)*lane,y:point.y+Math.cos(point.angle)*lane,angle:point.angle,speed:0,vx:0,vy:0,steer:0,throttle:0,next_cp:0,lap:0,lapStarted:start,best_lap:null,last_lap:null,finish_time:null,finish_order:null,boost:0,offroad:false,in_race:true,lastInput:now(),distance:0,boosts:0,collisions:0,lastS:point.s,safeS:point.s,distanceProgress:offset,gatesPassed:0,offroadTime:0,impact:null,lastWallHit:-99});}
function rank(){return [...players.values()].filter(p=>p.in_race).sort((a,b)=>(a.finish_order||999)-(b.finish_order||999)||b.distanceProgress-a.distanceProgress);}
function state(){const ranks=rank();return{type:'state',status,laps,countdown:status==='countdown'?Math.max(0,3-now()+countdownStarted):0,race_time:raceStarted?Math.max(0,(resultsAt||now())-raceStarted):0,tick,track:TRACK,checkpoint_count:track.gates,players:[...players.values()].map(p=>({id:p.id,name:p.name,color:p.color,x:p.x,y:p.y,angle:p.angle,speed:p.speed,connected:p.connected,lap:p.lap,next_cp:p.next_cp,best_lap:p.best_lap,last_lap:p.last_lap,finish_time:p.finish_time,finish_order:p.finish_order,position:ranks.indexOf(p)+1,offroad:p.offroad,impact:p.impact,in_race:p.in_race}))};}
function broadcast(){runtime.ui?.({phase:status==='lobby'?'waiting':status==='racing'?'playing':status,endsAt:status==='countdown'?Date.now()+Math.max(0,3-now()+countdownStarted)*1000:status==='racing'?Date.now()+Math.max(0,(firstFinish?30-(now()-firstFinish):600-(now()-raceStarted)))*1000:null,label:status==='racing'?'Гонка':'Картинг',progress: laps+' кругов',currentPlayer:null,actions:[]});const data=state();for(const ws of wss.clients)send(ws,data);}
function finish(){if(status==='results')return;status='results';resultsAt=now();runtime.report({eventId,gameId:'kart',duration:resultsAt-raceStarted,players:rank().map((p,i)=>({id:p.id,name:p.name,score:Math.max(0,players.size-i)*100,won:i===0,metrics:{laps:p.lap,bestLap:p.best_lap,finishTime:p.finish_time,distance:Math.round(p.distance),boosts:p.boosts,collisions:p.collisions}}))});}
function roadBarrier(p,t){const hit=track.contain(p);p.offroad=false;if(hit&&hit.strength>35&&t-(p.lastWallHit||-99)>.12){p.impact={...hit,time:t-raceStarted,seq:tick};p.lastWallHit=t;p.collisions++;}return hit;}
function step(dt){tick++;const t=now();if(status==='countdown'){if(t-countdownStarted>=3){status='racing';raceStarted=t;for(const p of players.values())p.lapStarted=t;}return;}if(status!=='racing')return;
 for(const p of players.values()){if(!p.in_race)continue;if(!p.connected||p.finish_time!==null||t-p.lastInput>.45){p.throttle=0;p.steer=0;}
 let projection=track.nearest(p.x,p.y);p.offroad=false;
 p.speed=clamp((p.speed+(p.offroad?135:420)*p.throttle*dt)*Math.pow(p.throttle>0?.985:.945,dt*60),0,p.offroad?145:430);p.angle+=p.steer*2.65*clamp(p.speed/160,.08,1)*dt;
 const grip=p.offroad?3.8:Math.abs(p.steer)>.7?5.5:9;p.vx+=(Math.cos(p.angle)*p.speed-p.vx)*Math.min(1,grip*dt);p.vy+=(Math.sin(p.angle)*p.speed-p.vy)*Math.min(1,grip*dt);p.x+=p.vx*dt;p.y+=p.vy*dt;p.distance+=Math.hypot(p.vx,p.vy)*dt;
 roadBarrier(p,t);
 projection=track.nearest(p.x,p.y);p.boost-=dt;if(!p.offroad&&p.boost<=0&&[.07,.40,.68].some(f=>Math.abs(track.delta(f*track.length,projection.s))<34)){p.speed=Math.min(500,p.speed+100);p.boost=1.5;p.boosts++;}
 if(p.finish_time===null&&track.advance(p,projection,dt)){p.lap++;p.last_lap=t-p.lapStarted;p.best_lap=p.best_lap===null?p.last_lap:Math.min(p.best_lap,p.last_lap);p.lapStarted=t;if(p.lap>=laps){p.finish_time=t-raceStarted;p.finish_order=++finishCounter;firstFinish||=t;}}p.next_cp=p.gatesPassed%track.gates;
 }
 const cars=[...players.values()].filter(p=>p.connected);for(let i=0;i<cars.length;i++)for(let j=i+1;j<cars.length;j++){const a=cars[i],b=cars[j],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy);if(d>.01&&d<29){const overlap=(29-d)*.5;a.x-=dx/d*overlap;a.y-=dy/d*overlap;b.x+=dx/d*overlap;b.y+=dy/d*overlap;a.speed*=.97;b.speed*=.97;a.collisions++;b.collisions++;}}
 for(const p of cars)roadBarrier(p,t);
 if((cars.length&&cars.every(p=>p.finish_time!==null))||(firstFinish&&t-firstFinish>30)||t-raceStarted>600)finish();}
function info(){const port=server.address()?.port;return{port,lan_ip:'127.0.0.1',join_url:process.env.PARTY_JOIN_URL||`http://localhost:${port}/controller`,host_url:`http://localhost:${port}/`};}
app.use((req,res,next)=>{res.set('Cache-Control','no-store');next();});app.get('/',(req,res)=>res.sendFile(__dirname+'/static/host.html'));app.get('/controller',(req,res)=>res.sendFile(__dirname+'/static/controller.html'));app.get('/api/info',(req,res)=>res.json(info()));app.get('/qr.png',async(req,res)=>res.type('png').send(await qr.toBuffer(info().join_url)));app.use('/static',express.static(__dirname+'/static'));
wss.on('connection',ws=>{send(ws,state());ws.on('message',raw=>{let d;try{d=JSON.parse(raw);}catch{return;}if(d.type==='join'||d.type==='resume'){const identity=runtime.identify(d);if(managed&&!identity)return send(ws,{type:'resume_error'});const id=identity?.id||(d.type==='resume'?d.player_id:crypto.randomUUID());let p=players.get(id);if(p&&!identity&&p.token!==d.token)return send(ws,{type:'resume_error'});if(!p&&d.type==='resume'&&!identity)return send(ws,{type:'resume_error'});if(!p){if(players.size>=16)return send(ws,{type:'join_error',message:'Максимум 16 игроков'});p={id,token:identity?.token||crypto.randomUUID(),name:String(identity?.name||d.name||'Driver').slice(0,28),color:colors[players.size%colors.length],connected:true,handedness:identity?.hand||d.handedness||'right'};reset(p,players.size,raceStarted||now());players.set(id,p);}const old=p.ws;p.ws=ws;p.connected=true;p.throttle=p.steer=0;ws.player=p;if(old&&old!==ws)old.close(4001,'Identity reconnected');send(ws,{type:'joined',player_id:p.id,token:p.token,name:p.name,color:p.color});broadcast();}
else if(d.type==='input'&&ws.player?.ws===ws){Object.assign(ws.player,{steer:clamp(d.steer,-1,1),throttle:clamp(d.throttle,0,1),lastInput:now()});}
else if(d.type==='set_hand'&&ws.player?.ws===ws)ws.player.handedness=d.handedness==='left'?'left':'right';
else if(d.type==='host_start'&&!ws.player&&[...players.values()].filter(p=>p.connected).length>=2){status='countdown';countdownStarted=now();raceStarted=firstFinish=finishCounter=resultsAt=0;eventId=crypto.randomUUID();[...players.values()].forEach((p,i)=>reset(p,i,countdownStarted+3));broadcast();}
else if(d.type==='host_reset'&&!ws.player){status='lobby';raceStarted=resultsAt=0;[...players.values()].forEach((p,i)=>reset(p,i,now()));broadcast();}
else if(d.type==='host_set_laps'&&!ws.player&&status==='lobby'){laps=Math.round(clamp(d.laps,1,99));broadcast();}});ws.on('close',()=>{if(ws.player?.ws===ws){runtime.presence(ws.player.id,false);ws.player.connected=false;ws.player.ws=null;ws.player.throttle=ws.player.steer=0;broadcast();}});});
let last=now();runtime.setInterval(()=>{const t=now();step(Math.min(.05,t-last));last=t;},1000/60);runtime.setInterval(broadcast,50);server.listen(Number(process.env.PORT||0),managed?'127.0.0.1':'0.0.0.0',()=>console.log(`KART listening http://127.0.0.1:${server.address().port}/`));

app.use('/assets/fonts',express.static(require('path').resolve(__dirname,'../../public/assets/fonts')));

runtime.onPause(()=>{for(const p of players.values()){p.steer=0;p.throttle=0;p.lastInput=0;}});
