'use strict';
const {webkit}=require('playwright'),{spawn}=require('node:child_process'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve('output/playwright/push128');fs.mkdirSync(out,{recursive:true});
const child=spawn(process.execPath,['server.js'],{env:{...process.env,PARTY_EMBEDDED:'1',PARTY_INTERNAL_PORT:'0',PARTY_EPHEMERAL:'1',PARTY_PORT:'0',PARTY_NO_BROWSER:'1',PARTY_ADMIN_KEY:'curtain132'}});let log='',browser;child.stdout.on('data',d=>log+=d);child.stderr.on('data',d=>log+=d);const sleep=ms=>new Promise(r=>setTimeout(r,ms));const report={errors:[],cases:[]};
(async()=>{try{
for(let n=0;n<400&&!/localhost:(\d+)/.test(log);n++)await sleep(50);const origin='http://127.0.0.1:'+log.match(/localhost:(\d+)/)[1];const api=async b=>(await fetch(origin+'/api/manage',{method:b?'POST':'GET',headers:{Authorization:'Bearer curtain132','Content-Type':'application/json'},body:b?JSON.stringify(b):undefined})).json();
browser=await webkit.launch();const tv=await browser.newPage({viewport:{width:1280,height:720}});tv.on('pageerror',e=>report.errors.push(e.message));await tv.goto(origin+'/tv');await sleep(2200);await api({type:'bots-set',count:4});await sleep(400);await api({type:'launch',id:'push'});await sleep(2000);const instance=(await api()).active.instance;for(let i=0;i<60;i++){const r=await api({type:'force-start',instance});if(!r.error)break;await sleep(100);}const frame=tv.frames().find(f=>f.url().includes('/host?'));assert(frame,'party frame');await frame.waitForFunction(()=>typeof state!=='undefined'&&state?.players?.length===4&&window.PushSumoArt?.ready);
await frame.evaluate(()=>{const s=structuredClone(state);s.game.status='playing';s.game.round=100;s.players.forEach((p,i)=>{const a=-Math.PI/2+i*Math.PI/2;p.active=p.alive=true;p.vx=p.vy=0;p.x=s.center.x+Math.cos(a)*180;p.y=s.center.y+Math.sin(a)*180;});visualClock.sample=()=>s;window.__startFixture=s;});await sleep(500);
report.fixture='Real launcher renderer; frozen cardinal spawn positions, zero velocity';report.facing=await frame.evaluate(()=>({center:__startFixture.center,players:window.PartyPushSumoFrame}));for(const p of report.facing.players){const dx=report.facing.center.x-p.x,dy=report.facing.center.y-p.y;assert((Math.sin(p.rotation)*dx-Math.cos(p.rotation)*dy)/Math.hypot(dx,dy)>.9999);}assert.equal(report.facing.players.length,4);await tv.screenshot({path:path.join(out,'start-1280.png')});await tv.setViewportSize({width:1920,height:1080});await sleep(300);await tv.screenshot({path:path.join(out,'start-1920.png')});assert.deepEqual(report.errors,[]);report.ok=true;
}catch(e){report.failure=e.stack;process.exitCode=1;}finally{fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));await browser?.close();child.kill();console.log(JSON.stringify(report));}})();