const fs=require('fs');
let p='games/tanks/server.js',s=fs.readFileSync(p,'utf8');s=s.replace('let bullets = [];','let bullets = [];\nlet combatEffects = [];\nfunction impact(b, heavy=false){combatEffects.push({x:b.x,y:b.y,color:heavy?"#ffb96c":b.color||"#ffdb92",t:heavy?.6:.32,max:heavy?.6:.32});if(combatEffects.length>40)combatEffects.shift();}');s=s.replace('function updateBullets(dt) {','function updateBullets(dt) {\n  combatEffects=combatEffects.filter(e=>(e.t-=dt)>0);');s=s.replace('if (bulletHitsWall(b)) continue;','if (bulletHitsWall(b)) {impact(b);continue;}');s=s.replace('if (!hit) survivors.push(b);','if (hit) impact(b,true);\n    if (!hit) survivors.push(b);');s=s.replace('world: WORLD,','world: WORLD,\n    effects: combatEffects,');s=s.replace('radius:b.radius,color:b.color })),','radius:b.radius,color:b.color,vx:b.vx,vy:b.vy,life:b.life })),');fs.writeFileSync(p,s);
p='games/tanks/public/host.js';s=fs.readFileSync(p,'utf8');let start=s.indexOf('function drawGrid(){'),end=s.indexOf('function drawWalls',start);s=s.slice(0,start)+`let terrainCache;
function drawGrid(){
 if(!terrainCache){terrainCache=document.createElement('canvas');terrainCache.width=1280;terrainCache.height=720;const t=terrainCache.getContext('2d');const g=t.createLinearGradient(0,0,1280,720);g.addColorStop(0,'#273831');g.addColorStop(.5,'#192927');g.addColorStop(1,'#17252e');t.fillStyle=g;t.fillRect(0,0,1280,720);
 for(let i=0;i<460;i++){const x=(i*197)%1280,y=(i*113)%720;t.fillStyle=i%3?'#bed0b008':'#030e1715';t.fillRect(x,y,2+i%9,1+i%3);}
 t.strokeStyle='#bcc8b009';t.lineWidth=1;for(let x=0;x<1280;x+=80){t.beginPath();t.moveTo(x,0);t.lineTo(x,720);t.stroke();}for(let y=0;y<720;y+=80){t.beginPath();t.moveTo(0,y);t.lineTo(1280,y);t.stroke();}
 const v=t.createRadialGradient(640,360,80,640,360,750);v.addColorStop(0,'#00000000');v.addColorStop(1,'#02081399');t.fillStyle=v;t.fillRect(0,0,1280,720);}
 ctx.drawImage(terrainCache,0,0);
}
function drawCombatEffects(effects){for(const e of effects||[]){const t=1-e.t/e.max;ctx.save();ctx.translate(e.x,e.y);ctx.globalAlpha=(1-t)*(1-t);ctx.strokeStyle=e.color;ctx.lineWidth=3*(1-t)+1;ctx.beginPath();ctx.arc(0,0,4+36*(1-(1-t)**3),0,Math.PI*2);ctx.stroke();for(let i=0;i<9;i++){const a=i*2.399,r=8+55*t;ctx.strokeStyle=i%2?'#fff3c7':e.color;ctx.beginPath();ctx.moveTo(Math.cos(a)*r,Math.sin(a)*r);ctx.lineTo(Math.cos(a)*(r+12*(1-t)),Math.sin(a)*(r+12*(1-t)));ctx.stroke();}ctx.restore();}}
`+s.slice(end);s=s.replace("ctx.fillStyle='rgba(255,255,255,.035)';ctx.fillRect", "ctx.fillStyle='rgba(221,239,224,.20)';ctx.fillRect");s=s.replace('drawCenterMessage(s.game);','drawCombatEffects(s.effects);\n    drawCenterMessage(s.game);');fs.writeFileSync(p,s);
p='games/tankarena/server.js';s=fs.readFileSync(p,'utf8');s=s.replace('p.hp-=b.damage;','p.hp-=b.damage;effects.push({x:b.x,y:b.y,t:.25,color:"#ffe2a2"});if(effects.length>48)effects.shift();');fs.writeFileSync(p,s);
