const fs=require('fs'),path=require('path');
const dir='.superdesign/init';fs.mkdirSync(dir,{recursive:true});
const read=f=>fs.readFileSync(f,'utf8'),code=f=>'\n## '+f+'\n```\n'+read(f)+'\n```\n';
const files={
 'components.md':'# Components\nVanilla DOM, no framework. Buttons/cards/dialogs built in public/app.js; shared game controls use CSS and bridge.\n'+code('public/app.js')+code('public/game-polish.css'),
 'layouts.md':'# Layouts\nShared host/player shell branches on PARTY_HOST_KEY and active match. Complete shell:\n'+code('public/index.html'),
 'routes.md':'# Routes\n/ = mobile player onboarding + lobby/controller. /host = local computer host catalog + active game iframe. /games/{id}/* = proxied game-specific pages from catalog. Shared shell source public/index.html + public/app.js.\n'+code('catalog.json'),
 'theme.md':'# Current tokens\nCurrent light bg #f2f1e9, ink #263326, accent #c8ff73 desired. Old Arial. Breakpoints700,1100,1500. User approved wholesale dark glass redesign: #0b0e12 canvas, #151b22 opaque reading surfaces, lime #c8ff73 controls, violet/cyan glow, 16px body, Rubik normal/bold/italic, radius24cards/18panels/pillchips.\n'+code('public/style.css')+code('public/refresh.css'),
 'pages.md':'# Dependency trees\n/ and /host\n- public/index.html\n  - public/style.css\n  - public/refresh.css\n  - public/app.js\n- server.js injects profile/host boot + catalog\nActive child iframe\n- /games/{id}/host or player\n  - public/bridge.js injected globally\n  - public/game-polish.css injected globally\n- lib/party-runtime.js publishes gamephase/deadline\nNew target: shared compact dark gameplay HUD and bento catalog overhaul.\n',
 'extractable-components.md':'# Extractable components\nNo framework layout components: current monolithic HTML is being replaced under approved design. Shared button/card primitives are inline. New shared top navigation/timer/ranking sheets will be authored in dark shell, not extracted from obsolete light layout.\n'
};for(const [name,value]of Object.entries(files))fs.writeFileSync(path.join(dir,name),value);
fs.writeFileSync('.superdesign/design-system.md','# Local Party — approved direction\nDark playful premium LAN party UI, text logo localparty unchanged. 20 colorful toy-3D game emblems on dark cards, huge fadingwhite numbers, frosted lowergradient text and limepillCTA. Asymmetric bento with one large featuredtank card, slow aurora/metaballbackground. Sidebar lively avatars and globaltop. Single compact mobile gameplay header: playerleft, highcontrast timercenter, topbuttonright. Host persistentjoinQR, alwaysvisibleleaderboard. 16px+ body; bolditalicRubik hero and highcontrast headings. Shared UI chrome in everygame, gamefields remain individual. All screens Russian, values/controls legible, heldpress .96 and easedrelease. Design desktopcatalog plus mobileplaycontroller, quizhost,navalphone and results as connectedflow.\n');
