from pathlib import Path
import json,hashlib,html
root=Path('output/playwright/keyboard243');before=json.loads((root/'browser-before/report.json').read_text());after=json.loads((root/'browser-after/report.json').read_text());host=json.loads((root/'host-after/report.json').read_text())
labels={'room-rename':'Название своей комнаты + подтверждение','room-code':'6 цифр кода + Connect','profile-name':'Имя профиля + Save / Back','catalog-search':'Поиск игр'}
comments={'room-rename':'Поле и галочка видны одновременно. Черновик сохраняется при очередном обновлении соседних комнат. Во время ввода вторичные Players / Rankings освобождают место; после клавиатуры возвращаются.','room-code':'Все шесть ячеек, Connect и Back помещаются в видимую область. Ввод переводит фокус вперёд, удаление пустой ячейки — назад. Блок создания своей онлайн-комнаты временно освобождает место для ввода.','profile-name':'Имя автоматически видно в прокручиваемой области. Save и Back закреплены выше границы клавиатуры. Остальные настройки остаются доступны внутренней прокруткой.','catalog-search':'Поле автоматически оказывается в видимой области, сохраняя положение и материал шапки.'}
css='''*{box-sizing:border-box}body{margin:0;background:#110d1b;color:#f1e6ff;font:16px/1.55 system-ui,sans-serif}main{max-width:1260px;margin:auto;padding:30px 22px}h1{font-size:32px;line-height:1.15}h2{margin-top:48px}p{max-width:920px}a{color:#caaaef}button{background:#31243e;color:#ede2ff;border:1px solid #ad8bce77;border-radius:24px;padding:9px 16px;cursor:pointer}button.active{color:#d7ffa0;border-color:#d7ffa0}nav{display:flex;gap:9px;flex-wrap:wrap;margin:20px 0}.note{background:#261d36;border:1px solid #8e76ad55;padding:16px 20px;border-radius:20px}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:22px}.card{background:#20182c;border:1px solid #ac8fcd44;border-radius:22px;padding:16px}.pair{display:grid;grid-template-columns:1fr 1fr;gap:12px}.solo{max-width:280px;margin:auto}.shot{display:block;position:relative;line-height:0}.shot img{display:block;width:100%;border-radius:12px}.edge{position:absolute;left:0;right:0;border-top:2px dashed #b6ed7888;pointer-events:none}.caption{font-size:13px;color:#cdbee0;margin:8px 0}.status{color:#d4ff9f}.tag{font-size:12px;letter-spacing:.04em;color:#bbaecc}details{margin:10px 0}summary{cursor:pointer}.card[hidden]{display:none}.report{display:flex;gap:14px;flex-wrap:wrap}footer{margin:36px 0;color:#c7b4dc;font-size:13px}'''
parts=[f'<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>HeyPals — keyboard243</title><style>{css}</style></head><body><main><h1>Поля над клавиатурой — проверка 243</h1><p>Общий обработчик оставляет поле и подтверждение в видимой части экрана. Материал 93%, размытие 8px, зелёные действия и светлая кнопка Back сохранены.</p><div class="note"><b>Разные виды доказательств.</b> Браузерные снимки ниже моделируют доступную высоту при клавиатуре: сама клавиатура не нарисована. Пунктир отмечает её верхнюю границу. Настоящий WKWebView Simulator проверен отдельно с фокусом, однако вызвать настоящую программную клавиатуру не удалось. Эти снимки не подтверждают поведение физического iPhone или AirPlay.</div><p class="report"><span>Пульт: <b class="status">32/32</b></span><span>Native host: <b class="status">24/24</b></span><span>Ошибки JS: <b class="status">0</b></span><a href="browser-before/report.json">Baseline: 17 нарушений границы</a><a href="browser-after/report.json">Отчёт пульта</a><a href="host-after/report.json">Отчёт хоста</a></p><nav id="filters"><button class="active" data-filter="all">Все 56 состояний</button><button data-filter="393">393px</button><button data-filter="320">320px</button><button data-filter="webkit">WebKit</button><button data-filter="chromium">Chrome</button><button data-filter="overlay">Клавиатура поверх layout</button><button data-filter="resize">Layout уменьшается</button></nav><h2>Пульт: до / после</h2><p>Настоящий маршрут /play с controller-bridge.js и tabs.js. Комнаты — явно заданные QA-данные; подключение по интернету не имитируется.</p><section class="cards">']
lookup={(r['engine'],r['width'],r['mode'],r['name']):r for r in before['rows']}
def shot(folder,row):
 frac=row['bottom']/row['innerHeight']*100
 return f'<a href="{folder}/{row["file"]}" class="shot"><img loading="lazy" src="{folder}/{row["file"]}" alt="{labels[row["name"]]}"><span class="edge" style="top:{frac:.4f}%"></span></a>'
for r in after['rows']:
 b=lookup[(r['engine'],r['width'],r['mode'],r['name'])];tags=f'{r["engine"]} {r["width"]} {r["mode"]}'
 parts.append(f'<article class="card" data-tags="{tags}"><div class="tag">{tags} · доступно {round(r["bottom"])}px</div><h3>{labels[r["name"]]}</h3><div class="pair"><div>{shot("browser-before",b)}<p class="caption">До</p></div><div>{shot("browser-after",r)}<p class="caption">После · проверено визуально</p></div></div><p>{comments[r["name"]]}</p></article>')
parts.append('</section><h2>Приложение: native host</h2><p>Источник главного native-меню с его действительными tabs. У хоста нет controller-bridge в production, поэтому его не добавляли в этот fixture. На всех 24 снимках проверены размеры, clipping и изображение.</p><section class="cards">')
for r in host['rows']:
 tags=f'{r["engine"]} {r["width"]} {r["mode"]}'
 parts.append(f'<article class="card" data-tags="{tags}"><div class="tag">{tags} · доступно {round(r["bottom"])}px</div><h3>{labels[r["name"]]}</h3><div class="solo">{shot("host-after",r)}</div><p>{comments[r["name"]]}</p></article>')
parts.append('</section><h2>Настоящий Simulator WKWebView</h2><p>iPhone 17 / 402×874pt. Baseline: установленный Simulator 145. After: тот же WKWebView с инъекцией нового исходного JS/CSS через opt-inDEBUG audit; нативный executable не заменялся. Фокус настоящий, однако visualViewport остался 874px — программной клавиатуры нет. Before/after имена и соседние комнаты являются QA-данными и могут обновляться Bonjour.</p><section class="cards">')
for file,title,comment in [('simulator145-before-rename-expanded.png','Baseline: раскрытая своя комната','До исправления, текущий bundle. Фокус имени задан; программная клавиатура не показалась.'),('simulator145-after-source-rename.png','Новый source: название комнаты','Поле и галочка видны; раскрытие и материал проверены в действительном WKWebView. Без клавиатуры.'),('simulator145-after-source-code.png','Новый source: By Code','Фокус прошёл до шестой ячейки; цифры и Connect корректны. Без клавиатуры.'),('simulator145-after-source-profile.png','Новый source: профиль','Имя, Save и Back выровнены. У материала alpha .93, на фоновых ветвях blur 8px. Без клавиатуры.'),('simulator145-after-source-search.png','Новый source: поиск','После закрытия профиля нет остаточного размытия; фокус поиска виден. Без клавиатуры.')]:
 parts.append(f'<article class="card"><h3>{title}</h3><div class="solo"><a class="shot" href="{file}"><img loading="lazy" src="{file}" alt="{title}"></a></div><p>{comment}</p></article>')
parts.append('</section><footer>Проверка 243: 2026-10-07.55 ms close/reopen, быстрое раскрытие/сворачивание, сохранение черновика, ввод/удаление кода и очистка blur проходят в browser regression. Это не измерение скорости реального AirPlay.</footer></main><script>document.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-filter]").forEach(n=>n.classList.toggle("active",n===b));document.querySelectorAll("[data-tags]").forEach(n=>n.hidden=b.dataset.filter!=="all"&&!n.dataset.tags.split(" ").includes(b.dataset.filter))})</script></body></html>')
(root/'index.html').write_text(''.join(parts))
files=['public/input-viewport.js','public/input-viewport.css','public/native-shell/nearby-rooms.js','public/index.html','public/native-shell/index.html','server.js']
manifest={'date':'2026-10-07','controller':{'reviewed':32,'baselineViewportFailures':17,'afterFailures':0,'bridgeAndTabs':True},'host':{'reviewed':24,'failures':0,'actualHostTabsOnly':True},'simulator':{'reviewed':5,'softwareKeyboardShown':False,'sourceInjectedAfter':True,'bundle':145},'contactsReviewed':[f'{folder}/review-{engine}-{width}.jpg' for folder in ['browser-before','browser-after','host-after'] for engine in ['webkit','chromium'] for width in [320,393]]+['review-simulator145.jpg'],'sourceSha256':{f:hashlib.sha256(Path(f).read_bytes()).hexdigest() for f in files},'limits':['No genuine Simulator software keyboard','No physical iPhone/AirPlay evidence from this lane','Internet service not connected']}
(root/'visual-review.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2))
