'use strict';
// Offline, Node-only portable distribution builder. Verify before replacing a release.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),zlib=require('node:zlib'),AdmZip=require('adm-zip'),tar=require('tar-stream');
const ROOT=path.resolve(__dirname,'..'),CACHE=path.join(ROOT,'runtime-cache'),DIST=path.join(ROOT,'dist'),prefix='LOCAL_PARTY/';
const targets=['windows-x64','macos-arm64','macos-x64'];
const VERSION=JSON.parse(fs.readFileSync(path.join(ROOT,'package.json'),'utf8')).version;
const GAME_COUNT=26;
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const excluded=new Set(['__pycache__','.git','.DS_Store','tests','test','.cache','data-local']);
const include=name=>!/(^|\/)(certs|[.]certificates|[.]superdesign|data)(\/|$)/.test(name)&&!/(^|\/)[.]env($|[.])/.test(name)&&!/[.](pem|key|pfx|p12)$/i.test(name)&&!/(^|\/)public\/assets\/games\/premium-v2\/sources(\/|$)/.test(name)&&!/(^|\/)public\/assets\/games\/flat-test(\/|$)/.test(name)&&!/(^|\/)public\/assets\/gameplay\/sources(\/|$)/.test(name)&&!/(^|\/)public\/assets\/gameplay\/[^/]+-source[.]png$/.test(name)&&!name.split('/').some(p=>excluded.has(p))&&!/\.(py|pyc|pyo|whl)$/.test(name)&&!/[.]test[.]|[.]spec[.]/.test(name)&&!['requirements.txt','.complete.json'].includes(path.basename(name))&&!(name.startsWith('games/')&&/\.(bat|command|sh)$/.test(name));
function walk(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>{const f=path.join(dir,e.name),rel=path.relative(ROOT,f).replaceAll('\\','/');if(!include(rel))return [];return e.isDirectory()?walk(f):e.isFile()?[f]:[];});}
const modes=new Map();
function add(zip,name,bytes,mode=0o644){zip.addFile(prefix+name,Buffer.from(bytes));modes.set(prefix+name,mode);}
async function runtime(zip,file){const allowed=new Set(['node.exe','bin/node','LICENSE','README.md','CHANGELOG.md']);if(file.endsWith('.zip')){for(const e of new AdmZip(file).getEntries()){const rel=e.entryName.split('/').slice(1).join('/');if(!e.isDirectory&&allowed.has(rel))add(zip,'runtime/node/'+rel,e.getData(),rel==='node.exe'?0o755:0o644);}return;}
 await new Promise((resolve,reject)=>{const extract=tar.extract();extract.on('entry',(header,stream,next)=>{const rel=header.name.split('/').slice(1).join('/'),chunks=[];stream.on('data',b=>{if(allowed.has(rel))chunks.push(b);});stream.on('end',()=>{if(header.type==='file'&&allowed.has(rel))add(zip,'runtime/node/'+rel,Buffer.concat(chunks),header.mode);next();});stream.on('error',reject);});extract.on('finish',resolve);extract.on('error',reject);const source=fs.createReadStream(file),gunzip=zlib.createGunzip();source.on('error',reject);gunzip.on('error',reject);source.pipe(gunzip).pipe(extract);});}
function verify(file,target){const zip=new AdmZip(file);if(!zip.test())throw Error('ZIP checksum failure');const catalog=JSON.parse(zip.readAsText(prefix+'catalog.json'));if(JSON.parse(zip.readAsText(prefix+'package.json')).version!==VERSION||JSON.parse(zip.readAsText(prefix+'package-lock.json')).version!==VERSION)throw Error('Release version mismatch');if(catalog.length!==GAME_COUNT)throw Error('Release requires '+GAME_COUNT+' games');const node=target.startsWith('windows')?'runtime/node/node.exe':'runtime/node/bin/node',launcher=target.startsWith('windows')?'START_WINDOWS.bat':'START_MAC.command';for(const name of [node,launcher,'server.js','lib/party-runtime.js','public/glass.css','public/assets/fonts/Rubik.ttf','node_modules/@dimforge/rapier3d-compat/dist/rapier_wasm3d_bg.wasm','node_modules/@dimforge/rapier2d-compat/dist/rapier_wasm2d_bg.wasm',...catalog.map(g=>'public/assets/games/'+g.id+'.webp')])if(!zip.getEntry(prefix+name))throw Error('Missing '+name);for(const e of zip.getEntries())if(!include(e.entryName)||e.entryName.includes('/runtime/python/'))throw Error('Unexpected file '+e.entryName);for(const name of ['server.js','catalog.json','public/app.js','public/glass.css','public/ux.css','public/bridge.js','public/game-clock-client.js','public/test-bot.js','public/catalog-previews.js','public/catalog-previews.css','lib/session-controls.js','lib/game-clock.js','lib/party-runtime.js'])if(!zip.readFile(prefix+name).equals(fs.readFileSync(path.join(ROOT,name))))throw Error('Stale '+name);if(target.startsWith('macos'))for(const name of [node,launcher])if(!((zip.getEntry(prefix+name).header.attr>>>16)&0o111))throw Error('Executable bit absent '+name);return {bytes:fs.statSync(file).size,sha256:sha(fs.readFileSync(file))};}
(async()=>{const args=process.argv.slice(2),selected=args.includes('--target')?[args[args.indexOf('--target')+1]]:targets;if(selected.some(t=>!targets.includes(t)))throw Error('Unknown target');const manifest=JSON.parse(fs.readFileSync(path.join(CACHE,'manifest.json'),'utf8'));for(const target of selected){const node=manifest[target].node;if(sha(fs.readFileSync(path.join(CACHE,node.file)))!==node.sha256)throw Error('Node runtime hash mismatch '+target);}if(args.includes('--prepare'))return console.log('Verified cached Node runtimes');fs.mkdirSync(DIST,{recursive:true});for(const target of selected){console.log('Packaging '+target);modes.clear();const zip=new AdmZip();for(const name of ['server.js','catalog.json','package.json','package-lock.json','README.md','RELEASE_NOTES.md','ARCHIVE_AUDIT.md']){let b=fs.readFileSync(path.join(ROOT,name));if(name==='package.json'){const p=JSON.parse(b);p.scripts={start:'node server.js'};delete p.devDependencies;b=Buffer.from(JSON.stringify(p,null,2));}add(zip,name,b);}const launcher=target.startsWith('windows')?'START_WINDOWS.bat':'START_MAC.command';add(zip,launcher,fs.readFileSync(path.join(ROOT,launcher)),0o755);for(const folder of ['public','games','lib','node_modules','licenses'])if(fs.existsSync(path.join(ROOT,folder)))for(const f of walk(path.join(ROOT,folder)))add(zip,path.relative(ROOT,f).replaceAll('\\','/'),fs.readFileSync(f));await runtime(zip,path.join(CACHE,manifest[target].node.file));add(zip,'RUNTIME_MANIFEST.json',JSON.stringify({version:VERSION,node:manifest[target].node},null,2));for(const entry of zip.getEntries()){entry.header.made=(3<<8)|20;entry.header.attr=((0o100000|(modes.get(entry.entryName)||0o644))<<16)>>>0;}const dest=path.join(DIST,'LOCAL_PARTY_'+VERSION+'_'+target+'.zip'),pending=dest+'.building';zip.writeZip(pending);const result=verify(pending,target);fs.renameSync(pending,dest);fs.writeFileSync(dest+'.sha256',result.sha256+'  '+path.basename(dest)+'\n');console.log(JSON.stringify({file:dest,...result}));}})().catch(e=>{console.error(e);process.exitCode=1;});

