'use strict';
// Real embedded server, real bot controllers and one real phone. Browser-only
// workload for shared canvas/layout hot paths; no synthetic match state.
const {spawn}=require('node:child_process'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium,webkit}=require(process.env.PARTY_PLAYWRIGHT||'playwright');
const root=path.resolve(__dirname,'..'),game=process.env.GAME||'pocket_siege',engine=process.env.QA_ENGINE||'chromium',out=path.resolve(process.env.QA_OUTPUT||'output/playwright/performance244/deluxe/'+game),wait=ms=>new Promise(r=>setTimeout(r,ms));fs.mkdirSync(out,{recursive:true});
const child=spawn(process.execPath,['server.js'],{cwd:root,env:{...process.env,PARTY_EMBEDDED:'1',PARTY_EPHEMERAL:'1',PARTY_NO_BROWSER:'1',PARTY_ADMIN_KEY:'deluxe244',PARTY_PORT:'0'}});let log='',browser,base;child.stdout.on('data',b=>log+=b);child.stderr.on('data',b=>log+=b);
async function until(fn,label){for(let i=0;i<400;i++){if(await fn())return;await wait(50);}throw Error(label+' '+log.slice(-800));}
async function api(body){const r=await fetch(base+'/api/manage',{method:body?'POST':'GET',headers:{Authorization:'Bearer deluxe244','Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const s=await r.json();assert.equal(r.status,200,JSON.stringify(s));return s;}
(async()=>{try{
 await until(()=>/localhost:(\d+)/.test(log),'server');base='http://127.0.0.1:'+log.match(/localhost:(\d+)/)[1];await api({type:'server-start'});
 browser=await(engine==='webkit'?webkit:chromium).launch({headless:true,...(engine==='chromium'?{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}:{})});
 const tv=await browser.newPage({viewport:{width:3840,height:2160}}),phone=await browser.newPage({viewport:{width:393,height:852},isMobile:true,hasTouch:true,deviceScaleFactor:3}),errors=[];
 for(const p of[tv,phone]){p.on('pageerror',e=>errors.push(e.message));if(process.env.PERF_SOURCE_DIR)await p.route(/\/games\/(?:pocket_siege|marble_bloom)\/(render|host|controller|pocket-deck)\.js(?:\?.*)?$/,async route=>{const f=path.join(process.env.PERF_SOURCE_DIR,new URL(route.request().url()).pathname.split('/').at(-1));await route.fulfill({path:f,contentType:'application/javascript'});});await p.addInitScript(()=>{window.__familyPerf={rects:{},mutations:0,frames:[],measureText:0,clears:0,snapshots:0};const rect=Element.prototype.getBoundingClientRect;Element.prototype.getBoundingClientRect=function(...args){const key=this.id||this.className||this.tagName;__familyPerf.rects[key]=(__familyPerf.rects[key]||0)+1;return rect.apply(this,args);};const clear=CanvasRenderingContext2D.prototype.clearRect;CanvasRenderingContext2D.prototype.clearRect=function(...args){if(this.canvas.id==='game')__familyPerf.clears++;return clear.apply(this,args);};const measure=CanvasRenderingContext2D.prototype.measureText;CanvasRenderingContext2D.prototype.measureText=function(...args){__familyPerf.measureText++;return measure.apply(this,args);};addEventListener('DOMContentLoaded',()=>new MutationObserver(r=>__familyPerf.mutations+=r.length).observe(document.body,{subtree:true,attributes:true,childList:true,characterData:true}));let last;requestAnimationFrame(function sample(t){if(last)__familyPerf.frames.push(t-last);last=t;requestAnimationFrame(sample);});});}
 await phone.addInitScript({content:'window.__partyPersistentTabs=true;window.webkit={messageHandlers:{partyShell:{postMessage(){}}}};'+fs.readFileSync(path.join(root,'public/native-shell/controller-bridge.js'),'utf8')+'\n'+fs.readFileSync(path.join(root,'public/native-shell/tabs.js'),'utf8')});
 await tv.goto(base+'/tv');await until(async()=>(await api()).screens===1,'TV');await phone.goto(base+'/play');await phone.locator('#name').fill('Family 243');await phone.locator('#joinForm button[type=submit]').click();await phone.locator('#home').waitFor();await api({type:'bots-set',count:game==='marble_bloom'?2:game==='pocket_siege'?5:3});await wait(600);
 const run=(await api({type:'launch',id:game})).active;await phone.waitForFunction(()=>!document.querySelector('#readyButton').disabled);await phone.locator('#readyButton').click();await until(async()=>(await api()).active?.ui?.phase==='playing','playing');await wait(2200);
 const frame=tv.frames().find(f=>f.url().includes('/games/'+game+'/'));assert(frame,'actual game frame');
 const session=engine==='chromium'?await tv.context().newCDPSession(tv):null;if(session)await session.send('Performance.enable');const phoneSession=engine==='chromium'?await phone.context().newCDPSession(phone):null;if(phoneSession)await phoneSession.send('Performance.enable');const metrics=async(target=session)=>target?Object.fromEntries((await target.send('Performance.getMetrics')).metrics.map(m=>[m.name,m.value])):{};
 const phoneFrame=phone.frames().find(f=>f.url().includes('/games/'+game+'/'));assert(phoneFrame,'real native controller frame');for(const f of[tv.mainFrame(),frame,phoneFrame])await f.evaluate(()=>{__familyPerf={rects:{},mutations:0,frames:[],measureText:0,clears:0,snapshots:0};});const before=await metrics(),phoneBefore=await metrics(phoneSession);await wait(6000);const after=await metrics(),phoneAfter=await metrics(phoneSession);
 const surfaces=[];for(const[label,f]of[['tv',tv.mainFrame()],['game',frame],['phone',phoneFrame]])surfaces.push(await f.evaluate(label=>{const p=__familyPerf,frames=p.frames.sort((a,b)=>a-b);return{label,rects:p.rects,mutations:p.mutations,measureText:p.measureText,clears:p.clears,frames:frames.length,p95:frames[Math.floor(frames.length*.95)],canvas:[...document.querySelectorAll('canvas')].map(c=>({id:c.id,width:c.width,height:c.height,clientWidth:c.clientWidth,clientHeight:c.clientHeight}))};},label));
 await tv.screenshot({path:path.join(out,'tv-playing.png')});await phone.screenshot({path:path.join(out,'phone-playing.png')});
 await api({type:'pause',paused:true});await tv.locator('#paused').waitFor();await phone.locator('#pauseOverlay').waitFor();await wait(1000);
 const pausedFirst=await frame.evaluate(()=>document.querySelector('#game').toDataURL());
 for(const f of[tv.mainFrame(),frame,phoneFrame])await f.evaluate(()=>{__familyPerf={rects:{},mutations:0,frames:[],measureText:0,clears:0,snapshots:0};});const pauseBefore=await metrics();await wait(3000);const pauseAfter=await metrics();
 const paused=await frame.evaluate(()=>({clears:__familyPerf.clears,measureText:__familyPerf.measureText,mutations:__familyPerf.mutations,raf:window.__arcadeRenderer.raf,t:window.__arcadeRenderer.s.t,key:JSON.stringify(window.__arcadeRenderer.s),width:document.querySelector('#game').width,height:document.querySelector('#game').height,clock:window.__arcadeRenderer.juice.clock}));
 paused.pixelEqual=pausedFirst===await frame.evaluate(()=>document.querySelector('#game').toDataURL());delete paused.key;assert(paused.pixelEqual,'Paused output remains pixel-identical');if(process.env.EXPECT_PAUSED_PARK==='1'){assert.equal(paused.clears,0,'Stable server-paused canvas does not repaint');assert.equal(paused.raf,0,'Paused presentation loop parks');}
 paused.phone=await phoneFrame.evaluate(()=>({mutations:__familyPerf.mutations,clock:document.querySelector('#clock').textContent,disabled:document.querySelector('#tankFire').disabled||document.querySelector('#marbleFire').disabled}));
 paused.cpu=Object.fromEntries(['TaskDuration','ScriptDuration','LayoutDuration','RecalcStyleDuration','LayoutCount','RecalcStyleCount'].map(k=>[k,pauseAfter[k]-pauseBefore[k]]));
 await tv.screenshot({path:path.join(out,'tv-paused.png')});await phone.screenshot({path:path.join(out,'phone-paused.png')});
 await tv.setViewportSize({width:1280,height:720});await wait(350);
 const resize=await frame.evaluate(()=>{const c=document.querySelector('canvas'),r=window.__arcadeRenderer,box=c?.getBoundingClientRect();return{viewport:[innerWidth,innerHeight],canvas:c?{width:c.width,height:c.height,clientWidth:c.clientWidth,clientHeight:c.clientHeight}:null,actualRect:box?{width:box.width,height:box.height}:null,cachedRect:r?.surfaceRect?{width:r.surfaceRect.width,height:r.surfaceRect.height}:null,dpr:r?.surfaceDpr??Math.min(1.5,devicePixelRatio||1)};});
 if(['pocket_siege','marble_bloom'].includes(game)){if(!process.env.PERF_SOURCE_DIR)assert(Math.abs(resize.cachedRect.width-resize.canvas.clientWidth)<2,'ResizeObserver invalidates actual canvas geometry');assert.equal(resize.canvas.width,Math.round(resize.canvas.clientWidth*resize.dpr),'Backing density remains unchanged');}
 await api({type:'pause',paused:false});await tv.locator('#paused').waitFor({state:'hidden'});await wait(200);const resumed=await frame.evaluate(()=>({raf:window.__arcadeRenderer.raf,t:window.__arcadeRenderer.s.t,clears:__familyPerf.clears,clock:window.__arcadeRenderer.juice.clock}));assert(resumed.raf>0,'Resume restarts presentation');assert(resumed.t>paused.t,'Authoritative simulation resumes');
 const input=await phoneFrame.evaluate(isTank=>{const net=window.__arcadeConnection,s=window.__arcadeState,me=s.players.find(p=>p.id===net.id);return{sent:net.send('aim',isTank?{angle:53,power:61}:{x:903,y:233}),id:me.id,was:{angle:me.angle,power:me.power,aim:me.aim},active:s.activeId};},game==='pocket_siege');await wait(150);input.after=await frame.evaluate(id=>{const p=window.__arcadeRenderer.s.players.find(p=>p.id===id);return{angle:p.angle,power:p.power,aim:p.aim};},input.id);assert(input.sent,'Actual connected controller sends immediate input');if(game==='pocket_siege'&&input.active===input.id){assert.equal(input.after.angle,53);assert.equal(input.after.power,61);}else if(game==='marble_bloom'){assert.equal(input.after.aim.x,903);assert.equal(input.after.aim.y,233);}
 assert.equal((await api()).active.instance,run.instance,'Resize/pause does not restart match');assert.equal(errors.length,0,errors.join('\n'));
 const environment=await frame.evaluate(()=>({reduced:window.__arcadeRenderer.reduced,visibility:document.visibilityState,devicePixelRatio,rendererMode:window.__arcadeRenderer.s?.mode,nativeRoute:document.documentElement.className}));const report={game,sourceDir:process.env.PERF_SOURCE_DIR||'production',environment,engine:'desktop '+engine,method:'Actual worker/TV3840x2160/native bridge+tabs phone+real bots, six seconds playing and three seconds paused',surfaces,cpu:Object.fromEntries(['TaskDuration','ScriptDuration','LayoutDuration','RecalcStyleDuration','LayoutCount','RecalcStyleCount'].map(k=>[k,after[k]-before[k]])),phoneCpu:Object.fromEntries(['TaskDuration','ScriptDuration','LayoutDuration','RecalcStyleDuration','LayoutCount','RecalcStyleCount'].map(k=>[k,phoneAfter[k]-phoneBefore[k]])),paused,resize,resumed,input,errors};fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{await browser?.close();child.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
