// Performance 243: isolated real worker, 4K TV + controller, attributed hot paths.
// Set PARTY_PLAYWRIGHT to a Playwright module path if it is not installed locally.
// GAME=kart (default) or tankarena; REPORT optionally saves the measurements.
const {spawn}=require('node:child_process'),fs=require('node:fs'),assert=require('node:assert/strict');
const path=require('node:path');const root=path.resolve(__dirname,'..');const WS=require(root+'/node_modules/ws');
const {webkit,chromium}=require(process.env.PARTY_PLAYWRIGHT||'playwright');
const engine=process.env.QA_ENGINE||'webkit';
const delay=ms=>new Promise(r=>setTimeout(r,ms));const id=process.env.GAME||'kart';const child=spawn(process.execPath,['server.js'],{cwd:root,env:{...process.env,PARTY_EMBEDDED:'1',PARTY_EPHEMERAL:'1',PARTY_NO_BROWSER:'1',PARTY_ADMIN_KEY:'perf-test',PARTY_PORT:'0'}});let log='',browser,base,input,sockets=[];child.stdout.on('data',d=>log+=d);child.stderr.on('data',d=>log+=d);
async function until(fn){for(let i=0;i<300;i++){if(await fn())return;await delay(50);}throw Error('timeout '+log.slice(-1000));}
async function manage(value){const r=await fetch(base+'/api/manage',{method:value?'POST':'GET',headers:{Authorization:'Bearer perf-test','Content-Type':'application/json'},body:value?JSON.stringify(value):undefined});const m=await r.json();assert.equal(r.status,200,JSON.stringify(m));return m;}
async function socket(route='/lobby'){const s=new WS(base.replace('http','ws')+route);sockets.push(s);s.on('message',d=>{const m=JSON.parse(d);if(m.type==='joined')s.profile=m.data||m;});await new Promise((r,j)=>{s.once('open',r);s.once('error',j);});return s;}
(async()=>{try{await until(()=>/localhost:(\d+)/.test(log));base='http://127.0.0.1:'+log.match(/localhost:(\d+)/)[1];await manage({type:'server-start'});browser=await (engine==='chromium'?chromium:webkit).launch({headless:true,...(engine==='chromium'?{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}:{})});const tv=await browser.newPage({viewport:{width:3840,height:2160}});const phone=await browser.newPage({viewport:{width:393,height:852},isMobile:true,hasTouch:true,deviceScaleFactor:3});console.log('browser ready');const cpuSessions=[];if(engine==='chromium')for(const page of[tv,phone]){const session=await page.context().newCDPSession(page);await session.send('Performance.enable');cpuSessions.push(session);}const metrics=async()=>Promise.all(cpuSessions.map(async session=>Object.fromEntries((await session.send('Performance.getMetrics')).metrics.map(m=>[m.name,m.value]))));const errors=[];for(const page of [tv,phone]){page.on('pageerror',e=>errors.push(e.message));if(process.env.PERF_SOURCE_DIR)await page.route(/\/(rankings-theme|game-ui-system|bridge|host|controller)\.js(?:\?.*)?$/,async route=>{const pathname=new URL(route.request().url()).pathname,relative=pathname.startsWith('/games/kart/')?'games/kart/static/'+pathname.split('/').at(-1):'public/'+pathname.split('/').at(-1),file=path.join(process.env.PERF_SOURCE_DIR,relative);if(fs.existsSync(file))await route.fulfill({path:file,contentType:'application/javascript'});else await route.continue();});await page.addInitScript(()=>{const p=window.__perf={frames:[],mutations:0,layouts:0,canvases:0,stableMutations:0,targets:{},rectTargets:{},longTasks:[]};const create=document.createElement.bind(document);document.createElement=(...a)=>{if(a[0]==='canvas')p.canvases++;return create(...a)};const rect=Element.prototype.getBoundingClientRect;Element.prototype.getBoundingClientRect=function(...a){p.layouts++;const caller=(new Error().stack||'').split('\n').find(v=>/\.js[:@]/.test(v)&&!v.includes('bootstrap.js'))||'unknown';p.rectTargets[caller]=(p.rectTargets[caller]||0)+1;return rect.apply(this,a)};try{new PerformanceObserver(list=>p.longTasks.push(...list.getEntries().map(e=>({duration:e.duration,start:e.startTime})))).observe({type:'longtask',buffered:true});}catch{};addEventListener('DOMContentLoaded',()=>new MutationObserver(records=>{p.mutations+=records.length;for(const r of records){const el=r.target.nodeType===1?r.target:r.target.parentElement;if(!el?.closest('#gameMetric,#gameTitle,#timer'))p.stableMutations++;const k=(r.target.id||r.target.className||r.target.nodeName)+':'+(r.attributeName||r.type);p.targets[k]=(p.targets[k]||0)+1;}}).observe(document.body,{attributes:true,childList:true,characterData:true,subtree:true}));let last;requestAnimationFrame(function sample(t){if(last)p.frames.push(t-last);last=t;requestAnimationFrame(sample);});});}
await tv.goto(base+'/tv');console.log('TV ready');await until(async()=>(await manage()).screens===1);
const people=[];for(let n=0;n<2;n++){const s=await socket();s.send(JSON.stringify({type:'join',name:'Perf '+n}));await until(()=>s.profile);people.push(s);}
await phone.goto(base+'/play');await phone.evaluate(p=>localStorage.setItem('local-party-profile',JSON.stringify({id:p.id,token:p.token,name:p.name,hand:p.hand})),people[0].profile);await phone.reload();await until(async()=>(await manage()).players.length===2);
console.log('players ready');const run=(await manage({type:'launch',id})).active;const c=await socket('/games/'+id+'/ws');const p=people[1].profile;c.send(JSON.stringify(id==='kart'?{type:'join',partyId:p.id,partyToken:p.token}:{type:'join',data:{partyId:p.id,partyToken:p.token}}));await until(()=>c.profile);people[1].send(JSON.stringify({type:'game-status',status:'ready',instance:run.instance}));people[1].send(JSON.stringify({type:'ready-set',ready:true,instance:run.instance}));console.log('controller ready');await phone.locator('#readyButton').click();await until(async()=>(await manage()).active.ui.phase==='playing');
console.log('playing');const pf=phone.frames().find(f=>f.url().includes('/games/'));const tf=tv.frames().find(f=>f.url().includes('/games/'));
await pf.evaluate(game=>{window.__drive=setInterval(()=>{if(game==='kart'){steer=.15;throttle=1;}else {joy.x=.4;joy.y=.2;joy.fire=true;send('input',joy);}},33)},id);
input=setInterval(()=>c.send(JSON.stringify(id==='kart'?{type:'input',steer:-.2,throttle:1}:{type:'input',data:{x:-.3,y:.2,fire:true}})),33);await delay(2000);
for(const f of [tv.mainFrame(),tf,phone.mainFrame(),pf])await f.evaluate(()=>{__perf.frames=[];__perf.mutations=__perf.layouts=__perf.canvases=0;__perf.stableMutations=0;__perf.targets={};__perf.rectTargets={};__perf.longTasks=[];});
const cpuBefore=await metrics();await delay(12000);const cpuAfter=await metrics();clearInterval(input);const result={game:id,engine:'desktop '+engine+', local worker server, 2 players, TV 3840x2160 + phone',surfaces:[],errors,cpu:cpuAfter.map((after,i)=>({surface:i===0?'tv-tab-with-game-frame':'phone-tab-with-controller-frame',...Object.fromEntries(['TaskDuration','ScriptDuration','LayoutDuration','RecalcStyleDuration','LayoutCount','RecalcStyleCount'].map(key=>[key,after[key]-cpuBefore[i][key]]))}))};for(const [label,f] of [['tv',tv.mainFrame()],['game',tf],['phone',phone.mainFrame()],['controller',pf]])result.surfaces.push(await f.evaluate(label=>{const p=__perf,a=p.frames.sort((a,b)=>a-b);return {label,frames:a.length,median:a[Math.floor(a.length*.5)],p95:a[Math.floor(a.length*.95)],max:a.at(-1),over50:a.filter(x=>x>50).length,mutations:p.mutations,stableMutations:p.stableMutations,layouts:p.layouts,canvases:p.canvases,targets:Object.entries(p.targets).sort((a,b)=>b[1]-a[1]).slice(0,20),rectTargets:Object.entries(p.rectTargets).sort((a,b)=>b[1]-a[1]).slice(0,12),longTasks:p.longTasks,canvasesNow:[...document.querySelectorAll('canvas')].map(c=>({id:c.id,width:c.width,height:c.height,visible:!!c.getClientRects().length}))}},label));
if(process.env.QA_OUTPUT){fs.mkdirSync(process.env.QA_OUTPUT,{recursive:true});await tv.screenshot({path:path.join(process.env.QA_OUTPUT,'tv-playing.png')});await phone.screenshot({path:path.join(process.env.QA_OUTPUT,'controller-playing.png')});}
if(id==='kart'){
 const rows=await tf.evaluate(()=>{
  const saved=state,first=state.players[0].id,second=state.players[1].id;
  const original=document.querySelector('[data-id="'+first+'"]');
  state={...state,players:state.players.map((p,i)=>({...p,position:i===0?2:1,name:i===0?'<not-markup>':p.name,speed:p.speed+1}))};
  updateHud();const result={same:original===document.querySelector('[data-id="'+first+'"]'),first:leaderboard.firstElementChild.dataset.id,expected:second,name:original.querySelector('.leader-name strong').textContent,html:!!original.querySelector('not-markup')};
  state=saved;updateHud();return result;
 });
 assert(rows.same,'Speed/rank updates preserve row identity');assert.equal(rows.first,rows.expected);assert.equal(rows.name,'<not-markup>');assert.equal(rows.html,false);
}
const before=await tv.locator('#timer').innerText();await delay(1100);assert.notEqual(await tv.locator('#timer').innerText(),before,'TV clock advances');await manage({type:'pause',paused:true});await tv.locator('#paused').waitFor({state:'visible'});await phone.locator('#pauseOverlay').waitFor({state:'visible'});await manage({type:'pause',paused:false});await tv.locator('#paused').waitFor({state:'hidden'});await tv.setViewportSize({width:1280,height:720});await delay(300);const size=await tv.locator('#gameFrame').boundingBox();assert(size.height>500&&size.y+size.height<=721);assert.equal(errors.length,0,errors.join('\n'));console.log(JSON.stringify(result,null,2));if(process.env.REPORT)fs.mkdirSync(path.dirname(process.env.REPORT),{recursive:true});if(process.env.REPORT)fs.writeFileSync(process.env.REPORT,JSON.stringify(result,null,2));if(!process.env.PARTY_PERF_BASELINE){for(const item of result.surfaces.filter(s=>s.label==='tv'||s.label==='phone')){assert.equal(item.canvases,0,'No hidden title canvases during gameplay');assert(item.stableMutations<100,'Stable shell must not rebuild on timer ticks: '+JSON.stringify(item));}}if(process.env.REPORT)fs.writeFileSync(process.env.REPORT,JSON.stringify(result,null,2));
}finally{clearInterval(input);for(const s of sockets)s.terminate();await browser?.close();child.kill();}})().catch(e=>{console.error(e);process.exitCode=1});
