'use strict';
// Real embedded server, real bot controllers and one real phone. Browser-only
// workload for shared canvas/layout hot paths; no synthetic match state.
const {spawn}=require('node:child_process'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium,webkit}=require(process.env.PARTY_PLAYWRIGHT||'playwright');
const root=path.resolve(__dirname,'..'),game=process.env.GAME||'pocket_siege',engine=process.env.QA_ENGINE||'chromium',out=path.resolve(process.env.QA_OUTPUT||'output/playwright/performance243/family/'+game),wait=ms=>new Promise(r=>setTimeout(r,ms));fs.mkdirSync(out,{recursive:true});
const child=spawn(process.execPath,['server.js'],{cwd:root,env:{...process.env,PARTY_EMBEDDED:'1',PARTY_EPHEMERAL:'1',PARTY_NO_BROWSER:'1',PARTY_ADMIN_KEY:'family243',PARTY_PORT:'0'}});let log='',browser,base;child.stdout.on('data',b=>log+=b);child.stderr.on('data',b=>log+=b);
async function until(fn,label){for(let i=0;i<400;i++){if(await fn())return;await wait(50);}throw Error(label+' '+log.slice(-800));}
async function api(body){const r=await fetch(base+'/api/manage',{method:body?'POST':'GET',headers:{Authorization:'Bearer family243','Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const s=await r.json();assert.equal(r.status,200,JSON.stringify(s));return s;}
(async()=>{try{
 await until(()=>/localhost:(\d+)/.test(log),'server');base='http://127.0.0.1:'+log.match(/localhost:(\d+)/)[1];await api({type:'server-start'});
 browser=await(engine==='webkit'?webkit:chromium).launch({headless:true,...(engine==='chromium'?{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}:{})});
 const tv=await browser.newPage({viewport:{width:3840,height:2160}}),phone=await browser.newPage({viewport:{width:393,height:852},isMobile:true,hasTouch:true,deviceScaleFactor:3}),errors=[];
 for(const p of[tv,phone]){p.on('pageerror',e=>errors.push(e.message));if(process.env.PERF_SOURCE_DIR)await p.route(/\/(bridge|rankings-theme|render|host)\.js(?:\?.*)?$/,async r=>{const pathname=new URL(r.request().url()).pathname;let relative;if(pathname.includes('/games/')&&pathname.endsWith('/render.js'))relative='games/arcade_deluxe/public/render.js';else if(/\/games\/(?:bowling|curling|swarm_gate|peek_shoot)\/host\.js$/.test(pathname))relative='games/sports_siege/public/host.js';else relative='public/'+pathname.split('/').at(-1);const f=path.join(process.env.PERF_SOURCE_DIR,relative);if(fs.existsSync(f))await r.fulfill({path:f,contentType:'application/javascript'});else await r.continue();});await p.addInitScript(()=>{window.__familyPerf={rects:{},mutations:0,frames:[],measureText:0};const rect=Element.prototype.getBoundingClientRect;Element.prototype.getBoundingClientRect=function(...args){const key=this.id||this.className||this.tagName;__familyPerf.rects[key]=(__familyPerf.rects[key]||0)+1;return rect.apply(this,args);};const measure=CanvasRenderingContext2D.prototype.measureText;CanvasRenderingContext2D.prototype.measureText=function(...args){__familyPerf.measureText++;return measure.apply(this,args);};addEventListener('DOMContentLoaded',()=>new MutationObserver(r=>__familyPerf.mutations+=r.length).observe(document.body,{subtree:true,attributes:true,childList:true,characterData:true}));let last;requestAnimationFrame(function sample(t){if(last)__familyPerf.frames.push(t-last);last=t;requestAnimationFrame(sample);});});}
 await phone.addInitScript({content:'window.__partyPersistentTabs=true;window.webkit={messageHandlers:{partyShell:{postMessage(){}}}};'+fs.readFileSync(path.join(root,'public/native-shell/controller-bridge.js'),'utf8')+'\n'+fs.readFileSync(path.join(root,'public/native-shell/tabs.js'),'utf8')});
 await tv.goto(base+'/tv');await until(async()=>(await api()).screens===1,'TV');await phone.goto(base+'/play');await phone.locator('#name').fill('Family 243');await phone.locator('#joinForm button[type=submit]').click();await phone.locator('#home').waitFor();await api({type:'bots-set',count:game==='marble_bloom'?2:game==='pocket_siege'?5:3});await wait(600);
 const run=(await api({type:'launch',id:game})).active;await phone.waitForFunction(()=>!document.querySelector('#readyButton').disabled);await phone.locator('#readyButton').click();await until(async()=>(await api()).active?.ui?.phase==='playing','playing');await wait(2000);
 const frame=tv.frames().find(f=>f.url().includes('/games/'+game+'/'));assert(frame,'actual game frame');
 const session=engine==='chromium'?await tv.context().newCDPSession(tv):null;if(session)await session.send('Performance.enable');const metrics=async()=>session?Object.fromEntries((await session.send('Performance.getMetrics')).metrics.map(m=>[m.name,m.value])):{};
 for(const f of[tv.mainFrame(),frame])await f.evaluate(()=>{__familyPerf={rects:{},mutations:0,frames:[],measureText:0};});const before=await metrics();await wait(6000);const after=await metrics();
 const surfaces=[];for(const[label,f]of[['tv',tv.mainFrame()],['game',frame]])surfaces.push(await f.evaluate(label=>{const p=__familyPerf,frames=p.frames.sort((a,b)=>a-b);return{label,rects:p.rects,mutations:p.mutations,measureText:p.measureText,frames:frames.length,p95:frames[Math.floor(frames.length*.95)],canvas:[...document.querySelectorAll('canvas')].map(c=>({id:c.id,width:c.width,height:c.height,clientWidth:c.clientWidth,clientHeight:c.clientHeight}))};},label));
 await tv.screenshot({path:path.join(out,'tv-playing.png')});await phone.screenshot({path:path.join(out,'phone-playing.png')});
 await api({type:'pause',paused:true});await tv.locator('#paused').waitFor();await phone.locator('#pauseOverlay').waitFor();await wait(150);await tv.setViewportSize({width:1280,height:720});await wait(350);
 const resize=await frame.evaluate(()=>{const c=document.querySelector('canvas'),r=window.__arcadeRenderer,box=c?.getBoundingClientRect();return{viewport:[innerWidth,innerHeight],canvas:c?{width:c.width,height:c.height,clientWidth:c.clientWidth,clientHeight:c.clientHeight}:null,actualRect:box?{width:box.width,height:box.height}:null,cachedRect:r?.surfaceRect?{width:r.surfaceRect.width,height:r.surfaceRect.height}:null,dpr:r?.surfaceDpr??Math.min(1.5,devicePixelRatio||1)};});
 if(['pocket_siege','marble_bloom'].includes(game)){if(!process.env.PERF_SOURCE_DIR)assert(Math.abs(resize.cachedRect.width-resize.canvas.clientWidth)<2,'ResizeObserver invalidates actual canvas geometry');assert.equal(resize.canvas.width,Math.round(resize.canvas.clientWidth*resize.dpr),'Backing density remains unchanged');}
 await api({type:'pause',paused:false});await tv.locator('#paused').waitFor({state:'hidden'});assert.equal((await api()).active.instance,run.instance,'Resize/pause does not restart match');assert.equal(errors.length,0,errors.join('\n'));
 const report={game,engine:'desktop '+engine,method:'Actual worker/TV3840x2160/phone+real bots, six seconds playing',surfaces,cpu:Object.fromEntries(['TaskDuration','ScriptDuration','LayoutDuration','RecalcStyleDuration','LayoutCount','RecalcStyleCount'].map(k=>[k,after[k]-before[k]])),resize,errors};fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{await browser?.close();child.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
