'use strict';
// Actual worker, real TV socket, actual phone and existing bot controllers.
// Routes instrument test responses only; production has no debug backdoor.
const {spawn}=require('node:child_process'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium,webkit}=require(process.env.PARTY_PLAYWRIGHT||'playwright');
const root=path.resolve(__dirname,'..'),game=process.env.GAME||'peek_shoot',engine=process.env.QA_ENGINE||'chromium',roster=Number(process.env.QA_ROSTER||16),seconds=Number(process.env.QA_SECONDS||12),dpr=Number(process.env.QA_DPR||1),width=Number(process.env.QA_WIDTH||1920),height=Number(process.env.QA_HEIGHT||1080),out=path.resolve(process.env.QA_OUTPUT||'output/playwright/performance247/sports/'+game),wait=ms=>new Promise(r=>setTimeout(r,ms));
assert(['swarm_gate','peek_shoot','curling','bowling'].includes(game));fs.mkdirSync(out,{recursive:true});
const child=spawn(process.execPath,['server.js'],{cwd:root,env:{...process.env,PARTY_EMBEDDED:'1',PARTY_EPHEMERAL:'1',PARTY_NO_BROWSER:'1',PARTY_ADMIN_KEY:'sports247',PARTY_PORT:'0'}});let log='',browser,base;child.stdout.on('data',b=>log+=b);child.stderr.on('data',b=>log+=b);
async function until(fn,label){for(let i=0;i<400;i++){if(await fn())return;await wait(50);}throw Error(label+' '+log.slice(-1000));}
async function api(body){const r=await fetch(base+'/api/manage',{method:body?'POST':'GET',headers:{Authorization:'Bearer sports247','Content-Type':'application/json'},body:body?JSON.stringify(body):undefined}),s=await r.json();assert.equal(r.status,200,JSON.stringify(s));return s;}
const frozenReference=path.join(root,'.localparty-build/perf247/sports-before/games/sports_siege/public/host.js'),referenceHost=process.env.QA_UI_ORACLE==='1'?(fs.existsSync(frozenReference)?fs.readFileSync(frozenReference,'utf8'):require('node:child_process').execFileSync('git',['show','87dd64fa783c3092061ac5a77074839e2fbfb185:games/sports_siege/public/host.js'],{cwd:root,encoding:'utf8'})):fs.readFileSync(path.join(root,'games/sports_siege/public/host.js'),'utf8'),referenceStart=referenceHost.indexOf('function paintUI(s){'),referenceEnd=referenceHost.indexOf('\nnet.addEventListener(\'state\',',referenceStart);assert(referenceStart>=0&&referenceEnd>referenceStart);
const referenceDrawerStart=referenceHost.indexOf('function setScoreDrawer(open)'),referenceDrawerEnd=referenceHost.indexOf('\nconst settings=',referenceDrawerStart);assert(referenceDrawerStart>=0&&referenceDrawerEnd>referenceDrawerStart);
const referenceDrawer=referenceHost.slice(referenceDrawerStart,referenceDrawerEnd).replaceAll('setScoreDrawer','referenceSetScoreDrawer').replaceAll('paintScoreDrawer','referencePaintScoreDrawer');
const cameraFixture=require('../tests/fixtures/curling-camera-87dd64f.cjs'),cameraReference=cameraFixture.method;assert(cameraReference.startsWith('  updateCamera(s, active, positions, dt, stageChanged) {'));
const probe=`
${referenceDrawer}
window.__sportsQA={get view(){return view},get state(){return state},paintUI,stopPresentationConnection:()=>net.stop(),referenceUI:${referenceHost.slice(referenceStart,referenceEnd).replace('paintScoreDrawer(s);','referencePaintScoreDrawer(s);')},THREE};
const qp=window.__sportsProbe, originalEffects=Stage.prototype.updateEffects, originalPopup=Stage.prototype.scorePopup, originalEffect=Stage.prototype.effect;
Stage.prototype.updateEffects=function(...args){const start=performance.now();qp.popupMax=Math.max(qp.popupMax,this.popups.length);qp.effectMax=Math.max(qp.effectMax,this.effects.length);const value=originalEffects.apply(this,args);qp.effectMs.push(performance.now()-start);return value;};
Stage.prototype.scorePopup=function(...args){qp.scoreEvents++;return originalPopup.apply(this,args);};
Stage.prototype.effect=function(e,...args){qp.events[e.kind]=(qp.events[e.kind]||0)+1;const at=${process.env.QA_NATIVE_VISIBILITY==='1'}?performance.now():0,value=originalEffect.call(this,e,...args);if(${process.env.QA_NATIVE_VISIBILITY==='1'})qp.eventMs.push(performance.now()-at);return value;};
if(view?.curling){
 const c=view.curling,currentCamera=c.updateCamera,currentFit=c.fit,currentShot=c.feel?.shot;
 const stateOf=()=>({cameraReady:c.cameraReady,houseView:c.houseView,camRate:c.camRate,camPos:c.camPos.toArray(),camLook:c.camLook.toArray(),camVel:c.camVel?.toArray(),lookVel:c.lookVel?.toArray(),position:c.camera.position.toArray(),quaternion:c.camera.quaternion.toArray(),fov:c.camera.fov,projection:c.camera.projectionMatrix.toArray(),matrix:c.camera.matrixWorld.toArray(),trauma:c.feel?.trauma});
 const restore=v=>{for(const key of['cameraReady','houseView','camRate'])c[key]=v[key];for(const key of['camPos','camLook','camVel','lookVel']){if(v[key]){if(!c[key])c[key]=new THREE.Vector3();c[key].fromArray(v[key]);}else c[key]=undefined;}c.camera.position.fromArray(v.position);c.camera.quaternion.fromArray(v.quaternion);c.camera.fov=v.fov;c.camera.updateProjectionMatrix();c.camera.updateMatrixWorld();if(c.feel)c.feel.trauma=v.trauma;};
 const compare=(args,label)=>{const before=stateOf();currentCamera.apply(c,args);const actual=stateOf();restore(before);qp.referenceCamera=true;try{c.__qaReferenceUpdateCamera.apply(c,args);}finally{qp.referenceCamera=false;}const expected=stateOf();restore(actual);const diff=Object.keys(expected).filter(k=>JSON.stringify(expected[k])!==JSON.stringify(actual[k]));const numbers=[...actual.position,...actual.quaternion,...actual.projection,...actual.matrix,...actual.camPos,...actual.camLook,actual.fov,actual.camRate];const finite=numbers.every(Number.isFinite);qp.cameraChecks.push({label,phase:args[0].phase,stage:args[0].stage,t:args[0].t,finite,diff,...(diff.length?{actual,expected}:{})});return actual;};
 c.__qaCompareCamera=compare;c.__qaCameraState=stateOf;c.__qaRestoreCamera=restore;
 c.fit=function(points,...rest){if(qp.referenceCamera)return currentFit.call(this,points,...rest);const at=performance.now(),key=qp.directingCamera?'directed':'fallback';try{return currentFit.call(this,points,...rest);}finally{qp.fits[key].calls++;qp.fits[key].projections+=points.length*69;qp.fits[key].ms+=performance.now()-at;}};
 if(currentShot)c.feel.shot=function(...args){const previous=qp.directingCamera;qp.directingCamera=true;try{const value=currentShot.apply(this,args);if(!qp.referenceCamera){qp.directedCalls++;if(value)qp.directedShots++;}return value;}finally{qp.directingCamera=previous;}};
 c.updateCamera=function(...args){c.__qaLatestCameraInputs=args;const at=performance.now();if(${process.env.QA_CAMERA_ORACLE==='1'})compare(args,'actual-frame');else currentCamera.apply(this,args);qp.cameraMs.push(performance.now()-at);};
}
if(view){const render=view.renderer.render.bind(view.renderer),gl=view.renderer.getContext(),timer=${process.env.QA_GPU==='1'}&&gl.getExtension('EXT_disjoint_timer_query_webgl2'),pending=[];qp.gpu=timer?{main:[],other:[],disjoint:0}:null;view.renderer.render=function(scene,camera){
 while(timer&&pending.length&&gl.getQueryParameter(pending[0].query,gl.QUERY_RESULT_AVAILABLE)){const item=pending.shift();if(gl.getParameter(timer.GPU_DISJOINT_EXT))qp.gpu.disjoint++;else qp.gpu[item.label].push(gl.getQueryParameter(item.query,gl.QUERY_RESULT)/1e6);gl.deleteQuery(item.query);}
 const label=camera===view.camera?'main':'other',query=timer&&pending.length<128?gl.createQuery():null;if(query)gl.beginQuery(timer.TIME_ELAPSED_EXT,query);let value;try{value=render(scene,camera);}finally{if(query){gl.endQuery(timer.TIME_ELAPSED_EXT);pending.push({query,label});}}
 const info=this.info.render;qp.passes++;qp.calls+=info.calls;qp.triangles+=info.triangles;qp.cameraPasses[label]++;qp.programPeak=Math.max(qp.programPeak,this.info.programs.length);return value;};
 const descriptor=Object.getOwnPropertyDescriptor(THREE.Material.prototype,'needsUpdate');Object.defineProperty(THREE.Material.prototype,'needsUpdate',{...descriptor,set(value){if(value===true)qp.materialUpdates++;return descriptor.set.call(this,value);}});}
`;
function initProbe(){
 window.__sportsProbe={cameraMs:[],cameraChecks:[],fits:{fallback:{calls:0,projections:0,ms:0},directed:{calls:0,projections:0,ms:0}},directedCalls:0,directedShots:0,uiMs:[],uiPhases:{},rects:{},mutations:0,frames:[],effectMs:[],eventMs:[],events:{},scoreEvents:0,popupMax:0,effectMax:0,passes:0,calls:0,triangles:0,cameraPasses:{main:0,other:0},programPeak:0,materialUpdates:0,programCreated:0,shadersCompiled:0,spriteCreated:0,spriteDisposed:0,spriteLive:0,spritePeak:0,colorCreated:0};
 for(const Constructor of[window.WebGLRenderingContext,window.WebGL2RenderingContext])if(Constructor)for(const[name,key]of[['createProgram','programCreated'],['compileShader','shadersCompiled']]){const original=Constructor.prototype[name];Constructor.prototype[name]=function(...args){window.__sportsProbe[key]++;return original.apply(this,args);};}
 const rect=Element.prototype.getBoundingClientRect;Element.prototype.getBoundingClientRect=function(...args){const p=window.__sportsProbe,key=this.hasAttribute('data-ss-score-popup')?'scorePopup':this.id||this.tagName;p.rects[key]=(p.rects[key]||0)+1;return rect.apply(this,args);};
 addEventListener('DOMContentLoaded',()=>new MutationObserver(r=>window.__sportsProbe.mutations+=r.length).observe(document.body,{subtree:true,attributes:true,childList:true,characterData:true}));let last;requestAnimationFrame(function sample(t){if(last)window.__sportsProbe.frames.push(t-last);last=t;requestAnimationFrame(sample);});
}
async function read(frame){return frame.evaluate(()=>{const p=__sportsProbe,v=__sportsQA.view,renderer=v.renderer,gl=renderer.getContext(),canvas=renderer.domElement,sort=a=>a.slice().sort((a,b)=>a-b),frames=sort(p.frames),fx=sort(p.effectMs);return{...p,frames:{count:frames.length,p50:frames[Math.floor(frames.length*.5)],p95:frames[Math.floor(frames.length*.95)]},effectMs:{count:fx.length,total:fx.reduce((a,b)=>a+b,0),p50:fx[Math.floor(fx.length*.5)],p95:fx[Math.floor(fx.length*.95)]},quality:document.body.dataset.renderQuality,viewport:[innerWidth,innerHeight,devicePixelRatio],canvas:{width:canvas.width,height:canvas.height,clientWidth:canvas.clientWidth,clientHeight:canvas.clientHeight,pixels:canvas.width*canvas.height},gl:{maxTexture:gl.getParameter(gl.MAX_TEXTURE_SIZE),maxRenderbuffer:gl.getParameter(gl.MAX_RENDERBUFFER_SIZE),antialias:gl.getContextAttributes().antialias,samples:gl.getParameter(gl.SAMPLES),depthBits:gl.getParameter(gl.DEPTH_BITS),stencilBits:gl.getParameter(gl.STENCIL_BITS),timerQueryAvailable:!!gl.getExtension('EXT_disjoint_timer_query_webgl2')},shadow:{enabled:renderer.shadowMap.enabled,type:renderer.shadowMap.type,maps:v.scene.children.filter(x=>x.isLight&&x.castShadow).map(x=>({size:x.shadow.mapSize.toArray(),allocated:x.shadow.map?{width:x.shadow.map.width,height:x.shadow.map.height}:null}))},memory:{...renderer.info.memory,programs:renderer.info.programs.length},inset:v.curling?.insetRT?{width:v.curling.insetRT.width,height:v.curling.insetRT.height,samples:v.curling.insetRT.samples}:null,nativeHidden:!!window.__partyNativeHidden,liveEffects:v.effects.length,livePopups:v.popups.length,phase:__sportsQA.state?.phase,stage:__sportsQA.state?.stage,popupComparison:window.__sportsPopupComparison||null,players:__sportsQA.state?.players.length,popupRects:v.popups.filter(x=>!x.el.hidden).map(x=>{const r=x.el.getBoundingClientRect();return{text:x.el.textContent,left:r.left,top:r.top,width:r.width,height:r.height,transform:x.el.style.transform};})};});}
(async()=>{try{
 await until(()=>/localhost:(\d+)/.test(log),'server');base='http://127.0.0.1:'+log.match(/localhost:(\d+)/)[1];await api({type:'server-start'});
 browser=await(engine==='webkit'?webkit:chromium).launch({headless:true,...(engine==='chromium'?{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}:{})});
 const tv=await browser.newPage({viewport:{width,height},deviceScaleFactor:dpr}),phone=await browser.newPage({viewport:{width:393,height:852},isMobile:true,hasTouch:true,deviceScaleFactor:3}),errors=[];
 for(const p of[tv,phone]){p.on('pageerror',e=>errors.push(e.message));if(process.env.QA_NATIVE_VISIBILITY==='1')await p.addInitScript({path:path.join(root,'public/native-shell/visibility.js')});await p.addInitScript(initProbe);}
 await tv.route(/\/games\/(?:swarm_gate|peek_shoot|curling|bowling)\/[^/]+\.js(?:\?.*)?$/,async route=>{const name=new URL(route.request().url()).pathname.split('/').at(-1),file=path.join(process.env.PERF_SOURCE_DIR||root,'games/sports_siege/public',name);if(!fs.existsSync(file))return route.continue();let source=fs.readFileSync(file,'utf8');if(name==='scene-curling.js')source+='\nCurlingScene.prototype.__qaReferenceUpdateCamera=({'+cameraReference+'}).updateCamera;\n';if(name==='host.js'){source=source.replace('function paintUI(s){','function paintUI(s){const started=performance.now();try{');const end='  paintScoreDrawer(s);view?.resize();\n}';assert(source.includes(end));source=source.replace(end,'  paintScoreDrawer(s);view?.resize();\n}finally{const p=window.__sportsProbe,ms=performance.now()-started;p.uiMs.push(ms);const k=s.phase+":"+s.stage,q=p.uiPhases[k]||(p.uiPhases[k]={calls:0,ms:0});q.calls++;q.ms+=ms;}}');source+='\n'+probe;}await route.fulfill({body:source,contentType:'application/javascript'});});
 await tv.route(/\/games\/[^/]+\/vendor\/three\.core\.js(?:\?.*)?$/,async route=>{let source=fs.readFileSync(path.join(root,'node_modules/three/build/three.core.js'),'utf8');const anchor='this.isSpriteMaterial = true;';assert(source.includes(anchor));source=source.replace(anchor,anchor+`\nconst qp=window.__sportsProbe;if(qp){qp.spriteCreated++;qp.spriteLive++;qp.spritePeak=Math.max(qp.spritePeak,qp.spriteLive);this.addEventListener('dispose',()=>{qp.spriteDisposed++;qp.spriteLive--;});}`);source=source.replace('this.isColor = true;','this.isColor = true; if(window.__sportsProbe)window.__sportsProbe.colorCreated++;');await route.fulfill({body:source,contentType:'application/javascript'});});
 await phone.addInitScript({content:'window.__partyPersistentTabs=true;window.webkit={messageHandlers:{partyShell:{postMessage(){}}}};'+fs.readFileSync(path.join(root,'public/native-shell/controller-bridge.js'),'utf8')+'\n'+fs.readFileSync(path.join(root,'public/native-shell/tabs.js'),'utf8')});
 await tv.goto(base+'/tv');await until(async()=>(await api()).screens===1,'TV');await phone.goto(base+'/play');await phone.locator('#name').fill('Sports 247');await phone.locator('#joinForm button[type=submit]').click();await phone.locator('#home').waitFor();await api({type:'bots-set',count:roster-1});await wait(500);
 const run=(await api({type:'launch',id:game})).active;await phone.waitForFunction(()=>!document.querySelector('#readyButton').disabled);await phone.locator('#readyButton').click();await until(async()=>(await api()).active?.ui?.phase==='playing','playing');const frame=tv.frames().find(f=>f.url().includes('/games/'+game+'/'));assert(frame,'actual game frame');await frame.waitForFunction(()=>window.__sportsQA?.view&&document.body.dataset.shaderWarmup==='ready');await frame.evaluate(()=>document.fonts.ready);
 if(['curling','bowling'].includes(game)){
 const control=phone.frames().find(f=>f.url().includes('/games/'+game+'/'));assert(control);await control.locator('#ss-throw-pad').waitFor();const box=await control.locator('#ss-throw-pad').boundingBox();await phone.mouse.move(box.x+box.width*.5,box.y+box.height*.78);await phone.mouse.down();await wait(80);await phone.mouse.move(box.x+box.width*.5,box.y+box.height*.46,{steps:5});await wait(80);await phone.mouse.move(box.x+box.width*.5,box.y+box.height*.33,{steps:3});await phone.mouse.up();await frame.waitForFunction(()=>__sportsQA.state?.stage==='rolling');
 }
 await wait(2000);
 const phoneSession=engine==='chromium'?await phone.context().newCDPSession(phone):null;if(phoneSession)await phoneSession.send('Performance.enable');const phoneMetrics=async()=>phoneSession?Object.fromEntries((await phoneSession.send('Performance.getMetrics')).metrics.map(m=>[m.name,m.value])):{};
 const workload=await frame.evaluate(()=>{const s=__sportsQA.state;return{phase:s.phase,stage:s.stage,t:s.t,currentId:s.currentId,turnToken:s.turnToken,throwIndex:s.throwIndex,sweepAmount:s.sweepAmount,stones:s.stones?structuredClone(s.stones):null,ball:s.ball?structuredClone(s.ball):null};});
 const setup=await read(frame),session=engine==='chromium'?await tv.context().newCDPSession(tv):null;if(session)await session.send('Performance.enable');const metrics=async()=>session?Object.fromEntries((await session.send('Performance.getMetrics')).metrics.map(m=>[m.name,m.value])):{};
 await frame.evaluate(()=>{const p=__sportsProbe;for(const key of['mutations','scoreEvents','popupMax','effectMax','passes','calls','triangles','materialUpdates','programCreated','shadersCompiled','colorCreated','spriteCreated','spriteDisposed'])p[key]=0;p.spritePeak=p.spriteLive;p.rects={};p.frames=[];p.cameraMs=[];p.fits={fallback:{calls:0,projections:0,ms:0},directed:{calls:0,projections:0,ms:0}};p.directedCalls=p.directedShots=0;p.uiMs=[];p.uiPhases={};p.effectMs=[];p.eventMs=[];p.events={};if(p.gpu){p.gpu.main=[];p.gpu.other=[];p.gpu.disjoint=0;}p.cameraPasses={main:0,other:0};});const timedCss=Object.fromEntries(fs.readdirSync(path.join(root,'public')).filter(x=>x.endsWith('.css')).map(x=>[x,require('node:crypto').createHash('sha256').update(fs.readFileSync(path.join(root,'public',x))).digest('hex')]));const before=await metrics(),phoneBefore=await phoneMetrics();await wait(seconds*1000);const after=await metrics(),phoneAfter=await phoneMetrics(),sample=await read(frame);
 await tv.screenshot({path:path.join(out,'tv-playing.png')});await phone.screenshot({path:path.join(out,'phone-playing.png')});
 let hidden=null;if(process.env.QA_NATIVE_VISIBILITY==='1'){
 await frame.evaluate(()=>dispatchEvent(new Event('party-native-hide')));const start=await read(frame),stateStart=await frame.evaluate(()=>({t:__sportsQA.state.t,eventSerial:__sportsQA.state.events.at(-1)?.id||0,score:__sportsQA.state.players.reduce((sum,p)=>sum+p.score,0)}));assert.equal(start.nativeHidden,true,'Exact production native signal entered hidden state');await wait(800);const end=await read(frame),stateEnd=await frame.evaluate(()=>({t:__sportsQA.state.t,eventSerial:__sportsQA.state.events.at(-1)?.id||0,score:__sportsQA.state.players.reduce((sum,p)=>sum+p.score,0)}));assert.equal(end.nativeHidden,true);assert.equal(end.passes,start.passes,'Native visibility hook parks actual scene renders');assert(stateEnd.t>stateStart.t,'Authoritative worker/snapshot time continues while only presentation frame is hidden');
 await frame.evaluate(()=>dispatchEvent(new Event('party-native-resume')));await wait(450);const resumed=await read(frame);assert.equal(resumed.nativeHidden,false,'Native signal resumes visible state');assert(resumed.passes>end.passes,'Scene renderer resumes');assert.equal((await api()).active.instance,run.instance,'Hide/resume does not restart');hidden={method:'Controlled host-frame hide/resume signal with injected production native visibility script; bots/worker stay visible and running; not physical UIView proof',ms:800,renderDelta:end.passes-start.passes,spriteCreated:end.spriteCreated-start.spriteCreated,colorCreated:end.colorCreated-start.colorCreated,eventCpuMs:end.eventMs.slice(start.eventMs.length).reduce((a,b)=>a+b,0),scoreEvents:end.scoreEvents-start.scoreEvents,events:Object.fromEntries(Object.entries(end.events).map(([k,v])=>[k,v-(start.events[k]||0)])),authoritativeTimeDelta:stateEnd.t-stateStart.t,authoritativeEventDelta:stateEnd.eventSerial-stateStart.eventSerial,authoritativeScoreDelta:stateEnd.score-stateStart.score,queuedEffectsBefore:start.liveEffects,queuedEffectsAfter:end.liveEffects,resumedRenderDelta:resumed.passes-end.passes};await tv.screenshot({path:path.join(out,'tv-resumed.png')});
 }
 await api({type:'pause',paused:true});await tv.locator('#paused').waitFor();await phone.locator('#pauseOverlay').waitFor();await wait(200);const paused=await read(frame);await tv.setViewportSize({width:1280,height:720});await wait(400);const resized=await read(frame);await api({type:'pause',paused:false});await tv.locator('#paused').waitFor({state:'hidden'});await wait(350);assert.equal((await api()).active.instance,run.instance,'Pause/resize does not restart match');assert.equal(resized.players,roster,'Roster retained');assert.equal(errors.length,0,errors.join('\n'));
 let reconnect=null;if(process.env.QA_RECONNECT==='1'){
 const humanId=await phone.evaluate(()=>PARTY_PROFILE.id),beforeReconnect=await frame.evaluate(id=>{const p=__sportsQA.state.players.find(p=>p.id===id);return {id:p.id,name:p.name,number:p.number,score:p.score};},humanId);
 await phone.goto('about:blank');await frame.waitForFunction(id=>__sportsQA.state.players.find(p=>p.id===id)?.connected===false,humanId,{timeout:10000});const disconnected=await frame.evaluate(id=>{const p=__sportsQA.state.players.find(p=>p.id===id),card=document.querySelector('[data-player-id="'+id+'"]');return{id:p.id,connected:p.connected,offline:card.classList.contains('offline'),name:card.querySelector('.hp-player-name').textContent};},humanId);assert(disconnected.offline,'Real controller disconnect marks its unchanged card offline');
 await phone.goto(base+'/play');await phone.waitForFunction(id=>window.PARTY_PROFILE?.id===id,humanId);await frame.waitForFunction(id=>__sportsQA.state.players.find(p=>p.id===id)?.connected===true,humanId,{timeout:10000});await phone.waitForFunction(id=>document.getElementById('gameFrame').src.includes('/games/'+id+'/'),game);const returned=await frame.evaluate(id=>{const p=__sportsQA.state.players.find(p=>p.id===id),card=document.querySelector('[data-player-id="'+id+'"]');return{id:p.id,name:p.name,number:p.number,connected:p.connected,offline:card.classList.contains('offline'),literalName:card.querySelector('.hp-player-name').textContent,noTranslate:card.querySelector('.hp-player-name').hasAttribute('data-no-translate')};},humanId);assert.equal(returned.id,beforeReconnect.id);assert.equal(returned.name,beforeReconnect.name);assert.equal(returned.number,beforeReconnect.number);assert.equal(returned.literalName,returned.name);assert(returned.noTranslate);assert.equal(returned.offline,false);assert.equal((await api()).active.instance,run.instance,'Real disconnect/reconnect preserves authoritative match');reconnect={method:'Actual phone navigation closes both sockets, same saved profile rejoins same worker; no state injection',before:beforeReconnect,disconnected,returned};await tv.screenshot({path:path.join(out,'tv-reconnected.png')});await phone.screenshot({path:path.join(out,'phone-reconnected.png')});
 }
 const replay=await frame.evaluate(()=>{const observer=new MutationObserver(()=>{});observer.observe(document.body,{subtree:true,attributes:true,childList:true,characterData:true});const value=__sportsQA.state,at=performance.now();for(let i=0;i<100;i++)__sportsQA.paintUI(value);const ms=performance.now()-at,records=observer.takeRecords();observer.disconnect();return {calls:100,ms,mutations:records.length,types:records.reduce((a,x)=>(a[x.type]=(a[x.type]||0)+1,a),{}),unchanged:true};});
 const sourceFile=path.join(process.env.PERF_SOURCE_DIR||root,'games/sports_siege/public/host.js'),sourceHash=require('node:crypto').createHash('sha256').update(fs.readFileSync(sourceFile)).digest('hex');
 let cameraOracle=null;if(process.env.QA_CAMERA_ORACLE==='1'&&game==='curling')cameraOracle=await frame.evaluate(()=>{const c=__sportsQA.view.curling,args=c.__qaLatestCameraInputs,original=c.__qaCameraState(),actualFrames=__sportsProbe.cameraChecks.slice(),cases=[];for(const phase of ['playing','results','waiting'])for(const stage of ['aim','rolling','reveal','end'])for(const lastStone of [false,true]){const value=structuredClone(args[0]);value.phase=phase;value.stage=stage;value.throwIndex=lastStone?value.throwCount-1:0;for(const reduced of [false,true]){const wasReduced=c.reduced,feelReduced=c.feel.reduced;c.reduced=reduced;c.feel.reduced=reduced;c.__qaCompareCamera([value,args[1],args[2],1/60,true],'controlled-camera-fixture');cases.push(__sportsProbe.cameraChecks.at(-1));c.__qaRestoreCamera(original);c.reduced=wasReduced;c.feel.reduced=feelReduced;}}return{method:'Exact numeric original-module camera comparison on actual frames plus explicitly controlled camera-only phase/reduced fixtures; no worker state or score injection',actualFrames,cases};});if(cameraOracle)assert([...cameraOracle.actualFrames,...cameraOracle.cases].every(x=>x.finite&&!x.diff.length),JSON.stringify([...cameraOracle.actualFrames,...cameraOracle.cases].filter(x=>!x.finite||x.diff.length).slice(0,3)));
 let oracle=null;if(process.env.QA_UI_ORACLE==='1')oracle=await frame.evaluate(async()=>{
  __sportsQA.stopPresentationConnection();const original=structuredClone(__sportsQA.state),summarize=()=>{
    const fields=[...document.querySelectorAll('#ss-overlay,#ss-overlay *,#ss-mode,#ss-stage,#ss-status,#ss-primary-label,#ss-primary-value,#ss-secondary-label,#ss-secondary-value,#ss-gate-health,#ss-gate-value,#ss-gate,#ss-scoreboard,#ss-scoreboard *,#ss-score-drawer,#ss-score-drawer *,#ss-scores-toggle')];
    return [{bodyScoreRows:document.body.dataset.ssScoreRows},...fields.map(el=>({id:el.id,cls:el.className,hidden:el.hidden,text:el.textContent,attrs:[...el.attributes].filter(a=>a.name!=='class'&&a.name!=='style').map(a=>[a.name,a.value]).sort(),style:el.style.cssText,box:Object.fromEntries(['x','y','width','height'].map(k=>[k,Number(el.getBoundingClientRect()[k].toFixed(3))]))}))];
  },cases=[],report=[];original.events=[];
  cases.push(['real',original]);const updated=structuredClone(original);updated.players[0].name='<bold> & Алекс';updated.players[0].score+=11;updated.players[0].connected=false;updated.players[0].number=17;updated.players[0].frames=[{rolls:[3,7]}];updated.players[0].energy=.39;updated.players[0].heat=.21;updated.players[0].kills=15;updated.players[0].gunUntil=updated.t+4;updated.players[0].lockedUntil=updated.t+2;updated.deadline=updated.t+7;updated.stage='aim';updated.sweepAmount=1;updated.teams=[7,3];cases.push(['changed',updated]);
  const fractional=structuredClone(updated);fractional.players[0].energy=1/3;fractional.players[0].heat=2/3;fractional.players[0].gunUntil=fractional.t+.4;fractional.players[0].streak=1;cases.push(['fractional-percent',fractional]);const regroup=structuredClone(fractional);regroup.players[0].team=regroup.players[0].team===0?1:0;regroup.players.reverse();cases.push(['team-order',regroup]);const identity=structuredClone(regroup),oldId=identity.players[0].id;identity.players[0].id=oldId+'-qa247';if(identity.currentId===oldId)identity.currentId=identity.players[0].id;cases.push(['identity-replaced',identity]);cases.push(['identity-return',updated]);const avatar=structuredClone(updated);avatar.players[0].avatar='/assets/avatars/atlas-mascots/mascot-01.webp';cases.push(['avatar-present',avatar]);cases.push(['avatar-removed',updated]);
  const sparse=structuredClone(updated);sparse.players=sparse.players.slice(0,4);cases.push(['sparse',sparse]);cases.push(['dense-return',updated]);const disconnected=structuredClone(updated);disconnected.players[0].participant=false;disconnected.players[0].gunUntil=0;cases.push(['spectator',disconnected]);const waiting=structuredClone(sparse);waiting.phase='waiting';cases.push(['waiting',waiting]);const results=structuredClone(sparse);results.phase='results';results.result={eventId:'qa247',reason:'Матч завершён',winners:[results.players[0].id],players:results.players.map((p,i)=>({...p,won:i===0}))};cases.push(['results',results]);cases.push(['waiting-return',waiting]);cases.push(['results-return',results]);
  for(const locale of ['en','ru','en']){PartyI18n.setLanguage(locale,{persist:false});for(const [name,value]of cases){__sportsQA.paintUI(value);PartyI18n.apply(document.body);const after=summarize();__sportsQA.referenceUI(value);PartyI18n.apply(document.body);const reference=summarize();const differing=after.map((v,i)=>JSON.stringify(v)!==JSON.stringify(reference[i])?{i,after:v,reference:reference[i]}:null).filter(Boolean);report.push({name,locale,fields:after.length,differing});}}
  PartyI18n.setLanguage('en',{persist:false});__sportsQA.paintUI(original);PartyI18n.apply(document.body);return {method:'Controlled same-module UI-only snapshot variations after actual-worker timing; not authoritative game state or physical cast',report};
});if(oracle)assert(oracle.report.every(x=>!x.differing.length),JSON.stringify(oracle.report.filter(x=>x.differing.length)));
 if(process.env.QA_REQUIRE_STABLE==='1')assert.equal(replay.mutations,0,'100 unchanged Sports snapshots perform no DOM mutations');
 const cssHashes=Object.fromEntries(fs.readdirSync(path.join(root,'public')).filter(x=>x.endsWith('.css')).map(x=>[x,require('node:crypto').createHash('sha256').update(fs.readFileSync(path.join(root,'public',x))).digest('hex')]));
 const phoneCpu=Object.fromEntries(['TaskDuration','ScriptDuration','LayoutDuration','RecalcStyleDuration','LayoutCount','RecalcStyleCount'].map(k=>[k,phoneSession?phoneAfter[k]-phoneBefore[k]:null]));
 const report={workload,cameraOracle,cameraTimingContainsOracle:process.env.QA_CAMERA_ORACLE==='1',sourceHash,sceneHash:require('node:crypto').createHash('sha256').update(fs.readFileSync(fs.existsSync(path.join(process.env.PERF_SOURCE_DIR||root,'games/sports_siege/public/scene-curling.js'))?path.join(process.env.PERF_SOURCE_DIR||root,'games/sports_siege/public/scene-curling.js'):path.join(root,'games/sports_siege/public/scene-curling.js'))).digest('hex'),revision:'87dd64fa783c3092061ac5a77074839e2fbfb185',reconnect,phoneCpu,cssStable:JSON.stringify(timedCss)===JSON.stringify(cssHashes),oracle,replay,hidden,cssHashes,game,engine:'desktop '+engine,method:'Actual worker + TV + phone + existing bot controllers, timed playing sample; browser is not physical cast',roster,seconds,setup,sample,cpu:Object.fromEntries(['TaskDuration','ScriptDuration','LayoutDuration','RecalcStyleDuration','LayoutCount','RecalcStyleCount','JSHeapUsedSize'].map(k=>[k,session?after[k]-before[k]:null])),paused:{phase:paused.phase,stage:paused.stage},resize:{viewport:resized.viewport,canvas:resized.canvas,memory:resized.memory},errors};fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({out,game,roster,replay,uiMs:{count:sample.uiMs.length,total:sample.uiMs.reduce((a,b)=>a+b,0)},quality:sample.quality,canvas:sample.canvas,cpu:report.cpu,events:sample.events,scoreEvents:sample.scoreEvents,popupMax:sample.popupMax,effectMs:sample.effectMs,rects:sample.rects,spriteCreated:sample.spriteCreated,colorCreated:sample.colorCreated,materialUpdates:sample.materialUpdates,programCreated:sample.programCreated,shadersCompiled:sample.shadersCompiled,passes:sample.cameraPasses,gpu:sample.gpu?Object.fromEntries(Object.entries(sample.gpu).map(([k,v])=>[k,Array.isArray(v)?{count:v.length,p50:v.slice().sort((a,b)=>a-b)[Math.floor(v.length*.5)],p95:v.slice().sort((a,b)=>a-b)[Math.floor(v.length*.95)]}:v])):null,memory:sample.memory}));
}finally{await browser?.close();child.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
