'use strict';
// Matched native shell fixture, real shipped DOM/styles/tabs. Swift discovery and
// state delivery are labelled fixtures. No physical phone/casting claim.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),frozen=path.join(root,'.localparty-build/perf245/source-before');
const output=path.resolve(process.env.QA_OUTPUT||'output/playwright/performance245/ui');
const lane=process.env.QA_LANE||'stack',engine=process.env.QA_ENGINE||'chromium',behaviorOnly=process.env.QA_BEHAVIOR==='1',controllerRoute=process.env.QA_ROUTE==='controller';
const sourceDir=path.join(output,'isolated-source');fs.mkdirSync(sourceDir,{recursive:true});
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');
const sourceFiles=['public/native-shell/host.js','public/native-shell/nearby-rooms.js'];
const before=Object.fromEntries(sourceFiles.map(f=>[f,fs.readFileSync(path.join(frozen,f),'utf8')]));
const stackAnchor="document.body.classList.add('stack-backed');";
assert.equal(before[sourceFiles[0]].split(stackAnchor).length,2);
const stackCandidate=before[sourceFiles[0]].replace(stackAnchor,"if(!document.body.classList.contains('stack-backed'))document.body.classList.add('stack-backed');");
let roomsCandidate=before[sourceFiles[1]];
const replacements=[
 ["const paintNetworkIcon=()=>{if(!window.PartyIcons)return;toggle.replaceChildren(window.PartyIcons.create('share'));};","const paintNetworkIcon=()=>{if(!window.PartyIcons||toggle.querySelector('svg'))return;toggle.replaceChildren(window.PartyIcons.create('share'));};"],
 ["let last='',pending=null,saveTimer=null;","let last='',pending=null,saveTimer=null;\n const roomLabels=new WeakMap();\n const roomText=(node,value)=>{const text=String(value??'');if(roomLabels.get(node)===text)return;roomLabels.set(node,text);node.textContent=text;};"],
 ["const key=JSON.stringify([rooms,selected]);if(key===last)return;last=key;","const key=JSON.stringify([rooms,selected]);if(key===last)return;last=key;"],
 ["toggle.title='Games on Wi-Fi · '+rooms.length;paintNetworkIcon();","const title='Games on Wi-Fi · '+rooms.length;if(toggle.dataset.roomTitle!==title){toggle.dataset.roomTitle=title;toggle.title=title;}paintNetworkIcon();"],
 ["notice.textContent=missing?","roomText(notice,missing?"],
 ["Keep both phones on the same Wi-Fi.';}","Keep both phones on the same Wi-Fi.');}"],
 ["row.dataset.current=String(room.id===selected);row.querySelector('b').textContent=room.name;const input=row.querySelector('input');if(input&&!row.classList.contains('renaming')&&pending!==row){input.value=room.name;input.dispatchEvent(new Event('input'));}let hue=0;for(const c of room.id)hue=(hue*31+c.charCodeAt(0))%50;row.style.setProperty('--room-hue',String(265+hue));","const current=String(room.id===selected);if(row.dataset.current!==current)row.dataset.current=current;roomText(row.querySelector('b'),room.name);const input=row.querySelector('input');if(input&&!row.classList.contains('renaming')&&pending!==row&&input.value!==room.name){input.value=room.name;input.dispatchEvent(new Event('input'));}let hue=0;for(const c of room.id)hue=(hue*31+c.charCodeAt(0))%50;const hueText=String(265+hue);if(row.style.getPropertyValue('--room-hue')!==hueText)row.style.setProperty('--room-hue',hueText);"],
 ["const meta=row.querySelector('small');meta.replaceChildren();const game=document.createElement('span');game.className='nearby-game';game.textContent=(room.game||'Lobby')+(room.phase==='waiting'?' · Getting ready':room.phase==='results'?' · Results':'');const count=document.createElement('span');count.className='nearby-count';count.textContent=String(room.players);count.setAttribute('aria-label',room.players+' players');meta.append(game,count);","const meta=row.querySelector('small');let game=meta.querySelector('.nearby-game'),count=meta.querySelector('.nearby-count');if(!game||!count){game=document.createElement('span');game.className='nearby-game';count=document.createElement('span');count.className='nearby-count';meta.replaceChildren(game,count);}roomText(game,(room.game||'Lobby')+(room.phase==='waiting'?' · Getting ready':room.phase==='results'?' · Results':''));roomText(count,room.players);if(count.dataset.roomPlayers!==String(room.players)){count.dataset.roomPlayers=String(room.players);count.setAttribute('aria-label',room.players+' players');}"],
 ["const button=row.querySelector('.nearby-join');button.disabled=room.id===selected;button.className='nearby-join '+(room.id===selected?'quiet':'primary');button.textContent=room.id===selected?'Connected':room.id==='own'?'Return':'Join';","const button=row.querySelector('.nearby-join'),disabled=room.id===selected,buttonClass='nearby-join '+(disabled?'quiet':'primary');if(button.disabled!==disabled)button.disabled=disabled;if(button.className!==buttonClass)button.className=buttonClass;roomText(button,disabled?'Connected':room.id==='own'?'Return':'Join');"]
];
for(const [a,b]of replacements){assert(roomsCandidate.includes(a),'Rooms anchor missing '+a);roomsCandidate=roomsCandidate.replace(a,b);}
fs.writeFileSync(path.join(sourceDir,'stack-host.js'),stackCandidate);
fs.writeFileSync(path.join(sourceDir,'rooms-nearby-rooms.js'),roomsCandidate);
fs.writeFileSync(path.join(sourceDir,'source-manifest.json'),JSON.stringify({before:Object.fromEntries(sourceFiles.map(f=>[f,hash(before[f])])),candidates:{stack:hash(stackCandidate),rooms:hash(roomsCandidate)}},null,2)+'\n');
if(process.argv.includes('--prepare')){console.log(JSON.stringify({prepared:sourceDir}));process.exit(0);}
const {chromium,webkit}=require(process.env.PARTY_PLAYWRIGHT||'playwright'),express=require('express'),{spawn}=require('node:child_process');
const report={lane,engine,behaviorOnly,route:controllerRoute?'/play':'/native-shell/index.html',method:'Isolated frozen sources, actual native-shell or shipped /play and persistent tabs/visibility/controller bridge; Swift state/discovery fixtures. Browser CPU/DOM/layout, no physical phone/cast claim. Keyboard viewport resize is simulated, not hardware keyboard.',samples:[],checks:[],captures:[],errors:[],sourceManifest:JSON.parse(fs.readFileSync(path.join(sourceDir,'source-manifest.json'),'utf8'))};
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function initProbe(){
 const state=()=>({bodyClasses:0,inputInk:0,inputStyles:0,inputStyleReads:0,rects:0,created:0,mutations:0,added:0,removed:0,observerCallbacks:{},frames:[],longTasks:[]});
 window.__ui245=state();window.__reset245=()=>window.__ui245=state();
 window.__commands=[];window.__partyPersistentTabs=true;window.webkit={messageHandlers:{partyShell:{postMessage:m=>__commands.push(m)}}};
 const NativeMO=MutationObserver;
 window.MutationObserver=class extends NativeMO{constructor(callback){const stack=new Error().stack||'',site=stack.split('\n').find(line=>/app-ux-20261005|motion\.js|game-spotlight|i18n\.js/.test(line))?.trim()||'other';super((records,observer)=>{const p=window.__ui245;p.observerCallbacks[site]=(p.observerCallbacks[site]||0)+1;callback(records,observer);});}};
 const style=getComputedStyle;window.getComputedStyle=function(n,...a){if(n?.matches?.('input[type=text],input[type=search],#name'))__ui245.inputStyleReads++;return style.call(this,n,...a);};
 const rect=Element.prototype.getBoundingClientRect;Element.prototype.getBoundingClientRect=function(...a){__ui245.rects++;return rect.apply(this,a);};
 const create=document.createElement;document.createElement=function(...a){__ui245.created++;return create.apply(this,a);};
 addEventListener('DOMContentLoaded',()=>new NativeMO(records=>{const p=__ui245;p.mutations+=records.length;for(const r of records){p.added+=r.addedNodes.length;p.removed+=r.removedNodes.length;if(r.target===document.body&&r.attributeName==='class')p.bodyClasses++;const node=r.target.nodeType===1?r.target:r.target.parentElement;if(node?.matches('.hp-input-ink')){if(r.attributeName==='style')p.inputStyles++;else p.inputInk++;}}}).observe(document.body,{subtree:true,attributes:true,childList:true,characterData:true}));
 try{new PerformanceObserver(list=>__ui245.longTasks.push(...list.getEntries().map(e=>({duration:e.duration,start:e.startTime})))).observe({type:'longtask',buffered:true});}catch{}
 let last;requestAnimationFrame(function sample(t){if(last)__ui245.frames.push(t-last);last=t;requestAnimationFrame(sample);});
}
const rooms=[{id:'own',name:'Friday night',game:'Push Pit',phase:'waiting',players:4},{id:'other',name:'Alexandra’s Friday party',game:'Pocket Strike',phase:'waiting',players:8},{id:'third',name:'Друзья в гостиной',game:'',phase:'lobby',players:16}];
const players=[{id:'one',name:'Alexandra',gameReady:true,connected:true}];
const snapshot={catalog:require('../lib/catalog'),players,leaderboard:[],votes:[],screens:1,native:{ready:true,catalogReady:true},selected:'push',active:{id:'push',instance:'ui245-fixture',ui:{phase:'waiting'},session:{paused:false,readyIds:[]},roster:players,ready:['one']},tv:{canCover:true,mode:'none',focusNumber:1,total:36}};
function summary(p){const frames=p.frames.slice().sort((a,b)=>a-b);p.frameP95=frames[Math.floor(frames.length*.95)]||0;p.over50=frames.filter(x=>x>50).length;p.frameCount=frames.length;delete p.frames;return p;}
async function settle(page){await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(800);const active=await page.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running'&&a.effect?.getTiming().iterations!==Infinity).map(a=>({target:a.effect?.target?.id||a.effect?.target?.className,state:a.playState,timing:a.effect?.getTiming(),time:a.currentTime})));if(active.length)console.log(JSON.stringify({stage:'finite-after-cold-settle',active}));}
async function nativeGeometry(page){return page.evaluate(()=>{const box=n=>{const r=n.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height,bottom:r.bottom,right:r.right};};const card=document.querySelector('#activeCard'),tools=document.querySelector('.native-catalog-tools'),circle=document.querySelector('#activeCard .hp-pick-circle,#activeArt');return {scrollY,compact:card.classList.contains('is-compact'),card:box(card),tools:box(tools),circle:circle?box(circle):null,tab:LocalPartyTabs.current,masked:document.body.hasAttribute('data-hp-modal-active')};});}
(async()=>{
 let server,child,origin,browser;
 if(controllerRoute){let log='';child=spawn(process.execPath,['server.js'],{cwd:root,env:{...process.env,PARTY_EMBEDDED:'1',PARTY_INTERNAL_PORT:'0',PARTY_EPHEMERAL:'1',PARTY_PORT:'0',PARTY_NO_BROWSER:'1',PARTY_ADMIN_KEY:'ui245-controller-behavior'}});child.stdout.on('data',d=>log+=d);child.stderr.on('data',d=>log+=d);for(let n=0;n<200&&!/localhost:(\d+)/.test(log);n++)await wait(50);assert.match(log,/localhost:(\d+)/);origin='http://127.0.0.1:'+log.match(/localhost:(\d+)/)[1];}else{server=express().use(express.static(path.join(root,'public'))).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));origin='http://127.0.0.1:'+server.address().port;}
 try{
  browser=await(engine==='webkit'?webkit:chromium).launch({headless:true,...(engine==='chromium'?{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}:{})});
  for(const variant of (behaviorOnly?['baseline','candidate']:['baseline','candidate','baseline','candidate'])){
   const pair=report.samples.filter(s=>s.variant===variant).length;
   const page=await browser.newPage({viewport:{width:393,height:852},isMobile:true,hasTouch:true,deviceScaleFactor:3});page.on('pageerror',e=>report.errors.push(e.message));
   await page.route('**/*',async route=>{const url=new URL(route.request().url()),relative='public'+url.pathname,oldFile=path.join(frozen,relative);if(url.pathname==='/native-shell/host.js')return route.fulfill({body:variant==='candidate'&&lane==='stack'?stackCandidate:before[sourceFiles[0]],contentType:'application/javascript'});if(url.pathname==='/native-shell/nearby-rooms.js')return route.fulfill({body:variant==='candidate'&&lane==='rooms'?roomsCandidate:before[sourceFiles[1]],contentType:'application/javascript'});if(fs.existsSync(oldFile)&&fs.statSync(oldFile).isFile())return route.fulfill({path:oldFile,contentType:relative.endsWith('.css')?'text/css':'application/javascript'});return route.continue();});
   await page.addInitScript(initProbe);
   await page.addInitScript({content:fs.readFileSync(path.join(root,'public/native-shell/visibility.js'),'utf8')+'\n'+(controllerRoute?fs.readFileSync(path.join(root,'public/native-shell/controller-bridge.js'),'utf8')+'\n':'')+fs.readFileSync(path.join(root,'public/native-shell/tabs.js'),'utf8')});
   console.log(JSON.stringify({stage:'setup',lane,engine,variant,pair,controllerRoute}));await page.goto(origin+(controllerRoute?'/play':'/native-shell/index.html'));
   if(controllerRoute){await page.locator('#name').fill('Native Rooms QA');await page.locator('#joinForm button[type=submit]').click();await page.waitForFunction(()=>document.body.classList.contains('lobby-connected'));assert(await page.evaluate(()=>document.body.classList.contains('native-controller')&&!!LocalPartyNative?.isNative));}else await page.evaluate(s=>{window.__snapshot=s;LocalPartyHost.update(s);},snapshot);await settle(page);await page.waitForSelector('#partyNativeDock.native-tabs',{state:'attached'});
   await page.addScriptTag({url:'/native-shell/nearby-rooms.js'});await page.evaluate(r=>LocalPartyRooms.update(r,'own'),rooms);await settle(page);
   const session=engine==='chromium'&&!behaviorOnly?await page.context().newCDPSession(page):null;if(session)await session.send('Performance.enable');const metrics=async()=>session?Object.fromEntries((await session.send('Performance.getMetrics')).metrics.map(m=>[m.name,m.value])):{};
   async function measure(name,work){console.log(JSON.stringify({stage:'measure',lane,engine,variant,pair,name}));await page.evaluate(()=>__reset245());const start=await metrics();const behavior=await work();await page.waitForTimeout(80);const end=await metrics(),probe=summary(await page.evaluate(()=>__ui245));report.samples.push({variant,pair,name,behavior,probe,cpu:Object.fromEntries(['TaskDuration','ScriptDuration','LayoutDuration','RecalcStyleDuration','LayoutCount','RecalcStyleCount'].map(k=>[k,(end[k]||0)-(start[k]||0)]))});}
   if(lane==='stack'){
    // Warm one reversible compaction before measuring, retaining its flow margin.
    await page.evaluate(()=>scrollTo(0,180));await page.waitForTimeout(400);await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(400);
    await measure('twelve-real-scroll-crossings',()=>page.evaluate(async stable=>{const result=[];for(let n=0;n<12;n++){scrollTo(0,n%2?0:180);await new Promise(r=>setTimeout(r,360));const c=document.querySelector('#activeCard'),t=document.querySelector('.native-catalog-tools');if(stable){const began=performance.now(),wanted=n%2?208:62;while(Math.abs(c.getBoundingClientRect().height-wanted)>1){if(performance.now()-began>3500)throw new Error('Settled Host Pick height deadline: expected '+wanted+' got '+c.getBoundingClientRect().height+' '+JSON.stringify(c.getAnimations().map(a=>({state:a.playState,time:a.currentTime,timing:a.effect.getTiming()}))));await new Promise(r=>setTimeout(r,100));}}result.push({scrollY,compact:c.classList.contains('is-compact'),height:c.getBoundingClientRect().height,toolsTop:t.getBoundingClientRect().top});}return result;},behaviorOnly));
    const geometry=await nativeGeometry(page);assert.equal(geometry.compact,false);assert(Math.abs(geometry.card.height-208)<=1,'Expanded card keeps its full height');report.checks.push({variant,pair,name:'expanded-final',geometry});
    await page.evaluate(()=>scrollTo(0,180));await page.waitForFunction(()=>Math.abs(document.querySelector('#activeCard').getBoundingClientRect().height-62)<=1,{},{polling:100,timeout:4000});report.checks.push({variant,pair,name:'compact-final',geometry:await nativeGeometry(page)});
    if(pair===0){const file=`${engine}-${lane}-${variant}-compact.png`;await page.screenshot({path:path.join(output,file)});report.captures.push(file);}
   }else{
    await page.locator('#nearbyToggle').click();await settle(page);
    await measure('100-unchanged-discovery-payloads',()=>page.evaluate(r=>{for(let n=0;n<100;n++)LocalPartyRooms.update(r,'own');return {rows:document.querySelectorAll('.nearby-room').length};},rooms));
    await measure('100-single-room-real-player-changes',()=>page.evaluate(r=>{for(let n=0;n<100;n++){const payload=structuredClone(r);payload[1].players=n%2?7:8;LocalPartyRooms.update(payload,'own');}return {count:document.querySelector('[data-room=other] .nearby-count').textContent};},rooms));
    for(const language of ['ru','en']){await page.evaluate(l=>PartyI18n.setLanguage(l),language);await page.evaluate(r=>{LocalPartyRooms.update(r,'own');},rooms);await settle(page);const data=await page.evaluate(()=>[...document.querySelectorAll('.nearby-room')].map(row=>{const box=n=>{const r=n.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height};};return{id:row.dataset.room,title:row.querySelector('b').textContent,meta:row.querySelector('small').textContent,action:row.querySelector('.nearby-join').textContent,disabled:row.querySelector('.nearby-join').disabled,row:box(row),count:box(row.querySelector('.nearby-count')),button:box(row.querySelector('.nearby-join'))};}));report.checks.push({variant,pair,name:'locale-'+language,data});}
    const own=page.locator('[data-room=own]');await own.locator('.nearby-rename-toggle').click();await own.locator('input').fill('Pending edited room');const identity=await own.locator('input').evaluate(input=>{window.__savedInput245=input;return input.value;});
    await page.evaluate(r=>{for(let n=0;n<5;n++){const data=structuredClone(r);data[1].players=9+n;LocalPartyRooms.update(data,'own');}},rooms);assert.equal(await own.locator('input').inputValue(),identity);assert(await own.locator('input').evaluate(n=>document.activeElement===n&&n===__savedInput245));
    if(behaviorOnly){await page.setViewportSize({width:393,height:500});await page.waitForTimeout(600);const field=await own.locator('input').boundingBox(),save=await own.locator('.nearby-rename-save').boundingBox();assert(field.y>=0&&field.y+field.height<=488,'Field reachable above resized keyboard viewport');assert(save.y>=0&&save.y+save.height<=488,'Save reachable above resized keyboard viewport');report.checks.push({variant,pair,name:'keyboard-simulated-viewport',field,save});const file=`${engine}-${controllerRoute?'controller':'native'}-${variant}-rename-keyboard.png`;await page.screenshot({path:path.join(output,file)});report.captures.push(file);}
    await own.locator('.nearby-rename-save').click();assert(await page.evaluate(()=>__commands.some(m=>m.type==='rename-room'&&m.name==='Pending edited room')));await page.evaluate(()=>LocalPartyRooms.renamed('Pending edited room'));if(behaviorOnly)await page.setViewportSize({width:393,height:852});await settle(page);assert.equal(await own.locator('b').textContent(),'Pending edited room');
    if(pair===0){const file=`${engine}-${controllerRoute?'controller':lane}-${variant}-nearby.png`;await page.screenshot({path:path.join(output,file)});report.captures.push(file);}
    if(behaviorOnly){await page.locator('.rooms-tabs button').nth(1).click();const inputs=page.locator('.rooms-code-cells input');for(let n=0;n<6;n++)await inputs.nth(n).fill(String(n+1));assert.equal(await inputs.evaluateAll(nodes=>nodes.map(n=>n.value).join('')),'123456');const file=`${engine}-${controllerRoute?'controller':'native'}-${variant}-by-code.png`;await settle(page);await page.screenshot({path:path.join(output,file)});report.captures.push(file);await page.locator('.rooms-tabs button').nth(0).click();}
    await page.locator('#nearbyClose').click();await page.waitForFunction(()=>!document.querySelector('#nearbyDialog').open);if(!controllerRoute){await page.evaluate(()=>LocalPartyTabs.select('host',false));await settle(page);assert(await page.evaluate(()=>document.body.classList.contains('native-host-tab')&&document.querySelector('#hostPanel').open));await page.evaluate(()=>LocalPartyTabs.select('games',false));await settle(page);assert(await page.evaluate(()=>!document.body.classList.contains('native-host-tab')&&!document.querySelector('#hostPanel').open));}else{await page.evaluate(()=>{window.__partyNativeHidden=true;dispatchEvent(new Event('party-native-hide'));});await page.evaluate(()=>{window.__partyNativeHidden=false;dispatchEvent(new Event('party-native-resume'));});assert(await page.evaluate(()=>document.body.classList.contains('native-controller')&&!!LocalPartyTabs));}
    report.checks.push({variant,pair,name:'rename-focus-save-and-native-tabs',passed:true});
   }
   await page.close();
  }
  assert.deepEqual(report.errors,[]);report.ok=true;
 }finally{await browser?.close();if(server)await new Promise(r=>server.close(r));child?.kill();fs.writeFileSync(path.join(output,`${engine}-${controllerRoute?'controller':lane}${behaviorOnly?'-behavior':''}-report.json`),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({ok:report.ok,lane,engine,samples:report.samples.map(s=>({variant:s.variant,pair:s.pair,name:s.name,cpu:s.cpu,bodyClasses:s.probe.bodyClasses,inputStyleReads:s.probe.inputStyleReads,inputInk:s.probe.inputInk,inputStyles:s.probe.inputStyles,created:s.probe.created,added:s.probe.added,removed:s.probe.removed,callbacks:s.probe.observerCallbacks,frameP95:s.probe.frameP95}))}));}
})().catch(e=>{console.error(e);process.exitCode=1;});
