'use strict';
// Actual Bow Club worker/TV/native-route touch controller. Sequential profile only.
const {spawn}=require('node:child_process'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium,webkit}=require(process.env.PARTY_PLAYWRIGHT||'playwright');
const root=path.resolve(__dirname,'..'),engine=process.env.QA_ENGINE||'chromium',before=process.env.PERF_SOURCE_DIR,out=path.resolve(process.env.QA_OUTPUT||'output/playwright/performance244/canvas/bow-after'),wait=ms=>new Promise(r=>setTimeout(r,ms));fs.mkdirSync(out,{recursive:true});
const child=spawn(process.execPath,['server.js'],{cwd:root,env:{...process.env,PARTY_EMBEDDED:'1',PARTY_EPHEMERAL:'1',PARTY_NO_BROWSER:'1',PARTY_ADMIN_KEY:'canvas244',PARTY_PORT:'0'}});let log='',browser,base;child.stdout.on('data',b=>log+=b);child.stderr.on('data',b=>log+=b);
async function until(fn,label){for(let i=0;i<400;i++){if(await fn())return;await wait(50);}throw Error(label+' '+log.slice(-1200));}
async function api(body){const r=await fetch(base+'/api/manage',{method:body?'POST':'GET',headers:{Authorization:'Bearer canvas244','Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const s=await r.json();assert.equal(r.status,200,JSON.stringify(s));return s;}
(async()=>{try{
 await until(()=>/localhost:(\d+)/.test(log),'server');base='http://127.0.0.1:'+log.match(/localhost:(\d+)/)[1];await api({type:'server-start'});
 browser=await(engine==='webkit'?webkit:chromium).launch({headless:true,...(engine==='chromium'?{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}:{})});
 const tv=await browser.newPage({viewport:{width:1920,height:1080}}),phone=await browser.newPage({viewport:{width:393,height:852},isMobile:true,hasTouch:true,deviceScaleFactor:3}),second=await browser.newPage({viewport:{width:393,height:852},isMobile:true,hasTouch:true}),errors=[],sourceRoutes=[];
 for(const p of[tv,phone,second]){p.on('pageerror',e=>errors.push(e.message));if(before){for(const [pattern,file]of[[/\/games\/bow_club\/src\/mini3d\.mjs(?:\?.*)?$/,'games/bow_club/public/src/mini3d.mjs'],[/\/games\/bow_club\/phone\.js(?:\?.*)?$/,'games/bow_club/public/phone.js']])await p.route(pattern,r=>{sourceRoutes.push({url:r.request().url(),file});return r.fulfill({path:path.join(before,file),contentType:'application/javascript'});});}}
 for(const p of[phone,second])await p.addInitScript({content:"localStorage.setItem('local-party-language','en');window.__partyPersistentTabs=true;window.webkit={messageHandlers:{partyShell:{postMessage(){}}}};"+fs.readFileSync(path.join(root,'public/native-shell/controller-bridge.js'),'utf8')+'\n'+fs.readFileSync(path.join(root,'public/native-shell/tabs.js'),'utf8')});
 await phone.addInitScript(()=>{
  window.__bowPerf={typedArrays:0,typedBytes:0,bufferData:0,bufferDataBytes:0,bufferSubData:0,bufferSubDataBytes:0,draws:0,mutations:0,frames:[]};
  const Typed=Float32Array;window.Float32Array=new Proxy(Typed,{construct(T,args){const v=new T(...args);__bowPerf.typedArrays++;__bowPerf.typedBytes+=v.byteLength;return v;}});
  const proto=WebGLRenderingContext.prototype;for(const key of['bufferData','bufferSubData','drawArrays']){const fn=proto[key];proto[key]=function(...args){if(this.canvas.id==='bow'){if(key==='drawArrays')__bowPerf.draws++;else{__bowPerf[key]++;const data=args[key==='bufferData'?1:2];__bowPerf[key+'Bytes']+=typeof data==='number'?data:data?.byteLength||0;}}return fn.apply(this,args);};}
  addEventListener('DOMContentLoaded',()=>new MutationObserver(r=>__bowPerf.mutations+=r.length).observe(document.body,{subtree:true,attributes:true,childList:true,characterData:true}));let last;requestAnimationFrame(function sample(t){if(last)__bowPerf.frames.push(t-last);last=t;requestAnimationFrame(sample);});
 });
 await tv.goto(base+'/tv');await until(async()=>(await api()).screens===1,'TV');for(const [i,p]of[phone,second].entries()){await p.goto(base+'/play');await p.locator('#name').fill('Archer '+i);await p.locator('#joinForm button[type=submit]').click();await p.locator('#home').waitFor();}
 await api({type:'settings',id:'bow_club',settings:{mode:'versus',arrows:'10'}});const run=(await api({type:'launch',id:'bow_club'})).active;
 for(const p of[phone,second]){await p.waitForFunction(()=>!document.querySelector('#readyButton').disabled);await p.locator('#readyButton').click();}await until(async()=>(await api()).active?.ui?.phase==='playing','playing');
 const frame=phone.frames().find(f=>f.url().includes('/games/bow_club/'));assert(frame,'actual game frame');await frame.locator('#touch').click();await frame.locator('#draw').waitFor();await wait(1200);if(before)for(const file of['games/bow_club/public/src/mini3d.mjs','games/bow_club/public/phone.js'])assert(sourceRoutes.some(r=>r.file===file),'Frozen module actually intercepted '+file);
 const session=engine==='chromium'?await phone.context().newCDPSession(phone):null;if(session)await session.send('Performance.enable');const metrics=async()=>session?Object.fromEntries((await session.send('Performance.getMetrics')).metrics.map(m=>[m.name,m.value])):{};
 for(const f of[phone.mainFrame(),frame])await f.evaluate(()=>{__bowPerf={typedArrays:0,typedBytes:0,bufferData:0,bufferDataBytes:0,bufferSubData:0,bufferSubDataBytes:0,draws:0,mutations:0,frames:[]};});
 const beforeCpu=await metrics();await wait(6000);const afterCpu=await metrics();
 const summarize=async()=>frame.evaluate(()=>{const p=__bowPerf,frames=p.frames.sort((a,b)=>a-b),c=document.querySelector('#bow');return{...p,frames:frames.length,p95:frames[Math.floor(frames.length*.95)],backing:{width:c.width,height:c.height},renderer:c.dataset.renderer,display:getComputedStyle(c).display};});const settled=await summarize();assert.equal(settled.renderer,'webgl','Real phone renderer must be WebGL, not fallback');
 const draw=frame.locator('#draw');assert(await draw.isEnabled(),'Actual worker accepts draw');const box=await draw.boundingBox();await phone.mouse.move(box.x+box.width/2,box.y+box.height/2);await phone.mouse.down();await wait(700);await phone.screenshot({path:path.join(out,'phone-draw.png')});await phone.mouse.up();await wait(500);assert((await api()).active?.ui?.phase==='playing','Real shot leaves match active');await phone.screenshot({path:path.join(out,'phone-settled.png')});await tv.screenshot({path:path.join(out,'tv-playing.png')});
 const readout=await frame.locator('#score strong').allTextContents();assert.equal(readout[1],'9','Actual accepted release consumes one arrow');const postShot=await summarize();if(postShot.display==='none'&&!before){assert.equal(postShot.draws,0,'Declared hidden touch Bow must not draw');assert.equal(postShot.bufferDataBytes+postShot.bufferSubDataBytes,0,'Declared hidden touch Bow must not upload');}else assert(postShot.bufferSubData>settled.bufferSubData||before,'Changed visible pull/recoil geometry must upload');await frame.locator('#hand').click();await wait(100);await phone.screenshot({path:path.join(out,'phone-left.png')});
 await phone.setViewportSize({width:320,height:568});await wait(200);const resized=await frame.evaluate(()=>({width:document.querySelector('#bow').width,height:document.querySelector('#bow').height,viewport:[innerWidth,innerHeight]}));await phone.screenshot({path:path.join(out,'phone-320.png')});if(settled.draws){assert.equal(resized.width,Math.round(resized.viewport[0]*1.5));assert.equal(resized.height,Math.round(resized.viewport[1]*1.5));}
 await frame.evaluate(()=>window.PartyI18n?.setLanguage('ru',{persist:false}));await wait(80);const ru=await frame.locator('#draw b').textContent();assert.equal(ru,'НАТЯНИ','Real locale switch remains responsive');await frame.evaluate(()=>window.PartyI18n?.setLanguage('en',{persist:false}));await wait(80);const en=await frame.locator('#draw b').textContent();assert.equal(en,'DRAW');await api({type:'pause',paused:true});await phone.locator('#pauseOverlay').waitFor();await api({type:'pause',paused:false});await phone.locator('#pauseOverlay').waitFor({state:'hidden'});assert.equal((await api()).active.instance,run.instance,'Resize, hand and pause keep the match');assert.equal(errors.length,0,errors.join('\n'));
 const report={method:'Actual worker, dedicated desktop TV1920x1080 + real native-route393x852 touch controller; six seconds settled aim, genuine draw/release then hand/resize/pause. Browser evidence, no camera or AirPlay.',engine,before:!!before,settled,cpu:Object.fromEntries(['TaskDuration','ScriptDuration','LayoutDuration','RecalcStyleDuration','LayoutCount','RecalcStyleCount'].map(k=>[k,afterCpu[k]-beforeCpu[k]])),postShot,resized,readout,locale:{ru,en},sourceRoutes,errors};fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
}finally{await browser?.close();child.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
