const fs=require('fs');let p='games/party/public/host.js',s=fs.readFileSync(p,'utf8'),a=s.indexOf('  const active=s.players.filter(p=>p.active)',s.indexOf('function drawWestern(s)')),b=s.indexOf('  let cue=null',a);
s=s.slice(0,a)+`  const active=s.players.filter(p=>p.active),poses=westernPositions(active.length),roundKey=s.game.round;
  if(westernPoseRound!==roundKey){westernPoseRound=roundKey;westernDeaths.clear();westernAlive.clear();}
  active.forEach((p,i)=>{if(westernAlive.get(p.id)===true&&!p.alive&&!p.falseStart&&w.shots?.length)westernDeaths.set(p.id,s.visualTime);westernAlive.set(p.id,p.alive);const pose=poses[i],{x,y,scale,flip}=pose,age=s.visualTime-p.shotVisualTime,shot=p.shotThisRound&&age>=0&&age<220,recoil=shot?Math.sin(Math.min(1,age/220)*Math.PI)*6:0,dead=!p.alive;
    ctx.save();ctx.translate(x,y);ctx.fillStyle='#0006';ctx.beginPath();ctx.ellipse(0,8*scale,34*scale,9*scale,0,0,7);ctx.fill();ctx.scale(scale*flip,scale);ctx.translate(-recoil,0);if(dead){ctx.translate(0,5);ctx.rotate(-1.15);ctx.globalAlpha=.6;}
    if(!window.PartyArt?.draw(ctx,'cowboy',0,-66,100,150,{color:p.color})){ctx.fillStyle=p.color;roundRect(-22,-90,44,90,10);ctx.fill();ctx.fillStyle='#e5b485';ctx.beginPath();ctx.arc(0,-109,20,0,7);ctx.fill();ctx.fillStyle='#382c25';ctx.fillRect(-32,-129,64,10);ctx.fillStyle='#c3d5db';ctx.fillRect(18,-68,32,7);}
    ctx.restore();
    if(shot){const mx=x+flip*scale*(49-recoil),my=y-66*scale;ctx.save();ctx.globalAlpha=1-age/220;ctx.translate(mx,my);ctx.scale(flip,1);ctx.fillStyle=p.falseStart?'#eab477':'#fff0ad';ctx.beginPath();ctx.moveTo(0,-4);ctx.lineTo(26*(1-age/220)+5,0);ctx.lineTo(0,5);ctx.lineTo(7,0);ctx.fill();ctx.restore();if(!p.falseStart){const target=poses[poses.length-1-i]||pose,end=target.x-flip*35*target.scale;ctx.save();ctx.globalAlpha=Math.max(0,1-age/160);ctx.strokeStyle='#fff1bb';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(mx+flip*12,my);ctx.lineTo(end,my);ctx.stroke();ctx.restore();}}
    const hitAge=s.visualTime-westernDeaths.get(p.id);if(hitAge>=0&&hitAge<340){ctx.save();ctx.translate(x,y-60*scale);ctx.globalAlpha=(1-hitAge/340)**2;ctx.strokeStyle='#ffd991';ctx.lineWidth=3;for(let n=0;n<8;n++){const angle=n*Math.PI/4,r=8+hitAge*.10;ctx.beginPath();ctx.moveTo(Math.cos(angle)*r,Math.sin(angle)*r);ctx.lineTo(Math.cos(angle)*(r+9),Math.sin(angle)*(r+9));ctx.stroke();}ctx.restore();}
    ctx.fillStyle=dead?'#ffcfb4':'#fff';ctx.font='italic 800 '+(active.length>8?11:14)+'px PartyRubik, Rubik, system-ui';ctx.textAlign='center';ctx.fillText(p.name,x,y+28,pose.labelWidth);ctx.fillText(dead?(p.falseStart?'РАНО — ВЫБЫЛ':'НЕ УСПЕЛ'):p.reactionMs!=null?p.reactionMs+' мс':'ГОТОВ',x,y+47,pose.labelWidth);
  });
`+s.slice(b);s=s.replace('function drawWestern(s){',`let westernPoseRound=null;const westernDeaths=new Map(),westernAlive=new Map();
function westernPositions(count){const rows=count>8?2:1,cols=Math.ceil(count/rows);return Array.from({length:count},(_,i)=>{const row=Math.floor(i/cols),col=i%cols,n=Math.min(cols,count-row*cols),x=n===1?640:n===2?380+col*520:170+col*940/(n-1);return{x,y:rows===1?570:row?638:470,scale:rows===1?Math.min(1.15,940/n/105):.75,flip:x<640?1:-1,labelWidth:n===2?230:Math.min(170,940/n)};});}
function drawWestern(s){`);fs.writeFileSync(p,s);
p='games/western_duel/public/app.js';s=fs.readFileSync(p,'utf8');s=s.replace("if(shot&&t<200){ctx.fillStyle='#ffe1a0';ctx.beginPath();ctx.moveTo(69,-109);ctx.lineTo(100,-102);ctx.lineTo(68,-97);ctx.fill();}","if(shot&&t<200){ctx.globalAlpha=1-t/200;ctx.fillStyle='#ffe1a0';ctx.beginPath();ctx.moveTo(56,-91);ctx.lineTo(82,-86);ctx.lineTo(56,-82);ctx.fill();}");const token='ctx.restore();ctx.font=\'italic 800 14px PartyRubik';s=s.replace(token,`ctx.restore();if(d&&state?.phase==='reveal'&&t>=0&&t<300){const shot=d.shots.find(s=>!s.early);if(shot){const left=shot.id===d.pair[0],from=w*(left?.26:.74)+(left?1:-1)*56*scale,to=w*(left?.74:.26),yy=h*.86-86*scale;ctx.save();ctx.globalAlpha=Math.max(0,1-t/230);ctx.strokeStyle='#fff0b5';ctx.lineWidth=2.5;ctx.beginPath();ctx.moveTo(from,yy);ctx.lineTo(to,yy);ctx.stroke();if(d.loser){ctx.globalAlpha=(1-t/300)**2;ctx.translate(to,yy);for(let n=0;n<9;n++){const a=n*2.399,r=8+t*.12;ctx.beginPath();ctx.moveTo(Math.cos(a)*r,Math.sin(a)*r);ctx.lineTo(Math.cos(a)*(r+12),Math.sin(a)*(r+12));ctx.stroke();}}ctx.restore();}}ctx.font='italic 800 14px PartyRubik`);fs.writeFileSync(p,s);
