 'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('assert/strict'),{spawn}=require('child_process');
const {webkit}=require(process.env.PARTY_PLAYWRIGHT);
const out=path.resolve(process.env.QA_OUTPUT||'output/playwright/screen-state-audit-2026-10-03/tv-before');fs.mkdirSync(out,{recursive:true});
const files=['public/tv.js','public/tv.css','public/tv.html','public/tv-show.js','public/tv-show.css','public/tv-information.css','public/tv-menu-polish.css','public/game-art.js'];
const hashes=()=>Object.fromEntries(files.map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex')]));
const report={method:'Real isolated localhost launcher, actual two browser controllers/worker/readiness/admin overlay state; no substituted UI state.',sourceStart:hashes(),screens:[],errors:[]};
const key='tv-state-audit';let log='',browser,origin;
const data=path.join(out,'isolated-room.json');fs.writeFileSync(data,JSON.stringify({version:1,players:[],events:[],tvOptions:{autoPodium:true,idleBrowse:false}}));
const cached=path.resolve('output/playwright/main-menu-material-2026-10-03/confirmation/https');fs.cpSync(cached,path.join(out,'https'),{recursive:true});
const child=spawn(process.execPath,['server.js'],{env:{...process.env,PARTY_DATA_FILE:data,PARTY_EMBEDDED:'1',PARTY_EPHEMERAL:'0',PARTY_INTERNAL_PORT:'0',PARTY_PORT:'0',PARTY_NO_BROWSER:'1',PARTY_ADMIN_KEY:key}});child.stdout.on('data',d=>log+=d);child.stderr.on('data',d=>log+=d);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));const save=()=>fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));
async function until(fn,label,limit=30000){const end=Date.now()+limit;while(Date.now()<end){if(await fn())return;await sleep(100);}throw Error(label);}
async function api(body){const r=await fetch(origin+'/api/manage',{method:body?'POST':'GET',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const j=await r.json();assert(r.ok,JSON.stringify(j));return j;}
async function sample(p){return p.evaluate(()=>{const selectors=['#lobby','#play','#waiting','#paused','.gamebar.tv-information','.tv-info-dock','#tvPresentation','#tvLargeInvite','#tvAudioDialog','#tvSceneTransition','#gameFrame'];const box=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height,bottom:r.bottom,right:r.right}};return{phase:window.PARTY_UI?.phase,classes:document.body.className,items:Object.fromEntries(selectors.map(s=>{const e=document.querySelector(s),c=getComputedStyle(e);return[s,{hidden:e.hidden,open:e.open,display:c.display,visibility:c.visibility,opacity:c.opacity,overflow:c.overflow,mask:c.maskImage,rect:box(e)}]})),frame:document.querySelector('#gameFrame').src,scrollY:scrollY,browseScroll:document.querySelector('#tvBrowse').scrollTop,capVisible:!!document.querySelector('.tv-info-dock').getClientRects().length};});}
async function shot(p,name){await p.evaluate(async()=>{await document.fonts.ready;await Promise.allSettled([...document.images].filter(x=>x.src).map(x=>x.decode()));});await sleep(650);await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const metrics=await sample(p);const file=name+'-'+p.viewportSize().width+'.png';await p.screenshot({path:path.join(out,file)});report.screens.push({file,metrics,viewport:p.viewportSize()});save();if(process.env.QA_AFTER==='1'&&name.includes('waiting')){assert.equal(metrics.capVisible,false,'waiting never exposes gameplay cap');assert.equal(metrics.items['#gameFrame']?.visibility||metrics.frameVisibility,'hidden','waiting hides mounted gameplay frame');}}
async function pair(p,name){for(const width of[1280,1920]){await p.setViewportSize({width,height:width*9/16});await shot(p,name);}}
(async()=>{try{
 await until(()=>/localhost:(\d+)/.test(log),'server');origin='http://127.0.0.1:'+log.match(/localhost:(\d+)/)[1];browser=await webkit.launch({headless:true});
 const tv=await browser.newPage({viewport:{width:1280,height:720}});await tv.addInitScript(()=>localStorage.setItem('local-party-language','en'));tv.on('pageerror',e=>report.errors.push(e.message));await tv.goto(origin+'/tv');await tv.locator('#tvStage.tv-show-ready').waitFor();await tv.evaluate(()=>{window.__visibilityViolations=[];new MutationObserver(()=>{const phase=document.body.dataset.tvPhase;if(phase==='waiting'&&(!document.querySelector('.gamebar').hidden||getComputedStyle(document.getElementById('gameFrame')).visibility!=='hidden'))window.__visibilityViolations.push({phase,src:document.getElementById('gameFrame').src});}).observe(document.getElementById('play'),{subtree:true,attributes:true,attributeFilter:['hidden','src','style']});});await until(()=>tv.locator('#tvStartup').isHidden(),'startup');
 const phones=[];for(const name of['Alexandra LongSurname','Christopher LongSurname']){const p=await browser.newPage({viewport:{width:402,height:874}});await p.addInitScript(()=>localStorage.setItem('local-party-language','en'));await p.goto(origin+'/play');await p.locator('#name').fill(name);if(!phones.length)await p.locator('#avatarLibrary').setInputFiles(path.resolve('public/assets/spectators-20261002/spectator-01-coral.png'));await p.locator('#joinForm button[type=submit]').click();await p.locator('#home').waitFor();phones.push(p);}
 await api({type:'network-set',enabled:true});await pair(tv,'lobby');await tv.locator('#tvAudioToggle').click();if(!await tv.locator('#tvAudioDialog').evaluate(e=>e.open))await tv.locator('#tvAudioToggle').click();const before=await sample(tv);await pair(tv,'audio-open');await tv.keyboard.press('Escape');await sleep(70);const closing=await sample(tv);await pair(tv,'audio-closed');await tv.locator('#tvAudioToggle').click();await tv.locator('#tvAudioClose').click();report.audio={before,closing,after:await sample(tv)};
 await api({type:'tv-overlay',mode:'qr'});await tv.locator('#tvLargeInvite').waitFor({state:'visible'});await pair(tv,'invite-open');await api({type:'tv-overlay',mode:'none'});await tv.locator('#tvPresentation').waitFor({state:'hidden'});await pair(tv,'invite-closed');
 for(const id of ['push','naval','sinyakquiz','bow_club']){await api({type:'launch',id});await tv.locator('#waiting').waitFor({state:'visible'});await until(async()=>phones.every(p=>p.isClosed()===false)&&await Promise.all(phones.map(p=>p.locator('#readyButton').isVisible())).then(a=>a.every(Boolean)),'ready controls');await pair(tv,id+'-waiting');await api({type:'stop'});await tv.locator('#lobby').waitFor({state:'visible'});}
 await api({type:'launch',id:'push'});for(const p of phones)await p.waitForFunction(()=>!document.getElementById('readyButton').disabled);await phones[0].locator('#readyButton').click();await pair(tv,'push-partial-waiting');await phones[1].locator('#readyButton').click();await until(async()=>['playing','reveal'].includes((await api()).active?.ui?.phase),'playing');await pair(tv,'push-playing');
 await api({type:'pause',paused:true});await pair(tv,'push-paused');await api({type:'tv-overlay',mode:'qr'});await pair(tv,'push-paused-invite');await api({type:'pause',paused:false});await tv.locator('#tvPresentation').waitFor({state:'hidden'});await pair(tv,'push-resumed');await api({type:'stop'});await tv.locator('#lobby').waitFor({state:'visible'});await pair(tv,'returned-lobby');
 await api({type:'launch',id:'punchmeter'});for(const p of phones){await p.waitForFunction(()=>!document.getElementById('readyButton').disabled);await p.locator('#readyButton').click();}await until(async()=>(await api()).active?.ui?.phase==='results','real punch results',120000);await tv.locator('#tvPodium').waitFor({state:'visible'});await pair(tv,'punch-results');report.result=(await api()).active.result;await api({type:'stop'});await pair(tv,'results-returned-lobby');
 report.visibilityViolations=await tv.evaluate(()=>window.__visibilityViolations);assert.deepEqual(report.visibilityViolations,[]);assert.deepEqual(report.errors,[]);report.ok=true;
}catch(e){report.failure=e.stack;console.error(e);process.exitCode=1;}finally{report.sourceEnd=hashes();report.changedFiles=files.filter(f=>report.sourceStart[f]!==report.sourceEnd[f]);save();fs.writeFileSync(path.join(out,'server.log'),log);await browser?.close();child.kill();}})();
